### ISSUE TITLE
change semantics of m()

### ISSUE THREAD

**Issue by aplicacionamedida** [lhorie/mithril.js#1000]
I think that it's not a good idea to use CSS selectors to declare HTML elements. It's a little bit confusing because they are not real CSS selector. Maybe it's better to change this:
` m("a#google.external[href='http://google.com']", "Google"); `

to something like this:
` m("a id='google' class="external" href='http://google.com'", "Google"); `

It's much more clear.

**Comment by barneycarroll** [comment]
The semantics of selectors are terse and well established by CSS. If you don't like the short ID and CLASSNAME references `#` and `.`, you can use CSS selector long form:

```Javascript 
m("a[id=google][class=external][href=http://google.com]", "Google");
```

Alternatively you can avoid string representation of attributes and properties entirely and simply use Javascript object notation to populate the optional attributes map:

```Javascript 
m("a", { id : 'google', class : "external", href : 'http://google.com' }, "Google");
```

**Comment by Bondifrench** [comment]
@aplicacionamedida I think that your statement that your proposal makes it more clear is debatable, a lot of developers are used to CSS selectors:
- CSS selectors make coding more concise
- Mithril is not the first one to use CSS selectors, another great tool for web development is [Emmet](http://emmet.io/) which does the same, so I would tend to think this syntax is quite familiar to a lot of developers

**Comment by lhorie** [comment]
If you're interested in having syntax that is closer to HTML, consider looking into [msx](https://github.com/insin/msx)

The current `m` syntax is inspired by Emmet and is unlikely to change
