### ISSUE TITLE
Incorrecting test summary backbone.js

### ISSUE THREAD

**Issue by paninRadario** [lhorie/mithril.js#1011]
Incorrecting test
`<% _.each(items, function( item ){ %><input value="<%= item.name %>" /><% })%>`

Use for test
`<% _.each(items, function( item ){ %><input value="<%- item.name %>" /><% })%>`

**Comment by isiahmeadows** [comment]
Could you explain? I have no clue how this relates to Mithril.

**Comment by Naddiseo** [comment]
He probably means from the "Test Summary" link on the main website page which links to http://mithril.js.org/comparisons/backbone.safety.html

**Comment by lhorie** [comment]
The point of the comparison was that you had to explicitly use `<%-` to avoid an attack, but documentation uses `<%=` as the default interpolation syntax and it's extremely reasonable to expect that a developer would use the wrong thing
