### ISSUE TITLE
Cannot add !important property to css style

### ISSUE THREAD

**Issue by ghpu** [lhorie/mithril.js#1017]
When trying to render a div with m("div", style: { display: "inline-flex !important"} ,"...") ,
the browsers ignore the display property.
Is there a specific way to enforce the "important" attribute on css style generated with Mithril ?

**Comment by ghpu** [comment]
You can use a "config" function to work-around this issue :
m("div", config: function(element,isinit,context) {element.style.cssText += ';display: inline-flex !important;';}, ...)

**Comment by barneycarroll** [comment]
There's nothing about Mithril that should affect `!important`. Here's a little playground where you can try applying different styles to an element inline and in a stylesheet. I don't have any problems applying importance: https://jsfiddle.net/barney/7vcnf4uy/

**Comment by isiahmeadows** [comment]
@ghpu That's an HTML/DOM issue. You don't need `!important`, because DOM-level changes take precedence over any CSS you might have. Mithril, in this case, sets `el.style.display = "inline-flex !important"`, which won't work as intended. Try just doing this:

```js
m("div", style: { display: "inline-flex"} ,"...")
```

**Comment by ghpu** [comment]
In fact, I was trying to add "!important" as inline style, to try and override some class styles already containing "!important" keywords.

My context is that I made a widget with mithril, and then inject it in a web page already containing some styles. Using a reset css (which contains a lot of !important keywords), I must then force some css to override reset css styles.

**Comment by barneycarroll** [comment]
@ghpu did you manage to get it to work in the end? The fiddle still works: https://jsfiddle.net/barney/7vcnf4uy/

**Comment by isiahmeadows** [comment]
@ghpu Welp...that should say `style: "display: inline-flex !important"`. That will trigger `setAttribute` instead of `style.whatever`. My bad.
