### ISSUE TITLE
css styles are not yet rendered in cofig

### ISSUE THREAD

**Issue by rupasetty** [lhorie/mithril.js#1018]
Trying to get computed styles of an element in config (getBoundingClientRect) and the styles are not rendered yet. I need to dynamically create a tooltip for the element how am I supposed to get the position in config?

**Comment by barneycarroll** [comment]
I've never had this problem — it certainly works in this simple test case: https://jsfiddle.net/barney/rkm673tu/

If for whatever reason the browser is deciding not to paint things immediately, you may have some luck trying to get the results inside a `requestAnimationFrame` callback?

**Comment by rupasetty** [comment]
Sorry to mention we also use shadow DOM..trying to replicate it outside my application in jsfiddle. Thanks for prompt help!

**Comment by lhorie** [comment]
shadow DOM needs to be imported into the document before it can be used. If it hasn't been imported, the issue might not have anything to do w/ Mithril
