### ISSUE TITLE
Nested component not rendered when mounted to document

### ISSUE THREAD

**Issue by epidemian** [lhorie/mithril.js#1019]
Suppose we have a `PageLayout` component that defines the basic layout of an app, and a `SamplePage` that uses that layout:

```javascript
var PageLayout = {
  view: function(ctrl, args, content) {
    return m("html", [
      m("link", {rel: "stylesheet", href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"}),
      m("body",
        m(".container", content)
      )
    ])
  }
}

var SamplePage = {
  view: function() {
    return m(PageLayout, {}, [
      m("h1", "Hello!")
    ])
  }
}

m.mount(document, SamplePage)
```

When mounted directly to `document`, it [doesn't render anything](https://jsfiddle.net/epidemian/55qkh74u/). `PageLayout.view` is in fact never called.

If instead of using a component for the layout i use a plain old function that returns a virtual DOM, [it works as expected](https://jsfiddle.net/epidemian/55qkh74u/2/):

```javascript
var pageLayout = function(content) {
  return m("html", [
    m("link", {rel: "stylesheet", href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"}),
    m("body",
      m(".container", content)
     )
  ])
}

var SamplePage = {
  view: function() {
    return pageLayout([
      m("h1", "Hello!")
    ])
  }
}

m.mount(document, SamplePage)
```

What is weird is that if i mount the `SamplePage` component (as defined in the first snippet) in some other element besides `document`, e.g., `document.body`, [it does render](https://jsfiddle.net/epidemian/55qkh74u/3/) (though it creates a weird DOM structure because i'm rendering an `<html>` inside the `<body>`).

Is this a bug?

I'd like to use a component for the layout because there's some page-wide state that i'd like to manage with a controller there. Does that make sense?

The examples are using MIthril 0.2.4.

Thanks for your time, and for this great library! :smiley_cat:

**Comment by barneycarroll** [comment]
Hiya @epidemian, the thing that immediately stands out is the fact that a component is returning another component as its root node. This is a recipe for trouble in Mithril, since it needs to be able to associate unique live DOM root nodes with components — 2 components sharing the same unique root DOM node immediately creates internal model problems.

[Here's a functioning pattern for doing the same thing](https://jsfiddle.net/barney/gpc1svft/). Control is inverted — `SamplePage` is ignorant of its context and is instead simply content passed into `pageLayout`.

**Comment by epidemian** [comment]
Thanks for the quick response and the working example @barneycarroll!

For my particular case, i'm going to use something similar to your example (some pages need to change some things of the layout, so they cannot be completely ignorant of it). BTW, i didn't know you could use components directly as virtual DOM nodes 😮

For the general case, if having a component's view return `m(AnotherComponent, ...)` causes trouble on Mithril's internals because it will have two different components to associate to the same DOM root, wouldn't it be better if Mithril could detect this and raise an exception instead of failing silently? If that's the case, i could investigate this a bit more and try to submit a patch for that 🙂

In [the weird case](https://jsfiddle.net/epidemian/55qkh74u/3/) where the component was mounted to `document.body` and the layout was rendered, is that working because the DOM root of `SamplePage` is `document.root` and the DOM root of it's nested `Layout` component is the `<html>` that gets rendered inside the body?

**Comment by isiahmeadows** [comment]
@epidemian You shouldn't be rendering DOM nodes to the `document` itself. Throwing an error is probably more informative than nothing (PRs welcome), but it's basic HTML/DOM.

Oh, and in your fiddle, you shouldn't return `html` or `body` nodes in your view. HTML says to silently ignore those elements (which Mithril does by deferring to the DOM), and anything to the contrary is unexpected.

**Comment by epidemian** [comment]
> @epidemian You shouldn't be rendering DOM nodes to the document itself.

You mean doing stuff like `m.mount(document, something)`? Because that's what the [Getting Started](mithril.js.org/getting-started.html) does. And the views there create `html` and `body` nodes.

It may be wise not to mount Mithril apps directly onto `document` though. Today after some fiddling i went back to mounting stuff on the `body`. Mounting the app on `document` had other nasty side effects, like requiring the CSS `<link>`s to be rendered by Mithril, thus deferring the CSS download till after the JS downloaded and executed. I just wanted to have a general layout and be able to change the page `<title>` within it :sweat_smile:

**Comment by tivac** [comment]
```js
document.title = "My New Title";
```

I do a [variation of that](https://github.com/tivac/anthracite/blob/master/src/pages/layout/index.js#L52) and haven't ever had any issues. Maybe that helps?

**Comment by isiahmeadows** [comment]
@epidemian 

> Because that's what the Getting Started does. And the views there create html and body nodes.

That would be a documentation error. I'd welcome a docs fix for that.

**Comment by isiahmeadows** [comment]
A downside to every line of documentation being handwritten and featuring in-depth usage and examples is that things like that can easily slip up. :smile:

**Comment by epidemian** [comment]
> I do a variation of that and haven't ever had any issues. Maybe that helps?

Yeah, i like that variation. I was looking for some kind reusable pattern to set up pages on the application (layout, title, some global state like authentication, etc). It's nice to see some other Mithril app for reference :smile_cat: 

I'll close this issue then. With the fixes on the docs i think this shouldn't be much of a problem.
