### ISSUE TITLE
[rewrite] dbmonster popups not showing up

### ISSUE THREAD

**Issue by leeoniya** [lhorie/mithril.js#1020]
@lhorie the rewrite LIVES! :D

The performance looks stellar, btw.

I noticed that the popovers in the dbmonster bench are not showing up even though they look correctly placed in the DOM. Maybe a css issue?

also, good riddance to "controller", you won't be missed.

**Comment by lhorie** [comment]
Thanks, Dominic just pointed out a typo in the benchmark code in the chat that is related to this. It's fixed now

**Comment by adriengibrat** [comment]
Demo seems broken http://cdn.rawgit.com/lhorie/mithril.js/rewrite/examples/dbmonster/mithril/index.html (link in the rewrite branch README)
