### ISSUE TITLE
[rewrite] Linter?

### ISSUE THREAD

**Issue by isiahmeadows** [lhorie/mithril.js#1021]
@lhorie 

Shall I see about incrementally linting the rewrite? I noticed that almost immediately that you didn't port the linter over. Heck, I might also find a few bugs.

Oh, and BTW...IT LIVES!!! :laughing: 

(I haven't gotten a chance to really dig into it yet, though, but I'll try to find time at some point to play around with it.)

**Comment by lhorie** [comment]
I have a .eslintrc file that I haven't committed (and is currently full of too-strict rules). I ran the recommended rules and that caught a few things already.

**Comment by isiahmeadows** [comment]
Okay. I'll wait for that. :smile:

**Comment by isiahmeadows** [comment]
@lhorie Ping? (re: .eslintrc file)

**Comment by lhorie** [comment]
@tivac found that there's an autoconfigure feature
