### ISSUE TITLE
component view gets wrong controller instance when removing component before it in list

### ISSUE THREAD

**Issue by rzetterberg** [lhorie/mithril.js#1024]
## Description

I have two components `ItemWidget` and `ItemRow`. `ItemWidget` creates  `ItemRow`s from an array of `Item` model instances. (The `Item` model only have two fields `id` and `name`.)

Let's say I have the following array of `Item`s:
- Item 1: First 
- Item 2: Second

This will render 2 `ItemRow`s that each has a button to delete the `Item` it was derived from.

When I delete `Item 1: First`, then the `ItemRow` created from `Item 2: Second` gets the controller instance of the `ItemRow` created from `Item 1: First`.

To illustrate what I'm trying to say, here's a jsfiddle with the scenario above: https://jsfiddle.net/qvvv0maL/

The problem only happens when deleting an `Item` that is not the last one. See the console for info.

I encounter the problem in Chromium 49 and Firefox 45 on Linux.

### NPM

- 0.2.0
- 0.2.4

### CDNJS

- 0.2.0
- 0.2.3

## Related issues

Here are some issues that seemed related (really new to mithril, so I'm just guessing).

- #765
- #631

**Comment by isiahmeadows** [comment]
Very odd...I'm not as familiar with how controllers are handled, and now that the rewrite has landed here, that's where most of the effort is pouring ATM as far as I can tell.

@lhorie You probably know more about this than I do. :wink:

**Comment by lhorie** [comment]
@rzetterberg Looks like you're just missing a key. This works for me:

https://jsfiddle.net/qvvv0maL/5/
