### ISSUE TITLE
m.route components with attributes

### ISSUE THREAD

**Issue by realdope** [lhorie/mithril.js#1029]
Hi,

It's my understanding that there is currently no way to pass an attributes hash into a component if I use m.route. If that is correct, can we implement attributes hash for m.route so that these components can be parameterized like any other components with m(MyComponent, {attr1: value1})?

Thanks.

**Comment by realdope** [comment]
I think I figured it out.. Passing m(MyComponent, {attr1: value1}) into each route works.

**Comment by isiahmeadows** [comment]
Also, you can route with parameters using `m.route(route, params)`. It passes `params` to `m.route.buildQueryString`, though, so that variable carries similar restrictions on its value.
