### ISSUE TITLE
[rewrite] migration path

### ISSUE THREAD

**Issue by oligot** [lhorie/mithril.js#1032]
Hi,

I just saw that there is a rewrite in progress [here](https://github.com/lhorie/mithril.js/tree/rewrite).

Given that it's not backward compatible with the 0.2.x API, are there any plans to support a migration path ? This could be a page on the wiki that explains how to upgrade to the new API, or even better a codemod, that is able to migrate the code base automatically, like for example [react-codemod](https://github.com/reactjs/react-codemod).

Another question: will it be possible to have a 0.2.x component interact with a 1.0.x component ?
If not, how will it be possible to migrate a large code base from 0.2.x to 1.0.x ?

Note that I don't expect to have all answers right now as the rewrite is still in progress. I just want to have your opinions on these to see how we could one day migrate to the new API.

**Comment by isiahmeadows** [comment]
We plan on eventually creating a migration path, but at the moment, the rewrite is still missing features, most notably component support. Given that, it doesn't quite make sense yet. 

Closing for now, and when we get to that point, feel free to open a new issue.

**Comment by oligot** [comment]
Ok, thanks.
