### ISSUE TITLE
m.request() mangles urls containing colon in the path

### ISSUE THREAD

**Issue by marcel-wolf** [lhorie/mithril.js#1039]
version: 0.2.4
browser: any

When calling m.request() with a colon in the url, the url is modified. I'm guessing this is a result of the parameter substitution for m.route(), but I wasn't expecting this for m.request(). Even if it is an intended feature, there doesn't seem to be a way to escape the colon in the url.

example:
`m.request({url:"http://example.org/some:path/", data:{q:1}})`

expected:
`GET http://example.org/some:path/?q=1`
got instead:
`GET  http://example.org/someundefined/?q=1`

**Comment by lhorie** [comment]
Fixed in origin/next

**Comment by marcel-wolf** [comment]
Works perfectly, thanks for the quick response!
