### ISSUE TITLE
Safari won't load scripts via m.trust()

### ISSUE THREAD

**Issue by ianhenderson** [lhorie/mithril.js#1045]
Hi there,

I'm using Mithril (version 0.2.4), and I noticed a bug where Safari won't parse script tags inside of HTML that is `m.trust()`ed, then injected. You can see a demonstration here:

http://jsbin.com/fixiyi/edit?js,output

After looking into it a bit more, it seems to be a problem with Safari throwing an error when the `createContextualFragment` method is invoked (relevant part of Mithril source [here](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L1173-L1180) ):

http://jsbin.com/luvoso/2/edit?js,output

Similar errors have been reported on Apple's communities [here](https://discussions.apple.com/thread/7521725?start=0&tstart=0), but no problem exists in Chrome/Firefox though (of course).

While an approach like that of jQuery's might be the most robust, perhaps something simple like that suggested in [this StackOverflow answer](http://stackoverflow.com/a/20584396) might be good for now?

I'm currently using a patched version for my project since this functionality is necessary, but would be happy to submit a pull request for review. 👍

**Comment by isiahmeadows** [comment]
@ianhenderson Go ahead and send the PR against `next` (0.2). It'll have to be ported separately to the rewrite, but it's probably more important to get into stable.

**Comment by ianhenderson** [comment]
Thanks @isiahmeadows . I've opened a PR at https://github.com/lhorie/mithril.js/pull/1051 for review. 👍
