### ISSUE TITLE
Migrate Mithril to its own organization?

### ISSUE THREAD

**Issue by ludbek** [lhorie/mithril.js#1050]
Just in case this topic has not come up. I think it would be good decision to migrate Mithril to its own organization. It could be used to house everything related to Mithril (core, website, helper packages, ...).

**Comment by isiahmeadows** [comment]
IMO I feel it's a bit premature for that. Currently, Mithril itself consists of 1 module only: `mithril`. The rest are community contributions and other things. Also, the community and tooling around aren't *quite* large enough to merit a dedicated organization.

I would think that it would be better to wait until it's no longer practically possible to reliably manage Mithril's code base and related tooling without one, but I'll defer this one to @lhorie.

**Comment by ludbek** [comment]
Eventually, we will have to do so. Since major changes are coming I think this is the perfect time to do so. Also, right now we have core and website to maintain, and it kind of feels scattered. The idea is to have a central place where official stuff resides.

**Comment by isiahmeadows** [comment]
Currently, there *is* a dedicated organization, but the code base hasn't been migrated yet. And IMHO it still doesn't yet seem like we need to quite *yet*. Closing this for now, and we can open a new issue later when it comes up again (we've been a little too busy writing and designing things to address this part).
