### ISSUE TITLE
npm target wrong version of mithril

### ISSUE THREAD

**Issue by accessibleweb** [lhorie/mithril.js#1065]
Hi,
https://www.npmjs.com/package/mithril
non minimify version is 0.2.3
minimified 0.2.4

**Comment by nbrunch** [comment]
The m.version value is 0.2.3 in minimified and non minimified version.
But the comment in the minimified version is 0.2.4.
Maybe they just forgot to change the return value of m.version ?

**Comment by tivac** [comment]
See #1030 for the discussion on this. Both the raw and minified versions of `v0.2.4` on npm are fine.

**Comment by lhorie** [comment]
0.2.5 is released now
