### ISSUE TITLE
Idea: make controller able to return a promise

### ISSUE THREAD

**Issue by jamescostian** [lhorie/mithril.js#1066]
# Examples
Before:
```js
m.route(document.body, '/', {
  '/': {
    controller: function () {
      m.startComputation()
      return {
        something: m.prop(somePromise().then(whatever => {
          setTimeout(m.endComputation, 0)
          return whatever
        }))
      }
    },
    view: function (controller) {
      return m('div', controller.something())
    }
  }
})
```

After:
```js
m.route(document.body, '/', {
  '/': {
    controller: function () {
      return somePromise()
    },
    view: function (controller) {
      return m('div', controller)
    }
  }
})
```

If you want to have multiple promises, that's easily achievable through `Promise.all()`. For example, if you want to run `somePromise()` and `anotherPromise()` and concatenate their results in your view:
```js
m.route(document.body, '/', {
  '/': {
    controller: function () {
      return Promise.all([somePromise(), anotherPromise()])
    },
    view: function (controller) {
      return m('div', controller[0] + controller[1])
    }
  }
})
```

# Motivation
`m.startComputation()` and `m.endComputation()` feel redundant for this use case. Returning a promise in controller code should *imply* a `m.startComputation()` and once the promise resolves, that should imply a `m.endComputation()`

I'd be happy to take a stab at implementing this idea and adding tests for it, if it gets a green light

**Comment by isiahmeadows** [comment]
How commonly does this scenario come up? Also, the in-progress rewrite renders completely synchronously, so it would be relatively difficult to implement in that.

**Comment by jamescostian** [comment]
I have this scenario come up all the time. Imagine you have a single page app (which seems to be Mithril's use case), with dynamic content on each page. You'll want each page to load whatever it needs before the page is drawn, and then trigger a redraw. If you want to load the data right before it's drawn (so it isn't stale), the only way to do that is through the view or controller (and really, this code feels like it belongs in the controller).

I'm not completely sure what you mean by "the in-progress rewrite renders completely synchronously," but if I understand correctly, you're talking about how you run `view(controller)` without any sort of waits, and how redraws happen 100% synchronously (and for a reason - something about videos on iOS needing to be triggered synchronously? I remember reading about this in one of this repo's issues).

I'm not asking for that to change, *unless* a promise is returned by the controller code. No one would pass a promise from the controller to the view and expect a synchronous redraw - by using a promise, it's implied that there will be <del>turtles</del> asynchrony all the way down. Of course, when a something that is not a promise is returned by the controller code, use the existing code for a synchronous render.

Redraws can already be triggered asynchronously by calling `m.endComputation()` (after setting up a `m.startComputation()`). While I am not familiar with the code base, I believe implementing this idea is as easy as doing the following after evaluating the controller function and putting it's output in a variable called `controller`:

```js
if (controller && controller.then && typeof controller.then === "function") {
  m.startComputation()
  controller.then(result => {
    controller = result
    m.endComputation()
  })
} else {
  view(controller)
}
```

The line that says `controller = result` may not be sufficient, but something along those lines would be. I could take a stab at implementing this if you'd like to see what an actual implementation looks like.

**Comment by isiahmeadows** [comment]
@jamescostian 

1. What I mean is there is no such thing as an async redraw in the rewrite. @lhorie made that decision before it got here. `m.redraw()` is always synchronous, no matter how you use it. Also, components are initialized and the view is rendered on the same tick. It's not possible to delay it with a Promise. For similar reasons, there isn't likely going to be a `m.{start,end}Computation()` equivalent.
2. If it's similar enough, would it be worth dropping into a helper function?

```js
function isThenable(v) {
  return (typeof v === "function" || typeof v === "object") &&
    typeof v.then === "function"
}

function wait(controller) {
  return function () {
    m.startComputation()
    var ret = controller.apply(this, arguments)
    if (isThenable(ret)) ret.then(m.endComputation)
  }
}

// Usage:
'/': {
  controller: wait(function () {
    this.something = m.prop()
    return somePromise().then(this.something)
  }),
  view: function (controller) {
    return m('div', controller.something())
  }
}
```

**Comment by isiahmeadows** [comment]
I will also note that it's not quite *that* simple with the current code base: the controller and view are both still called on the same tick of the event loop. No `requestAnimationFrame` between the two.

**Comment by jamescostian** [comment]
Your `wait` function is actually almost exactly what I need - I just added an `else` after the `if` which says `else m.endComputation()`, that way if the controller does not return a "thenable", there isn't a `m.startComputation()` call without a paired `m.endComputation()`

Thanks!
