### ISSUE TITLE
Firefox not pushing routes with m.route()

### ISSUE THREAD

**Issue by davegonzalez** [lhorie/mithril.js#1069]
Hi there!
I ran into this issue today with Firefox 46.0.1, but also tested it with FF 44 and 43 via browserstack. Chrome and Safari work as expected. Currently using Mithril v0.2.3. This is while using `m.route.mode = 'pathname';`- we haven't tried using a different mode.

I have click events setup which push certain routes using `m.route()`. As an example, clicking on a button will trigger `m.route('/admin/promotions/new');`. Clicking another button will trigger `m.route('/admin/promotions');` and take you back to the original page. For some reason, FF is not updating the route, so it remains at `/admin/promotions/new`.

In Chrome we see:
![chrome](https://cloud.githubusercontent.com/assets/1012987/15510959/97af3d7a-21a7-11e6-9c5b-25d150b190c4.png)

But in Firefox we see:
![firefox](https://cloud.githubusercontent.com/assets/1012987/15510960/97b15a38-21a7-11e6-8de6-7c3e713d54e5.png)

Please let me know if I can supply any other information!

**Comment by isiahmeadows** [comment]
First, Mithril's at v0.2.4. Little has actually changed between the two versions, but just thought I'd point that out. Second, could you verify this against `next`? Also, source code is helpful. :wink:

**Comment by davegonzalez** [comment]
Got it! Just FYI the link at http://mithril.js.org/installation.html - `http://mithril.js.org/mithril.min.zip` supplies Mithril v0.2.3 even though the main homepage says "Download v0.2.4"

Tested it against `next` and am still running into the same issue. Here's some src cod 🐟  for you.

routes.js

```
vhxm.layouts.table = {
  controller: function() { // API request here },
  view: function() {
    return m('.standard-width-container', [
      m('.promotions-table-container', [
        m.component(vhxm.components.table.ui.container)
      ]),
      m('.sidebar-container', [
        m.component(vhxm.components.sidebar.container)
      ])
    ]);
  }
};


m.route.mode = 'pathname';

m.route(document.getElementById('promotions-table'), '/admin/promotions', {
  '/admin/promotions': vhxm.layouts.table,
  '/admin/promotions/new': vhxm.layouts.table,
  '/admin/promotions/:id/edit': vhxm.layouts.table
});
```

We have one primary component (the table) which renders a main page and a sidebar. The sidebar opens if we hit the `/edit` or `/new`, closes if we go back to the root `/admin/promotions`. The initial sidebar opening/route change works without any issues. 

We have a cancel button within the sidebar that looks like this:

```
m('a.btn-gray.btn--medium.btn--fill', {
  config: animatorOut
}, 'Cancel')
```

and the animatorOut function:

```
var animatorOut = function(elem, isInit) {
  if (!isInit) {
    elem.onclick = function(ev) {
      ev.preventDefault();
      vhxm.components.sidebar.state.isOpen(false);

      $('.sidebar').velocity({
        right: '-470'
      }, {
        duration: 500,
        easing: [ 0.19, 1, 0.22, 1 ],
        complete: function() {
          m.route('/admin/promotions');
        }
      });
    }
  }
};
```

It does enter the complete callback and hits m.route, but never updates the route itself. 

Also to note, the same behavior occurs if I set up the cancel button like this:
```
m('a.btn-gray.btn--medium.btn--fill', {
  config: m.route,
  href: '/admin/promotions'
}, 'Cancel')
```

**Comment by davegonzalez** [comment]
Looks like it was something else we had running internally. Was able to find a workaround. Closing for now. Thanks!
