### ISSUE TITLE
Feature requests: static jsonp callback name

### ISSUE THREAD

**Issue by gustavopaes** [lhorie/mithril.js#1072]
Should be nice if I could define jsonp callback name instead of the random name.

It's necessary when:
* I do not want to hole through cache
* My jsonp service can't change callback name (static jsonp files, for example)

I make some changes on `handleJsonp` function, creating a request queue for that.

https://gist.github.com/gustavopaes/1f7187ccf1a39ffa202d6e60cf89e04c

Usage example:

    m.request({
        dataType: 'jsonp',
        callback: 'staticCallbackName',
        url: 'http://api.service.com/get/'
    });

**Comment by vicnicius** [comment]
@gustavopaes I don't know if I understood your problem well, but doesn't the `callbackKey` option already allow you to do it? 

Like on the second example here: http://mithril.js.org/mithril.request.html#using-json-p

**Comment by gustavopaes** [comment]
@vicnicius sorry if I was not clear. `callbackKey` changes the querystring key, not the querystring value.

Let's try again. Imagine I have an static file like this:

    // somedomain.com/static-file.js
    someCallbackFunction({...});

Today, I need to do:

    window.someCallbackFunction = function(data) { ... }

    // make request using Mithril.js
    m.request({ dataType: 'jsonp', url: 'http://somedomain.com/static-file.js'});

    // or with jQuery
    jQuery.getScript('http://somedomain.com/static-file.js');

But I want to do:

    m.request({
        dataType: 'jsonp',
        callback: 'someCallbackFunction',
        url: 'http://somedomain.com/static-file.js'
    }).then(function(data) { ... });

It's similar a `jsonpCallback` param on `jQuery.ajax`(http://api.jquery.com/jQuery.ajax/).

**Comment by isiahmeadows** [comment]
@lhorie Sound good for 1.x? It would also be trivial to add to 0.2.x.

**Comment by lhorie** [comment]
Added an options called `callbackName`
