### ISSUE TITLE
Can't use HTML5 patterns in m function

### ISSUE THREAD

**Issue by wedancedalot** [lhorie/mithril.js#1080]
Tried several variations:
```
m('input.[required][pattern="[a-zA-Z0-9]{56}"]');
m('input.[required][pattern=[a-zA-Z0-9]{56}]');
m('input.[required][pattern=\[a-zA-Z0-9\]{56}]');
```
All of those result in 
`<input pattern="[a-zA-Z0-9">`

P.S This is mithril@0.2.5 via npm

**Comment by louisgv** [comment]
Had the same issue upon updating to 0.2.5. Revert back to my previous version (0.2.3) fixed it, haven't tried with 0.2.4 yet.

**Comment by pygy** [comment]
@louisgv could you share an example of a regression between v0.2.3 and v0.2.5? 

@wedancedalot's is broken on both versions, and all the way back to v0.1.0.

**Comment by isiahmeadows** [comment]
By the way, I'd expect the second, unquoted version to fail:

```
input.[required][pattern=[a-zA-Z0-9]{56}]

input .  [ required ] [ pattern = [a-zA-Z0-9 ] {56}]
^     ^  ^ ^        ^ ^ ^       ^ ^          ^ ^
e     d! [ a        ] [ a       = v          ] !
```

*Legend:*

- `e` - element
- `.` - start class
- `[` - start attribute
- `a` - attribute name
- `=` - start attribute value
- `v` - attribute value
- `]` - end attribute
- `!` - possible error

It should throw a more helpful error than something like `TypeError: cannot read property <index> of null` or similar, though.

**Comment by lhorie** [comment]
I pushed a fix that should allow valid patterns as long as they follow standard string escaping rules. Escaping is not allowed outside quoted attribute values. 

This should be valid:

```
m('input[required][pattern="[a-zA-Z0-9]{56}"]')
```

But these should not:

```
m('input.[required][pattern=[a-zA-Z0-9]{56}]')
m('input.[required][pattern=\[a-zA-Z0-9\]{56}]')
m('input.[required][pattern=\\[a-zA-Z0-9\\]{56}]')
```
