### ISSUE TITLE
<input> value gets overwritten on every redraw

### ISSUE THREAD

**Issue by maranomynet** [lhorie/mithril.js#1087]
...regardless of whether it has changed or not.

It's as if `input.value` bypasses the diff algorithm altogether, whereas other types of properties only seem to be reapplied when they change.

Demonstration: https://jsfiddle.net/tezo5c2q/

This is surprising + annoying because it requires hacky special-casing for inputs - if you're not working outside the classic `oninput: m.withAttr('value', gettersetter)` pattern - or alike.

**Comment by lhorie** [comment]
It does this because the model may change differently from what was typed. Under what case is this problematic?

**Comment by maranomynet** [comment]
I'm comfortable with the diff-engine updating `input.value` when the vElm's attrs.value has changed between redraws - but that is not the case. Instead the `input.value` is overwritten/updated on every redraw.

This means `input.value` behaves differently from any other DOM property, attribute or nodeValue.

**Comment by lhorie** [comment]
As far I know it only does that if the input is in [focus](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L1094) AND its vdom node has a `value` property defined.

It needs to ensure that what's in the DOM mirrors what's in the virtual DOM. Here's an example:

```
var data = ""
function update(e) {
  if (data.length < 5) data = e.target.value
}

m.mount(document.body, {
  view: function() {
    return m("input", {oninput: update, value: data})
  }
})
```

In the case above, typing will clamp `data` to be 5 chars long at most, but if the DOM isn't synced to `data`, it will display wrong a value that doesn't match what's in `data` because typing in a input changes the DOM element's state on its own.

I don't understand what problem your jsfiddle is supposed to be demonstrating.

**Comment by maranomynet** [comment]
I guess my jsfiddle could have been more clear.

**Steps to replicate:**
1. Focus the <input> and type in some text.
2. Click anywhere inside the mithril rendered DOM.

**Result:**
The <input> value returns to its initial value - as soon as redraw is triggered by the no-op onclick handler on the containing <div>.

**Expected result:**
No change to the <input> displayed value - as the vdom node's value hasn't changed.

**Note** how if you focus the `<div class="input" contenteditable="true">` element below and type some text into it and then click, the redraw **does not** return the `<div>`'s `innerHTML` to its initial value.

**Comment by maranomynet** [comment]
My real-world use case involves a mithril-generated `<input>` that I want to allow user's to type freely and only parse and update the value property in the model onchange.

However, while I'm typing (and the input field is still focued) I move my mouse and trigger an onmouseover handler elsewhere in the DOM, my field's value gets returned to the last-saved value.

As I said, I know of at least two different ways I can work around this problem - but having to do that seems awkward and inconsistent with how mithril handles other similar cases (as illustrated in the jsfiddle) where the real DOM is left untouched as long as the vdom properties are unchanged.

I find myself unable to explain to my team-members, why mithril behaves this way only with input values. It feels like a bug - or an arbitrary inconsistency at best.

**Comment by lhorie** [comment]
Ah I see. To be honest, that's behaving as it should. The code literally says to set the value to "Default input value" on every redraw.

There are two ways to deal with it: one is to setup a variable to track the input value and update it on the `oninput` event, and the other is to set the initial value via `config`

A third slightly different option would be to use the placeholder attribute (but this one may or may not work for your specific case)

> I find myself unable to explain to my team-members, why mithril behaves this way only with input values. 

The explanation is the snippet I posted above. Basically, there's no way to support that use case and what you're expecting at the same time.

**Comment by maranomynet** [comment]
But why the difference between input.value and div.innerHTML ?

Why the difference between input.value and any other property – like for instance a div with a config function that updates the div's properties on the first draw (i.e. when `isInit===false`). The modified properties stay intact across all 'diff' redraws until the vdom property changes.

**Comment by maranomynet** [comment]
Or is my mistake, perhaps, to make any assumptions at all about the diff behavior?

Should I not be taking advantage of the 'diff' behavior, ever?

If so, how do config functions that initialize third-party plugins/etc. factor into that?

**Comment by lhorie** [comment]
input value almost always changes if the user types so it's relatively common to run into that use case. `innerHTML` typically doesn't react to user input. In the case of a contenteditable div, it might make sense for it to update like input value does, but the code currently doesn't special case it.

`config` breaks out of the diff engine and allows you to modify the DOM however you want. Ideally you should prefer to use the `oninput` solution if you're going to be tracking the data in input value.

**Comment by maranomynet** [comment]
Thank you for the help understanding.

**Comment by maranomynet** [comment]
**Lessons learned:**

1) Don't make any hard assumptions about redraw not updating DOM properties/nodes on next redraw - regardless of if the state has changed or not.
2) Assigning "static" initial value via a config function is the proper way to accomplish what I was trying.  Updated jsfiddle: https://jsfiddle.net/tezo5c2q/1/
