### ISSUE TITLE
Value on select tag not set when options are changed

### ISSUE THREAD

**Issue by epidemian** [lhorie/mithril.js#1091]
Hi! While implementing a form with two selects, i stumbled upon some funky behaviour of the select `value` attribute. Basically, it's the fairly common case of the options of a second select depending on the selected value of the first one. For example:

```javascript
let names = {
  'cat': ['Snowball', 'Scratchy'],
  'dog': ["Santa's Little Helper", 'Poochie', 'Brian'],
  'horse': ['Duncan']
}

function controller() {
  var ctrl = this
  ctrl.kind = 'cat'
  ctrl.name = 'Snowball'
  ctrl.chooseKind = (kind) => {
    ctrl.kind = kind
    ctrl.name = names[kind][0]
  }
}

function view(ctrl) {
  return [
    'Kind:', 
    m('select', 
      {value: ctrl.kind, onchange: m.withAttr('value', ctrl.chooseKind)},
      Object.keys(names).map(optionTag)),
    'Name:',
    m('select', 
      {value: ctrl.name, onchange: m.withAttr('value', (v) => ctrl.name = v)}, 
      names[ctrl.kind].map(optionTag)),
  ]
}

function optionTag(value) {
  return m('option', {value}, value)
}

m.mount(document.body, {controller, view})
```

In this case, everything [works fine](https://jsfiddle.net/epidemian/hbgvsqo0/): when the pet kind is selected, the first possible name for that kind is selected too. But it only seems to work because each pet kind has a different number of names.

If all pet kinds have the same number of names, and all name arrays start with a different name, then when the pet kind select is changed, the name select changes its options too but [does not display any selected value](https://jsfiddle.net/epidemian/hbgvsqo0/1/) (even though the controller state is correctly updated). Which is not a very happy behaviour:

![select-value-funk](https://cloud.githubusercontent.com/assets/722544/15797740/804b107e-29f8-11e6-9349-c805b323c72d.png)

Curiously, if two pet kinds share the first of their possible names, then switching between them updates the name value correctly. For example, in [this example](https://jsfiddle.net/epidemian/hbgvsqo0/2/), the cat and dog kinds share the same name option, "Max", while the horse kind doesn't (each of them has 2 possible options). Switching between cat and dog updates the name select correctly, but not when switching between cat/dog to horse or vice versa.

Does this look like a bug? Or am i doing something fundamentally wrong here?

A couple of workarounds i've found:

 * Setting the redraw strategy to "all" on the select change handler [makes everything work fine](https://jsfiddle.net/epidemian/hbgvsqo0/3/), which seems to indicate that there's something funky going on on the DOM diffing strategy, at least for select values. I'd prefer to avoid recreating all the DOM from scratch each time a select changes.

 * Setting a key attribute on the name select makes the selects work OK, but has the side effect of [screwing up their positioning](https://jsfiddle.net/epidemian/hbgvsqo0/4/) on the DOM:

    ![select-value-funk-2](https://cloud.githubusercontent.com/assets/722544/15797838/9d92d178-29fb-11e6-82b2-605893dccf3b.png)

    Weird. I don't know if this is intended behaviour either (if it isn't, please let me know and i'll create a separate issue).

 * Setting key attributes on the name select options. Does *somehing*, in the sense that it doesn't leave the selects with a blank value, but they don't seem to behave correctly either. For example, in [this case](https://jsfiddle.net/epidemian/hbgvsqo0/5/) the cat names are Max and Snowball, and the dog names are Poochie and Max (in that order). When switching from cat to dog, the selected name on the DOM is Max (at least it's not blank!), even though it should be Poochie (and it is in the controller state).

    At this point i should probably admit that i don't have a very good grasp on how the key attribute works :sweat_smile: 

The affected Mithril version is 0.2.5, and this was tried mostly on Firefox, but Chrome seems to have the same behaviour.

Thanks!

**Comment by isiahmeadows** [comment]
Does an explicit redraw fix the problem, specifically in your `onchange` handler?

**Comment by epidemian** [comment]
@isiahmeadows nope. I tried an explicit m.redraw call on the onchange handler but it had no effect. Kinda makes sense, as the onchange triggers an auto-redraw after it's finished anyway. 

What *does* make a difference is to set the redraw strategy to "all", so that that auto-redraw recreates the entire DOM from scratch. I think this points to there being some bug on the diffing code. Note that the \<option\> tags are always rendered correctly; only the \<select\>'s value seems to be having problems.

**Comment by vicnicius** [comment]
@epidemian This is probably related to https://github.com/lhorie/mithril.js/issues/912 which should be fixed on rewrite. Right now, to make your example work properly, you would need explicitly set your select components key and also your option components key. Did a [quick tweak on your example](https://jsfiddle.net/2h3jdo4e/).

**Comment by epidemian** [comment]
@vicnicius Thanks for the pointer to #912. That seems to be the same bug i mentioned in the second workaround. So that's taken care on the rewrite :smile_cat: 

However, using keys for both the selects and their options as you propose has the same problem i mentioned in the third workaround. Take a look of [this tweak of your tweak](https://jsfiddle.net/epidemian/2h3jdo4e/4/) hehe. I only changed the `names`. Notice that when switching from cat to dog, the name Max is selected, though it should be Poochie (and it is on the controller state). When switching from horse to dog, the correct dog name is seleted.

In my real code (i'm not doing a pet naming app BTW :stuck_out_tongue:) i think i can get away with setting a dynamic key on the second select though (to force it's re-creation). It shouldn't have the reordering problem from #912 as long as the keyed select is not a sibling to text nodes.

That being said, i'll leave this issue open, as forcing node recreations shouldn't be necessary to get selects working properly. If i have some spare time, i'll try to take a stab at fixing this. BTW, are changes to Mithril 0.2.x still accepted, or should i try this on the rewrite branch and try to fix it there if it's still a problem?

**Comment by tivac** [comment]
@epidemian Please feel free to fix bugs against `next`, they're still being merged when they come up! :+1:

**Comment by tivac** [comment]
Interestingly, this doesn't seem to be broken if you instead use `selected.selectedIndex`.

https://jsbin.com/mazise/2/edit?js,output

**Comment by epidemian** [comment]
@tivac wow, i didn't know about `selectedIndex`. Thanks!

And thanks for the pointer to the `next` branch too :blush:

**Comment by epidemian** [comment]
@tivac BTW, and for future reference, the example on jsbin is failing for some reason (raises a `TypeError: m.withAttr is not a function` on redraws), but the same thing [works fine on jsFiddle](https://jsfiddle.net/epidemian/2h3jdo4e/5/).

**Comment by tivac** [comment]
@epidemian JsBin is working fine for me in multiple browsers. It does seem to hiccup from time to time but I'll take an occasional hiccup over the jsfiddle UI any day.

**Comment by epidemian** [comment]
[offtopic]

@tivac that's funny. For me that jsbin works fine on the first render but after that it seems `m` is somehow set to "4" and so subsequent calls to `view` fail. Some weird jsbin bug assigning minified variables i imagine :confused:

**Comment by lhorie** [comment]
@epidemian I get that all the time too... drives me nuts :/

**Comment by pygy** [comment]
@epidemian [still off-topic] I missed this post initially... I get it systematically too. To make JSBin work reliably with Mithril, you must wrap the JS section like this:

```JS
( function (m){

// the code here

}(m) )
```

The inner `m` remains bound to Mithril whatever happens to the global `m` afterwards.

**Comment by isiahmeadows** [comment]
@pygy Adds to the list of reasons why I don't use JSBin... :wink:

**Comment by isiahmeadows** [comment]
Well...this bug is fixed (thank you @epidemian).
