### ISSUE TITLE
Empty attributes do not get added

### ISSUE THREAD

**Issue by realdope** [lhorie/mithril.js#1093]
The new release of Mithril.js appears to drop empty attributes when creating video elements using m(). This was working in 0.2.3.

For example, m('video[width=200][height=100][loop][autoplay]') would create ` <video width="200" height="100">` but does not add loop and autoplay.

[JSBin](http://jsbin.com/xowafigufu/edit?html,css,js,output)

**Comment by isiahmeadows** [comment]
@lhorie Should we backport the hyperscript parser from the rewrite? I know it works there.

**Comment by lhorie** [comment]
Fixed
