### ISSUE TITLE
Unable to dynamically set className on SVG element

### ISSUE THREAD

**Issue by sebastiansandqvist** [lhorie/mithril.js#1097]
### Description:

I have an SVG `Icon` component which is itself just `m('svg.Icon', vnode.attrs, vnode.children)`. When `attrs` contains a className (in order to add a dynamic className besides `Icon`) an error is thrown, but not initially. It works fine until `onupdate`.

Seems like it could be a simple fix:
https://github.com/adobe-webplatform/Snap.svg/issues/414
If the comments there are true, it's just a matter of using `setAttribute` or `className.baseVal` when the element is an svg.

### Steps to Reproduce:

```javascript
const Icon = {
  view(vnode) {
    return m('svg.Icon', vnode.attrs, vnode.children);
  }
};

const FooIcon = {
  view(vnode) {
    return m(Icon, {className: 'foo'}, m('path', {d: '' }) ); // empty path for simple demo
  }
};
```

### Expected:

SVG element should have className of `Icon foo`

### Actual:

`Uncaught TypeError: Cannot set property className of #<SVGElement> which has only a getter`

https://github.com/lhorie/mithril.js/blob/rewrite/mithril.js#L532

**Comment by lhorie** [comment]
Fixed in 693c87f5f1513d37e5a6a291ccc50f32503f8a22
