### ISSUE TITLE
mithril with dom animation

### ISSUE THREAD

**Issue by futurist** [lhorie/mithril.js#1099]
### Description:

Mithril with dom animation strange behavior

### Steps to Reproduce:

1. Please check below URL
https://jsfiddle.net/futurist/eaqqLqs9/4/

2. Click on **text1**, then click on **text2**, then click on **text4**

### Expected:

Click on each text item, it should fade out then removed from dom, not effect other items.

### Actual:

1. click **text1**, it's ok

2. click **text2**, **text3** disappeared. (why? )

3. click **text4**, **text6** disappeared. (and **text5** untouched? strange)

**Comment by indus** [comment]
that is because you are are removing elements according to their **initial** position in the array. But you also change the position every time you remove one.

after the first ```splice``` element "2" is at index 0 and "3" is at index 1; so when you make your second splice starting at index 1 you obviously remove "3".

``` javascript
//start
["1","2","3","4","5", ...]

// click on "text1" -> splice(0,1) gives
["2","3","4","5", ...]

// click on "text2" -> splice(1,1) gives
["2","4","5", ...]
// "text2" is still in the DOM but is hidden because of "fade-out"
```

you may want to use ```indexOf``` to find the current index of an element in the array

**Comment by isiahmeadows** [comment]
That is odd.

@indus Not exactly - [it works as intended when not animating](http://codepen.io/isiahmeadows/pen/wWWbrm?editors=0010), and [it works with vanilla JS](http://codepen.io/isiahmeadows/pen/ezzaGw?editors=1010).

**Comment by bruce-one** [comment]
I don't think it's a diffing issue.

I think it's wrapping the value of `args.i` in the click listener, and hence doing the `arr.splice(1, 1)` when the "first" element is clicked the second time.

Afaict, https://jsfiddle.net/eaqqLqs9/5/ fixes it?

(Not saying it's the best solution, but it demonstrates the modification to `args.i`)

(Add a `console.log('splicing from ' + args.i)` to the click listener to demonstrate the value of args.i used.)

**Comment by isiahmeadows** [comment]
@bruce-one That does appear to fix it for at least me.

(Oh, and BTW, you can always add the `click` handler within `if (!isInit)`, so you're only adding it once. just a little nit.)

**Comment by isiahmeadows** [comment]
The problem is that this needs keys to properly work.

**Comment by isiahmeadows** [comment]
I get the feeling it's because you have to deal with a newly different state, and your config has to react accordingly.
