### ISSUE TITLE
Get route URL

### ISSUE THREAD

**Issue by andi1984** [lhorie/mithril.js#1102]
Hi, 

I've a basic question. As far as I know the public API there is actually no way of getting an URL for a specific route name and maybe further parameters in case of a parametrized route like (project/:id). Is that correct?

I would like to have something like:

```html
<a href="getRouteURL('project', {id: 2})">...</a>
```

to return a URL like ``..../#/project/2`` in case I'm using ``route.mode = 'hash'``.

Hope my point is clear.

Thx in advance!

**Comment by lhorie** [comment]
I think this library is what you're looking for:

https://www.npmjs.com/package/mithril-router

**Comment by andi1984** [comment]
@lhorie Thx. Works like a charm! Any ideas to provide this functionality out-of-the-box with Mithril? Or will the router stay as simple and lightweight as it is right now? Have to say that I'm missing this reverse method in Mithril, but only my 2 cents. Can also understand to keep the router as simple as possible.

With that I close the issue, but would be nice if you could still give some feedback on the long-term perspective of Mithril. Thx!
