### ISSUE TITLE
m.route breaks back button when defaultRoute is triggered

### ISSUE THREAD

**Issue by sebastiansandqvist** [lhorie/mithril.js#1105]
### Description:

Using the rewrite with `m.route.prefix('')`, whenever the default route is triggered because the requested route did not have a corresponding path in the route definitions, it is impossible to use the browser's back button because it takes you back to the invalid url which is once again forwarded to the default route.

When forwarding the user to the default route, the invalid route should not be kept in history--only the prior valid route should. I believe that would resolve this issue.

### Expected:

Expected to be able to navigate back from a redirect to the default route.

### Actual:

Was unable to navigate back from a redirect to the default route.

**Comment by lhorie** [comment]
fixed in 084d99f125bbbcf54f7d3d2da8463335cebe840f
