### ISSUE TITLE
Include mithril.d.ts in NPM package

### ISSUE THREAD

**Issue by renstrom** [lhorie/mithril.js#1107]
### Description:

Include `mithril.d.ts` in the NPM package. TypeScript will automatically resolve it that way, see https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html for more information.

### Expected:

Get Mithril type information without going through the steps outlined in https://github.com/lhorie/mithril.js/blob/next/docs/tools.md#typescript-support

**Comment by isiahmeadows** [comment]
Done. Welcome!
