### ISSUE TITLE
Request data to variable

### ISSUE THREAD

**Issue by Lafriakh** [lhorie/mithril.js#1112]
### Description:

i want store request data on variable.
like this :
### Steps to Reproduce:

```
var Request = m.request({
            method: ''GET,
            url: 'http://example.com/json'
        });

console.log(Request);
```

### Expected:

i want  Request variable content json object 
### Actual:

it's return function b(){return arguments.length&&(a=arguments[0]),a}

**Comment by Bondifrench** [comment]
If you have a look at the documentation for [m.request](http://mithril.js.org/mithril.request.html), what's returned by `m.request` is an `m.prop` (ie a getter-setter)
so to see what is stored in Request (ie the result of your m.request()), you need to use the getter part of `m.prop` so:
`console.log(Request()) ` will return what you are expecting.

this is how `m.prop()` works:
````
 var users = m.prop();
````
to get the value of users, you just call `users()`
to set the value of users you write `users('Lafriakh')`

**Comment by lhorie** [comment]
What @Bondifrench said is correct but there's one caveat: m.request resolves asynchronously, so simply calling `Request()` right after the call will return `undefined`.

If you want to work with the resolved value in a controller, you should use promise chaining, e.g.

```
var Request = m.request(...)
Request.then(function(value) {
  //do stuff with value here
})
```

**Comment by Lafriakh** [comment]
@lhorie @Bondifrench Thanks to reply :smile: 
what if i want to create function return only data of the request like these:
```
function Request(option) {
	m.request(option).then(function(value) {
	  	return value;
	})
}
```
it's return undefined.
i think its because then return promise, is there any solution.

**Comment by lhorie** [comment]
You can't return a value from a asynchronous request. `return` is synchronous.

`m.request` and `.then` return promises, so you can keep chaining them if you need to further process the data

for the purpose of displaying the data in the view, you can do this:

```
var MyComponent = {
  controller: function() {
    this.data = m.request({method: "GET", url: "/api/things", initialValue: []}) // this.data is a promise
    console.log(this.data()) // logs an empty array (the initialValue)
  },
  view: function(ctrl) {
    return m("ul", ctrl.data().map(function(item) {
      return m("li", item.name)
    }))
  }
}
```
