### ISSUE TITLE
Error in todo example on edge browser.

### ISSUE THREAD

**Issue by saniko** [lhorie/mithril.js#1118]
SCRIPT5007: Unable to get property 'todos-mithril' of undefined or null reference

**Comment by isiahmeadows** [comment]
A stack trace would make this far easier to fix, by the way. :wink:

**Comment by saniko** [comment]
HI,
No stack trace..
This is the only error i get on console.

**Comment by lhorie** [comment]
Can you provide a jsfiddle showing the issue?

**Comment by tivac** [comment]
Closing due to lack of response.
