### ISSUE TITLE
Rendering a view with m.trust() inside an SVG element throws uncaught exception in Safari

### ISSUE THREAD

**Issue by raykyri** [lhorie/mithril.js#1123]
### Description:

m.trust() uses the parent.insertAdjacentHTML() API, which is not available on SVG elements in Safari.
### Steps to Reproduce:

See JSFiddle: http://jsfiddle.net/65pPq/12/

```
m.render(test, m("svg", {
    width: 100,
  height: 100,
}, [
    m("text", {
    stroke: "black",
    transform: "translate(0,20)"
  }, [
    "Go ",
      m.trust("&#9656;")
  ])
]));
```
### Expected:

A right triangular arrow should render next to the text.
### Actual:

A right triangular arrow does not render next to the text, and an error is produced in the JavaScript console. When the render code part of a refresh cycle, the uncaught exception prevents the rerender from completing successfully.

**Comment by isiahmeadows** [comment]
If you can figure out a replacement API that works, [here's the function](https://github.com/lhorie/mithril.js/blob/f226d5648108b42d2418b3d1ef1bf4c588af39dc/mithril.js#L1170-L1177).

**Comment by barneycarroll** [comment]
Vote to close: the bug was fixed in Safari in 2012, ie version 6.

https://bugs.webkit.org/show_bug.cgi?id=92903

**Comment by isiahmeadows** [comment]
@barneycarroll Yeah...Nobody thinks to check the WebKit tracker, it seems... (They don't especially promote it anywhere, though, not nearly to the degree that the other browser implementors do.)

**Comment by barneycarroll** [comment]
The OP makes it fairly clear this is a known browser defect. I'm just citing the ticket's resolution date as an argument for "won't fix".
