### ISSUE TITLE
m.route() is wrong after onunload calls event.preventDefault()

### ISSUE THREAD

**Issue by 2is10** [lhorie/mithril.js#1126]
### Description:

`m.route()` seems unaware that a component has canceled a navigation. Using Mithril v0.2.5, all browsers are affected.

### Steps to Reproduce:

https://jsfiddle.net/m01dw250/1/
1) Click the “Help” link.
2) Click the “Home” link.

### Expected:

`m.route()` should still be `"/help"`, since the `Help` component canceled the navigation.

### Actual:

`m.route()` is `"/"` as if the navigation had succeeded.

**Comment by isiahmeadows** [comment]
Seems like it shouldn't be hard enough to fix. Contributions welcome.
