### ISSUE TITLE
Velocity.js animations in Mithril passing 'id'

### ISSUE THREAD

**Issue by majka-dev** [lhorie/mithril.js#1127]
### Description:

Hi, 
I just found little mistake in your tutorial for using velocity in Mithril. 
http://lhorie.github.io/mithril-blog/velocity-animations-in-mithril.html
'key' should equal to 'person.id' not only an 'id'. ;)

Have a nice day, 
Maria
### Steps to Reproduce:

```
var view = function(ctrl) {
    return m("ul", [
        people.map(function(person) {
            return m("li", {
                key: id,
                onclick: ctrl.remove.bind(this, person)
            }, person.name)
        })
    ])
}
```
### Expected:

```
var view = function(ctrl) {
    return m("ul", [
        people.map(function(person) {
            return m("li", {
                key: person.id,
                onclick: ctrl.remove.bind(this, person)
            }, person.name)
        })
    ])
}
```

**Comment by isiahmeadows** [comment]
@majka-dev PRs welcome!

**Comment by barneycarroll** [comment]
The code for the blog is over here: https://github.com/lhorie/mithril-blog

Pull requests don't seem to be addressed @lhorie?

**Comment by lhorie** [comment]
Oh, I totally wasn't checking that. Thanks for the heads up, @barneycarroll

**Comment by barneycarroll** [comment]
@lhorie ping!

**Comment by lhorie** [comment]
Fixed
