### ISSUE TITLE
[rewrite] Piecemeal usage

### ISSUE THREAD

**Issue by tivac** [lhorie/mithril.js#1132]
There have been multiple calls for mithril to be made more modular, and I think there's some value in that. With the way the `rewrite` branch has been structured that's now possible, so here's an approach at defining how you might actually use just certain pieces of mithril.

This continues from the previous discussion in https://github.com/lhorie/mithril.js/issues/1044#issuecomment-222202813

``` js
// Everything
var m = require("mithril");

// Just the hyperscript function
var m = require("mithril/m");

// Just the router
var router = require("mithril/router");
```

This complicates manual redrawing some since `m.redraw()` won't just be stuck on `m` for users doing the piecemeal requires, but that can probably be another module that can be grabbed if necessary.

``` js
var mount = require("mithril/mount");
var redraw = require("mithril/redraw");

mount(document.body, Component);

setTimeout(redraw, 1000);
```

**Comment by hugufc** [comment]
I think that `router` requires a `redraw` as a peer dependecy, whatever it is mithril or third party.

**Comment by isiahmeadows** [comment]
@hugufc I'm not sure how useful the router is without Mithril itself. The routing is inherently coupled mainly because of the API itself, and there's hardly a use case. It's simple enough you could adapt it to something else, though (and it could be done within a few hours max unless you all have very testing requirements comparable to NASA's).

**Comment by lhorie** [comment]
update: I merged @sebastiansandqvist's PR as a starting point for this and made a few changes

Currently, these piecemeal modules exist:

- mithril/route
- mithril/mount
- mithril/stream
- mithril/render
- mithril/redraw

The only caveat the last two expose the parent object and not the method themselves, so consider them work in progress. The reason I haven't exposed those two properly has to do w/ some issues in bundler that I need to fix...

I haven't aliased `mithril/render/hyperscript` and `mithril/render/trust` but those should be easy to do if anyone wants to send a PR

**Comment by isiahmeadows** [comment]
With the current state of things, I'd consider this done.
