### ISSUE TITLE
[rewrite] No JSON-P docs yet

### ISSUE THREAD

**Issue by Bondifrench** [lhorie/mithril.js#1136]
### Description:

[Link](https://github.com/lhorie/mithril.js/blob/rewrite/docs/jsonp.md) for JSON-P in `request` [docs](https://github.com/lhorie/mithril.js/blob/rewrite/docs/request.md#why-xmlhttprequest-instead-of-fetch)

### Steps to Reproduce:

Click on JSON-P [link](https://github.com/lhorie/mithril.js/blob/rewrite/docs/jsonp.md)
### Expected:

docs for JSON-P
### Actual:

Gives a 404 page

**Comment by tivac** [comment]
Clarified the issue some. It's not that the link is wrong, necessarily. There just aren't any JSON-P docs for the rewrite yet.

https://github.com/lhorie/mithril.js/tree/rewrite/docs

**Comment by lhorie** [comment]
yeah, I just haven't gotten around to writing it yet
