### ISSUE TITLE
diffing algorithm bug with key attribute

### ISSUE THREAD

**Issue by longztian** [lhorie/mithril.js#1141]
### Description:
I split an item list into segments (pages), and have a pager component. The pager HTML element from the previous view gets left over when I load different pages (segments of the item list)

This should be a diff bug, because the HTML elements are not rendered correctly, pager element from the previous view won't get cleared.
This should be also related to the "key" attribute, when I comment out the key attribute, the app can render correctly (pager is created as expected)
Removing the key attribute will show expected pager behaviour, but I do need the key attribute because I will slice the items array.

### Steps to Reproduce:

test page (click the page numbers to show the bug):
https://jsfiddle.net/85b6tvuj/1/

```javascript
var store = [
  [11,12],
  [21,22,23],
  [31,32,33,34]
];

var app = {
  controller: function(){
    var pageNo = 1;
    if (window.location.hash.length > 1) {
      pageNo = window.location.hash.substring(1);
    }

    var self = this;

    this.pager = {
      pageNo: pageNo,
      pageCount: store.length,
      handler: self.loadPage
    };

    this.loadPage = function(i) {
      self.items = store[i-1];
      self.pager.pageNo = i;
      window.location.hash = "#" + i;
    }

    this.loadPage(pageNo);
  },
  view: function(ctrl){
    var body = ctrl.items.map(function(item){
      return m("div", {
          key: item            // pager works, if comment out this line
        }, "text " + item);
    });

    if (ctrl.pager.pageCount > 1) {
      var pager = m.component(Pager, {
        current: ctrl.pager.pageNo,
        count: ctrl.pager.pageCount,
        handler: ctrl.loadPage
      });
      body = [pager, body, pager];
    }

    return m("div", body);
  }

};

var Pager = {
  controller: function(data) {
    this.goToPage = function(i) {
      return function(ev){
        data.handler(i);
      };
    }
  },
  view: function(ctrl, data) {
    var links = [];
    for(var i = 1; i <= data.count; i++) {
      links.push(m("a", i == data.current ? {"class":"active"} : {onclick: ctrl.goToPage(i)}, i));
    }
    return m("nav", links);
  }
};

m.mount(document.getElementById("app"), app);
```

### Expected:
only two pager elements exist on the page

### Actual:
multiple pager elements at the bottom get left over while clicking the page numbers

**Comment by ikki3355** [comment]
Thanks for the explanation, bruce-one.
Both solutions work well for me.

Regards,
Longzhang

**Comment by tivac** [comment]
Nice catch @bruce-one, :+1:
