### ISSUE TITLE
How to expose methods of a component?

### ISSUE THREAD

**Issue by josdejong** [lhorie/mithril.js#1142]
I'm playing around with Mithril for the first time. I would like to use it to create a library which internally uses Mithril. 

There is one basic thing I cannot figure out: how to expose methods and have the controller and view updated when calling the method externally?

```js
function createMyComponent (container) {
  function controller() {
    const myData = m.prop('some text')

    return {
      myData,

      setMyData: function (text) {
        myData(text)
      },

      getMyData: function () {
        return myData()
      }
    }
  }

  function view(ctrl) {
    return m('div', [], ctrl.myData())
  }

  // initialize and expose the controller (methods setMyData, getMyData)
  return m.mount(container, {controller, view})
}
```

Now I would like to use this component externally like:

```js
const component = createMyComponent(document.getElementById('container'))

component.setMyData('other text')   // problem: view doesn't update
```

When I call the methods `setMyData` and `getMyData`, the state of the component (property `myData`) is updated, however, the view isn't updated. Do I have to trigger a redraw somehow?

**Comment by mindeavor** [comment]
@josdejong Yes, I believe you'll have to trigger the redraw yourself. Mithril will auto-draw in three cases:

1. Initial draw when using `m.mount` or `m.route`
2. After running a mithril-attached browser event listener (`onclick`, etc.)
3. After an `m.request` completes.

This is sufficient for 90% of cases; in the other cases, you'll have to call `m.redraw()` yourself.

**Comment by josdejong** [comment]
Thanks @mindeavor , I've changed the set method to:

```js
      setMyData: function (text) {
        myData(text)
        m.redraw()
      }
```

which indeed updates the view, that solves my issue. 

There are two things I still don't understand:
- Is this `m.redraw()` an expensive one or the same (diffing) mechanism used to update the view when you press a button in an input field or something like that? 
- I'm wondering though how `m.redraw()` knows which view to update since I don't pass it anything. I don't like that sort of "magic" and it's completely the opposite of the functional approach of Mithril that's so appealing to me. I guess `m` keeps a list with all views on the page and  `m.redraw()` updates all views on the whole page?

**Comment by syaiful6** [comment]
@josdejong yes it same mechanism. Mithril run the diff algorithm on dom events. Yes, basically all virtual dom implementation "keep" the dom representation and run diff algorithm to know which one should be updated on real dom. So, m.redraw() doesn't updates all view.

**Comment by barneycarroll** [comment]
@josdejong redraws are global, so there's no need to worry about which part of the view needs to update — Mithril will re-execute every mounted component and determine if anything needs to change.

**Comment by josdejong** [comment]
Thanks for the feedback. You're right: when the diffing algorithm does it's job there is no need to worry about forcing a redraw of "everything".
