### ISSUE TITLE
In rewrite, even if successful, m.jsonp seems to trigger error

### ISSUE THREAD

**Issue by Bondifrench** [lhorie/mithril.js#1143]
### Description:

Trying to emulate the example `Loading icons and error messages` given in the rewrite docs for `m.request` 
### Steps to Reproduce:

See [Jsfiddle](https://jsfiddle.net/dpxgtdmj/4/)
### Expected:

`vnode.state.error` should only be populated if error happens not when `vnode.state.items()` gets populated

### Actual:

both `vnode.state.items` and `vnode.state.error` get populated
See [jsfiddle](https://jsfiddle.net/dpxgtdmj/4/)

Did I miss something or is it a bug in the `m.jsonp()` method?

**Comment by lhorie** [comment]
Sorry, it's actually an error in the docs. I've updated it and modified your jsfiddle to make it work on both success and error cases
