### ISSUE TITLE
[rewrite] reused vnodes lead to infinite recursion

### ISSUE THREAD

**Issue by mpfau** [lhorie/mithril.js#1150]
### Description:

An infinite recursion occurs if a single vnode is used below multiple component instances (and therefore copied multiple times:
* after the first processing of the parent component, the dom-attribute is defined with its dom element on the "identicalChild" vnode. 
* During the second processing of the vnode, the copy method recurses through the vnode structure which contains a reference to an HTMLElement (which has circular references).

### Steps to Reproduce:

```
    let identicalChild = m("span.icon", "huhuu")
    class TestComponent {
        constructor(child) {
            this.child = child
            this.view = () => m("div", this.child)
        }
    }
    // after the first processing of component, the dom-attribute is defined with its dom 
    // element on the "identicalChild" vnode. During the second processing of the vnode,
    // the copy method recurses through the vnode structure which contains a
    // reference to an HTMLElement (which has circular references).

    let component = new TestComponent(identicalChild)

    m.mount(document.body, {
        view: function () {
            return m("div", {
            }, [m(component), m(component)])
        }
    })
```

### Expected:

An infinite recursion shouldn't occur when reusing vnodes.

### Actual:

An infinite recursion occurs.

**Comment by mpfau** [comment]
A quick fix would be to patch the copy method (https://github.com/lhorie/mithril.js/blob/rewrite/mithril.js#L707) to ignore the dom-attribute on vnodes:
```
for (var i in data) if (i !== 'dom') output[i] = copy(data[i])
```

Or would it be better to ignore any attributes of type HTMLElement?

**Comment by pygy** [comment]
If the vnode maps to the same concrete element, there will be more problems, since a given element can't be inserted in several places in the DOM tree (it is removed from the previous parent when inserted in the new one).

**Comment by mpfau** [comment]
True, but then we should throw an explicit error if a vnode is reused.

**Comment by lhorie** [comment]
would it perhaps make more sense to only shallow copy?

**Comment by mpfau** [comment]
That would solve the problem with the infinite recursion. But it wouldn't solve the problem with the 1:1 association between vnode and dom element.

I don't know if we really need to reuse vnodes. I am currently recycling vnodes only for svg images/icons. But this is a premature optimization. I thought that it wouldn't be a good idea to invoke m.trust for every icon during every render-step. But after inspecting the source of m.trust and Node, it seems that this shouldn't be a performance problem... :)

**Comment by lhorie** [comment]
re: reusing vnodes - I don't recommend reusing vnodes. The diff engine assumes non-memoized vnodes for performance reasons (basically to avoid having to copy the entire tree to ensure a stable diff).  Recreating vnodes (especially via m.trust) is super cheap relative to their dom creation cost and will likely never be a bottleneck.

There were some discussions in the chat regarding experimental usage of memoization with streams to achieve onbeforeupdate-like behavior, but I haven't had a chance to explore all the corner cases. For anything else, I think reusing vnodes will do more harm than good.

**Comment by lhorie** [comment]
I changed the code to only shallow copy
