### ISSUE TITLE
[rewrite] onremove is only called on top-level components

### ISSUE THREAD

**Issue by sebastiansandqvist** [lhorie/mithril.js#1155]
### Description:

The `onremove` lifecycle hook runs on top level components, but when their descendants are also removed as a result of the parent being removed, their `onremove`s are never called.

### Steps to Reproduce:

https://jsfiddle.net/jwa7phmq/1/

**Comment by leeoniya** [comment]
FWIW, i've gone through this issue in my own lib [1] [2].

In the end I had to give up a bunch of emoval optimizations and always do bottom-up removal in case there are deep lifecycle hooks to trigger. It gets even more hairy when those hooks can invoke async css transitions to animate out, delaying parent removal until resolution (i don't handle this case as it is complex and uncommon). Some things to consider ;)

[1] https://github.com/leeoniya/domvm
[2] https://leeoniya.github.io/domvm/demos/lifecycle-hooks.html

**Comment by lhorie** [comment]
fixed in 519b352c2c05ae7e7a94f23ace60c8d47dbad540
