### ISSUE TITLE
Expectations when applying `config : m.route` to a link & binding `onclick`

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1164]
### Description

[As discussed in the chatroom recently](https://gitter.im/lhorie/mithril.js?at=578ddd9d179b42515e221e31) there's an ambiguity over expected behaviour when a link has both a `config : m.route` and an `onclick` handle. [As seen here](http://jsbin.com/guceti/1/edit?js,output), the `routeUnobtrusive` callback never fires.

### Steps to Reproduce:

```js
m.route( document.body, '/', {
  '/' : {
    controller : function(){
      alert( 'Route loaded' )
    },
    
    view : () =>
      m( 'a', {
        textContent : 'Hello',
        href        : '/',
        config      : m.route,
        onclick     : e => {}
      } )
  }
} )
```

### Expected:

The `onclick` handler should trigger first, followed by the `routeUnobtrusive` handler (unless the `onclick` handler stops immediate propagation). You can see this generic behaviour — without Mithril's `m.route` behaviour — in action [here](http://jsbin.com/guceti/6/edit?js,output).

### Actual:

`routeUnobtrusive` never fires.

**Comment by isiahmeadows** [comment]
So, basically, it should be using `addEventListener("click", ...)` + IE fallback instead.

**Comment by barneycarroll** [comment]
False alert: this does work — attributes including inline event handlers are bound during build, unobtrusive route config listeners are attached after injection — the test case was broken. [Here's a demo](https://jsbin.com/yudaqa/edit?js,output).

To prevent a route change from within a click handler, either:
1. Return `false`
2. Explicit invoke `e.stopImmediatePropagation()` to stop the config handler firing, and `e.preventDefault()` to prevent native link behaviour
