### ISSUE TITLE
ospec: consider to replace 'equals' with 'deepEquals'

### ISSUE THREAD

**Issue by longztian** [lhorie/mithril.js#1167]
The goal is to make things as simple as possible.

I think it is very rare to check whether two object references point to the same object. Most of the time, we care about values/states of an object.

So the test framework only needs the 'deepEquals' assertion. We can name it 'equals'.

What do you think?

**Comment by lhorie** [comment]
I use `equals` for DOM element comparisons

**Comment by longztian** [comment]
@lhorie good to know that there are cases for reference comparison
