### ISSUE TITLE
[rewrite] Questions about rewrite migration breaking changes

### ISSUE THREAD

**Issue by veloce** [lhorie/mithril.js#1176]
I'm currently testing the rewrite branch in my application: 
https://github.com/veloce/lichobile/pull/387

I want to say a big "thank you!" to @lhorie and all contributors.
I tested quickly with chrome timeline: it much more fast than the v0.2. My most complex screen (game analysis) appears to be about 2x faster (unoptimized) than the previous (optimized) version (with precompiled templates and `{ subtree: retain }` in all places).

I could migrate quite easily the code base so far, so this is all good. Also I have a couple of questions due to undocumented breaking changes that I found.
- there is no support for `pushState` api while using the `file:` protocol. I don't get why since it was supported in v0.2?
- when calling `m.route.set(path)` on the same route we are currently on, nothing happens. Again this was not the case in v0.2. I have a use case where I need to reload the current screen. In v0.2 I could do this either with `m.redraw.strategy('all')` or calling `m.route(path)` on the same route. Can we restore this `m.route` behavior in v1.0, or is there a way to do this in 1.0 that I don't see?
- there is no more `unwrapSuccess` and `unwrapError` options in m.request. It's not a big deal since we can access `xhr` object in `config` option. But the latter was convenient to get xhr status in error rejection handler for instance.
- the `background` option in m.request is not there anymore. I assume this is simply not relevant anymore in v1.0?

**Comment by tivac** [comment]
Wish I could authoritatively answer more of these, but I can help w/ at least one!

> the background option in m.request is not there anymore. I assume this is simply not relevant anymore in v1.0?

Correct, `m.request` no longer triggers a redraw.

**Comment by lhorie** [comment]
- there is no support for pushState api while using the file: protocol. It's actually Chrome that doesn't support it
- when calling m.route.set(path) on the same route we are currently on, nothing happens: this one should probably be flagged as a bug if no redraw occurs. I'm not planning on re-adding semantics for redraw from scratch in route change because it was creating a need for API complexity that no one liked
- there is no more unwrapSuccess and unwrapError options: I felt like accessing xhr should stay within the `extract` option, and that the unwrap options could be achieved via chaining
- the background option in m.request is not there anymore: redraws are no longer "blocked" by requests, so I feel like there's no need for this flag (but contrary to what @tivac said, m.request does trigger a redraw)

**Comment by tivac** [comment]
Shows what I know :disappointed:

**Comment by veloce** [comment]
For the pushState problem, I'm using a chrome with disable security flag, that's why I don't see the error I guess :)

But when I test in my android app (it's a cordova app so it's using the `file:` protocol too, but in a webview maybe security checks for pushState are different, I've actually no idea), I see that a route change triggers a full reload (because of the added condition). And in version 0.2 is was working properly as a single page app.

Something I forgot to mention: I'm using `m.route.prefix('?')` because the default route prefix has changed since v0.2, the default is now '#'. Maybe that's something to add in the migration guide?

**Comment by lhorie** [comment]
Hmm maybe I should make that code branch only for Chrome then

**Comment by isiahmeadows** [comment]
@lhorie Or you could use a try-catch + fallback.

**Comment by lhorie** [comment]
For now, I'm simply sniffing for feature presence (i.e. `typeof history.pushState === "function"`). There's some more legwork required in the pushStateMock to make tests pass when doing a try/catch + fallback

**Comment by isiahmeadows** [comment]
@lhorie [Modernizer simply sniffs for the `file:` protocol](https://github.com/Modernizr/Modernizr/blob/e4105ac0cc296aae14782495f2c18ac05dc64d8b/feature-detects/history.js#L36-L38), which might be best for working around this.

**Comment by lhorie** [comment]
@isiahmeadows I think the issue here is that cordova runs on `file:` protocol *and* has working pushState

**Comment by isiahmeadows** [comment]
@lhorie That's why I think sniffing for `file:` and using an unconditional fallback instead would be best.
