### ISSUE TITLE
[rewrite] Don't no-op route.set

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1177]
### Description:

As @veloce says in #1176:

> when calling m.route.set(path) on the same route we are currently on, nothing happens. Again this was not the case in v0.2. I have a use case where I need to reload the current screen. In v0.2 I could do this either with m.redraw.strategy('all') or calling m.route(path) on the same route. Can we restore this m.route behavior in v1.0, or is there a way to do this in 1.0 that I don't see?

Basically, `m.route.set` no-ops if it resolves to the current route.

### Steps to Reproduce:

```
m.route(document.body, '/', {
  '/' : {
    oninit( vnode ){
      console.log( 'welcome' )
    },

    onbeforeupdate( vnode ){
      console.log( 'welcome back' )
    },

    view : () =>
      m( 'a', {
        onclick : () =>
          m.route.set( m.route.get() )
      },
        'Refresh'
      )
  }
})
```

### Actual:

Following the link does nothing.

### Expected:

I think the component should be redrawn and the console should log 'welcome back'. A voice in my head says this is unintuitive, and the component should re-initialise, but I disagree:

`oninit` is currently consistent in meaning the corresponding DOM does not yet exist, and there is no prior state to query. That isn't and shouldn't be the case here, and in a route reload a comparison of new attributes to previous state is likely to be useful. I have elsewhere expressed the minor frustration that in some scenarios, the v0 implementation detail of having all lifecycle hooks within a single scope is useful for DRY logic (I want to do the same thing regardless of whether this is the first or a subsequent redraw; shared scope means I can closure private state which is an unhelpful liability if exposed to the rest of the tree), but these are minor aesthetic opinions that are outweighed by the benefits of a discrete 'first draw' lifecycle loop, and don't pose any practical problems that can't be solved with WeakMaps or aliasing via a manual closure.

**Comment by tivac** [comment]
Am I missing something?

https://jsbin.com/kuboni/1/edit?html,js,console,output

This seems to be working fine for me.

![mithril-1177](https://cloud.githubusercontent.com/assets/49545/17222222/00fd492a-54ac-11e6-8ab4-c98361871c63.gif)

**Comment by barneycarroll** [comment]
No tests to speak of. Please ignore and follow up if #1178 gets re-opened. Over-enthusiastic comunity support, innit. Sorry!
