### ISSUE TITLE
[rewrite] m.route.set('/path/:param', { param: 'foo' }) is a no-op when :param arg changes

### ISSUE THREAD

**Issue by veloce** [lhorie/mithril.js#1178]
### Description:

I guess this is actually linked to https://github.com/lhorie/mithril.js/issues/1177 but this bug is different so I file it here for clarity.

### Steps to Reproduce:

```
// Using pushState with whatever route prefix

m.route(document.body, '/', {
  '/game/:id' : {
    oninit( vnode ){
      console.log( 'welcome ' + vnode.attrs.id )
    },
    view : (vnode) =>m( 'div', 'game ' + vnode.attrs.id) 
  }
});

m.route.set('/game/1234');
m.route.set('/game/5678');
```

### Expected:

The view should change from game 1234 to game 5678.

### Actual:

The url is updated correctly but nothing happens on the screen.

**Comment by tivac** [comment]
Tried this out with the current `rewrite` [mithril.js](https://github.com/lhorie/mithril.js/blob/1155027c9125f9d157318d0c2d7583b90e2e1832/mithril.js)

https://jsbin.com/janelu/2/edit?html,js,console,output

I slightly modified your repro code, but nothing substantial. Here's what I'm seeing:

![mithril-1178](https://cloud.githubusercontent.com/assets/49545/17221612/5ce41802-54a9-11e6-9986-2d5555a2f088.gif)

**Comment by veloce** [comment]
I did not test actually the code pasted, it was just for the example. I can confirm the bug in my application: I am able to reproduce it constantly. But as it's working in jsbin I should investigate further. Sorry for the noise if it's only on my side.

**Comment by veloce** [comment]
I guess it can be closed then.

**Comment by tivac** [comment]
I'm not saying you haven't found a bug, I just can't tell yet.

If you find a repro definitely re-open this please!

**Comment by veloce** [comment]
Yep for now I have no idea of what's going on specifically in my app, so I'm going to look further :)
Maybe I'll reopen or file another if this description does not correspond to the actual bug.
