### ISSUE TITLE
content gets duplicated

### ISSUE THREAD

**Issue by lhorie** [lhorie/mithril.js#1185]
### Description:

m.trust intermittently creates nodes instead of replacing

### Steps to Reproduce:

https://jsfiddle.net/xnyz10d5/

### Expected:

Clicking should never cause `bye` to be duplicated

### Actual:

Clicking many times sometimes causes `bye` to be duplicated

**Comment by lhorie** [comment]
Fixed in f4b267ff39686e2d6f0dc4a86a533e4416137c9c

**Comment by jhenderson** [comment]
@lhorie Thanks for fixing this so quickly - much appreciated.
