### ISSUE TITLE
Mithril rewrite: "Cannot read property 'oninit' of undefined"

### ISSUE THREAD

**Issue by Bondifrench** [lhorie/mithril.js#1193]
### Description:

Using Mithril.min.js, simple example where I am only using the view to render different buttons, will cause a blank page with the rewrite with the error: 
`VM600 mithril.min.js:36 error Script error. (line 0)
VM600 mithril.min.js:25 Uncaught TypeError: Cannot read property 'oninit' of undefined`

### Steps to Reproduce:

```
var Buttons = {};

Buttons.view = function (vnode) {
  return m('section', [
    		m("h3",
			"Buttons"
		),
		m("ul.actions", [
			m("li",
				m("a.button.special[href='#']",
					"Special"
				)
			),
			m("li",
				m("a.button[href='#']",
					"Default"
				)
			),
			m("li",
				m("a.button.alt[href='#']",
					"Alternate"
				)
			)
		]),
		m("ul.actions", [
			m("li",
				m("a.button.special.big[href='#']",
					"Big"
				)
			),
			m("li",
				m("a.button[href='#']",
					"Default"
				)
			),
			m("li",
				m("a.button.alt.small[href='#']",
					"Small"
				)
			)
		])
  ]);
};

var App = {};

App.view = function () {
  return m('', [
    Buttons
  ]);
};

m.route(document.body, '/' , {
  '/': App});
```

### Expected:

# Buttons

- Special
- Default
- Alternate
 
- Big
- Default
- Small 

See [jsbin](http://jsbin.com/muhuwiveve/edit?html,js,output) with older version of Mithril
### Actual:

Blank page

See [jsbin](http://jsbin.com/xelosoqixi/edit?html,js,console,output) with the rewrite

**Comment by gyandeeps** [comment]
Here is the small change i made to make it work. Now components are created using `m`.

```js
App.view = function (vnode) {
  return m('', [
    m(Buttons)  /// --> changed
  ]);
};
```

**Comment by Bondifrench** [comment]
Interesting, so now, components need to be encapsulated with `m()`? should probably be indicated in the `migration` docs then

**Comment by gyandeeps** [comment]
It is: https://github.com/lhorie/mithril.js/blob/rewrite/docs/v1.x-migration.md#passing-components-to-m

**Comment by pygy** [comment]
@Bondifrench [It's there already](https://github.com/lhorie/mithril.js/blob/608a494538daede4e16c6e02114e36366d2d49d5/docs/v1.x-migration.md#passing-components-to-m).

**Comment by Bondifrench** [comment]
My bad, closing

**Comment by alexxroche** [comment]
I was following https://ratfactor.com/mithril2/#_how_i_write_reusable_components and ended up here, (with what seemed like a dead-end). With a little drilling into the rewrite branch I found the answer here: https://github.com/MithrilJS/mithril.js/blob/rewrite/docs/components.md#user-content-passing-data-to-components   (which gave me the two lines that made the example work with mithril 2.0.4  `view: function(c){ var ctrl = c.attrs;` )
