### ISSUE TITLE
IE8 compatibility fixes

### ISSUE THREAD

**Issue by yaruson** [lhorie/mithril.js#1195]
I had some issues with Mithril + ES5-Shim in Internet Explorer 8. Unfortunately I can't submit a PR at the time, but I hope these points could be discussed and fixed by the community.

### Individual characters in a string can't be adressed with square braces

In `parseTagAttrs` method we look for attribute definition like this:
```
} else if (match[3][0] === "[") {
	var attrValue = match[6]
	if (attrValue) attrValue = attrValue.replace(/\\(["'])/g, "$1")
	cell.attrs[match[4]] = attrValue || true
}
```
This works well in Chrome, but causes exception in IE8. Condition could be rewritten like this:
```
} else if (match[3].charAt(0) === "[") {
```

### Overwriting type attribute in checkboxes causes an exception

In last if-else blocks of function `setSingleAttr` we set attribute values.

In IE8 one can't change type of input control once it has been placed into DOM. As a workaround we may change attributes only if value was changed:

```
    if (node[attrName] !== dataAttr) {
        try {
            if (tag !== "input" || node[attrName] !== dataAttr) {
                node[attrName] = dataAttr
            }
        } catch (e) {
            node.setAttribute(attrName, dataAttr)
        }
    }
}
else if (node[attrName] !== dataAttr) {
    node.setAttribute(attrName, dataAttr)
}
```

**Comment by isiahmeadows** [comment]
Ugh...I think a few of us (me included) forgot that 0.2 still supports ES3 environments such as IE 6-8. It's not actively tested, so it's easy for that to slip through the cracks.
