### ISSUE TITLE
[rewrite] Should travis generate mithril.js?

### ISSUE THREAD

**Issue by tivac** [lhorie/mithril.js#1207]
I think it'd be good if any commit to the main `rewrite` branch that passed tests then committed updated `mithril.js` and `mithril.min.js` files.

I did some research on how to have Travis create & commit build artifacts over in my [`travis-artifacts-test`](https://github.com/tivac/travis-artifacts-testing) repo, and would like to implement that for the `rewrite` branch.

@lhorie Any interest? I don't think I have any Travis permissions to get this set up, but would be happy to take a stab at it & bother you whenever I hit a roadblock.

**Comment by lhorie** [comment]
yeah I think this would be good

**Comment by tivac** [comment]
Ok. I'll send a PR once I've got things set up in my local fork and then we can just swap out creds.

**Comment by tivac** [comment]
PR #1210
