### ISSUE TITLE
Minified JS file for git tag v0.2.5 actually corresponds to version 0.2.4

### ISSUE THREAD

**Issue by octurion** [lhorie/mithril.js#1214]
### Description:

There's a version discrepancy at [tag v0.2.5,](https://github.com/lhorie/mithril.js/tree/v0.2.5) regarding the unified JS file (https://github.com/lhorie/mithril.js/blob/v0.2.5/mithril.js) and the minified one (https://github.com/lhorie/mithril.js/blob/v0.2.5/mithril.min.js). The corresponding `.map` file may also be affected.

### Steps to Reproduce:

1. https://github.com/lhorie/mithril.js/blob/v0.2.5/mithril.min.js
2. Ctrl+F "0.2."

### Expected:

1. Two matches, both corresponding to version 0.2.5

### Actual:

1. Two matches, both corresponding to version 0.2.4

### Additional information

The reason I'm reporting this bug is because the 0.2.5 mithril webjar is affected by it (proof: http://cdn.jsdelivr.net/webjars/org.webjars/mithril/0.2.5/mithril.min.js)

**Comment by tivac** [comment]
It's a documentation bug, but the code looks correct. Hopefully fixed in the next release.
