### ISSUE TITLE
[rewrite] Removing second-to-last item in list results in ordering issues

### ISSUE THREAD

**Issue by gregod** [lhorie/mithril.js#1216]
### Description:
Im experiencing an issue when removing the second-to-last item, maybe related to node recycling.

A simple use case consisting an list of items with lifecycle methods is shown in : https://jsfiddle.net/jkp6Lto7/3/   Key attributes are set. The button removes the item at index 4, whose lifecycle animation applies a bold font style and then removes the item after 1s. 

Press the button once to see the expected result, then again to the remove the next item once the animation has finished.

On the first press everything works as expected, on the second press however the item instantly jumps from second-to-last to the last position where it completes its lifecycle animation. 

This happens on the current rewrite head (85ecd3545fed01da8ca1473e8aea6547d12609d6) in FF and Chromium

**Comment by lhorie** [comment]
fixed
