### ISSUE TITLE
[rewrite] HALT is not defined

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1230]
I assume down to changes in [the bundler](https://github.com/lhorie/mithril.js/tree/rewrite/module), the bundled output isn't honouring the [unclosured variable declarations in stream](https://github.com/lhorie/mithril.js/blob/rewrite/util/stream.js#L3), so `m` fails to build on account of `HALT` being a null reference.

https://jsbin.com/goxide/edit?html,console

**Comment by lhorie** [comment]
Should be fixed now
