### ISSUE TITLE
[rewrite] Dependent streams run when m.prop initialized with m.prop.HALT

### ISSUE THREAD

**Issue by sebastiansandqvist** [lhorie/mithril.js#1232]
### Description:

(Feature request)

In the rewrite, it looks like the following causes anything mapping over the stream to run:

```js
var someCondition = false;
var stream = m.prop(someCondition || m.prop.HALT);
```

I was hoping to use this as a more terse way to express the following:

```js
var someCondition = false;
var stream = m.prop();
if (someCondition) {
  stream(someCondition);
}
```

### Expected:

When passing `m.prop.HALT` as the initial value to an `m.prop` stream, I expected any dependent streams to not run.

Expected `stream.map(() => alert('failed'))` to not run.

### Actual:

Dependent streams still ran when the parent stream was initialized with `m.prop.HALT`.

**Comment by lhorie** [comment]
I'd say this a bug. Fixed
