### ISSUE TITLE
Diff function add extra element when using m.render() 2nd time

### ISSUE THREAD

**Issue by brunettdan** [lhorie/mithril.js#1238]
### Description:

Found a bug related to m.render(). On first re-render, every array items wrapped in m.trust() are duplicated. Mithril version 0.2.5 from NPM. Built with browserify. Tested in Chrome 52.0.2743.116 m.  

### Steps to Reproduce:

```
var m = require('mithril');

var i = 0;
function add(){
    i++;
    render();
}
function getVal(){
    return i;
}

function render(){
    m.render(document.body, m('div', [
        m.trust('<p>Hello</p>')
        , m('button', {onclick:add}, 'Add')
        , m.trust(`<p>${getVal()}</p>`)
    ]));
}

setTimeout(()=>{
    render()
},1000);
```

### Expected:

This is how the element renders first time:
<div>
<p>Hello</p>
<button>Add</button>
<p>1</p>
&lt;span&gt;last&lt;/span&gt;
<div>Some other val</div>
</div>

This is how the element should re-render:
<div>
<p>Hello</p>
<button>Add</button>
<p>2</p>
&lt;span&gt;last&lt;/span&gt;
<div>Some other val</div>
</div>

### Actual:

This is how the element re-renders after the first click. It adds the <p>2</p> and another copy of <div>Some other val</div>:

<div>
<p>Hello</p>
<button>Add</button>
<p>1</p>
<p>2</p>
&lt;span&gt;last&lt;/span&gt;
<div>Some other val</div>
<div>Some other val</div>
</div>

**Comment by isiahmeadows** [comment]
Does this still hold true for the bundle in `next`?

(Oh, and BTW, could you make a [fiddle](https://jsfiddle.com)/[bin](https://jsbin.com)/[pen](https://codepen.com)/etc. out of it?)

**Comment by brunettdan** [comment]
After reading the docs, i noticed the "key" attribute which solves this problem.
