### ISSUE TITLE
[rewrite] Are fragment / text / trusted vnodes expected to have lifecycle methods?

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1242]
I would say 'no', but the docs aren't explicit about it AFAICT.

**Comment by pygy** [comment]
All vnodes currently [support `attrs`-based lifecycle methods](https://github.com/lhorie/mithril.js/blob/5f2c9a3a29caec82abb943a48fabd4e25b8d3c9b/render/render.js#L23-L193).

The hyperscript API only makes them available to components and elements.

**Comment by barneycarroll** [comment]
That's not what I'm seeing here: https://jsbin.com/jaleho/edit?js,output — can you spot a mistake?

**Comment by pygy** [comment]
They must be set in `attrs`.

**Comment by barneycarroll** [comment]
Thanks! God these generic references with variable meanings depending on context are confusing, aren't they?
