### ISSUE TITLE
[rewrite] Rethinking the removal hooks.

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#1245]
The current design of the `onbeforeremove` and `onremove` hooks is not optimal.
- `onremove` is called before the elements are inserted. It could be useful to run code after the `disconnectedCallback` hook of a custom element, for example, and the current design won't allow it.
- but if we moved it afterwards, we want to run `onbeforeremove` on every node to be removed, not just the root. We could pass `done` to the hooks of the detached vnodes (the ones that currently have their `onbeforeremove` honoured), and `null` deeper down the tree. Still, this hook would conflate two distinct concerns: cleanup before node removal and delaying the removal.
- alternatively, we could decouple cleanup and delay hooks. That would be cleaner, IMO.

**Comment by lhorie** [comment]
> It could be useful to run code after the disconnectedCallback

I've heard this point a few times, but It's still not clear to me what real life use case is currently not possible to implement with the current semantics. Can you give an example?

**Comment by pygy** [comment]
I don't have a concrete example because custom elements are still very new, but you could want to assess the side effects of `disconnectedCallback` after they occur.

**Comment by isiahmeadows** [comment]
Closing, since this issue/PR has not been updated in over a month, and typically, issues inactive for that long do not usually produce any action. If you feel something in Mithril needs added or changed, please file a new issue/PR.
