### ISSUE TITLE
contenteditable, text-transform:uppercase and cursor position

### ISSUE THREAD

**Issue by elishacook** [lhorie/mithril.js#1252]
### Description:

In Chrome, when editing an element with `contenteditable="true"` that is styled with `text-transform: uppercase`, mithril does not maintain cursor position.

### Steps to Reproduce:

```js
m.mount(document.body,
{
  controller: function ()
  {
    this.value = m.prop('foo')
  },

  view: function (ctrl)
  {
    return m('h1', {
      innerText: ctrl.value(),
      contentEditable: "plaintext-only",
      style: {
        textTransform: 'uppercase'
      },
      oninput: function (e)
      {
        ctrl.value(e.target.innerText)
      }
    })
  }
})
```

And there is a fiddle here: https://jsfiddle.net/139btxf2/6/

### Expected:

The cursor position is maintained during editing.

### Actual:

The cursor jumps back to the beginning of the element after typing a character.

**Comment by pygy** [comment]
See #1253 :-)
