### ISSUE TITLE
[ospec] provide diffing hook for failed tests?

### ISSUE THREAD

**Issue by leeoniya** [lhorie/mithril.js#1257]
@lhorie 

any interest in providing a hook to display an actual vs expected diff for failed tests. maybe also for rendering the expected values of passing tests.

thanks!

**Comment by lhorie** [comment]
It already displays expected and actual values on a failure. Do you mean like an output formatter?

**Comment by leeoniya** [comment]
right, a pluggable diff renderer. a la http://kpdecker.github.io/jsdiff/

**Comment by lhorie** [comment]
sorry, no, "pluggable" is like the [antithesis](https://github.com/lhorie/mithril.js/tree/rewrite/ospec#goals) of ospec :)

**Comment by leeoniya** [comment]
the alternatives being?

- some anointed dependency (also antithesis)
- baked-in fast diff implementation (bloat, moar antithesis)
- `¯\_(ツ)_/¯`

**Comment by lhorie** [comment]
> the alternatives being?

- leaving it the way it is because I don't use diff reporting
- use another tool that embraces configurability if diff reports matter enough to warrant it
