### ISSUE TITLE
[rewrite] A view that returns its own vnode will cause a circular loop in render.js

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1260]
[As seen here](https://jsbin.com/piduyo/edit?js,console), it's possible to get a view to return the component vnode, which causes an infinite loop.

It's a silly but believable mistake (currently tests seem to rely on the fact that RouteResolver views are provided pre-built div vnodes!), and when the call stack exceeds these things get very difficult to trace back to source.

I reckon we should throw with explicit guidance if a component's view return is the vnode itself.

The alternative is to do what RouteResolvers currently do, and give people a free placeholder div (until they override or replace it). Which I don't recommend.

**Comment by pygy** [comment]
Generally the DOM is supposed to be acyclic. Checking for cycles in general would be costly... Would you want an error thrown if `vnode.instance` === `vnode`?

**Comment by barneycarroll** [comment]
Yeah I dislike the general idea and I think throwing is the best course of action. What do you think?

**Comment by pygy** [comment]
No opinion really... Both would be fine with me.

**Comment by mindeavor** [comment]
Throwing is definitely better. Obscure errors are no good if you can avoid them! :)

**Comment by lhorie** [comment]
Fixed in #1263
