### ISSUE TITLE
[rewrite:core router] in non-hash mode, anchor-based navigation triggers the router resolution logic

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#1270]
Setting the hash of the location triggers `onpopsate` which triggers the route resolution logic.

It means that if someone wants to use local anchors in a page/app, they'll have to take that quirk into account...

A partial solution would be to set a flag to `true` when `setPath()` is called and skip resolution in non-hash mode when it hasn't been set... But it probably breaks the back button, so it isn't satisfactory...

**Comment by lhorie** [comment]
I think it should trigger it in that case, since hash can have route parameters and you'd want a redraw if they changed

**Comment by pygy** [comment]
So, in non-hash mode, the router will parse parameters that happen after the pound sign?

Routing to `/foo#bar?baz=qux` should populate `vnode.attrs` with `baz: 'qux'`? That sounds very backwards to me...

**Comment by lhorie** [comment]
@pygy that specific case wouldn't work as expected, because query is supposed to comes before hash. `/foo?a=1#b=2` yields `{a: 1, b: 2}` though.

**Comment by pygy** [comment]
In what scenario would you want to do that rather than `/foo?a=1&b=2`? Do you rely on it?

It looks like an exotic use case compared to having anchors that work without triggering routing.
