### ISSUE TITLE
[rewrite:router] Mithril shouldn't claim the `path` and `route` args. 

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#1271]
Currently the route and path are passed as attributes on the `onmatch`/`render`/`view` vnode, potentially erasing useful information in the process.

Frontend devs don't always control the URLs they are given, I think we should go back to

`onmatch(resolve, args, path, route)` and maybe to `render(vnode, path, route)` ?

**Comment by barneycarroll** [comment]
@pygy unless I've missed something the `vnode.attrs` object is never going to be accessible to the user before Mithril has populated it: they can choose to *overwrite* `vnode.attrs.path` if they really want to (don't I remember you telling me that binding an asynchronously loaded component to `attrs` was messy?), but at that point it's their choice: I could just as easily overwrite attributes passed in to a nested component in `oninit`, or replace `vnode.instance` or `vnode.tag` if I was insistent.

**Comment by pygy** [comment]
It is populated by the [route](https://github.com/lhorie/mithril.js/blob/a1a087c4be50afa8208043184b0d68ae79be28e4/router/router.js#L90) [params](https://github.com/lhorie/mithril.js/blob/a1a087c4be50afa8208043184b0d68ae79be28e4/router/router.js#L90)

**Comment by barneycarroll** [comment]
I finally get it: `route` and `path` could be parameters of the routed URI itself, at which point Mithril will overwrite them :boom:.

Regardless of whether or not it's a good idea to move this information out of `vnode.attrs` or `vnode` altogether, I think it's imperative route [parameters](https://github.com/lhorie/mithril.js/blob/rewrite/docs/route.md#routing-parameters) get their own namespace isolated from the application sandbox. Simplest fix:

```js
{
  path: "/?foo=bar&path=neverseen&route=neither&baz=qux",
  route: "/",
  params : {
    baz: "qux",
    foo: "bar",
    path: "neverseen",
    route: "neither"
}
```

**Comment by lhorie** [comment]
The other option is to simply not expose `route` since `path` is retrievable via `m.route.get()`. To be honest, I can't think of a reason to expose `route` other than "well, it's there, so just pass it forward"

**Comment by pygy** [comment]
Well, I agree with both of you.

`route` makes little sense in app space, and I was about to suggest to keep the `query` parameters in a distinct object, thereby taking away a single, predictable name from `/route/:params`.

**Comment by barneycarroll** [comment]
@lhorie I'm guessing the standalone route module isn't privy to what happens in the distinct router module, such that any method in route module can't get route parameters from the path — would it be possible to return the decomposed route attributes via a new method in `api/router` though?

**Comment by pygy** [comment]
@barneycarroll do you mean respectively `api/router` and `router/router`?

Also, check you gitter private messages...

**Comment by barneycarroll** [comment]
Yes, I'm wondering about extending the API of the api/router :)

**Comment by lhorie** [comment]
yes it is possible. But again, if the rationale for removing it from vnode.attrs is that it's not useful, then why add an API method for it?

**Comment by barneycarroll** [comment]
It's not that it isn't useful — the idea of breaking it out into another API was your idea :)

The problem is that if the route ends up with parameters of `route` or `path`, those parameters will never be accessible. Hence my proposal to move parameters into a distinct property within the received route object.

**Comment by lhorie** [comment]
I think we might be getting terminology confused. `route` is the string you type as a key in the routes map, e.g. `"/foo/:id"`. `path` is the actual path that you navigate to, e.g. `"/foo/1"` and route parameters are the data that was interpolated into `route` to get `path`, e.g. `{id: "1"}`. Parameters are accessible via the vnode.attrs in the root, and path is accessible via `m.route.get`. What I was saying (which @pygy agreed w/) is that I don't see why you would ever need the `route` string in app space

**Comment by pygy** [comment]
This makes me think, shouldn't `m.route.get` return the last path that was explicitly resolved to rather that the content of `window.location`?

Err, no, not unless the new `path` is passed to `onmatch`, at least...

The intent was to be resilient against, direct `window.location` modifications using `history.pushState` that the router can't notice. It is also cheaper than re-computing the path using `getPath()`

**Comment by pygy** [comment]
Thinking about this further, mandating a component as the potential argument to `resolve` may be too restrictive.

Render could instead receive arbitrary payloads as `render(payload, attrs)` and have the default implementation as

```JS
function defaultRender(payload, attrs){
  return Vnode(payload, null, attrs)
}
```

**Comment by lhorie** [comment]
Removed in 00d555b9f41c071f1c455d6ead9f5e1bfcac684a
