### ISSUE TITLE
[rewrite] Add onbeforerender hook?

### ISSUE THREAD

**Issue by ludbek** [lhorie/mithril.js#1285]
It would allow one to do things like validation and modification of attributes before rendering a component.

**Comment by panych** [comment]
(`oninit`)[https://github.com/lhorie/mithril.js/blob/rewrite/docs/lifecycle-methods.md#oninit]  ?

**Comment by ludbek** [comment]
`oninit` is called only when vdom is attached to the dom for the first time. Its not called in subsequent render.

**Comment by mindeavor** [comment]
How would this differ from [onbeforeupdate](https://github.com/lhorie/mithril.js/blob/rewrite/docs/lifecycle-methods.md#onbeforeupdate)?

**Comment by pygy** [comment]
That can be achieved by doing this:
```JS
{
  onbeforerender(vnode) {/* your logic here */},
  oninit(vnode) {this.onbeforerender(vnode)},
  onbeforeupdate(vnode) {return this.onbeforerender(vnode)},
  view() {}
}
```

Or by calling `onbeforeudate()` from `oninit()` (or the inverse).

**Comment by ludbek** [comment]
@pygy your solution is efficient. thanx :)
