### ISSUE TITLE
[rewrite] If a `tag` property of a vnode is a component, is it always the same instance of that component?

### ISSUE THREAD

**Issue by nlutterman** [lhorie/mithril.js#1292]
Just a question asking for clarification.  The [documentation](https://github.com/lhorie/mithril.js/blob/rewrite/docs/vnodes.md) notes:

>If tag is a Javascript object with a view method, the vnode represents the DOM generated by rendering the component.

Does this mean that the tag object is the same object as the originally defined component object, or is it a copy?

The reason that I'm asking is that I'd like to write a wrapper component that can utilize the methods defined on the child components, if the methods are available.

**Comment by pygy** [comment]
The `tag` is literally the object. Give it a try:

http://jsbin.com/gilucamizo/edit?js,console

It is also the case when the component is passed to `m(...)`.

`vnode.state` is a shallow copy of `vnode.tag` (performed before `oninit` is called) that is preserved from render to render.

**Comment by nlutterman** [comment]
@pygy Awesome, thanks a ton.  I boogered around with it a little bit but couldn't manage to convince myself and I'm a bit of a dunce and couldn't follow the source all that well.
