### ISSUE TITLE
[rewrite: bundler] m.mount not exposed in some circumstances

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#1295]
Without [this  change](https://github.com/lhorie/mithril.js/pull/1291/commits/057f3a9d2f1511ebe2802f7a4d9804bb9dc74861#diff-168726dbe96b3ce427e7fedce31bb0bc), the `m.mount` is not defined (there are `tests/test-api.js` failures).

**Comment by lhorie** [comment]
merged
