### ISSUE TITLE
[rewrite] Recycled node with leftover class?

### ISSUE THREAD

**Issue by spacejack** [lhorie/mithril.js#1312]
### Description:

When an element with a class is replaced with an element without a class, it seems the element is recycled and the old class remains. Eg, one render outputs `m('.content', ...` the other renders `m('div', ...`

### Steps to Reproduce:

Example:

https://jsbin.com/dunotolewa/edit?html,css,js,output

### Expected:

The "deleted" state should not have the `content` class applied to it.

### Actual:

The `content` class is applied to both renders.

### Workaround:

Using a class in both cases will work. eg, instead of `'div'` use `'.deleted'`.

**Comment by lhorie** [comment]
Fixed
