### ISSUE TITLE
Share a scope between components within a tree.

### ISSUE THREAD

**Issue by ludbek** [lhorie/mithril.js#1315]
This would allow implicit communication and data flow between components. We could modify hyperscirpt to pass down a scope object to components in a tree.

**Comment by lhorie** [comment]
Like `context` in React? Not sure this really belongs in core. Can't we do something like this instead?

```javascript
//scope.js
module.exports = {}

//somecomponent.js
var scope = require("./scope")

var MyComponent = {
  view: function() {
    //use scope here
  }
}
```

**Comment by isiahmeadows** [comment]
I agree that it should remain explicit, even if it is just a simple reference passed down. Besides, React [strongly discourages its use](https://facebook.github.io/react/docs/context.html) anyways.

**Comment by barneycarroll** [comment]
The usual scenario for a Mithril app involves a single mount point and one tree, do the trivial way to achieve this is simply using a global store (either imported as a module or hanging off a global object — `window`). 

In practice, I would imagine it's less intuitive to reference an object passed in to lifecycle methods than it is to simply use a custom global reference directly — compare:

```javascript
// built into Mithril
const Component = {
  view : ( vnode, scope ) =>
    m( 'input', {
      value : scope.valueX(),
      oninput : e => scope.valueX( e.target.value )
    } )
}

// explicit import
// store.js
export default {}
// app.js
import scope from 'store'

const Component = {
  view : () =>
    m( 'input', {
      value : scope.valueX(),
      oninput : e => scope.valueX( e.target.value )
    } )
}

// browser environment implicit globals
var scope = scope || {}

const Component = {
  view : () =>
    m( 'input', {
      value : scope.valueX(),
      oninput : e => scope.valueX( e.target.value )
    } )
}
```

What use cases do you have in mind?

**Comment by isiahmeadows** [comment]
I also agree that `context` rarely has a use case. (By the way, React's
context feature is closer to a shared `this.state` than anything truly
global.)

**Comment by ludbek** [comment]
I agree with you guys with this implicit stuff. But there some rare cases where implicit nature is really handy, easier and cleaner than passing a scope down every component in a tree.

Consider a situation where components use inline styles and need to pass a theme object down a components tree. Passing it explicitly as component attribute is kind of overhead and repetitive. I was thinking of passing the scope/context object as component or vdom property `(this.scope)` instead of attribute `(vnode.attrs.scope)`.

**Comment by ludbek** [comment]
Closing this in favor of component mixin.

**Comment by ludbek** [comment]
@lhorie @isiahmeadows @barneycarroll 

I still have some issues with this explicit thing in some scenarios. May be you guys have better solution to one of the situation I am facing.

Consider this, I have components which store their state in single store. Now since my entire application use that store I have two options:
1. explicitly pass down the store to each component in the app tree
2. import the store and use it in the components

The problem with the #1 is, its kind of repetitive. Imagine I have two such dependencies e.g. store and theme. I have to pass them to each any every components. It is not a problem while working with few components but as their number grows, It starts to feel painful.

The problem with #2 is, since the store is being imported from a module somewhere, the component cannot be reused in other projects without editing the path to the store. I thought mixins would solve the problem but it still has to be applied before the component can be used in new projects.

**Comment by barneycarroll** [comment]
If the problem with both these methods is the repetitive cruft, and your original desire was for implicit state sharing, then  it really sounds like you want to store and access application state on the global object. This way you're free to establish this as an application concern without the library needing to be aware of the mechanism. In the same way a component won't do anything unless it's imported and invoked somewhere, ultimately relying on the app being mounted somewhere in an initializing file, that same file might contain the following:

```js 
window.store = {}
```

**Comment by isiahmeadows** [comment]
Yeah, that or similar is what I would normally do as well.

**Comment by ludbek** [comment]
Using globals would demand boiler codes during tests.

I think component mixins is better solution. Even though I have to write some extra code to mix mixins, at least I can reuse to the original components.

e.g.

```javascript
// @ apackage/button.js
export const button = {
    view ({attrs, children, state}) {
        ...
    }
};

// @ myButton.js
import {button} from "apackage/button";
import {astore} from "./store.js";
import {atheme} from "./theme.js";

export const  myButton = Object.assign(button, {store: astore, theme: atheme});
```

I was biased on which option to choose. Thanx guys for your time and insight.

**Comment by janny199523** [comment]
6+5465
