### ISSUE TITLE
[rewrite] feature request: Allow "array" as event handler

### ISSUE THREAD

**Issue by syaiful6** [lhorie/mithril.js#1316]
Currently we always create closure to keep track of "context". Even though the code of the handler is same,
we will end up create different closure for each item. 

To make it clear, this pattern is common:
```javascript
function remove(id) {
	return function (ev) {
		// do something with the id
	}
}
```
common usage
```javascript
someArray.map((item, i) => m('li', {onclick: remove(i)}), ...)
```

My request is to allow array as event handler. The first item in the array is the real function,
and the rest are arguments for the functions and mithril will invoke that function with them + event object. 

```javascript
function remove(id, ev) {
	//do something with the id
}
```

and usage:
```javascript
someArray.map((item, i) => m('li', {onclick: [remove, i]}), ...)
```

That way, we can avoid unnecessary create different closures for the event handler.

**Comment by SkylerLipthay** [comment]
I can't speak about Mithril's implementation details to form a technical argument here, but I believe the officially suggested way to do this is with partial binding:

```
function remove(id, ev) {
    //do something with the id
}
```

```
someArray.map((item, i) => m('li', { onclick: remove.bind(null, i) }), ...)
```

This method allows the additional capability of specifying a `this` argument (`null` here), and adheres to the policy of using plain JS wherever possible.

**Comment by syaiful6** [comment]
The this keyword on event handler is element that I believe helpful when handling the event. Specify this keyword on my suggestion also possible. Just bind it like in your example which I believe it uncommon use case because in most case you need this point to the element instead.

Also bind will create new function. That was the problem I want to avoid here. Since the creation of function is unnecessary considering the code of handler is identical.

**Comment by sdougbrown** [comment]
Pointing to the element with `this` would be confusing and unnecessary (available under `vnode.dom` anyhow, and `this` typically points to `vnode.state` within the component logic).

I think that major deviations from the DOM spec - like this one - would make for a confusing api, and as far as I can tell `onclick` isn't currently treated differently from any other attributes (and rightfully so).  I see what you're trying to get at, but it seems like a damaging change for minor (if any) gain.

**Comment by syaiful6** [comment]
@sdalezman do you comment to me? i am sorry i dont clear what you mean, but the current Mithril implementation is ```this``` keyword on event handler is ```element```. [here](https://github.com/lhorie/mithril.js/blob/rewrite/render/render.js#L476) the ref.

**Comment by sdougbrown** [comment]
Oops, you're right - I don't use `this` in my event handlers and missed that. 😄

**Comment by kcjpop** [comment]
@syaiful6 Your example code is my current approach for writing event handlers in Mithril. I find it has a nicer syntax when using with ES6 fat arrows.
```js
const remove = (param1, param2, ...params) => e => {
  e.preventDefault()
}
```
I guess it's a bit counter-intuitive when using array as event handler, especially when you don't need to access extra params (at the first glance I may think `onclick` supports multiple event handlers, as shown below).

```js
{onclick: [remove]}
```

Plus I assume it'll add a bit performance hit when `.slice`-ing the parameters (sorry no proper benchmarking, just intuition).

**Comment by syaiful6** [comment]
@kcjpop yes, maybe it counter-intuitive. :) I dont know about the perf.

**Comment by barneycarroll** [comment]
FWIW I've always used this function to wrap several functions into one:

```javascript 
function multi(){
	var handlers = Array.prototype.filter.call( arguments, function( x ){
		return x instanceof Function 
	} )

	return function handle(){
		for( var i = 0; i < handlers.length; i++ )
			handlers[ i ].apply( this, arguments )
	}
}

// usage:
m( 'button', {
  onclick : multi(
    ctrl.method,
    e => e.preventDefault()
  )
} )
```

[Gist here if you're interested](https://gist.github.com/barneycarroll/6671463fbe593b2bd8a8).

In ES6 this becomes kinda redundant as writing anonymous arrow functions and explicitly invoking all desired functions sequentially becomes easier to read:

```javascript
m( 'button', {
  onclick : e => {
    ctrl.method()
    e.preventDefault()
  }
} )
```
