### ISSUE TITLE
m.request exceptions are suppressed if you throw.

### ISSUE THREAD

**Issue by robinchew** [lhorie/mithril.js#1322]
### Description:
Exceptions are silenced during `.then` of `m.request`. Similar to https://github.com/lhorie/mithril.js/issues/968 but this is specifically when you `throw` an exception.

### Steps to Reproduce:
```
a = function() {
  // Exception which doesn't raise
  console.log('before throw');
  throw 'Thrown!';
  console.log('after throw');
}

m.request({
  method: "GET",
  url: "https://api.github.com/users?since=10000"
}).then(a);
```
Demo at https://jsfiddle.net/tc5t2s30/8/

### Expected:

See exception raised in console.

### Actual:

No exception raised in console.

**Comment by vicnicius** [comment]
Hello, @robinchew!

Promise handlers return new promises. Throwing an exception from a promise handler, [most of the time](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch#Gotchas_when_throwing_errors) means you are rejecting the promise it will return. In this case, you would have to add a `.catch` handler after the promise to intercept the thrown error on the next step of the promise chain. 

```
m.request({ method: "GET", url: "https://api.github.com/users?since=10000" })
  .then(a)
  .catch(console.log); //'Thrown!' 
```

**Comment by robinchew** [comment]
But what if I really want `throw` an exception instead of `console.log`. I can't seem to make that work.
```
m.request({ method: "GET", url: "https://api.github.com/users?since=10000" })
  .then(a)
  .catch(function(e){throw e}); // silence
```

**Comment by robinchew** [comment]
Skimming through http://www.2ality.com/2016/03/promise-rejections-vs-exceptions.html, I came across `Promise.reject(e)`. So:
```
m.request({ method: "GET", url: "https://api.github.com/users?since=10000" })
  .then(a)
  .catch(function(e){Promise.reject(e)});
```
Would this be the recommendation?

**Comment by robinchew** [comment]
But this means I have to always remember to chain `.catch(function(e){Promise.reject(e)});` after every `.then()`. I attempted saving myself from writing the catch by writing my own request function like:
```
function myRequest(){
    return m.request().catch(function(e){Promise.reject(e)});
}
myRequest().then(function(){});
```
But that won't work because `.catch` must always come after `.then`.

**Comment by robinchew** [comment]
Unless I do:
```
export function then(promise, ...args) {
    return promise.then(...args).catch(e => Promise.reject(e));
}
then(m.request(), function(){});

```

**Comment by pygy** [comment]
`Promise.reject(x)` will not throw, but return a rejected promise:
`Promise.reject(5).catch(x => console.log(x))` => `5`

```JS
m.request({
  ///...
}).then(
  ()=>Promise.reject(5)
).catch(
  e => console.log(e) // => 5
)
```
Without the last `catch` bock, nothing will happen.

In general, promises won't allow you to rethrow, you have to use the `catch()` handler...

Mithril promises have an escape hatch in the form of native errors (any native Error type that isn't literally `Error`). This should throw:

```JS
m.request({...}).then(...).catch((e)=>{throw new TypeError(e)})
```

This is one of the things that makes Mithril promises non-A+ spec compliant. `Promise.reslove()` and `Promise.reject()` are part of the ES6 Promise spec that Mithril doesn't follow either (Mithril was released before promises were standardized and some quirks persist).

**Comment by robinchew** [comment]
This sounds like an expected behaviour and not a bug, so I'll close it. Thanks for the help.
