### ISSUE TITLE
[rewrite] Make m.route parameters more consistent with m.route and m.mount

### ISSUE THREAD

**Issue by simov** [lhorie/mithril.js#1326]
I just got bitten by this:

``` js
// ok
m.render(document.querySelector('body'), m(app.components.base))
// not ok
m.render(document.querySelector('body'), app.components.base)
```

``` js
// ok
m.mount(document.querySelector('body'), app.components.base)
// not ok
m.mount(document.querySelector('body'), m(app.components.base))
```

Previously in 0.x I was able to quickly swap `mount` with `render` and vise versa while testing.

IMO it would be better (if possible) to have consistent behavior for render, mount and route. It's very easy to forget the m wrapper when dealing with components.

**Comment by pygy** [comment]
API design is up to Leo, but this is [documented](https://github.com/lhorie/mithril.js/blob/fe7cc3efe6ebaa25e1638d420802e11bd88670c6/docs/mount.md#api) [behaviour](https://github.com/lhorie/mithril.js/blob/fe7cc3efe6ebaa25e1638d420802e11bd88670c6/docs/render.md#api) [described](https://github.com/lhorie/mithril.js/blob/fe7cc3efe6ebaa25e1638d420802e11bd88670c6/docs/v1.x-migration.md#passing-components-to-m) [in the migration guide](https://github.com/lhorie/mithril.js/blob/fe7cc3efe6ebaa25e1638d420802e11bd88670c6/docs/v1.x-migration.md#passing-vnodes-to-mmount-and-mroute).

It could be made to work by cloning the vnode passed to `mount` for each redraw, and wrapping the component passed to `render` in a vnode...

**Comment by isiahmeadows** [comment]
@simov Think of it this way, you render a node, but you mount a component. Rendering is a one off job - render once and you're done, so all you need is a stateless tree to render. Mounting is a persistent thing, where you mount the component, and it lives there, responding to user actions until you unmount it, if you choose to do so. This requires a stateful component to manage the interactions you deal with from the user.

@lhorie Ping me if I'm wrong, and one of us can reopen it.
