### ISSUE TITLE
Mithril dbmon implementation is not working

### ISSUE THREAD

**Issue by giancarlocp** [lhorie/mithril.js#1334]
### Description:

The [Mithril v0.2.4 dbmon implementation](http://cdn.rawgit.com/lhorie/mithril.js/rewrite/examples/dbmonster/mithril/index.html) app is not working.

### Steps to Reproduce:

Click [here](http://cdn.rawgit.com/lhorie/mithril.js/rewrite/examples/dbmonster/mithril/index.html)
Tested in Firefox 48.0 and Chrome 51.0.

### Expected:

It should do the same as [React v15.0.2](http://cdn.rawgit.com/lhorie/mithril.js/rewrite/examples/dbmonster/react/index.html) and [Angular v2.0.0-beta.17](http://cdn.rawgit.com/lhorie/mithril.js/rewrite/examples/dbmonster/angular/index.html) dbmon implementation.

### Actual:

It does nothing.

**Comment by lhorie** [comment]
fixed

**Comment by giancarlocp** [comment]
It is not working yet, at least for me.
Sorry, i tested on Win10(machine1) and Linux(machine2), so i didn't believe was my particular problem.
I ran it in a remote virtual machine and works.
I use 5 proxys in machine2 and didn't work in 4(hide.me, zend2.com, whoer.net and hidemyass.com) of them, finally works on [kproxy](https://server9.kproxy.com/servlet/redirect.srv/sruj/scsrinf/sduu/p1/lhorie/mithril.js/rewrite/examples/dbmonster/mithril/index.html).
Thank you.
