### ISSUE TITLE
The controller method is declared as required in mithril.d.ts

### ISSUE THREAD

**Issue by andraaspar** [lhorie/mithril.js#1336]
### Description:

mithril.d.ts declares the controller method as required, whereas the [documentation says it is optional](http://mithril.js.org/mithril.component.html#optional-controller).
This causes components written in TypeScript to always require a controller.
### Expected:

```
    interface Component<T extends Controller> {
        ...
        controller?: ControllerFunction<T> | ControllerConstructor<T>;
        ...
    }
```
### Actual:

```
    interface Component<T extends Controller> {
        ...
        controller: ControllerFunction<T> | ControllerConstructor<T>;
        ...
    }
```

Adding that question mark seems to do the trick.

**Comment by andraaspar** [comment]
### Example:

This should be valid:
```ts
import * as m from 'mithril'

export default class Form implements Mithril.Component<any> {

	view() {
		return m('h3', 'Todos')
	}
}
```

But it emits an error:
```
Class 'Form' incorrectly implements interface 'Component<any>'.
  Property 'controller' is missing in type 'Form'.
```

**Comment by isiahmeadows** [comment]
I'd merge a simple PR for this. (Good catch, BTW. It's easy to miss a single character like that.)
