### ISSUE TITLE
[Rewrite] How to create a Multi-tenancy app?

### ISSUE THREAD

**Issue by luanlv** [lhorie/mithril.js#1347]
How to create Multi-tenancy mithril 1.0 app. I can't use {subtree: retain}. Please help me find something similar or show me how to stop redraw function in a view. Tks very much!

**Comment by pygy** [comment]
You can return `false` from the `onbeforerender` hook. Alternatively, when you call `m.mount(root, component)`, the `root` gets a `root.redraw()` method that only redraws it (but it isn't documented, so I would't rely on it ultil it is if I were you).

**Comment by isiahmeadows** [comment]
@pygy is correct here, although it's [`onbeforeupdate`](https://github.com/lhorie/mithril.js/blob/rewrite/docs/lifecycle-methods.md#onbeforeupdate) that you need, not `onbeforerender` (which doesn't exist).
