### ISSUE TITLE
Is it possible to use onchange method like this?

### ISSUE THREAD

**Issue by Rexota** [lhorie/mithril.js#1348]
### Description:

Is it possible to use `onchange` (or other) method like this? I don't want to use `m.withAttr() `method. When I use this approach,` todo.vm.onchange()` method is not firing.

```
<!doctype html>
<title>Todo app</title>
<script src="//cdnjs.cloudflare.com/ajax/libs/mithril/0.2.5/mithril.min.js"></script>
<body>
<script>

var todo = {};
todo.vm = (function() {
    
    var vm = {}

    vm.init = function() {
        vm.description = m.prop("");
        vm.click = function() {
            console.log("click", vm.description())
        };
        vm.onchange = function() {
            console.log("onchange", vm.description())
        };
    }
    return vm
}())

todo.controller = function() {
    todo.vm.init()
}

//here's the view
todo.view = function() {
    return m("html", [
        m("body", [
            m("input", {
                //this is from example
            	//onchange: m.withAttr("value", todo.vm.description), 
                onchange: todo.vm.onchange, // <------
            	value: todo.vm.description()
            }),
            m("button", {
            	onclick: todo.vm.click
            }, "Add")
        ])
    ]);
};

//initialize the application
m.mount(document, {controller: todo.controller, view: todo.view});

</script>
</body>
```

**Comment by tivac** [comment]
Your code is working fine for me.

https://jsbin.com/rohile/1/edit?js,console,output

![onchange](https://cloud.githubusercontent.com/assets/49545/19198165/81753c2c-8c72-11e6-80cd-15bea826bf56.gif)

Note that for the `change` event you need to "commit" the value before it fires, I do so by clicking outside of the `<input>` element. https://developer.mozilla.org/en-US/docs/Web/Events/change

**Comment by Rexota** [comment]
@tivac, As you see onchange method is called only when button clicked. Not when the input change. Is this expected behaviour?

**Comment by tivac** [comment]
The `change` event only fires when the field is blurred, yes. Check out the MDN link I provided.

If you want the event to fire every time the value changes you should use the `input` event instead.

**Comment by Rexota** [comment]
Thanks!
