### ISSUE TITLE
Fantasy Land types have changed

### ISSUE THREAD

**Issue by isiahmeadows** [lhorie/mithril.js#1352]
Two things need changed to retain Fantasy Land compatibility:

1. [`ap` is now reversed: instead of `this` wrapping the function, the argument wraps the function.](https://github.com/fantasyland/fantasy-land/issues/144)
2. [The spec names are now prefixed.](https://github.com/fantasyland/fantasy-land/issues/92) I'd still recommend keeping the original names for ease of use, though.

I linked to the issues instead of their related PRs to help guide you all to the rationale for the changes.

**Comment by isiahmeadows** [comment]
Also, I think it might be nice for some to implement for streams Semigroup (`stream.concat(other)`) and Monoid (`m.stream.empty()`/`m.stream.resolve()` for symmetry with `m.stream.reject()`) as well. But that's just another orthogonal idea.

**Comment by lhorie** [comment]
Updated
