### ISSUE TITLE
Iframe content gets reset on a redraw

### ISSUE THREAD

**Issue by v4n** [lhorie/mithril.js#1353]
I have an iframe that is dynamically populated with a config attribute and a button that adds a new div to the view. When the button is clicked the iframe content gets cleared out.

```
// populate the iframe dynamically with the config attribute
function setup(iframe, init) {
  if (init) return;

  const doc = iframe.contentDocument;
  doc.open();
  const content = document.createElement('div');
  content.textContent = 'hello there';
  doc.appendChild(content);
  doc.close();
};

// the view
m('div',
  m('button', {onclick: (() => { controller.list.push('abc')} )}, 'Click me'),
  controller.list((item) => return <div>{item}</div>),
  m('iframe', {config: setup}),
)
```
A placed a breakpoint and inspected it just before the iframe content gets cleared out (on the first button click) here: https://github.com/lhorie/mithril.js/blob/ec95de99083b0c220567e98d36defea7ae7bb7e8/mithril.js#L627

The following values are contained:
```
$ data
> [button, div, iframe]
$ cached
> [button, iframe]

// in this loop we are dealing with the div added by the button click
$ data[i]
> div

// but the cached item that is being used is the iframe (cacheCount = 1)
$ cached[cacheCount]
> // iframe is returned
```
So my understanding is that Mithril thinks the iframe has changed since it compares the iframe cache and the new div. Thinks the iframe has changed and clears it out.

Strange part is that I tried reproducing this with a fresh mithril setup and couldn't replicate this behavior. Any pointers on what to look into in order to understand what's causing this behavior would be appreciated!

**Comment by v4n** [comment]
Replicated the issue https://codepen.io/anon/pen/XjYaKZ

When you click on the button you should see the iframe content be set to a new value.
Is this expected behavior?

**Comment by hugufc** [comment]
Try to set a key prop on iframe vnode. Something like this:

`
m('iframe', {key: 1, config: initFrame.bind(controller)})
`

**Comment by v4n** [comment]
@hugufc cheers, tried it on the codepen example and it does solve the issue. Though I haven't had a chance to test it on my real codebase.
