### ISSUE TITLE
How to handle two events that are triggered in the same draw cycle

### ISSUE THREAD

**Issue by vince166** [lhorie/mithril.js#1359]
http://stackoverflow.com/questions/25845110/onclick-event-not-running-on-first-button-click-in-mithril

When a component contains a TextArea and a Button, there seems to be a race condition between the onchange event (on the TextArea) and the onmousedown event (on the Button). How to implement the onmousedown event handler if its operations depend on the data binding performed in the onchange event handler?

**Comment by lhorie** [comment]
you can either use a setTimeout inside the onmousedown or use a onclick instead
