### ISSUE TITLE
mithril#rewrite withAttr docs

### ISSUE THREAD

**Issue by pine3ree** [lhorie/mithril.js#1366]
Hello @lhorie,

wouldn't it be better to change the name `value` in the [signature of `withAttr`](https://github.com/lhorie/mithril.js/blob/rewrite/docs/withAttr.md) to something like `name`, `attribute`, `attr`.... in 
In my opinion `value` is a bit misleading as we are not actually passing a value or a m.prop but just an attribute name.

kind regards

**Comment by lhorie** [comment]
hmm yeah, you're right. Want to send a PR?

**Comment by pine3ree** [comment]
@lhorie 

sure, what do you reckon to be best? 

`attr` or `attrName`

I would now exclude my proposal for `name` because even if  this signature `m.withAttr(name, callback, thisArg?)` sound good when reading it - the "Attr(name" part can be read as "attribute name"  - this could also lead to confusion as "name" itself is also a common attribute name exactly like "value";
`m.withAttr("name", doSomethingWithTheNameAttribute)`

One could object that attr could also be a property name, but attr is obviously more in line with the method name. :-)

Should i add the optional argument in the signature as well? `withAttr(attr/attrName, callback, thisArg?)`

(btw...naming stuff in development it's always been a long process to me, i like signatures to be as much self-explaining and precise as possible)

kind regards

**Comment by lhorie** [comment]
attrName seems like the best choice
