### ISSUE TITLE
Infinite redraw on exception.

### ISSUE THREAD

**Issue by ludbek** [lhorie/mithril.js#1369]
I am facing an infinite redraw situation. 
I have a component whose `oninit` method requests for a piece of data from server and requests `mithril to redraw`. I hit a situation where if the component's view throws an exception, Mithril infinitely mounts the component and infinitely throws same exception.

```javascript
let aComponent = {
    oninit () {
        // async redraw
    },
    view () {
        // throws exception
    }
};


// results in infinite exception and redraws
```
Is there a solution?

**Comment by spacejack** [comment]
I repro'd a similar thing in this issue: https://github.com/lhorie/mithril.js/issues/1311

**Comment by lhorie** [comment]
@ludbek the solution would be to not throw the error in the view

**Comment by ludbek** [comment]
@lhorie It was a `AttributeError`. Its a rare case but was hard to diagnose.

I was hopping for is a way to prevent this scenario.

**Comment by ludbek** [comment]
@spacejack Yeah same situation. Closing this on favor yours. https://github.com/lhorie/mithril.js/issues/1311
