### ISSUE TITLE
ContentEditable Content Redundantly Appends Last Line when Tabbed out

### ISSUE THREAD

**Issue by yossicadaner** [lhorie/mithril.js#1372]
### Description:

When tabbing out of a contenteditable element with an added line break, the last line is redundantly appended to the contenteditable's content. 
[Describe bug here]
Example, a contenteditable that had added "welcome\nhome", will end up with "welcome\nhomehome"
### Steps to Reproduce:

Edit contenteditable element, add new line(press enter), and tab out.

```js
var value = 'Edit me! - Add new line and tab out';
m.mount(document.body, {
  view: () => m('div', [
    m('[contenteditable]', {
      onblur: (e) => value = e.target.innerHTML
    }, m.trust(value))
  ])
})
```

see [Fiddle](https://jsfiddle.net/mmwhLp2p/6/)

**Comment by isiahmeadows** [comment]
@yossicadaner Reformatted your report :smile:
