### ISSUE TITLE
documentation for oncreate is not clear

### ISSUE THREAD

**Issue by eladzlot** [lhorie/mithril.js#1377]
It is not clear whether nodes with `oncreate` can be recycled

> This hook does not get called when an element is updated, but **it does get called if an element is recycled**.
> 
> Like in other hooks, the this keyword in the oncreate callback points to vnode.state. DOM elements whose vnodes have an oncreate hook **do not get recycled**.

**Comment by lhorie** [comment]
I removed the incorrect statement ("it does get called if an element is recycled") as that is no longer the case
