### ISSUE TITLE
[rewrite] Dragula example no longer working in 1.x

### ISSUE THREAD

**Issue by valtron** [lhorie/mithril.js#1380]
### Description:

The Dragula example from https://github.com/lhorie/mithril.js/wiki/Recipes-and-Snippets doesn't work anymore because 1.x assumes the DOM isn't externally modified, and tries to `removeChild` from the expected parent: [see here](https://github.com/lhorie/mithril.js/blob/bc0a75a6a20f1cbefe0c58b7b2f1687f34a7746d/mithril.js#L804).

### Steps to Reproduce:

1. Go to http://codepen.io/bugmenot/pen/ZBzrmr
2. Open dev console
3. Drag and drop an item from left to right
4. Press "redraw"

### Expected:

No error should be thrown.

### Actual:

Error thrown:

```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

### Solution:

Might be as easy as:

```diff
- if (vnode.dom.parentNode != null) parent0.removeChild(vnode.dom)
+ if (vnode.dom.parentNode != null) vnode.dom.parentNode.removeChild(vnode.dom)
```

...but I'm not familiar with the code and don't know if this will break something else. I could file a PR, if needed.

**Comment by lhorie** [comment]
PR would be welcome

**Comment by lhorie** [comment]
Thanks for the PR @valtron
