### ISSUE TITLE
How set note properties after render

### ISSUE THREAD

**Issue by SuselMan** [lhorie/mithril.js#1384]
### Description:
I have a component witch include textarea. If i change texarea's value from view-model, IE11 reset caret position. I want to change selectionStart and selectionEnd position after view rendering but cant find way how i can listen event like "onrender". How can i catch re-rendering moment?

```
  CARET = 0

  class TitleEditor
    view: (ctrl, {prop, max}) ->
      m "div.title-editor", {class: c('error': not prop())}, [
        m "textarea[autofocus]", {
          maxlength: max  # works for all modern browsers
          placeholder: prop.placeHolder
          config: autosize
          value: prop()
          onkeydown: (e) ->
            e.preventDefault() if e.keyCode is ENTER
          oninput: (e) ->
            CARET=@selectionStart
            @value = sanitize(@value)
            prop(@value)
        }
      ]
```

**Comment by isiahmeadows** [comment]
Have you tried using the `config` Mithril-specific attribute? That runs
right after each render.

http://mithril.js.org/mithril.html#the-config-attribute

-----

Isiah Meadows
me@isiahmeadows.com

**Comment by SuselMan** [comment]
Thank you very much! It is working.
