### ISSUE TITLE
[rewrite] Event handlers not removed correctly from DOM

### ISSUE THREAD

**Issue by valtron** [lhorie/mithril.js#1385]
### Description:

Something's going wrong when events are removed on redraw: `undefined` passed in [updateAttrs](https://github.com/lhorie/mithril.js/blob/bc0a75a6a20f1cbefe0c58b7b2f1687f34a7746d/render/render.js#L458), and used in [updateEvent](https://github.com/lhorie/mithril.js/blob/bc0a75a6a20f1cbefe0c58b7b2f1687f34a7746d/render/render.js#L499). Problem might be the `if (key in element) ...` line.

### Steps to Reproduce:

1. Go to http://codepen.io/bugmenot/pen/NbWNjq
2. Open dev console
3. Click twice on "Click Twice Here"
4. Click on "Then Click Here"

### Expected:

"divclick" should be printed to console. No error should be thrown.

### Actual:

Error thrown:

```
mithril.min.js:33 Uncaught TypeError: Cannot read property 'call' of undefined
```

**Comment by pygy** [comment]
Your analysis looks correct. This [only affects events that can be set inline](https://github.com/lhorie/mithril.js/blob/bc0a75a6a20f1cbefe0c58b7b2f1687f34a7746d/render/render.js#L503) on (real DOM) elements as `onfoo=...`.

Events that require `addEventListener` are not affected.

**Comment by lhorie** [comment]
Fixed
