### ISSUE TITLE
[rewrite] vdom oncreate doesn't get called

### ISSUE THREAD

**Issue by simov** [lhorie/mithril.js#1386]
### Description:

I have a deep data structure that I'm rendering in my app. I finally was able to isolate the issue and reproduce it in a small example.

```js
var tables = [
  {name: 'Table1', records: [{name: 'Record1'}]}
]

var add = (table) => () => {
  table.records.push({name: 'Record1'})
}

var remove = (table, record) => () => {
  var index = table.records.indexOf(record)
  table.records.splice(index, 1)
}

var oncreate = () => {
  console.log('initialize jquery plugin for this vnode.dom')
}

m.mount(document.querySelector('body'), {
  view: (vnode) => [
    m('ul', tables.map((table) =>
      m('li', [
        table.name,
        m('ul', table.records.map((record) =>
          m('li', [
            record.name,
            m('button', {oncreate, onclick: remove(table, record)}, 'Remove')
          ])
        )),
        m('button', {onclick: add(table)}, 'Add')
      ])
    ))
  ]
})
```

### Steps to Reproduce:

The code example is deployed here: http://codepen.io/simov/pen/bBGawj, no idea what 1.0.0rc2 refers to but this behavior is reproducible with the current rewrite branch as well.

1. Open up the console in the above [pen](http://codepen.io/simov/pen/bBGawj)
2. Click on remove
3. Click on add

### Expected:

I'm expecting the `oncreate` event for the newly added element to be called **always** as it is used for initializing jquery plugins.

### Actual:

The `oncreate` event doesn't get called for some reason. I'm assuming it have something to do with the fact that the newly added element is very similar to the removed one.

In my app I'm adding a template object that is always the same, but it needs the `oncreate` event for initializing the jquery plugins in that component.

**Comment by lhorie** [comment]
Try adding a key to the `li`s

**Comment by simov** [comment]
I ended up doing something like this:

```js
{key: record.id || (record.id = (Math.random()*0xFFFFFF<<0).toString(16))}
// some code for generating random hex color :)
```

Because I don't have id's returned from the database for these elements. Seems to be working.

On a side note: I'm migrating my 0.2.5 app to rewrite and this was working without keys and with the old `config` method, but as I understand the new keys logic fixes other issues from 0.x  :+1:
