### ISSUE TITLE
Streams missing map methods after FL prefix update

### ISSUE THREAD

**Issue by JAForbes** [lhorie/mithril.js#1387]
#1352 introduced the FL prefix change to streams, however Stream.map should be exported as before as well.  The prefixing is just for libraries like Lodash/Ramda to safely dispatch.

https://github.com/lhorie/mithril.js/blob/rewrite/util/stream.js#L19

**Comment by lhorie** [comment]
Based on the [discussion that led to the change in the FantasyLand spec](https://github.com/fantasyland/fantasy-land/issues/92), I decided to export `map` as a function:

https://github.com/lhorie/mithril.js/blob/rewrite/stream/map.js
