### ISSUE TITLE
[rewrite] TypeScript types for 1.0

### ISSUE THREAD

**Issue by spacejack** [lhorie/mithril.js#1402]
This is a github repo for Mithril 1.0 types that I've been working on (with valuable help and input from a few other mithril devs and users.)

https://github.com/spacejack/mithril.d.ts

It's been working out pretty well for my own projects so far, though I haven't been using the Stream API all that heavily and there are other corners of the API I likely haven't touched, so they could use some additional eyes on them.

@lhorie - was wondering if you would like to include the type definitions in the mithril repo itself. I'd be willing to field issues/PRs for the 1.0 types. (I'm too out of touch with the 0.2 version to address those.)

Alternately, I could submit this to DefinitelyTyped where it would be maintained by the community. MS has made 3rd party types installation process pretty easy (it would be: `npm install @types/mithril`).

**Comment by isiahmeadows** [comment]
Whoever does this, remember to file a pull request against DefinitelyTyped's [`types-2.0`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0) branch.

**Comment by lhorie** [comment]
@spacejack I'd suggest that you submit to DefinitelyTyped if you feel it'll be better maintained there. Personally, I don't use Typescript and I rely almost exclusively on community PRs for TS support

**Comment by spacejack** [comment]
Ok, I'll submit to DefinitelyTyped types-2.0 branch when 1.0 is officially released. In the meantime I'll try to keep it in sync with any API changes. Any other suggestions, testing, feedback is welcome.

**Comment by lhorie** [comment]
I really really really want to lock down the API now so I can actually get a release out of the door :)

**Comment by isiahmeadows** [comment]
@spacejack I'll note that if you use `moduleResolution: "node"` (and you generally should with the rewrite), the definitions can remain here.

**Comment by lhorie** [comment]
Some updates:

- `background:boolean` and `withCredentials:boolean` were added to `m.request`
- `m.jsonp` now has the same signature as `m.request` (namely, the first param can be a URL string)

**Comment by spacejack** [comment]
Ok! Thanks for the heads up.
