### ISSUE TITLE
[rewrite] Feature proposal: allow whitespace between tokens in hyperscript attribute selectors

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1407]
The current docs recommend that [static DOM attributes be defined in the selector string](https://github.com/lhorie/mithril.js/blob/next/docs/mithril.md#usage):

> The CSS selector syntax (e.g. `a#google.external[href='http://google.com']`) is meant to be used for declaring static attributes in the element, i.e. attribute values that don't change dynamically when the user interacts with the app.

This makes great sense because it makes it easy to distinguish static and dynamic elements when parsing hyperscript structures.

When writing verbose attribute-laden markup, it's also desirable to keep attributes on different lines (see Nicolas Gallagher's [idiomatic HTML advice on the subject](https://github.com/necolas/idiomatic-html#exceptions-and-slight-deviations)). Another opinionated preference for code readability that I'm a big fan of involves vertically aligning keys and values.

A simple example of a hyperscript selector adopting those elements of style would look like this:

```javascript
m(`span[
  id    = foo
][
  class = '
    bar 
    baz
  '
]`)
```

That's a contrived strawman (the right way of expressing that would be as `m('span#foo.bar.baz')` ) but it's a grokkable minimal test case for what I'm proposing. A credible scenario in which this would be desirable might consist of eg large SVG structures, where many static attributes are often necessary (in the case of the `path` attribute it's even desirable to have a multiline attribute).

Would this feature be desirable? Would implementing this have a detrimental effect on hyperscript selector parser efficiency?

**Comment by thysultan** [comment]
a simple removal of tabs, newlines and space(more than one at a time) should make this work. `.replace(/\n|\t|  /g, "")`

**Comment by barneycarroll** [comment]
@thysultan this would apply to the internal content of attributes, which is undesirable - in the test case we would end up with a `classList` of `['barbaz']` rather than the desired `['bar', 'baz']`. This is why it's preferable to introduce this logic into Mithril's internal selector parser, rather than duplicating some of it's careful distinctions before supplying a single-line string to it. As an edge case, it's worth pointing out that there are cases - the most pertinent being SVG path attributes - where advanced whitespace formatting is desirable *within* an attribute value, eg in this code to produce the negative space of the top left corner of a circle:

```javascript
const controlPoint = 50 * ( 4 / 3 ) * Math.tan( Math.PI / 8 )

const path = m( `path[
  fill = white 
][
  d    = "
    M 50,    0
    C ${ 50 + controlPoint }, 0
      100,  ${ 50 - controlPoint}
      100,  50
    L 150,  50
      150, -50
      50,  -50
  "
]
` )
```

IIt's equally helpful for this formatting to appear in the rendered output for inspection.

**Comment by thysultan** [comment]
@barneycarroll  the case `['barbaz']` will not happen since it is only removing additional spaces and not single spaces.

```javascript
.replace(/\n|\t|  /g, '');
```

**Comment by barneycarroll** [comment]
@thysultan that's better than the original Regexp you posted, and would address the initial test case. However it doesn't address the example I posted in reply — and I still believe this is desirable as default behaviour as part of the hyperscript selector parser.

**Comment by lhorie** [comment]
The `class` example is not technically the same as its one-liner counter part (the latter yields "bar baz", the former yields "\n    bar\n    baz\n  ", and this is a case where clever trimming should NOT occur, since that would affect e.g. `vnode.dom.className === someString`.

Another example (very non-idiomatic, but valid nonetheless):

```
m(`textarea[value=${somePythonCode}]`)
```

Re: `path` example, couldn't you just do this?

```
const path = m( "path[fill=white]", {d: `
    M 50,    0
    C ${ 50 + controlPoint }, 0
      100,  ${ 50 - controlPoint}
      100,  50
    L 150,  50
      150, -50
      50,  -50
`})
```

I'm not convinced we need to complicate selector parsing given that there's a similar alternative that is just as effective, and several corner cases that would not behave as expected
