### ISSUE TITLE
Contenteditable elements require a child ?

### ISSUE THREAD

**Issue by oliverhunt** [lhorie/mithril.js#1421]
when an element is contenteditable it now gets run through a function which checks it has a child. This seems to be because its looking for a single child of m.trust(value). However whenever using contenteditables with mithril before I have always set the value user innerText or innerHtml or whatever it is in the attrs onject.

**Comment by barneycarroll** [comment]
The condition is faulty - [an empty array is the default value for `vnode.children`](https://github.com/lhorie/mithril.js/blob/rewrite/render/hyperscript.js#L60). Why were no tests written for this feature?

**Comment by oliverhunt** [comment]
Perhaps the error should state that the value of a contenteditable must be set through content rather than a js object attribute.

**Comment by barneycarroll** [comment]
Nah it was just plain wrong. If you don't pass any children in to hyperscript, it always creates a vnode with an empty array of children, so it's flat out wrong for contenteditable to complain when it sees the array. I've got a fix pending in #1425

**Comment by lhorie** [comment]
#1425 is merged
