### ISSUE TITLE
[rewrite] implement vnode.parentVnode

### ISSUE THREAD

**Issue by darsain** [lhorie/mithril.js#1427]
Or `vnode.parent` for simplicity.

Currently we can walk the tree down via `vnode.children`, which is awesome and powerful. But in case you need to go the other way around, you are out of luck.

## Use case

Any need to access vnode ancestors or find the vnode in a tree if you already have the vnode.

## Real world use case

*Sorry for the wall of text below, I'm just trying to make my case that this is all very useful, and I'd love to have an interface that would allow me to implement it efficiently.* ❤️

I'm implementing mithril bindings for redux. It works by having a top `Provider` component that has redux store attached to its state. All descendant `connect()`ed containers (wrappers that provide `store state -> attrs` mapping for actual components) than need to access that store, map it to `attrs`, and render the connected component with it.

Currently, without `vnode.parent`, `Provider` has to `oninit` & `onupdate` walk the whole tree below it to find `connect()` wrappers and attach store to their state. In real world this is going to be a thousand of vndoes long walk on init **and** each update (since new wrappers might have been added).

*Edit: turns out this implementation is broken, and can't be implemented in a stable way without `vnode.parent`, read more in https://github.com/lhorie/mithril.js/issues/1427#issuecomment-262939334 below.*

With `vnode.parent`, the wrappers themselves could just `oninit` do a couple lookups for an ancestor `Provider` up the chain and get the store from there, reducing complexity and speeding up the providing part of the implementation by several orders of magnitude.

My mithril-redux implementation prototype is here (*broken, read https://github.com/lhorie/mithril.js/issues/1427#issuecomment-262939334 below*):

- http://jsbin.com/qanorec/edit?js,output
- https://codepen.io/darsain/pen/pNPZzy?editors=0010

#### API:

`mount(root, component, store)`

Mounts component inside a `Provider` in an isolated render island that redraws only when store state changes, unaffected by other mithril apps/mounts on a page.

`Provider` => `m(Provider, {store, [redraw]}, m(component))`

Creates a store & redraw method provider for all descendant `connect()` wrappers.

`connect([mapStateToAttrs], [mapDispatchToAttrs], [customMerge], [options])(component)` 

Wraps `component` so the `attrs` it receives are mapped from store on a closest ancestor `Provider`, and don't have to be passed through every component above.

```js
const defaultMapState = state => ({});
const defaultMapDispatch = dispatch => ({dispatch});
const defaultMerge = (state, dispatch, own) => assign({}, own, state, disp);
const defaultOptions = {pure: true};
```

#### Features:

- Per mount store provider with no reliance on a single global store or singleton.
- Multiple apps/widgets with different stores on page (not possible with current mithril-redux npm module, which is for 0.x anyway).
- Isolated mounts that redraw only when their own state changes.
- `connect()` isolated components to the store on the closest ancestor `Provider`.
- Pure `connect()`ed components cache and redraw only when their `attrs` (mapped from store state) change.
- Impure `connect()`ed component's `attrs` receive scoped `redraw()` to redraw only the current mount.

*Pure component*

Component that relies only on `attrs`, and doesn't keep its own state, thus can be easily cached. In this kind of architecture, where 99% of the state is kept in one store saved on a `Provider`, this will be 99% of the components.

*Impure component*

Component that keeps its own state, which means `connect()` wrapper can't cache these kind of components.

You define an impure component by passing `{pure: false}` into `connect()` options argument.

#### What is actually all this `Provider` + `connect()` stuff for?

It's solving the pain of passing shared data and event handlers to components via `attrs` through many levels of components that don't care about them, while still retaining isolation of each component. Meaning, no component taps to any global or per app state/store/context. They all still work on `attrs` and can be consumed in other places. They don't even know about redux, context, global stores/states or anything of the sorts. The are still completely isolated and architecture agnostic. `connect()` than allows you to connect these isolated components to redux store, which is saved on `Provider`, doing the relevant data/handlers passing only in one single place, and that is the `connect()` wrapper definition.

The example of a shared data that would have to live in root component and be passed everywhere via `attrs` is user configurable (via some UI) per app `config` object. With this kind of architecture, if any component needs a config value, you can just `connect()` it to it, and it'll receive that as `attr`. If it also needs a way how to change this value, again, `connect()` it to a `changeFoo(val)` handler received via `attrs`.

#### Differences with react-redux

React components don't have access to vnodes, so react-redux `Provider` & `connect()` have to be implemented using an unstable and discouraged React context API. With vnode references, we have a more stable and nicer API, and don't need context. But it desperately needs that `vnode.parent` 😃.

**Comment by barneycarroll** [comment]
@darsain following on from our conversation on Gitter, I think it's far preferable to implement the desired functionality without extending the vnode API.

I don't think it's a good idea to extend the vnode surface this way because it introduces extra complexity that tempts users into anti-patterns. If you think about it, not only does this force a whole extra dimension of impurity to the fundamental API even in a pure vnode application, it also relies on a hack which invites the user to violate the principle of uni-directional data flow that flux supposedly champions.

Crawling up the vnode tree is unnecessary (and unnecessarily costly) if we provide a dedicated model for managing context rather than extending vnode. We could easily create this as a dedicated wrapper API that left Mithril internals intact — which I'd be happy to help with to meet your requirements (based on the popularity of flux I think this could be a very successful project in its own right).

IIRC you had an aesthetic dislike of the single global state manager approach I took in my last gist, is that a sticking point for you? If so, we can actually do this in a much more explicit functional way while avoiding any dependencies in component files by providing a contextualised (see what I did there? ;P) hyperscript instance via vnode. This would have the aesthetic merits (up for debate) of totally internalising the dependency model and actually making the context API a significant degree more pure by providing all relevant hooks rather than using global context-aware imports. In other words, whereas my previous attempt went:

```javascript
import m from 'contextual-mithril'

export default {
  view(){
    return m( 'div', this.context.value )
  }
}
```

We could look at:

```javascript
// no imports, everything is provided by the consuming module

export default {
  view( { m } ){
    return m( 'div', this.context.value )
  }
}
```

Of course, that elides the explicit context dependency declarations (which IMO *feels* more correct), but of course this suggestion is independent of that API surface detail.

What do you think? Worth pursuing? :D

**Comment by darsain** [comment]
I don't want components to use a special mithril, or a special non-mithril API. I wan't them to be completely architecture agnostic and isolated, so you can reuse them in any project/app no matter what state management it's using.

`vnode.parent` won't add any more complexity and tempt people into anything more than `vnode.children` already does. I absolutely agree that users should be discouraged from using them. And in my redux binding implementation, they don't. They are just necessary for the implementation to work, so users don't ever have to touch them.

The data is still going only one way, but thanks to the `Provider` & `connect()` it's creating bridges to jump over components that don't need it. Otherwise you have to pass it everywhere via `attrs`, stuffing that object to the brim. The code than looks horrible. You need to keep every intermediate component in sync with all the data that it needs to pass down,... tons of ugliness. And `vnode.parent` would allow these bridges to get **a lot** more efficient.

Do you really see no value in `vnode.parent`? Would you rather 100% commit to the fools errant that is trying to stop stupid people from shooting themselves in the foot rather than implement useful tools?

You've surely seen all the warnings in react's context docs. They tell you right up front to not use it or you are gonna have a sore foot. But context is still in react with no plans of getting rid of it, because it's just that necessary to implement useful tools like redux bindings, which are written by same people that wrote that docs, and even recommended in them. Mithril, thanks to the way how its components and rendering work, doesn't need an unstable API like context. Vnode references solve this in a way more stable way. But without `vnode.parent` it's way less efficient than it could be :(

**Comment by darsain** [comment]
I've just realized my implementation is faulty, and the only reason it worked was a coincidence of how the testing examples were set up. It all relied on `view` running before `oninit` (didn't catch it due to insufficient testing examples). `Provider` just can't walk the children tree in its `oninit` hook, because it is not generated yet. As soon as I add one intermediate component between `Provider` and `connect()`ed component, the thing breaks:

https://codepen.io/darsain/pen/KNqbGR?editors=0010

So now I don't really have a choice but to wait for `vnode.parent`, without which there is no stable and solid way how to implement this.

Actually I'm lying. I made it work with this nasty hack:

https://codepen.io/darsain/pen/ObgrLy?editors=0010

1. `Provider` `oninit` & `onupdate` hooks populates a global variable with its store.
1. `connect()`ed components `oninit` hooks retrieve store from this variable.

It relies on a global variable (eewww) and `m.render()` being and always remaining synchronous. Needless to say I absolutely hate this hack, although it *is* fast 😄.

I now beg for `vnode.parent` ༼ つ ◕_◕ ༽つ

**Comment by barneycarroll** [comment]
@darsain BTW there's a built-in hook for sidestepping recomputation, you can use the [`onbeforeupdate` hook](https://github.com/lhorie/mithril.js/blob/rewrite/docs/lifecycle-methods.md#onbeforeupdate):

```javascript
const onbeforeupdate = ( { state } ) => !state.pure || state.dirty
```

If `onbeforeupdate` returns false, the view is not executed and Mithril skips the diff process for the subtree.

**Comment by darsain** [comment]
@barneycarroll thanks! missed that while reading docs :)

**Comment by epidemian** [comment]
Hmm, i can't wrap my head around how `vnode.parent` would make sense in the context of the virtual DOM.

(Disclaimer: i haven't used Mithril in quite some time, so i might have forgotten many things)

For example, in this code snippet:

```javascript
var alice = m('.person', 'Alice')
// Alice is both on the engineering and testing teams.
var engineering = m('.team', [alice, bob, carol])
var testing = m('.team', [alice, dave])
```

What would `alice.parent` be?

**Comment by pygy** [comment]
@epidemian Even without `parent` you can't have the same `vnode` object several times in a vDOM tree, because of the `vnode.dom` attribute (which is used by the diff engine, an can be reached in hooks).

The `parent` field would probably have to be populated at `render` time anyway...

**Comment by barneycarroll** [comment]
@epidieman you're right — `vnode` as it stands is a product of the hyperscript `m` function — a self-contained structure which is the pure product of the input given to it. To populate parent would require mutating the nodes after creation, during the lifecycle, and produce circular structures (eg `vnode.parent.children[0].parent.children[0]...`). No more finite JSON representations!

**Comment by isiahmeadows** [comment]
What's the status of this bug?

**Comment by barneycarroll** [comment]
@isiahmeadows it isn't a bug, it's a contentious feature request. Read the thread.

**Comment by lhorie** [comment]
FYI, I'm handling feature requests at low priority atm, in favor of finishing docs and bug fixes

**Comment by isiahmeadows** [comment]
Closing, since this issue has not been updated in over a month, and typically, issues inactive for that long do not usually produce any action. If you feel something in Mithril needs added or changed, please file a new issue.
