### ISSUE TITLE
[rewrite] MSX like transformer for Mithril js 1.0

### ISSUE THREAD

**Issue by lugrugzo** [lhorie/mithril.js#1432]
### Description:

Hello

Are there any working transformer like MSX? I want to use Mithril 1.0 without dealing `m("div") `functions. MSX is not updated for 2 years.

**Comment by Papipo** [comment]
Have you tried? Because I find straight m() calls to be way better than MSX.

**Comment by lugrugzo** [comment]
I tried both msx and m() unfortunately never get used to m() usage. It looks complicated to me.

**Comment by tivac** [comment]
You can use babel with a small annotation to have it replace things with `m()`.

https://babeljs.io/docs/plugins/transform-react-jsx/#custom
