### ISSUE TITLE
In rewrite version aka 1.0 theres no way to prevent view execution

### ISSUE THREAD

**Issue by volnei** [lhorie/mithril.js#1437]
### Description:

Im writing a new app using 1.x and can't prevent view rendering when user is not authenticated (or some rule), even when I redirect using m.route.set("...") the current component view method is called.

```javascript
var Layout = function(component) {
	return {
		oninit: function(vnode) {
			vnode.state.component = component
			return new Layout.oninit(vnode)
		},
		view: Layout.view
	}
}

Layout.oninit = function(vnode) {
	// pre validations
	if(1) {
		m.route.set("/notfound")
		return
	}

	vnode.state.component = vnode.state.component.view.bind(this, vnode)
}

Layout.view = function(vnode) {
	console.log("Called...")
	return m('#main', m.component(vnode.state.component()))
}
```

**Comment by lhorie** [comment]
You can use route resolvers for this, here's the section of the docs pertaining to authentication

https://github.com/lhorie/mithril.js/blob/rewrite/docs/route.md#authentication

**Comment by volnei** [comment]
Fantastic!! Thank you @lhorie
