### ISSUE TITLE
[rewrite] bug: conditional vnodes reconciliation behaviour

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1445]
#1014 raises the issue of reconciliation expectations regarding `null` vnodes.

For the sake of this ticket, the `null` value itself should be considered an implementation detail - whether or not it is a good sentinel value to signify what it does should be debated over at #1014.

The expectation is that toggling a vnode at any given position between a truthy value (or an empty string, or 0) and `null` - and vice-versa - should effectively remove the DOM from the real DOM while ensuring subsequent vnodes are correctly re-identified in virtual DOM reconciliation, such that they update in place. 

In practice, this doesn't work. This fiddle demonstrates issues with lifecycle & rendering when a vnode alternates between text and null: https://jsbin.com/xomehaz/edit?js,console,output

A conditional node precedes a persistent one, and the condition starts false. When the condition becomes true, Mithril render judiciously inserts the new node before the old one and leaves the second node intact (triggering update). But then when the condition returns to false, the button node somehow fires update (with old DOM reference) *and then* oncreate (with a new DOM reference).

**Comment by lhorie** [comment]
Fixed
