### ISSUE TITLE
Website makes project look dead.

### ISSUE THREAD

**Issue by finetype** [lhorie/mithril.js#1446]
I like Mithril, used it to build a site of my own for fun in the past. Haven't used it recently because I don't get to at work, and haven't worked on my own 'fun' side projects in a while.

Seeing the website say "2014" at the bottom, and not seeing any change, or any reference to the rewrite, or any updates, and the website itself looking pretty dated... I had to pause and wonder whether Mithril had died.

I'm not suggesting anyone has time to rewrite the site, but at least having something there to make it clear that the project isn't dead would probably be a good idea. Maybe even just some live-updated little reference to commits on github or something. Or just a note mentioning the site isn't frequently updated, and to check github for the latest. Maybe with a mention of that being due to a beautiful, new version being in the works.

Or at least changing the footer to say 2016. You know, since we're almost into 2017.

Looking forward to 1.0 being stable. Thumbs up to you guys. Just thought I'd mention it.

**Comment by isiahmeadows** [comment]
@finetype 

We all know. Trust me. :smile: 

> I'm not suggesting anyone has time to rewrite the site

Once it gets close to time for 1.0 to get released, it's going to get rewritten entirely, because 50% of the docs won't make sense.

> Or at least changing the footer to say 2016. You know, since we're almost into 2017.

It's been updated in 2016; the footer shouldn't be static text (even though it probably is, by the sounds of it).

> Looking forward to 1.0 being stable. Thumbs up to you guys. Just thought I'd mention it.

Thanks! :smile:

**Comment by lhorie** [comment]
The new site design just has a &copy; 

The copyright line doesn't actually need a date, and it doesn't even need to exist. That's something google used to do back in the days as a hint for people who had scrolled to the end of the page and weren't sure if the site was broken (because it was fast compared to other sites). Then other people started copying it and it stuck.

**Comment by isiahmeadows** [comment]
@lhorie 

(disclaimer: not a lawyer, so don't take this as legal advice :wink:)

IIRC at least in the US (most of the West is pretty similar to my understanding), all creative works are copyrighted by default, and the creator owns full rights to it. Websites are technically creative works and thus the design and site-specific content is likely copyrighted. IMHO, to avoid legal ambiguity, the site *should* have a copyright line, and preferably an associated license as well for the non-code content (code should have the same license as in the repo, but MIT isn't made for documentation). I'd err on the side of legal caution on this one.

In case you're curious, I, for similar reasons, licensed my website under two separate licenses: ISC for the source code and CC-BY 4.0 International for the rest (with specific exceptions so I can leave the previous CC-BY-NC 4.0 International on some of my older music I created). I'd rather err on the side of caution than to leave a legally ambiguous situation with how my website's content can be used.

*Similarly, I won't even touch the WTFPL or Unlicense - both are very legally ambiguous (the former's "do whatever you want" can still imply "within reason", and the latter is inconsistent), and in particular, the WTFPL doesn't include a warranty disclaimer.*
