### ISSUE TITLE
`m.redraw()` isn't throttled for routed trees anymore

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#1448]
### Description:

`m.redraw() should be throttled for routed trees.

### Steps to Reproduce:

http://jsbin.com/razirecejo/edit?js,console

```
var i = 0
m.route(document.body, '/', {
  '/':{view: function() {i++}}
})
console.log('route '+ i)

m.redraw()
m.redraw()

console.log('redraw ' + i)

setTimeout(function(){
  console.log('async ' + i)
},40)
```

### Expected:

The behavior before the #1404 fix

```
route 1
redraw 1
async 2
```

or alternatively, if it is decided that `route` first draws asynchronously:

```
route 0
redraw 0
async 1
```

### Actual:

```
route 0
redraw 2
async 3
```

**Comment by lhorie** [comment]
I'm going to honor the behavior from this test: 

https://github.com/lhorie/mithril.js/blob/f7c187eec98f3e58a9c6959490d0cd8c58d932cf/api/tests/test-router.js#L54-L66

and make extra redraw calls be async and throttled

**Comment by pygy** [comment]
Great!
