### ISSUE TITLE
The case for a mount-based router

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#1453]
Following up on #1404 @lhorie @barneycarroll 

The gist of a mount-based router is the following (omitting `attrs`, `path` and the race condition mitigation for clarity, and assuming a RouteResolver): 

1) When routes are defined, mount a component whose view returns `[curent.render(m(current.component))]`.

2) When routes are set (explicitly or through history navigation):
   1) define a `resolve(component)` function that sets `current.render` and `current.component`, then trigger a redraw.
   2) Pass said function to `payload.onmatch`.

That's it.

The additional conditional logic is there to assign fallbacks for `component`, `onmatch` and `render` when one is missing, and to ignore the `onmatch` and `render`  fields on components.

I find this more declarative and thus easier to reason about, but it may be a matter of taste.

Pros: 

- Redraws are identical to what happens with mounted trees, thus:
   - There's no router-related conditional logic on redraw (easier to debug).
   - The route matching logic doesn't run on redraw as it does currently
   - No `isAction` business is needed in `router/router` (and by consequence in `api/router`). Once again, less complexity.
   - There's no need to return `resolveRoute` from `router.defineRoute` either.
   - Harnessing the public API to make such a complex component ensures it is robust (thinking about timing here mostly).
  
Cons:

- Adds a component and a fragment to the tree for `render/render` to diff (probably minor when compared to the route matching logic).
- File size, maybe? I'll have to test.
- ???

**Comment by pygy** [comment]
Another thing in this design is that it treats components as if they were inheriting from a default RouteResolver (whose methods can't be overridden). It means that render-time logic is identical for both components and RouteResolvers.

**Comment by lhorie** [comment]
Ok, I finally understand where you were going w/ the mount-based strategy. I refactored api/router again to take advantage of your optimization for skipping route matching logic on non-routed redraws, except that I'm using render directly (which requires no wrapper components) instead of mount

**Comment by pygy** [comment]
It looks fine at a glance, I'll scrutinize it later. With the redraw service as a common ground, it looks like the best of both worlds.
