### ISSUE TITLE
contenteditable node with focus doesn't update on data change

### ISSUE THREAD

**Issue by igor-k** [lhorie/mithril.js#1458]
Hi,

I'm making a sort of autocomplete in a contenteditable node. But when the node has focus, if the content gets changed, the node is not updated. It gets ignored [here](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L527). Here is a [fiddle](https://jsfiddle.net/7ogwxu6j/1/) to demonstrate what I'm talking about.

I tried to write a test for it, but it's not working in your test harness, since the dom mock doesn't seem to handle focus state, document.activeElement is set to body when it matters.

Would there be any harm in also checking if the data has changed vs the cached value? Let me know what you think and how I can proceed.

Thanks!

**Comment by igor-k** [comment]
I guess some clarifications for the fiddle, the data changes in a timeout, but the node that has the focus doesn't get updated.

**Comment by isiahmeadows** [comment]
@igor-k Go ahead and file a PR with what you have, so I can take a look at it. Also note that I created a `dom(function() { /* body */ })` utility function to put whatever tests need a real, live DOM in (i.e. where the mock is insufficient). If you drop it in `test/mithril-render.js`, there should already be such a section IIRC.

**Comment by igor-k** [comment]
ok, done, #1475

**Comment by isiahmeadows** [comment]
@igor-k Reopened until the PR is merged.
