### ISSUE TITLE
Skip on undefined children

### ISSUE THREAD

**Issue by Satyam** [lhorie/mithril.js#146]
In [build](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L36), when `data` is `undefined`, it turns it into an empty string.  This seems somewhat wasteful as a node containing an empty text string won't be visible.  It takes an extra DOM text node, an extra element in `cellCache` and the time to process that for no use.  

It makes this seem wasteful:
```
m('div', whatever.map(function (item) {
     if (some condition) return 'something';
     /* return;  //nothing */ 
});
```
or:
```
m('div', [
     'something',
     (condition ? 'optional' : undefined);
]);
```
As a matter of fact, is it worth bothering with nulls at all?  
If, for some reason, an empty string is needed, let the developer explicitly put an empty string there and create the node but with undefined and null, why bother?

May I  suggest simply skipping over `undefined`s (and possibly `null`s)?  An undefined children seems a pretty good way of signalling there is nothing there to bother with.

**Comment by lhorie** [comment]
I'm going to keep the current behavior in order to maintain support for coffeescript's if expressions
