### ISSUE TITLE
Allow Headers to be set with m.request config

### ISSUE THREAD

**Issue by cetra3** [lhorie/mithril.js#1463]
### Description:

Sometimes you need to set http headers when making a request to a remote end service.  This includes things like custom headers your API requires such as tokens, etc...

It should be possible to set these headers or pass them in as a parameter when calling m.request

### Steps to Reproduce:

```
var headers = { "Authorization" : "Bearer 12345abcd12345" };
var users = m.request({method: "GET", url: "/user", headers: headers});
```

### Expected:

Headers are sent alongside the m.request

### Actual:

Headers aren't sent

**Comment by tivac** [comment]
http://mithril.js.org/mithril.request.html#configuring-the-underlying-xmlhttprequest provides access to do whatever configuration you desire to the underlying XHR object. Does that cover your use-case?

**Comment by cetra3** [comment]
Oh, I went a bit of a different route: https://github.com/lhorie/mithril.js/pull/1464

It's probably a redundant PR if you can do it that way.  Depends whether you feel that there should be a cleaner interface for this sort of stuff
