### ISSUE TITLE
[rewrite] Promise - console.error: Possible unhandled promise rejection

### ISSUE THREAD

**Issue by simov** [lhorie/mithril.js#1465]
Hi, 

I get this weird error message in my console and I don't know what to do with it. Here is how to reproduce it:

### server.js

```js
var http = require('http')
var server = http.createServer()
server.on('request', (req, res) => {
  res.writeHead(400, {
    'Access-Control-Allow-Origin': '*',
    'content-type': 'text/plain'
  })
  res.end('hi')
})
server.listen(3000)
```

### client.html

```html
<script>
  m.request({
    method: 'GET',
    url: 'http://localhost:3000'
  })
  .then(() => console.log('OK'))
  .catch((err) => console.log(err.message, 'totally not OK'))
</script>
```

### output

![totally-not-ok](https://cloud.githubusercontent.com/assets/1694112/20961070/19a04eaa-bc6c-11e6-99fc-67b44674ae87.png)

As you can see I'm making HTTP request to a server that responds with a 400 status code. Then I'm handling the error in the catch error handler by printing it out to the console, and yet I'm still getting the console.error message on line 101 - Possible unhandled promise rejection. I'm not sure what to do with this error message.

**Comment by isiahmeadows** [comment]
What version is this?

**Comment by simov** [comment]
Latest master from a few hours ago.

**Comment by isiahmeadows** [comment]
[Here's the problem section](https://github.com/lhorie/mithril.js/blob/rewrite/request/request.js#L19-L22). Should be easy to fix, even for those less familiar with the rewrite code base.

**Comment by lhorie** [comment]
Fixed

**Comment by simov** [comment]
Thanks to everyone involved :+1:

**Comment by isiahmeadows** [comment]
@lhorie I was kind of leaving it hanging in hopes for a potential new contributor. :wink:
