### ISSUE TITLE
[rewrite: mocks] changing the hash doesn't match the browser behaviour.

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#1467]
Changing `window.location.hash` triggers `window.onpopstate` in the browser, at least in some situations.

`window.onhashchage` but asynchronously and debounced.

The mocks don't emulate that behavior.

I've tried adding `popstate()` in the `hashchange()` function, but it breaks many tests and I don't have the time to investigate the intricacies of `location` and `history` and how the mock implement them right now, hence this report.

**Comment by isiahmeadows** [comment]
Closing, since this issue has not been updated in over a month, and typically, issues inactive for that long do not usually produce any action. If you feel something in Mithril needs added or changed, please file a new issue.
