### ISSUE TITLE
[rewrite: request] Add fetch feature

### ISSUE THREAD

**Issue by DonRiccardo** [lhorie/mithril.js#1474]
Can be the request updated with a fetch function?

The rewrite version already has the Promise polyfill, so we can add easily fetch polyfill (e.g. whatwg-fetch).

I know it will add to the size of the mithril package. But this version is made of modules, so why not to use modularity to add a new module for fetch request, so people who want fetch can use fetch and people who want less size in mithril package can use the old request module?

**Comment by barneycarroll** [comment]
The request API offers a range of possibilities fetch doesn't. Unlike fetch, request can:

* Communicate with JSONP endpoints 
* Receive data progressively instead of all at once
* Abort requests

But in the simplest case — getting JSON — request is also more concise than fetch, in that it unwraps JSON automatically by default:

```javascript 
// request
m.request('/url')
  .then(json => state.data = json)

// fetch
fetch('/url')
  .then(response => response.json())
  .then(json => state.data = json)
```

**Comment by DonRiccardo** [comment]
I didnt want to replace whole request API by fetch function. I just thought it would be better to use fetch when its available in browsers and use XHR when not. The fetch function should be faster and more optimized than the old XHR.

**Comment by leeoniya** [comment]
> I just thought it would be better to use fetch when its available in browsers and use XHR when not

They have different APIs and many other subtle differences that would not work uniformly in different browsers without some abstraction layer - which would be slower, buggy and would have to be maintained.

> The fetch function should be faster and more optimized than the old XHR.

It isn't, unless you're streaming.

**Comment by tivac** [comment]
We discussed it ended up keeping it XHR based. I think that's a reasonable choice, and it's not likely to change.
