### ISSUE TITLE
 [rewrite] onupdate not being called in 1.0.0-rc.6 (works in 1.0.0-rc.5)

### ISSUE THREAD

**Issue by vasilrimar** [lhorie/mithril.js#1476]
### Description

1.0.0-rc.5 version - <http://jsbin.com/deciyih/9/edit?js,output>

1.0.0-rc.6 version - <http://jsbin.com/jeharo/3/edit?js,output>

Clicking "Increment Counter from Portal" button should call `onupdate` for the "Portal" component but doesn't in `1.0.0-rc.6` version. Works as expected in `1.0.0-rc.5`.

**Comment by tivac** [comment]
Also failing in current `rewrite`, haven't dug into why though yet.

https://jsbin.com/yakezoj/1/edit?html,js,output

**Comment by Cybermage83** [comment]
yeah, adding m.redraw() in the view at Portal make it work heh. Please fix this

**Comment by tivac** [comment]
Actually looking at this closer I'm a little surprised that clicking that button ever hooked into the auto-redraw system. I don't really think manually-created DOM nodes filled out using `m.render` **should** hook into the auto-redraw.

Curious why you're rendering this way instead of making the Portal look something more like this: 

https://jsbin.com/foceciharo/1/edit?js,output

**Comment by vasilrimar** [comment]
I need the `vnode.children` to be rendered into the 'Portal' div (as opposed to inline) to avoid CSS z-index and overflow issues. 

Here's an example to illustrate what I mean:

<https://jsbin.com/nififes/10/edit?css,js,output>


And here's another with the children being rendered into the 'Portal' div: 

<https://jsbin.com/xecane/edit?css,js,output>

**Comment by tivac** [comment]
Oh, I see why it stopped working. There was a bug previously that tied `m.render` to the same `redrawService` that `m.mount`/`m.route` would use.

@lhorie fixed it in [this commit](https://github.com/lhorie/mithril.js/commit/f54f15d4ce748659dcdb9dbd53654ae55b71d143) by breaking that coupling that shouldn't have existed in the first place. 

If you want to continue using them together this way I recommend either adding `m.redraw` to your code where appropriate or maybe putting the component outside of the parent element if the styling requires that it live outside of it in the DOM.

**Comment by pygy** [comment]
@lhorie @tivac maybe we could expose the currently private `render` from `api/redraw.js`  as `m.redraw.render`?
