### ISSUE TITLE
Using routes to sort components (multiple routes per app)

### ISSUE THREAD

**Issue by kvanberendonck** [lhorie/mithril.js#1481]
### Description:

From reading the documentation my team got the impression we might be able to do this:

JS:
```
var Widget = {
  controller: function() {
    return {
      param1: m.route.param("param1"),
      param2: m.route.param("param2")
    }
  },
  view: function(controller) {
    return m('div', controller.param1 + "," + controller.param2);
  }
};

m.route(document.getElementById('widget1'), '/path/foo/bar', {
  '/path/:param1/:param2': Widget,
});

m.route(document.getElementById('widget2'), '/path/qux/herp', {
  '/path/:param1/:param2': Widget,
});
```

HTML:
```
<html>
  <head>
    <title>Route test</title>
    <script src="mithril.js"></script>
  </head>

  <body>
    <div id="widget1"></div>
    <div id="widget2"></div>
  </body>

  <script src="app.js"></script>
</html>
```

### Expected:

We expected the page to render both foo,bar and qux,herp but we only got foo,bar. The other routed component was ignored.

We wanted to load components from "URLs" so that developers in another part of the app could embed and re-use components by path name as we release them i.e. m.route(chartDiv, '/path/to/chart/databaseid/type/prefs', routes).

Perhaps our interpretation of the documentation was wrong.

**Comment by lhorie** [comment]
Yeah, you can only have one m.route call per application

**Comment by lhorie** [comment]
I made a note about this in the documentation
