### ISSUE TITLE
Use Promise returns for all Mithril APIs requiring user-defined async resolutions

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1486]
In an effort to make Mithril API signatures more consistent and defer to standard contracts where possible, I propose we ensure all APIs that allow for authors to provide async resolution conditions rely on returning Promises.

This is already the case for request resolution and onmatch, and AFAICT the only outstanding API is onbeforeremove, which can then become more consistent with onbeforeupdate, whereby the signature will fall inline with the other lifecycle methods and have special concerns dictated by return value.

**Comment by lhorie** [comment]
I'm +1 on this

**Comment by isiahmeadows** [comment]
The callbacks have admittedly felt a tad clunky.

**Comment by tivac** [comment]
I think callbacks are nice and simple for a use-case like this, but I'm not opposed to a promise. I just wish it was easier to create/resolve them 😒

**Comment by lhorie** [comment]
onbeforeremove now expects a promise
