### ISSUE TITLE
[rewrite] PromisePolyfill always overwrites `window.Promise`

### ISSUE THREAD

**Issue by valtron** [lhorie/mithril.js#1489]
[This line](https://github.com/lhorie/mithril.js/commit/846d6ce24b380bea12face9389a059583034d179#diff-63de04924f7fd5b53de072769e289dfbR4), bundled [here](https://github.com/lhorie/mithril.js/blob/bc01dad847f02aa1636fe1aba6057d6b338f02d6/mithril.js#L961), makes `Promise` a local variable, and [this](https://github.com/lhorie/mithril.js/blob/bc01dad847f02aa1636fe1aba6057d6b338f02d6/mithril.js#L177) checks _that_ instead of `window.Promise`. At the point of this check, `Promise` hasn't been assigned yet, so the polyfill will always replace `window.Promise`.

**Comment by lhorie** [comment]
yep, known bug in bundler. Haven't gotten around to fixing it

**Comment by isiahmeadows** [comment]
Fixed in #1490.
