### ISSUE TITLE
[ospec] deepEquals ignores non-numeric properties set on arrays

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#1497]
### Steps to Reproduce:

```
o('deepEquals should check non-numeric properties on arrays', function() {
  var a = ['a']
  a.a = 'a'
  o(a).notDeepEquals(['a'])
})
```

### Expected:

A passing test

### Actual:

```
deepEquals should check non-numeric properties on arrays:
["a"]
should not deep equal
["a"]
```

### Context:

I'd like use this to test a mock of a native browser object that is array-like, but with additional properties.
It can be worked around by using `equals` many times, but having native support would  help.

Edit: For my use case, since I don't need any array method after the object is created, I made a few helpers to build a psuedoArray as an object with a `length` property and "numeric" keys, and then some. A bit hacky but it works... Still, I'd prefer native support for `deepEquals`, if possible.

**Comment by lhorie** [comment]
Fixed

**Comment by pygy** [comment]
Great, many thanks!
