### ISSUE TITLE
[rewrite] m.route locks up browser

### ISSUE THREAD

**Issue by schtauffen** [lhorie/mithril.js#1498]
### Description:

When m.route fails to find an appropriate match, it is locking up my Chrome browser. I must manually kill chrome and reopen (hopefully not to the page which includes the misfiring m.route or it immediately does it again).

Tested in Chrome Version 55.0.2883.87 m
rewrite rc6

### Steps to Reproduce:

```js
var m = require('mithril')
m.route(document.body, '/') /* or specify a routes object which doesn't have '/' */
```

### Expected:

An error should be thrown

### Actual:

The browser locks up

**Comment by schtauffen** [comment]
I only looked at the router code briefly, but my assumption is bail needs to verify defaultRoute is defined before attempting to go there.

**Comment by lhorie** [comment]
This is fixed in rc7
