### ISSUE TITLE
broken doc link

### ISSUE THREAD

**Issue by cmnstmntmn** [lhorie/mithril.js#1508]
the last [link](https://github.com/lhorie/mithril.js/blob/rewrite/docs/simple-application.md) on [this page](https://github.com/lhorie/mithril.js/blob/rewrite/docs/introduction.md) is broken

**Comment by porsager** [comment]
I think Leo mentioned on gitter a couple of days that he's working on it, so it'll probably come when he's done ;)

**Comment by lhorie** [comment]
^ what @porsager said
