### ISSUE TITLE
[rewrite: docs] git vs npm

### ISSUE THREAD

**Issue by IBwWG** [lhorie/mithril.js#1515]
### Description:

Installing via npm per the README doesn't give you what you're looking at the in the docs section.

### Steps to Reproduce:

E.g. the docs talk about `options.headers` in `m.request()`, which was a feature added 7 days ago (apparently just *after* rc.7 was released, just my luck.)  I installed yesterday and was scratching my head why that feature didn't seem to work, when I noticed in the mithril source that it simply didn't exist.  :)

### Expected:

That the README would either:

a) tell you how to use the very latest version, or
b) give a docs caveat telling you to go to https://github.com/lhorie/mithril.js/tree/531f9a52ba3a5a7c0e639eedcd6857d5826a11cd/docs (rc.7 only) -- I know this adds a step to the release process, but it might help to confuse new users less

**Comment by tivac** [comment]
Once the docs are published to a static site as part of a release that won't be an issue, so I'm not sure doing the work to change this is really worth it.

**Comment by IBwWG** [comment]
Maybe just a caveat?

**Comment by isiahmeadows** [comment]
@IBwWG That's just a product of the fact we don't have commits automatically published on `npm` for the rewrite, and development is still active. :wink: Once `rc.8` is published, it should be fixed.
