### ISSUE TITLE
[rewrite] proposal: able to query vnode inside

### ISSUE THREAD

**Issue by futurist** [lhorie/mithril.js#1518]
### Description:

Think have a big component, it's good for looking for some `vnode` inside

Just like DOM methods: `dom.querySelector`, maybe the method name can be: `queryVnode`

This way can simplify the application design, by not passing data from one vnode to another, instead, manipulate every vnode's methods / props **in place** of vnode itself.

So the unit of data becomes **vnode**, each vnode can expose it's own methods / props, more OOP way.

Make mithril vnode less **Coupling** and more **Sealed**

### Steps to Reproduce:

```javascript
m( BigComponent ).queryVnode('ul li').forEach(vnode => dosomething )

// Or use more javascript way
m( BigComponent ).visit( vnode => testOf(vnode)  )  -> Array<vnode>
```

### Expected:

Get all `ul li` vnode, and user can do some thing with the vnode, like call some methods of each vnode

### Actual:

N/A. Several things maybe think:

1. This way was it break the `redraw everything` ideology?

2. Bigger idea, maybe there's a module called `traverse.js`, can get most vnode things, like `vnode.parent`, `vnode.siblings`, `vnode.mountPoint`(the root DOM this component mounted)

3. Maybe it should not be in core? should just be a helper program for mithril? Well, this depends on how this issue people will like it, or discuss it.

**Comment by lhorie** [comment]
I don't really understand the use case for this. Are you trying to do something like [mithril-query](https://github.com/StephanHoyer/mithril-query) (e.g. for testing purposes)?

**Comment by purefan** [comment]
My use case is to set autofocus on a child node, I tried to set it `oncreate` on the actual _input_ but that didnt work, perhaps Im missing an obvious "workaround"

**Comment by isiahmeadows** [comment]
@purefan Could you file that as a new issue, so it can be addressed separately? It's off-topic here.

**Comment by purefan** [comment]
:) Sure will, and sorry for reviving the dead
