### ISSUE TITLE
[rewrite] Routing request: Have onmatch and view in the same object

### ISSUE THREAD

**Issue by ciscoheat** [lhorie/mithril.js#1519]
Would it be possible to have `onmatch` and `view` in the same object? Right now I have to use `render` instead of view, which looks a bit odd. My use case is that I'm deriving some state based on the route parameters.

**Comment by lhorie** [comment]
You mean rename render to view? No. They have different semantics. `{onmatch, view}` is component with a custom method called onmatch. `{onmatch, render}` is a routeresolver. m.route takes a map of components or route resolvers. If route resolvers have a method called view, there's no way to tell them apart.

You can put a component in a route resolver, e.g.

```
{
  render: vnode => [
    m(Foo, vnode.attrs),
    // or
    m(Bar, {oninit: () => doStuff(vnode.attrs)}),
  ]
}
```

**Comment by ciscoheat** [comment]
Ok, thanks, I also found out in the new router docs about using `:key`, as a a way of doing approximately the same thing as I wanted.

However, since you can pass both components and route resolvers to the `routes` parameter in `m.route`, but those objects cannot simultaneously have a `view` and a `render` method, that's a typing issue. (Because what types are `{onmatch, render, view}`?)

So maybe the question is if they *should* be told apart, or at least if this limitation should be enforced by `m.route`, to avoid confusion?

**Comment by pygy** [comment]
In practice, the router code dispatches on the presence of `view`. The docs may need a clarification (a RouteResolver can't have a `view` field as it would make it a component).

**Comment by lhorie** [comment]
The rule of thumb is if it has a view method, it's a component.

**Comment by ciscoheat** [comment]
My mistake was to add `onmatch` to the Component object, expecting it to be added like any lifecycle event, since it apparently also fulfilled the criteria for being a RouteResolver.

Having read more of the excellent documentation, I understand now how it's supposed to work, but I have the feeling there could be others surprised by the `onmatch` method, because you can pass `Component|RouteResolver` in `m.route`. Wouldn't it be quite safe to assume that a Component with an `onmatch` method is a mistake that should be revealed?

**Comment by barneycarroll** [comment]
@ciscoheat or better yet, allow the method to co-exist with generic component lifecycle methods?

**Comment by pygy** [comment]
@barneycarroll That would make `onmatch` a class method, unlike other fields defined on the component that act as instance methods...

**Comment by ciscoheat** [comment]
From a type perspective there's an issue in stating that an object is only a Component, nothing else, when it has a `view` method. Because when we define any other type but a Component (approximation):

```haxe
RouteResolver = { 
    onmatch: Promise function(Object, String),
    render: Vnode function(Vnode),
    !view   (to prevent it being a Component)
}
```

I just made up the last line, but I think you'll see the problem. Which isn't a problem in Mithril since Leo made a definition (or at least a rule of thumb!), but it takes us out of type territory in a type-related area, which could justify a warning.
