### ISSUE TITLE
Ospec test example does not work

### ISSUE THREAD

**Issue by dontwork** [lhorie/mithril.js#1530]
### Description:

The first ospec test example here https://github.com/lhorie/mithril.js/blob/rewrite/docs/testing.md does not seem to work

### Steps to Reproduce:

```
try running that test locally. I have tried some other tests from the ospec.md file and they work
```

### Expected:

thought it would run a test

### Actual:

said 0 assertions completed

**Comment by dontwork** [comment]
It looks like the first `o` needs to be `o.spec`

**Comment by pygy** [comment]
I think `o('math'` should read `o.spec('math`.

**Comment by tivac** [comment]
Thanks!
