### ISSUE TITLE
Keys for components in route resolvers

### ISSUE THREAD

**Issue by dontwork** [lhorie/mithril.js#1531]
The example of using a layout component in the render method of a routeresolver is useful and a much clearer example of the same functionality than pre-1.0. But if you have a route like `/organisations/1` and you do this layout method then when you navigate between organisation pages... e.g `/organisations/1` to `/organisations/2` then the organisation component within layout e.g `m(layout, m(organisation))` will require a key. Is there a reccomendation for this? Typically across mithril applications I have used `:id` in routes but I wonder if a good idea would be to adopt using `:key` in routes so that the components within layout will get diffed properly. example:

```
    "/organisations/:key": {
        onmatch (args, path) {
            document.title = "Page title"
        },
        render (vnode) {
            return m(layout, m(organisation, vnode.attrs))
        }
    },
```

I havent tried this code but I take it that the organisation component would end up with a key of `:key` from the route.

I think the docs in the routeresolve example should mention this but I create this issue because I am not sure what the best solution is.

**Comment by lhorie** [comment]
This is covered earlier in the page, here: https://github.com/lhorie/mithril.js/blob/rewrite/docs/route.md#key-parameter
