### ISSUE TITLE
Typos in simple-application.md

### ISSUE THREAD

**Issue by germay** [lhorie/mithril.js#1540]
### Description:

Trying to setup the simple application I found some typos in simple-application.md:

### Actual

Now, let's modify the `UserList` view so that we can navigate from there to a `UserForm`:

```javascript
// src/views/UserForm.js
..
```

### Expected

Now, let's modify the `UserList` view so that we can navigate from there to a `UserForm`:

```javascript
// src/views/UserList.js
..
```

### Actual

Let's create a file `src/views/Layout.js`:

```javascript
var Layout = {
         ..
}
```

### Expected:

Let's create a file `src/views/Layout.js`:

```javascript
var m = require("mithril")
var Layout = {
          ..
}
module.exports = Layout
```

### Actual

The form itself still doesn't save when you press "Save". Let's make this form work:

```javascript
// src/views/UserForm.js
var m = require("mithril")
var User = require("./model/User")
..
```
### Expected

The form itself still doesn't save when you press "Save". Let's make this form work:

```javascript
// src/views/UserForm.js
var m = require("mithril")
var User = require("../model/User")
..
```

### Actual

Let's change the router in `index.js` to add our layout into the mix:

```javascript
// index.js
var m = require("mithril")

var UserList = require("./view/UserList")
var UserForm = require("./view/UserForm")

m.route(document.body, "/list", {
..
})
```

### Expected:

Let's change the router in `index.js` to add our layout into the mix:

```javascript
// index.js
var m = require("mithril")

var UserList = require("./view/UserList")
var UserForm = require("./view/UserForm")
var Layout = require("./view/Layout")

m.route(document.body, "/list", {
..
})
```

**Comment by lhorie** [comment]
Thanks for catching those! Fixed
