### ISSUE TITLE
[rewrite: docs] Wrong formatting of inline html code blocks

### ISSUE THREAD

**Issue by alexander-travov** [lhorie/mithril.js#1543]
Looks like [this line](https://github.com/lhorie/mithril.js/blob/rewrite/docs/generate.js#L27) from `docs/generate.js` combined with `marked` lead to wrong formatting in generated docs for inline html code blocks:

`<div></div>` -> generate.js -> `<div>&lt;/div>` -> marked -> `<code>&lt;div&gt;&amp;lt;/div&gt;</code>`

### Steps to Reproduce:

1. `npm run gendocs`
2. Open any html doc file, generated from `.md` with `<div></div>`-like block. (`css.html`, `installation.html`, `simple-application.html`, `jsx.html`).
3. See `&lt;` in inline html code blocks.

### Expected:

4. See `<` instead of `&lt;`.

**Comment by lhorie** [comment]
Fixed

**Comment by alexander-travov** [comment]
Although that fixed mentioned issues and more type signatures now render correctly, some new issues emerged. See:

1. `// <div>&lt;script&gt;alert('evil')</script&gt;</div>` comment in `trust.html` is no longer valid because it contains `<`.
2. Trusted vnode type renders as `{tag: "&lt;"}` in `vnodes.html`.
3. `npm version` command in `releasing.html` now contains `&lt;`.
4. `on<event>` in Events section of `hyperscript.html` now contains `&lt;`.
5. Type of `children` in `m.fragment` signature contains `&lt;`.

**Comment by alexander-travov** [comment]
@lhorie I ask for reopen.

**Comment by lhorie** [comment]
Yeah, good catch
