### ISSUE TITLE
mithril-rewrite: vnode.state question

### ISSUE THREAD

**Issue by pine3ree** [lhorie/mithril.js#1550]
This is not a bug reporting, just a question.

Hello @lhorie ,

would it be possible to have `vnode.state` bound to `this.state` inside the component lifecycle methods?
In my opinion having all state data under one component key `state` would lead to less polluted component objects as well.

thank you and kind regards

**Comment by lhorie** [comment]
Sorry, release is around the corner so I'm not making any more breaking changes at this point
