### ISSUE TITLE
[1.0] Make available m.request-like promise shortcuts

### ISSUE THREAD

**Issue by mindeavor** [lhorie/mithril.js#1557]
Pretend you have a fetch function that looks something like this:

```js
var cache = null
function getItems () {
  if (cache) return Promise.resolve(cache)

  return m.request('/items').then(function (items) {
    cache = items
    return cache
  })
}
```

The problem with this pattern is that it behaves differently whether your data is cached or not:

- On cache miss, a redraw is triggered after `m.request()` is complete
- On cache hit, no redraw is triggered.

Could we have some helpers to behave like an `m.request` promise? Maybe name them `m.request.resolve` and `m.request.reject`.

**Comment by barneycarroll** [comment]
Isn't it enough to use built in XHR abort where necessary and `notRequest().then(m.redraw)`?

**Comment by mindeavor** [comment]
If you mean `Promise.resolve(cache).then(m.redraw)`, that behaves differently because (if I'm not mistaken) m.request will redraw at the *end* of the promise chain.

**Comment by mindeavor** [comment]
Nevermind! I just realized `m.redraw` triggers a redraw asynchronously, so this is not an issue.

For the record, this does mean that `Promise.resolve(cache).then(m.redraw)` is indeed the solution.
