### ISSUE TITLE
[rewrite] m.request by default doesn't handle JSON arrays

### ISSUE THREAD

**Issue by kdar** [lhorie/mithril.js#1560]
### Description:

For m.request, when not using your own serialize function and when trying to pass a JSON array, m.request will not serialize the data. The reason being is because m.request attempts to get the keys of the data and using them to serialize:

```
var dataKeys = args.data && Object.keys(args.data)
if (useBody) args.data = args.serialize(args.data, dataKeys)
```

Obviously this doesn't work with a JSON array. This can be circumvented by providing your own serialize function, but this is surprising.

### Steps to Reproduce:

```
m.request({
    method: "PUT",
    url: "/messages",
    data: [{"some": "data"}]
})
```

### Expected:

For the data to be serialized.

### Actual:

It is serialized to [].

**Comment by lhorie** [comment]
fixed
