### ISSUE TITLE
Docs: warn about restrictive signatures in component methods 

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1562]
Supplement the style note about fat components with a warning about the vagaries of restrictive interfaces when using component methods — recommend free floating functions with explicit signatures and invocations as a way out

**Comment by davehayes** [comment]
As one possible source of this issue, I'd like to ask if there is any "valid" use case for adding custom methods to components? If so, an example may help steer people like me in the "best practice" direction. 

An example of "free floating functions with explicit signatures and invocations" would be great too.

**Comment by barneycarroll** [comment]
@davehayes I think a good explanation for the various problem cases and solutions to this is too long and subtle for inclusion as a continuous piece of documentation under an "avoid anti pattern X" heading. I saw @tivac linked you to a couple of the issue threads relating to that, which cover the bases. In the meantime I'm working on a [gist](https://gist.github.com/barneycarroll/72a2c2dd8f2da8c8e9b66e6345766ca2) (just a skeleton right now) to cover the subject with due focus, with an eye to getting it linked from the "avoid fat controllers" section.

**Comment by davehayes** [comment]
One example use case that I have found is a reusable drop down menu component. The reusable component will have to take some data telling it what menu items to display and what to execute when a menu item is selected. I'm presuming your recommendation would be to shoehorn this data into attributes. My question is where would the `activateMenu` code go?

**Comment by isiahmeadows** [comment]
Closing, since this issue has not been updated in over a month, and typically, issues inactive for that long do not usually produce any action. If you feel something in Mithril needs added or changed, please file a new issue.
