### ISSUE TITLE
Invalid default route crashes Chrome

### ISSUE THREAD

**Issue by jrwilliams** [lhorie/mithril.js#1579]
I accidentally introduced a typo in my default route:

```
m.route(root, '/home', { // Note case issue
    '/Home': Home,
    '/List': TodoList
  });
```

This causes Chrome (Version 55.0.2883.95) to lock up. Firefox behaves better, but CPU usage goes very high. A quick profile showed that `setTimeout` was being called constantly. 

I've made this gist to illustrate the issue: https://gist.github.com/jrwilliams/3a5decaeea440dbf7ae4f3654845ae8a  
Run that using `http-server` or however you like, and you should witness the lock up.

**Comment by lhorie** [comment]
Fixed in origin/next
