### ISSUE TITLE
Change-log page documentation link is broken

### ISSUE THREAD

**Issue by bdpiparva** [lhorie/mithril.js#1585]
Broken link on change-log page

### Summary

1. Go to [change-log](http://mithril.js.org/change-log.html)
2. Scroll to `m.prop` **removed**
3. Click on [the documentation](http://mithril.js.org/streams.html) on second line

![screen shot 2017-02-02 at 11 17 06 am](https://cloud.githubusercontent.com/assets/7871209/22538567/570f4d14-e939-11e6-9549-4a46a3231d10.png)

Error Page:

![screen shot 2017-02-02 at 11 19 01 am](https://cloud.githubusercontent.com/assets/7871209/22538585/77966018-e939-11e6-8411-69e651d99e45.png)

**Comment by tivac** [comment]
Fixed in #1569, just not published yet. Thanks!

**Comment by bdpiparva** [comment]
Thanks
