### ISSUE TITLE
Documentation: vnode.state.data or vnode.attr.data ?

### ISSUE THREAD

**Issue by waldhol** [lhorie/mithril.js#1590]
In the 1.0 documentation of Key Concepts / Components in chapter "State" the example reads:
```javascript
var ComponentWithInitialState = {
    data: "Initial content",
    view: function(vnode) {
        return m("div", vnode.state.data)
    }
}
```
Shouldn't this be `vnode.attr.data` at this point?
The copy from `attr` to `state` is shown in the next example only.

**Comment by sebastiansandqvist** [comment]
It's correct as it is in the docs.

Attrs get passed in when the component is used. For instance, this component might be used in another view like this:

```
m(ComponentWithInitialState, { foo: 'bar' })
```

In that case, it would be correct for the component to be implemented like you're suggesting:

```
var Component = {
    view: function(vnode) {
        return m("div", vnode.attrs.foo)
    }
}
```

But that's not what the example is demonstrating.

**Comment by waldhol** [comment]
Ok, now I get it.
Both intialize the given value.
`state.data` is set to `{data: value}` from inside the component.
`attr.data` is set to `{data: value}` from outside of the component.

Thanks.
