### ISSUE TITLE
Input looses internal focus state on redraw

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#1593]
[In this bin](https://jsbin.com/botucud/edit?js,output), a regular event triggers redraws. The caret / selection within the input will reset on each such redraw. I haven't been able to reproduce this bug consistently.

Inputs can reliably be safeguarded [by specifying `onbeforeupdate : ( now, then ) => now.attrs.value != then.attrs.value`](https://jsbin.com/nacodeq/edit?js,output), but this comes at the cost of not rebinding other attributes which may have changed, such as input handlers.

**Comment by daniel-j** [comment]
I had this issue too. I solved this by setting the value to the input as string, just append an empty string or something and it will remember cursor position/selection.

**Comment by barneycarroll** [comment]
Aha! How strange. Surely Mithril should compare the raw attributes?

**Comment by pygy** [comment]
Firefox appears to be immune though, but it happens in both Chrome and Safari 10

**Comment by magnumjs** [comment]
When input values are dynamically updated the selection range end must be set to what it was before
