### ISSUE TITLE
Component class lifecycle

### ISSUE THREAD

**Issue by andraaspar** [lhorie/mithril.js#1608]
Hi,

I have just noticed that in Mithril 1.0.0, component classes get removed and recreated rather than updated. Here's a fiddle: https://jsfiddle.net/andraaspar/ztkd157o/

Expected output:
```
VarComp oncreate
ClassComp oncreate
VarComp onupdate
ClassComp onupdate
```

Actual output:
```
VarComp oncreate
ClassComp oncreate
ClassComp onremove
VarComp onupdate
ClassComp oncreate
```

**Comment by andraaspar** [comment]
Please note that this used to work in 0.2.5.

**Comment by pygy** [comment]
Mithril v1 diffs vnode whose `vnode.tag` field is identical `===` and removes then inserts otherwise. Here you are passing new instances of your class on every redraw, which causes the behaviour you observe

#1339 had a functional implementation of classes as components, but it got shelved pending v1 release...

**Comment by isiahmeadows** [comment]
@andraaspar 

I'd have to say that's working as intended, and is a limitation of the diff algorithm. The fact it even works in 0.2 is a bug. Your `new ClassComp()` returns a new, unique instance each time, so it's constantly being fed a different component as far as Mithril can see, and it should be functionally no different than this:

```js
var App = {
  view: function() {
    return [
      m('b', 'Open the console!'),
      m(VarComp),
      m({
        view() { return m('div', 'Hi, I’m ClassComp') }.
        oncreate() { console.log('ClassComp oncreate') },
        onupdate() { console.log('ClassComp onupdate') }
        onremove() { console.log('ClassComp onremove') }
      }),
      m('button', {onclick: function() {}}, 'Let’s update!')
    ]
  }
}
```

**Comment by isiahmeadows** [comment]
@pygy 

> #1339 had a functional implementation of classes as components, but it got shelved pending v1 release...

That's only really tangentially related. @andraaspar is referring to `m(new ClassComp())`, not `m(ClassComp)`.

**Comment by andraaspar** [comment]
Thanks for your feedback. The reason I ran into this is that I use Mithril with TypeScript, and use component classes everywhere. This difference in handling classes could mean that porting my existing code base to 1.0.0 will be very difficult, if OOP inheritance is involved. So I'd vote +1 for #1339 (or its successor).

**Comment by isiahmeadows** [comment]
Welcome. And it'll likely have a successor.

**Comment by pygy** [comment]
@isiahmeadows the exact semantics may differ, but the root concern is the same, some people want Classes as components.

**Comment by andraaspar** [comment]
Consider my 0.2 code vs my 1.0 code:

```TypeScript
export class HelpContent implements Mithril.Component<any> {
	
	private visibleIndex = 0
	
	constructor(
		private imageUrls: string[]
	) { }
	
	isLast(): boolean {
		return this.visibleIndex + 1 >= this.imageUrls.length
	}
	
	next(e: Event): void {
		if (this.isLast()) {
			...
		} else {
			this.visibleIndex++
		}
	}
	
	view(): Mithril.VirtualElement {
		return (
			m('div',
				...
			)
		)
	}
}
```

Versus:

```TypeScript
interface State {
	visibleIndex: number
}

interface Attrs {
	imageUrls: string[]
}

type Vnode = Mithril.Vnode<State, Attrs>

export const HelpContent: Mithril.Component<State, Attrs> = {
	
	visibleIndex: 0,
	
	view() {
		return (
			m('div',
				...
			)
		)
	}
}

function isLast(vnode: Vnode) {
	return vnode.state.visibleIndex + 1 >= vnode.attrs.imageUrls.length
}

function next(vnode: Vnode, e: Event) {
	if (isLast(vnode)) {
		...
	} else {
		vnode.state.visibleIndex++
	}
}
```

It is not trivial to refactor a class into this. And that vnode passing looks like Python. I had to extract and name State and Attrs only because of that. It's a pain.

Having to write `vnode.state...` or `vnode.attrs...` in place of `this...` is another one of those inconveniences.

(BTW, the type defs are available in a PR to DefinitelyTyped here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14513)

**Comment by andraaspar** [comment]
And to say the positive as well: Mithril is still the best from a type safety perspective, compared to React and Angular. It is the only one that provides type safety in templates and model manipulation as well.

**Comment by andraaspar** [comment]
You know, that `visibleIndex` working across updates, with a new class instantiated each time, is awesome. It is unexpected, right? And it _was_ working with 0.2. Pure gold.

**Comment by andraaspar** [comment]
Ah, never mind. It was a mounted component, that's why.

**Comment by andraaspar** [comment]
> Having to write vnode.state... or vnode.attrs... in place of this... is another one of those inconveniences.

I take that back. It's great. And I'm shutting up. Now.

**Comment by isiahmeadows** [comment]
@pygy I was referring to the difference between type and instance, not so much classes vs objects for components themselves.

@andraaspar 

> Having to write `vnode.state...` or `vnode.attrs...` in place of `this...` is another one of those inconveniences.

Few notes:

1. `vnode.state` is equivalent to `this`, for a reason.
2. `vnode.state` inherits prototypically from the component.
3. Don't be afraid to leverage destructuring to your advantage. `view({attrs, state}) { ... }` will make your life a lot easier.
