### ISSUE TITLE
Why doesn't the onclick update vnode when you component from a function?

### ISSUE THREAD

**Issue by jamesguan** [lhorie/mithril.js#1621]
My main issue below is that the onclick function for the component defined in the same scope as the m.mount works.

However, when I try to return a component from a function and use that onclick defined within renderTestMVC function, there's no update whatsoever to the count defined in renderTestMVC and I can't figure out why. vnodes are defined in both and they seem to be separate vnodes as one updates fine, while the other is standing still.

Is it something I am doing wrong?

```javascript
function renderPaneStuff( ) {

  var Counter = {
    count: 0,
    view: function(vnode){
      console.log(vnode);
      console.log(vnode.state.count);
      return m("div",
        m("p", "Count: " + vnode.state.count ),
      m("button", {
        onclick: function() {
          vnode.state.count++
        }
      }, "Increase count")
    )
    }
  }
  
  m.mount(root, {
    view: function(vnode) {
      return [
        m(Counter),
        m(renderTestMVC()) // Clicking the button for this does not update
      ]
    }
  });

}

function renderTestMVC(){
  var Counter = {
    count: 0,
    view: function(vnode){
      console.log(vnode);
      console.log(vnode.state.count);
      return m("div",
        m("p", "Count: " + vnode.state.count ), // Is this not the same vnode.state.count???
      m("button", {
        onclick: function() {
          vnode.state.count++ // For some reason does not update vnode.state.count
        }
      }, "Increase count")
    )
    }
  }
  return Counter;
}
```

**Comment by tivac** [comment]
Your function returns a new component on every render that way, so clicking the button increments the counter on an old component reference that is no longer used.

http://mithril.js.org/components.html#avoid-creating-component-definitions-inside-views
