### ISSUE TITLE
Publish stream on npm

### ISSUE THREAD

**Issue by oligot** [lhorie/mithril.js#1629]
Hi,

We are currently using [flyd](https://github.com/paldepind/flyd) as our stream implementation (following @JAForbes great article [The power of m.prop](https://james-forbes.com/?/posts/power-of-m-prop)).
We'd like to migrate to Mithril [stream implementation](http://mithril.js.org/stream.html) in our projects but we are still using Mithril 0.2.
Do you think it would be possible to publish stream on npm (as done with ospec) so that we could use it with Mithril 0.2 ?

Regards,

Olivier

**Comment by isiahmeadows** [comment]
@oligot Try `require("mithril/stream")`.

**Comment by schtauffen** [comment]
@isiahmeadows afaik having different versions of a library in your `package.json` is impossible.

One can publish a wrapping npm module around mithril 1.0 but an official package would be better.

**Comment by isiahmeadows** [comment]
@schtauffen I see now.

**Comment by oligot** [comment]
@isiahmeadows Thanks for the detailed workaround !
I'll probably wait for the PR to be merged though.
I'll keep the workaround for the next time I'll try to use 2 versions of the same library.
