### ISSUE TITLE
Reusing DOM nodes without Affecting other DOM nodes

### ISSUE THREAD

**Issue by dalisoft** [lhorie/mithril.js#1636]
QUESTION 1:
Hi and thanks for best app.
I am made app (alternative to React/Mithril). I tested and seen some nice result.

```
LOG: NODES set to: 1000.
Tez.html:80 Tez[jQuery-way]: 6395.884ms
Tez.html:86 Native DOM: 3.000ms
Tez.html:94 Native DOM (+Fragment): 4.000ms
Tez.html:103 Default Tez[domClass]: append: 455.000ms
Tez.html:115 Default Tez[domClass]: append without Rendering for each call: 49.000ms
Tez.html:125 Tez[domClass]: append cached text and set/render once: 32.000ms
Tez.html:134 MithrilJS: 22.000ms
```

So i decided using MithrilJS and faced one big issue when re-using element.

```javascript
const p =  m("p", "My old content");
//HOW-TO change old content to NEW
```

For my app its easy as
```javascript
const p = new Tez.domClass("p", {content:"My old content"});

//p.setContent("YEAH, NEW");
```

How to-do that work in MithrilJS?
This is amazing feature.

-------------------------------------------------------

QUESTION 2:

My app
```javascript
const p = new Tez.domClass("body", {content:"<div><p></p></div>"});

p.setContent("<div><p><h1>Hey</h1></p></div>");

// Adding only <h1>Hey</h1> and my app works for this trick
```
MithrilJS
```javascript
const p = m.trust("body", "<div><p></p></div>");

m.render(root, p);

p = m.trust("<div><p><h1>Hey</h1></p></div>"); // THERE have method for this?

m.render(root, p);

// Adding only <h1>Hey</h1>, but Mithril.js changes all children of `root`. This is good, but when 10k nodes on site, very bad
```

Is this possible? And how? Thanks

EDIT:

QUESTION 3 [ANSWERED]:
`m.render(parent, content)` gives text, not a html parsing
Works: `m.trust` insteadof `m.render`

EDIT 2:

Please dont think me stupid for these question, just i want to use Mithril.js and there some issue, if this issue solved i starting using app.
React works, but slower as i tested, lowest result gives Mitrhil.js from:
* React
* my app
* Mithril
* VueJS

**Comment by tivac** [comment]
Mithril will automatically re-use DOM nodes where possible.

https://jsbin.com/magice/1/edit?js,output

Mithril doesn't natively support rendering to a string, you can use [`mithril-node-render`](https://github.com/StephanHoyer/mithril-node-render) for that though.

**Comment by isiahmeadows** [comment]
Closing, since this issue has not been updated in over a month, and typically, issues inactive for that long do not usually produce any action. If you feel something in Mithril needs added or changed, please file a new issue.
