### ISSUE TITLE
Pass Attributes to vnode.children

### ISSUE THREAD

**Issue by tonyalaribe** [lhorie/mithril.js#1637]
I have a wrapper component for authentication which should passdown the routing details down to its children, but it doesnt work. 

`
return m("div",vnode.attrs,vnode.children);
`

the child component still doesn't have access to the URL params. Am I missing something? how do you pass all attributes down to children?

**Comment by barneycarroll** [comment]
Hi @tonyalaribe, route parameters should be passed down as `attrs` the way you expect. Here's a simple example showing that a parameter labelled `routeNumber` can get passed down and read by a component (the same would apply to URL query parameters): https://jsbin.com/ribaref/edit?js,output

I'm confused by your example, because a route's parameters would not be expected to match up to the appropriate properties of a DOM element directly — and a route certainly wouldn't produce children. Can you give more detail about your problem?

**Comment by tonyalaribe** [comment]
Hello @barneycarroll, sorry i wasnt clear. Here is a trimmed down version of the code.


The route
`
  "/new_session":{
        view: function(vnode) {
            return m(Auth,vnode.attrs,m(NewVotingSessionPage))
        },
      },
`

The Auth component
`
 var Auth = {
  oncreate:function(){
    console.log("in auth")
    let auth = localStorage.getItem("auth")
    console.log(auth)
  },
  view:function(vnode){
    console.info(vnode.attrs.id)
    //return m("div",vnode.attrs,m.fragment(vnode.attrs,[vnode.children]));
    return m("div",vnode.attrs,vnode.children);
  }
}
`

**Comment by tivac** [comment]
That route wouldn't have any route params in `vnode.attrs`, it'd just be an empty object.

```js
m.route(document.body, "/user/foo", {
    "/user/:id" : {
        view : (vnode) => m("div", vnode.attrs.id)
    }
});
```

would render `<div>foo</div>`.

`vnode.attrs` when using the router only contains any routing parameters (`/:thing`) or variadic routes (`/:thing...`) in the matched route.

Here's the [docs section on routing parameters](http://mithril.js.org/route.html#routing-parameters) if it helps.

**Comment by tonyalaribe** [comment]
@tivac that was a mistake on my part. I made a workaround for the initial route. But rest assured the original route had the param section. And i'm able to access the parameter from the Auth component, but not from the underlying component wrapped by the auth component.

**Comment by tivac** [comment]
Ok, so you're talking about the `NewVotingSessionPage` component?

```js
m(Auth, vnode.attrs ,m(NewVotingSessionPage, vnode.attrs))
```

seems like it should do what you want then.

**Comment by tonyalaribe** [comment]
Thanks @tivac. That was my issue. I wasnt passing the vnode.attrs into the Page component
