### ISSUE TITLE
For components, vnode.attrs.oninit and vnode.attrs.oncreate don't recieve the proper context/vnode.state

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#1638]
These methods are [called / scheduled](https://github.com/lhorie/mithril.js/blob/3f3af74dde47a2c538944ac6b8c29a4056967a3c/render/render.js#L23) with `vnode.state` bound as `this` before the correct `vnode.state` is initialized in `createComponent`.

The fix isn't hard (the `initLifecycle()` call must duplicated, placed once one line below its current place and once in `createComponent`), but the tests need more work.

There was a reason for the shallow copy business, after all...

**Comment by isiahmeadows** [comment]
IMHO those should be called *after* the component itself initializes. Otherwise, how are you supposed to access the component's state? It doesn't make sense to me to do otherwise.
