### ISSUE TITLE
An issue with the tutorial in the docs

### ISSUE THREAD

**Issue by ofridagan** [lhorie/mithril.js#1644]
I'm new to mithril, so I maybe missing something...

After implementing the 'save' method from the User model in http://mithril.js.org/simple-application.html the result of clicking the Save button is a page refresh.
I tried ```return false``` after the call to ```m.request``` and that fixed the problem, so I assume the problem relates to preventing the browser's default event handling (?).
But now the function doesn't return the promise, which I guess is not good.

What is the correct way of writing that 'save' method.

btw, I have ```m.route.prefix("")``` not sure if that's important..

**Comment by lhorie** [comment]
I think the button should be type=button, not type-submit

**Comment by barneycarroll** [comment]
Better to bind a preventative handler to the form's submit property IMO, since this is never desired behaviour in this app.

**Comment by ofridagan** [comment]
@lhorie Thanks! that worked.

@barneycarroll I also like to bind to the form's submit, but then I can't return a promise (like the tutorial shows for 'load').
Is that not important in some why for mithril?

**Comment by barneycarroll** [comment]
It should be perfectly possible to prevent form onsubmit and use promises in your model: the return value of event handlers is unconnected to the model.

**Comment by ofridagan** [comment]
Thanks.
Created a PR: https://github.com/lhorie/mithril.js/pull/1646

**Comment by ofridagan** [comment]
ah turns out the docs are already fixed, but not published to the site.
