### ISSUE TITLE
CSS3 Animation with Mithril

### ISSUE THREAD

**Issue by volnei** [lhorie/mithril.js#1647]
Hi guys! 

I'm loving to work with Mithril 1.0 (aka rewrite), it is fast and awesome! But I'm a bit confused with using CSS3 animation with it. Can anyone show a pratical example? 

Thanks!

**Comment by pygy** [comment]
http://mithril.js.org/animation.html covers the basics. Is there something specific you want to discuss?

**Comment by volnei** [comment]
@pygy sorry for inconvenience... I just fall to look at the docs, cause I did not know they had already released the 1.0 documentation.

Thanks

**Comment by pygy** [comment]
No problem :-) have fun with the framework!

**Comment by volnei** [comment]
There any way to start animation by changing the class instead of adding or removing it?

Thanks :)

**Comment by pygy** [comment]
In `onbeforeremove`, you manipulate the real DOM directly... [classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) (IE 10+) allows to add and remove classes.

For animations of an element that is just updated, in the `view` you can do 

`m('div', {className: condition ? 'foo' : 'bar'})`

 or use [classnames](https://www.npmjs.com/package/classnames) for more advanced class manipulations.

**Comment by isiahmeadows** [comment]
Closing, since this issue has not been updated in over a month. If you feel something in Mithril needs added or changed, please file a new issue.
