### ISSUE TITLE
Uncaught ReferenceError: setImmediate is not defined

### ISSUE THREAD

**Issue by ludbek** [lhorie/mithril.js#1650]
I am getting `Uncaught ReferenceError: setImmediate is not defined` exception after my code is uglified using `UglifyJS2` with `mangle-props true`.

~~Looking at Mithril code it seems `setImmediate` is a global variable. May be we could import it?~~

Update:
This [doc](https://developer.mozilla.org/en/docs/Web/API/Window/setImmediate) says its a non-standard api.

**Comment by pygy** [comment]
That is strange because all `setImmediate` [references](https://github.com/lhorie/mithril.js/search?utf8=%E2%9C%93&q=setImmediate) are guarded by presence checks as 

```JS
	var callAsync = typeof setImmediate === "function" ? setImmediate : setTimeout
```

Could you post the minified build in a gist?

**Comment by ludbek** [comment]
The unminified code is given below:

```javascript
// setimmediate attaches itself to the global object
	__webpack_require__(10);
	exports.setImmediate = setImmediate;
	exports.clearImmediate = clearImmediate;
```

Now I dont think Mithril is causing it.

**Comment by pygy** [comment]
It looks like this doesn't come from Mithril, there are no `clearImmediate` in the code base, and `setImmediate` is only exported in a test helper as 

```JS
//callAsync.js
module.exports = typeof setImmediate === "function" ? setImmediate : setTimeout
```

Maybe Webpack injects it because it finds `setImmediate` references in the code?
