### ISSUE TITLE
question about gendocs

### ISSUE THREAD

**Issue by ericlenio** [lhorie/mithril.js#1658]
Small question: the gendocs script (npm run-script gendocs) has a hardcoded path to put stuff in ../mithril, yet my checkout directory is mithril.js, so it creates the documentation outside of my mithril checkout dir which I did not expect. Perhaps this is intentional?

**Comment by barneycarroll** [comment]
@ericlenio there's a separate [`/mithril`](https://github.com/lhorie/mithril) repo for the Mithril documentation: `gendocs` presumes that you have both repos installed side-by-side, and code from one populates the other. I agree it's very dodgy to make assumptions about file structure above the root of a package, and also confusing to have the responsibility and logic for documentation spread across multiple codebases.

There's a branch of work that @tivac has started on to try and consolidate the various Mithril repositories & packages into one codebase – hopefully we can find a way of making the sub-repo work with the publication setup.

**Comment by ericlenio** [comment]
Ah, I see. Thanks for the clarification...closing.
