### ISSUE TITLE
Hyperscript renders true but not false.

### ISSUE THREAD

**Issue by ludbek** [lhorie/mithril.js#1666]

**Comment by barneycarroll** [comment]
This is a feature. It allows declarative conditional vnodes:

```javascript 
m('header',
  title && m('h1', title)
)
```

The code above will render a heading when the title is truthy. It will render nothing when title is false, undefined or null.

**Comment by ludbek** [comment]
Yeah definitely a feature, `false + ""` will work for me. Thanx @barneycarroll

**Comment by barneycarroll** [comment]
@ludbek if you wanted to be more explicit, you could use `boolean.toString()`…

**Comment by ludbek** [comment]
Yeah that would work too. I read somewhere that pattern like `<atype> + ""` is faster than `<atype>.toString()`.

**Comment by barneycarroll** [comment]
I can't see how that would be the case - `<atype> + ""` runs conditional logic under the hood before deciding it needs to invoke `<atype>.toString()` anyway:

 ```javascript
({toString:() => 'WTF'}) + '' // === 'WTF'
```

**Comment by ludbek** [comment]
To quote from this [article](https://www.sitepoint.com/google-closure-how-not-to-write-javascript/).

> This code converts arguments[i] to a string object using the String conversion function. This is possibly the slowest way to perform such a conversion, although it would be the most obvious to many developers coming from other languages.

> Much quicker is to add an empty string ("") to the value you wish to convert:

**Comment by barneycarroll** [comment]
Execute the code I wrote above: performing addition of a string to a non-string will actually invoke `toString` under the hood. I searched for the quote you cited and ironically found it quoted again [in the comments](https://www.sitepoint.com/google-closure-how-not-to-write-javascript/#comment-1146884940):

> I compared the time it took to run 100,000 of each of String(fn) and fn + "", and found that the results were more ambiguous and less definitive than your assertion. In fact, fn + "" was 6.6% faster on Firefox 3.5, but 15.8% slower on a recent Chromium build. In any case, the difference was, even over 100,000 runs, a few milliseconds, so it hardly seems like this particular case would be an area to focus on for optimization.
>
> I wonder how many of your other strong claims would stand up to similar testing.
> 
> My test code and results: http://gist.github.com/232944

Many of the other comments are similarly dismissive / suspicious of these claims. In any case, the article is 7 years old – I think it's safe to say none of these measurements are reflective of anything any more.

**Comment by isiahmeadows** [comment]
FWIW, engines already lower the check into assembly. It's trivial for them to perform the code gen, and in practice, they avoid calling `toString` when the native instance method is unmodified (the common case), and if it's loop-invariant, they'll elide the action entirely.

Conversely, I don't know of any engine that doesn't delegate to a normal function call for `String(value)`, even though they *should* be able to do similar optimizations.

Although, I'll point out that this barely matters in practice, and won't even make a difference in your `view`, unless that particular function is being called literally several hundred times per animation frame (in which object allocations will mask the difference anyways).

**Comment by barneycarroll** [comment]
Thanks for the detail @isiahmeadows — your insight into under-the-hood runtime behaviour is invaluable for putting this kind of stuff to bed.

**Comment by ludbek** [comment]
@isiahmeadows Thanx for the insight :)
