### ISSUE TITLE
Bug & possible size improvement

### ISSUE THREAD

**Issue by userpixel** [lhorie/mithril.js#1667]
[hyperscript.js#L51](https://github.com/lhorie/mithril.js/blob/next/render/hyperscript.js#L51):

```javascript
if (arguments[1] == null || typeof arguments[1] === "object" && arguments[1].tag === undefined && !Array.isArray(arguments[1])) {
```

So if `arguments[1]` is `null` then the part after `&&` will be executed but `arguments[1].tag` will throw an TypeError exception.
I suspect it was meant to be `arguments[1] !== null` but if this is correct we can totally remove `arguments[1] == null` because `typeof arguments[1] === "object"` will be true weather it is null or an actual object.

**Comment by pygy** [comment]
Because of operator precedence rules, `a || b && c` really means `a || (b && c)`.

`typeof(null)` is `object` in some circumstances (is it sloppy mode or old IE versions? I don't remember exactly). Maybe we don't need this check anymore...

**Comment by isiahmeadows** [comment]
`typeof null === "object"` is required by spec.

**Comment by pygy** [comment]
Another bug crystallized into spec for Web compat reasons, I suppose :-/

I didn't know it was universal... It could have been addressed with strict mode or modules (things that allow clean  breaks from the past).

**Comment by isiahmeadows** [comment]
@pygy Sadly, [it is](https://tc39.github.io/ecma262/#table-35), and [here's a little bit of history for you](http://www.2ality.com/2013/10/typeof-null.html) on why `typeof null === "object"`

**Comment by isiahmeadows** [comment]
@userpixel Here's some equivalent code, with parentheses to show precedence:

```js
// Original, with `arguments[1]` factored out for readability
var arg = arguments[1]
if (arg == null || typeof arg === "object" && arg.tag === undefined && !Array.isArray(arg)) {
  // ...
}

// Same, with explicit precedence
var arg = arguments[1]
if (
  arg == null || (
    typeof arg === "object" &&
    (arg.tag === undefined && !Array.isArray(arg))
  )
) {
  // ...
}
```

**Comment by barneycarroll** [comment]
Can we produce an actionable bug report for this? I felt I was on the ball earlier but having forgotten & reading the thread back it looks like a series of disconnected academic observations…

**Comment by userpixel** [comment]
Considering the operator precedence the current behavior is not a bug.

**Comment by isiahmeadows** [comment]
If you can produce one @barneycarroll. So far, this appears to involve
generally correct behavior (although the tag check could admit nulls to
recover a few bits). Apart from that one nit, I don't see anything
actionable here.
