### ISSUE TITLE
Latest release is v0.2.3 latest tag is v1.0.1

### ISSUE THREAD

**Issue by winksaville** [lhorie/mithril.js#1676]
Is there a reason for not marking the v1.0.x tags as releases?

**Comment by pygy** [comment]
I suppose you mean GH [releases](https://github.com/lhorie/mithril.js/releases)...

**Comment by winksaville** [comment]
@pygy, yes

**Comment by isiahmeadows** [comment]
Consider our laziness as the driving reason - we already have npm, why duplicate the work?

**Comment by FibreFoX** [comment]
@isiahmeadows I came recently to mithril (and it really seems to be nice), but I don't use NPM for everything, especially when I don't require it. As mithril works without NPM, and does not require it, and for pre-1.0 version github-releases were provided, I personally would see this as a bad sign, makes it feel like mithril isn't being updated. "Oh, a new tool, lets check when the last commit have been made ... nice, just yesterday. Now lets check how often they are releasing ... oh, thats a bummer, no release, lets check a different tool", and there you go mister potential mithril-user.

**Comment by isiahmeadows** [comment]
In general, our community has very heavily relied on package management. And for what it's worth, [even Angular doesn't document their releases via GitHub](https://github.com/angular/angular/releases) - they just use Git tags like most others.

As I don't see anything actionable with this (we already use Git tags, and we advertise updates elsewhere), I'm going to close this.

**Comment by winksaville** [comment]
What about automatically creating a release tag when you publish to npm? Apparently it's possible using the [GitHub API](https://developer.github.com/v3/repos/releases/#create-a-release) if you'd like I can try to make a PR.

**Comment by isiahmeadows** [comment]
@winksaville You're probably misinterpreting what you're seeing. All those are tags, not releases. To see what I mean, compare [this tag](https://github.com/angular/angular/releases/tag/2.4.9) with [this release](https://github.com/atom/atom/releases/tag/v1.14.4).

**Comment by pygy** [comment]
I don't know what I'm doing with `j2c`, but GH marks [every `vX.Y.Z` tag as a release](https://github.com/j2css/j2c/releases) automatically... There's no extra info though.

I have `"prepublish": "(in-publish && git push --follow-tags) || not-in-publish",` in my `package.json` (where [in-publish](https://github.com/iarna/in-publish) asserts that we really did `npm publish`, not `npm install`.

Pinging both @tivac (for his automation know-how) and @lhorie (who does the releases): would you mind having it added?

**Comment by pygy** [comment]
@isiahmeadows We don't even have Angular-like stub releases in Mithril... It is better than nothing.

**Comment by isiahmeadows** [comment]
@pygy 

> Oh, now I see... We have the stubs, hidden unless you click the "Show N newer tags" button, because we have actual releases.

:+1:
