### ISSUE TITLE
@types/mithril out of date

### ISSUE THREAD

**Issue by jacobbridges** [lhorie/mithril.js#1677]
Hello all!

So it would seem the Mithril types for TypeScript (found [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/ae4fe7b6dec1fbbee9a2b454e7cc389b3bd2fd35/mithril), installable by running `npm install @types/mithril`) are out of date. I presume the types are for v0.2. 

I wouldn't mind helping someone make a pull request to update the package to v1, but I think it would require someone with more knowledge of the project.

**Comment by pygy** [comment]
[Up-to-date types](https://github.com/lhorie/mithril.js/blob/next/mithril.d.ts) were added after v1.0.1, they'll be part of the next release.

**Comment by jacobbridges** [comment]
You are awesome. I can't believe I didn't see that before!! Thanks so much @pygy!

**Comment by pygy** [comment]
Kudos should go to @spacejack who wrote the typings ;-)
