### ISSUE TITLE
m.request ignores specified method when using json instead of FormData

### ISSUE THREAD

**Issue by dabaer** [lhorie/mithril.js#1678]
For some reason when using an object in the data attribute of m.request, it overrides the method used to OPTIONS, instead of POST as i wanted.

```
m.request({
    method: "POST",
    url: "/",
    data: {field: "value"}
});
```

If i specify a form with FormData it works as expected.

**Comment by lhorie** [comment]
I just tried and POST w/ data seems to work. If you're getting an OPTIONS request, it sounds like it's a pre-flight request. The server needs to send a `Access-Control-Allow-Methods: POST` header or similar to prevent further pre-flight options requests

**Comment by codeliter** [comment]
Honestly this is a bug
 I just made a request 

`m.request({
            method: 'POST',
            url: endpoint,
            data: {}
        }).then(function(res) {
            if (res.status == "ok") {
                users.list = res.data;
                users.total = res.data.length;
            }
        });`

and it sent the request using the OPTIONS method

**Comment by pygy** [comment]
@codeliter is it a cross-domain request? If yes, then the browser sends an OPTIONS request first, no matter what you asked for. When that request succeeds, your payload is sent.

It is not something that Mithril controls, that's how XHR (the low level API behind `m.request` and other AJAX libs) and Fetch work.

**Comment by codeliter** [comment]
@pygy okay I understand thanks..I went with axios for the cross domain request
