### ISSUE TITLE
hyperscript delegated event handling question

### ISSUE THREAD

**Issue by ajaishankar** [lhorie/mithril.js#1683]
Just a question on hyperscript event handling - did not find anything in the documentation so asking as an issue.

When you register a handler like this, does the listener get added directly to the dom element

 `m("button", {onclick: function() {count++}}, count + " clicks"),`

Or does it end up as a "delegated event" similar to `jQuery.on` where there is a single listener for all descendent elements.

```
$( "#dataTable tbody" ).on( "click", "tr", function() {
});
```
Curious as to how many handlers get added when say we have a edit button on each row of a table with 1000 records.

**Comment by isiahmeadows** [comment]
It's added directly to the element via `addEventListener`. So if you had a table of 1k records, each one with that button, you'd have 1k listeners (in which case I'd advise adding it to a parent element instead).

**Comment by ajaishankar** [comment]
Thanks - I'd still be able to get the row that was clicked right?

Knockout has the `dataFor(element)` for getting the record that was clicked on.(http://knockoutjs.com/documentation/unobtrusive-event-handling.html)

Is there anything similar in Mithril? Or a recommended way to do this?

**Comment by pygy** [comment]
@ajaishankar this may help: http://lhorie.github.io/mithril-blog/asymmetrical-data-bindings.html

**Comment by ajaishankar** [comment]
Thanks @pygy! Just what I was looking for, excited to try out Mithril for some projects...

**Comment by tivac** [comment]
I wrote [delegated](https://www.npmjs.com/package/delegated) to handle event delegation because doing it manually was no fun.

**Comment by pygy** [comment]
@tivac I had completely forgotten about that lib... thanks for the reminder :-)
