### ISSUE TITLE
Register mitrhil.js as bower package

### ISSUE THREAD

**Issue by simov** [lhorie/mithril.js#1685]
Currently `mithril` is published on bower that is the other repo, [issue](https://github.com/lhorie/mithril/issues/59) and the latest published tag there is 1.0.0

I guess this repo `mithril.js` should be published as well, because it have the latest 1.0.1 tag.

**Comment by barneycarroll** [comment]
Oh, what @tivac meant is that the `mithril` Github repository is just for documentation, this (`mithril.js`) is the right Github repo to file issues for the 'mithril' codebase :)

There is already an issue about Bower for Mithril v1: #1649 — please read and comment as you see fit!

**Comment by simov** [comment]
Interesting, thanks @barneycarroll, I'm closing this one.
