### ISSUE TITLE
How to define components common to every route?

### ISSUE THREAD

**Issue by caleb531** [lhorie/mithril.js#1692]
Hi,

I'm using Mithril v1 to develop a moderately-sized app, and I'm using routing to define various "pages" of the app. I have some components which are common to every route (*e.g.* app header, sidebar, footer). I'd prefer to avoid duplicating references to these "static" components within every one of my route components.

Ideally, I'd love to do something like this:

```js
var AppComponent = {
  view: function (vnode) {
    return m('div#app', [
      m(HeaderComponent),
      m(SidebarComponent),
      m.route(vnode, '/home', {
        '/sign-in': SignInComponent,
        '/register': RegisterComponent
      }),
      m(FooterComponent)
    ]);
  }
};
```

Is there a recommended approach for accomplishing this kind of setup so as to avoid duplicating components everywhere?

Thanks,
Caleb

P.S. Mithril is absolutely amazing for writing web apps. @lhorie, you are a gentleman and a scholar (and a wizard, too).

**Comment by iamjohnlong** [comment]
you can use a layout component.

see http://mithril.js.org/simple-application.html towards the bottom of the page.

**Comment by caleb531** [comment]
Excellent, that should work perfectly. Thanks very much, and thanks for an impressively prompt reply. :)

**Comment by tivac** [comment]
@iamjohnlong Man that page needs some section headings for deep-linking. 😞

**Comment by iamjohnlong** [comment]
@tivac how do you run the docs locally?

**Comment by tivac** [comment]
`npm run gendocs`, they generate into a `./mithril` folder alongside `./mithril.js` though.

**Comment by iamjohnlong** [comment]
> folder alongside ./mithril.js though.

Ah.. missing that part :)

**Comment by tivac** [comment]
Working on making that less confusing :smile:
