### ISSUE TITLE
Warn user about non-function lifecyle-handles

### ISSUE THREAD

**Issue by StephanHoyer** [lhorie/mithril.js#1706]
If you e. G. create the following, UI freaks out

```
  m('div', {
    oncreate: true
  }, 'bar')
```

**Comment by pygy** [comment]
That's odd, hooks should only be called if `typeof source[$hook] === 'function'` where source can be `attrs` or `state` for components.

Do you have a repro?

**Comment by tivac** [comment]
https://jsbin.com/zawokuw/1/edit?js,output

Clicking the box seems to redraw fine, maybe there's something else going on?

**Comment by isiahmeadows** [comment]
@StephanHoyer Could you create a repro?

**Comment by StephanHoyer** [comment]
can't reproduce in a simple example. Will close this for now. If it occurs again, I'll create another issue

**Comment by pygy** [comment]
It affects `onremove` and `onbeforeremove` only. Patch incoming.

**Comment by pygy** [comment]
There's a fix as part of #1746 (the patch would have conflicted if independent).
