### ISSUE TITLE
Optional route parameters

### ISSUE THREAD

**Issue by volnei** [lhorie/mithril.js#1730]
Hi guys!

There any way to pass optional route parameters? Something like this...

```javascript
'/users/:id?': User
```

Tks!

**Comment by barneycarroll** [comment]
Afraid not, you have to explicitly declare the with and without routes:

```javascript
{
  '/users'    : User,
  '/users/:id' : User
}
```

**Comment by isiahmeadows** [comment]
@volnei Is this good to close now?

**Comment by volnei** [comment]
Yeap!! Thanks!!
