### ISSUE TITLE
Link parameters

### ISSUE THREAD

**Issue by volnei** [lhorie/mithril.js#1731]
Hi again!

There any way to configure link params like routes and m.route.set("/route/:arg", {arg:1})?
The concatanation works fine, but this is a little ugly imho.

If not, the sugestion is something like this:

```javascript
m("a[href=/user/:id]", {data: {id: user.id}, oncreate: m.route.link}, user.name)
```

Tks =D

**Comment by pygy** [comment]
The path interpolation code used by `m.route.set` is not currently exposed, but it could be... Alternatively, we could provide a link component instead of a hook, as suggested by @barneycarroll in https://github.com/lhorie/mithril.js/issues/1709#issuecomment-288384163...

**Comment by volnei** [comment]
I think in another, non intrusive suggestion, I've used this to another component types:

```javascript
   m("a[href=/user/:id]", {oncreate: m.route.link({id: 1})}, user.name)   
```
With the change in current link method to return a function

```javascript
	route.link = function(data, options) {
                 return function(vnode) {
		        vnode.dom.setAttribute("href", routeService.prefix + vnode.attrs.href)
		        vnode.dom.onclick = function(e) {
			        if (e.ctrlKey || e.metaKey || e.shiftKey || e.which === 2) return
			        e.preventDefault()
			        e.redraw = false
			        var href = this.getAttribute("href")
			        if (href.indexOf(routeService.prefix) === 0) href = href.slice(routeService.prefix.length)
			        route.set(href, data, options)
		}
}
```

**Comment by purefan** [comment]
Sorry to revive a closed issue but its still not clear to me (nor have I succeeded in) how should we make _dynamic_ links, some of the things I've tried:

```javascript
m('a', { 
    href: '/section/subsection', 
    onclick: vnode => m.route.set('/section/:subsection', {subsection:'subsection1'}), 
    oncreate: m.route.link, 
    onupdate: m.route.link 
}, 'subsection1')
```
With this code the url does change but the component does not change. I have registered _section_ as a route like this:
```javascript
m.route(document.body, '/', {
  // other routes
  '/section/:subsection': some_component
})
```

I have also tried a _traditional_ (hardcoding the subsection and without an onclick overloader) `a` with no success: 
```javascript
m('a[href=/section/subsection]', { 
  oncreate: m.route.link, 
  onupdate: m.route.link 
}, 'subsection1'),
```
In this case the effect is the same: the url changes but the component doesnt. I also tried a manual redraw but no luck.

Can someone please post the right way to link to components with params?
