### ISSUE TITLE
No longer possible to mount parameterized components?

### ISSUE THREAD

**Issue by bgstcola** [lhorie/mithril.js#1743]
In version 0.2x you could do like this:

`m.mount(el, m.component(myComp, {hello: hi}))`

Now that `m.component` has been removed I have tried

`m.mount(el, m(myComp, {hello: hi}))`

but that doesn't work since `m(myComp, {hello: hi})` returns a vnode and m.mount expects a component.

Am I missing something?

**Comment by pygy** [comment]
@bgstcola You're not missing anything, but you can work around it by using a component literal:

```JS
m.mount(el, {view: function() {
  return m(myComp, {hello: hi})
}})
```

It is [covered](http://mithril.js.org/change-log.html#passing-vnodes-to-mmount-and-mroute) in the migration guide.
