### ISSUE TITLE
Multiple docs pages didn't get converted from their markdown sources

### ISSUE THREAD

**Issue by andraaspar** [lhorie/mithril.js#1749]
https://mithril.js.org/lifecycle-methods.html

**Comment by isiahmeadows** [comment]
@tivac [We have an even bigger problem than this...](https://github.com/lhorie/mithril.js/tree/gh-pages/docs)

**Comment by tivac** [comment]
I'll take look as soon as i can.

**Comment by tivac** [comment]
@isiahmeadows I don't get what the "even bigger problem" is? Still digging into why some pages weren't generated properly.

**Comment by tivac** [comment]
`lifecycle-methods.md` isn't being generated because of [this line](https://github.com/lhorie/mithril.js/blob/934e0ac55ee6a0e3a5c3063ce151e5f0889a89af/docs/generate.js#L30) which filters it because it contains the word "methods".

I understand why that filter exists, I just don't understand how that page ever got generated correctly?

**Comment by tivac** [comment]
Ah, it was added in this commit: https://github.com/lhorie/mithril.js/commit/e3b0861b8a494e0f121b61e754cd744a87ff6e97

And docs hadn't been re-generated since. Not my fault, *phew*! I'll work on fixing this up.

**Comment by isiahmeadows** [comment]
@tivac If you notice, there's other `.md` files there, too.

**Comment by isiahmeadows** [comment]
Well...never mind. I forgot Jekyll was actually being used.

**Comment by isiahmeadows** [comment]
Me thinks that line should read like this:

```js
if (!/[\\\/](tutorials|archive|guides|methods)\./.test(pathname)) {
    // ...
}
```

**Comment by tivac** [comment]
I went with a different fix, PR incoming.

**Comment by tivac** [comment]
Merging changes to `master` so they get published now that #1754 is merged into `next`.

**Comment by tivac** [comment]
@isiahmeadows Oh I see, the first run generated some garbage in the `gh-pages` branch. I will clear that out manually in a bit. I also still need to copy over the archive versions from [lhorie/mithril](https://github.com/lhorie/mithril) so I'll tackle that at the site same.

**Comment by tivac** [comment]
Published, https://mithril.js.org/lifecycle-methods.html exists again.

**Comment by tivac** [comment]
Archives are back as well now.
