### ISSUE TITLE
A PR was merged directly onto master

### ISSUE THREAD

**Issue by tivac** [lhorie/mithril.js#1755]
#1753 got merged directly to `master` instead of `next`, that should be undone and applied to `next` to follow current release practices.

@isiahmeadows volunteered to do this work in [gitter](https://gitter.im/lhorie/mithril.js?at=58dae708408f90be6666f4f5).

The commit in question: 000eec90d85324df34fc51827d6c2bf2d75e11d9

**Comment by isiahmeadows** [comment]
That was my mistake, BTW. Apologies for the mess. 😉  😦

**Comment by isiahmeadows** [comment]
Fixed.

- Pushed revert for 000eec9 to `master`
- Pushed cherry-pick for 000eec9 to `next`
- Gandalf has already rebuilt the bundles on `next`.

**Comment by isiahmeadows** [comment]
Here's a thought to avoid future issues: have Gandalf automatically comment on new PRs targeting `master`, to avoid future scenarios like this.

**Comment by tivac** [comment]
@isiahmeadows #1784 for my proposal on how to avoid this.
