### ISSUE TITLE
Number zero not rendered in 1.1.0

### ISSUE THREAD

**Issue by tkazec** [lhorie/mithril.js#1768]
Hi, apologies if this was an intended change –

The following code produces different results in 1.0.1 and 1.1.0:

```javascript
m.render(document.body, [
    m("div", 0),
    m("div", 1),
]);
```

In 1.0.1, it has the intended effect of two divs containing `0` and `1`. In 1.1.0, only the second div contains `1`. Essentially, children who are `0` are no longer shown.

**Comment by tkazec** [comment]
Sorry, just saw #1753. Will there be a patch release for this? @lhorie @isiahmeadows

**Comment by pygy** [comment]
You're the third one to report this, and, yes, v1.1.1 will be released very soon.
