### ISSUE TITLE
Investigate post-filling vnodes

### ISSUE THREAD

**Issue by tivac** [lhorie/mithril.js#1780]
Idea from this thread: https://twitter.com/thysultan/status/849702731493330946

Benchmark: https://esbench.com/bench/58e5418d99634800a0347be0

Chrome
![image](https://cloud.githubusercontent.com/assets/49545/24738161/628adce6-1a83-11e7-8991-02d1635c0829.png)

Firefox
![image](https://cloud.githubusercontent.com/assets/49545/24738180/80e02b6a-1a83-11e7-8f89-c43b4b93876a.png)

IE11
![image](https://cloud.githubusercontent.com/assets/49545/24738192/972b8ae0-1a83-11e7-9412-f956d8a4c6dd.png)

Edge
![image](https://cloud.githubusercontent.com/assets/49545/24738213/b6820144-1a83-11e7-8e1c-a1704e70becb.png)

It's slower by a fair bit in every non-v8 environment, but the v8 perf difference is pretty shocking.

**Comment by tivac** [comment]
Probably not worth it, looks like v8's already working on fixing the bug causing the pre-fill slowdown.

https://twitter.com/bmeurer/status/849844623224844293

**Comment by pygy** [comment]
I'd say avoid it, post-fill is catastrophic in Firefox, worse in IE and Edge (and the ESBench crashes in Safari 10.1 with `QuotaExceededError (DOM Exception 22): The quota has been exceeded.`)

**Comment by tivac** [comment]
V8 fixed the bug, so this is a 100% won't do.

It does remind me that I really want an official mithril perf testing setup though so we can reasonably compare perf sensitive work. Something that runs in real browsers, ideally. I wonder how other frameworks do that?

In my fantasy world we'd run perf tests when the unit tests pass, and fail builds that don't meet our thresholds.

**Comment by pygy** [comment]
That would be awesome, at least for CI. I wonder how @lhorie did the initial perf tests.

If you want to do perf comparisons, you'd have to run the benchmarks before and after each change (since the code may run on different hardware). Also, what if the results are mixed? much faster in a browser, much slower in another?

**Comment by tivac** [comment]
I was thinking we'd set reasonable thresholds for perf that are correct for CI, wouldn't expect folks to run this code locally except manually.

It certainly wouldn't fail local builds though, perf numbers are too variable across hardware.
