### ISSUE TITLE
Rendering false as empty string doesn't work on IE

### ISSUE THREAD

**Issue by gaspoute** [lhorie/mithril.js#1785]
Hello,

I want to toggle a SVG when clicking on it by rendering `false` as an empty string but it doesn't work on IE: https://jsfiddle.net/8fgL456p/1/.
However, by using `null`, it works: https://jsfiddle.net/8fgL456p/3/.

Regards,
Gaspar.

**Comment by pygy** [comment]
Thanks for the report @gaspoute

I tried a minimal repro (https://jsfiddle.net/v3oae73n/) and neither `null` nor `false` are displayed (and the same code in IE9 with JSBin, but I've lost the link)...

Your example (https://jsfiddle.net/8fgL456p/1/.) works fine in IE11 as well (via SauceLabs).

Could you provide more details?

**Comment by gaspoute** [comment]
It's my fault. The example doesn't really reproduce my case.
It's originally a `key` problem.

Thanks :-)
