### ISSUE TITLE
Your CDN got hacked? 

### ISSUE THREAD

**Issue by dealercontrolrachel** [lhorie/mithril.js#1799]
I think someone hacked the CDN on your installation page. 

`<script src="https://unpkg.com/mithril/mithril.js"></script>`

I have a node server with this CDN on my HTML page and got the below screenshot when trying to load my page. Notice the 'compliance-jessica.xyz' in the bottom left, that is not from any of my stuff. I changed the CDN and the problem is gone. This could have been caused my something else but I think you guys may want to check. :P

![screen shot 2017-04-13 at 4 14 16 pm](https://cloud.githubusercontent.com/assets/23037511/25027815/503b0886-2064-11e7-9787-de0381ce4c75.png)

**Comment by tivac** [comment]
unpkg.com had some nameserver issues, not a mithril issue.

**Comment by dealercontrolrachel** [comment]
right, I just thought you might not want a broken CDN on your installation page :)

**Comment by tivac** [comment]
It's fixed already, things happen.

We could change the CDN but there's no guarantee it wouldn't happen to anything we change it to as well.

**Comment by dealercontrolrachel** [comment]
okay, was just trying to make sure you guys knew about it I guess.

**Comment by tivac** [comment]
I apologize, as I reread my past responses I was too terse and not appreciative enough. The heads-up was definitely appreciated!

**Comment by dealercontrolrachel** [comment]
haha it's okay. Sorry if I made an unnecessary issue :p
