### ISSUE TITLE
mithriljs.com (old address my browser autocompleted) redirects to a 404

### ISSUE THREAD

**Issue by finetype** [lhorie/mithril.js#1803]
redirects to this:
![mithriljs-not-available](https://cloud.githubusercontent.com/assets/6391152/25075174/e8497740-22d3-11e7-86f5-7d7fef2cb571.png)

**Comment by isiahmeadows** [comment]
[Known issue out of our control](https://github.com/lhorie/mithril.js/issues/1567).
