### ISSUE TITLE
Typescript definition: RouterResolver render type error

### ISSUE THREAD

**Issue by seoyeongB** [lhorie/mithril.js#1805]
My problem,

e.g) test.com/test/:test_number
```
interface MyAttrs {
  test_number: string;
}

class MyState {
  test: Test;
}

const TestRouteResolver: m.RouteResolver<MyState, MyAttrs> = {
  onmatch(args, requestedPath) {
    ...
  },
  render(vnode) {
    vnode.key = vnode.attrs.test_number; // <- compile error!
    return vnode;
  }
};
```

For me, it seems like definition of vnode in render function should be fixed.

While defining type of vnode interface, ‘Attrs’ comes first and ‘state’ follows.
However, order of vnode type in render function is ‘State, Params’

I think order of vnode type in render function be changed as defined in vnode interface, that is ‘Params, State’.

current code is..
```
render?(this: State, vnode: Vnode<State, Params>): Children; // vnode: Vnode<Params, State>?

```
Vnode interface is defined..
```
interface Vnode<Attrs, State extends Lifecycle<Attrs, State>>
```

**Comment by pygy** [comment]
Paging @spacejack who wrote the typings...

**Comment by spacejack** [comment]
Hi @seoyeongB, can you post this issue on [this repo](https://github.com/spacejack/mithril.d.ts)

**Comment by tivac** [comment]
Closing since the typings aren't part of the mithril repo.
