### ISSUE TITLE
Variadic route from root '/...'

### ISSUE THREAD

**Issue by dlepaux** [lhorie/mithril.js#1812]
I'm using an isomorphic javascript app based on Express and Mithril.

I have tried to use the variadic route to display my custom 404 error page (sent back by Express). But it don't work.

```javascript
'\...': error404Component
```
Do you have an alternative to display a custom page ?
Or to not redirect when mithril is loaded on a 404 page ?

Thanks

**Comment by tivac** [comment]
I gave you bad advice in gitter sorry. Here's a working example of a variadic route capturing 404 requests.

https://jsbin.com/wawemu/1/edit?js,output

The key is that it needs to be a parameterized route, `/:404...` seems pretty clear to me.

**Comment by tivac** [comment]
See the example in #890 as well.

**Comment by dlepaux** [comment]
Excellent ! Thank you i update my PR for the doc !
