### ISSUE TITLE
m.route(element, defaultRoute, router) should not overwrite list of routes if element is different on a second call

### ISSUE THREAD

**Issue by lhorie** [lhorie/mithril.js#250]

**Comment by Daiz** [comment]
Something I've been thinking in relation to this: What if there was an extra routing mode that was basically pure internal state only (`m.route.mode = "internal"` or so)? So basically your Mithril app/component would not trigger any visible URL changes or push history entries, but routing would still work all the same code-wise. This would naturally not allow navigation via a browser's back/forward actions, but I think it would make life much easier for multiple Mithril tenants. As an extra, if it would be somehow possible to detect if a routing Mithril entity exists as part of a parent Mithril entity, the sub-Mithril would automatically default to internal routing. This, I imagine, would make building Mithril apps composed of other Mithril apps/components much easier.

Another thing that would be cool is what I guess could be best described as "subrouting", so basically think like you had a Mithril app that defined route `/foo/bar`, in where another Mithril app with routing was embedded. Then in said app's routing `'/'` would automatically default to `/foo/bar/`. I haven't thought too deeply about how this one though.

**Comment by impinball** [comment]
@Daiz That's a great idea to drop into another bug.

**Comment by isiahmeadows** [comment]
Cleaning up old issues. If you feel this needs brought up again, please file a new issue.
