### ISSUE TITLE
Empty "class" attribute rendered in html when using "section" tag

### ISSUE THREAD

**Issue by saniko** [lhorie/mithril.js#382]
for instance this line of code:

	`m("section[id='site-orientation']", [....`
renders this html

       `<section id="site-orientation" class=""> ....`

i use the latest v0.1.27

**Comment by lhorie** [comment]
Hmm I'm [not able to reproduce this](http://jsfiddle.net/h4zjqtuq/).

Can you post a jsfiddle?

**Comment by saniko** [comment]
HI, not sure if this my bad or not
but apparently when i use velocity in a config block it renders an empty "class" property
regardless of the "section" tag, please check the fiddle:
http://jsfiddle.net/ccxLymyv/1/

**Comment by ilog2000** [comment]
I can confirm the issue

```javascript
	function tab(href, name) {
		var active = m.route().indexOf(href) == 0 ? "active" : "";
		var a = m("a", { href: href, config: m.route }, name);
		return { tag: "li", attrs: { role: "presentation", class: active }, children: [a] };
		//return m("li", { role: "presentation", class: active }, [a]);
	}

	var topTabs = {};
	topTabs.controller = function () { };
	topTabs.view = function (ctrl) {
		return [
			m("ul.nav.nav-tabs", [
				tab("/tab1", "tab1"),
				tab("/tab2", "tab2"),
			])
		];
	};
```

This code renders for inactive tabs
* in Chrome v.41 m-dev: `class`
* in IE 11: `class=""`

If swap commenting on return line in the tab function, then it becomes: `class=" "`

**Comment by lhorie** [comment]
This is fixed and will land in the next release

**Comment by kvanberendonck** [comment]
Does this need to be reopened?

**Comment by lhorie** [comment]
You won't get `class=" "`, so it should be fine. You will get the output `class=""` for input `{class: ""}` but I think that's a reasonable trade-off to ensure #512 works (besides, that's technically the correct output for the key with empty string input)

**Comment by saniko** [comment]
Is this issue back in 1.34?
please check the fiddle:
http://jsfiddle.net/ccxLymyv/23/

**Comment by kvanberendonck** [comment]
@lhorie
