### ISSUE TITLE
Question about controllers and view models

### ISSUE THREAD

**Issue by jasonhansel** [lhorie/mithril.js#391]
As far as I can understand, two instances of a controller (created with, for example, `new TodoList.controller()`) are supposed to share the same view model (for instance, `TodoList.vm`).

Is this correct? If so, why is `controller` treated as a constructor instead of just a regular function?

Sorry if this is a dumb question, I'm just having trouble figuring out how to structure my app.

**Comment by dotandimet** [comment]
Having two instances of the same controller sharing the same view model doesn't really seem to make sense.

I can think up of cases where you'll have two instances of the same controller with different view models - for example, if your want to show two todo lists side-by-side (Bob's tasks vs. Alice's tasks), 
or have two different controllers sharing the same view model (for example, tasks displayed by date vs. tasks displayed by assignee). In this case, the two controllers probably also have more data they don't share, perhaps in other view models - there's no reason for a controller to have just one view model.

It doesn't seem that mithril dictates a specific app structure - it's a set of tools and design principles more than a rigid framework.

**Comment by lhorie** [comment]
You can have the view-model be shared by using a singleton view model, or you can have distinct view-models per controller instance via a factory.

The structure of your code should be dictated by what your specific needs are, and should not necessarily have the same structure as examples in the docs.

**Comment by jasonhansel** [comment]
OK. Thank you!
