### ISSUE TITLE
Having CSS as part of a module

### ISSUE THREAD

**Issue by oren** [lhorie/mithril.js#394]
I just found about mithril and it looks pretty sweet so far!

What do you think of having a CSS file for each module lives in the same folder where the module is. Since a module represent part of the UI in our app, why not having the styling for this component at the same place where the rest of the module? (increase the cohesiveness of our modules) 

Here are a few options for implementing this - https://gist.github.com/substack/68f8d502be42d5cd4942#css

insert-css is one of those options:

```js
var fs = require('fs');
var insertCss = require('insert-css');
var css = fs.readFileSync(__dirname + '/style.css');
insertCss(css);
```
It uses browserify and injects the style.css into the header.

**Comment by lhorie** [comment]
Yeah, you could probably do this, but it's not really in scope for Mithril. Might be a good suggestion for [boilerplate](https://github.com/fristys/mithriljs-boilerplate) [projects](https://github.com/velveteer/mithril-boilerplate) though.

**Comment by oren** [comment]
thanks a lot. i'll look at those projects.
