### ISSUE TITLE
controller's onunload method on route change never called

### ISSUE THREAD

**Issue by saniko** [lhorie/mithril.js#395]
var module =  {
	controller: function() {
        this.onunload = function() {
         console.log("unload controller")   // do not see this.
        };
        this.modal = submodule(modal);
      },
        view:    //return some view
	};

**Comment by lhorie** [comment]
Tried and it works fine for me: http://jsfiddle.net/c1jbdb8g/

Can you post a jsfiddle demonstrating the issue?

**Comment by saniko** [comment]
hmm...
strange, could you check the following fiddle
http://jsfiddle.net/7j4xgeye/86/

**Comment by StephanHoyer** [comment]
Your `mainModule.controller` has no `onunload` method. This is the actual instantiated controller by the route. So either change this or dynamically ad the `onunload` of your `submodule.controller` to the `mainModule.controller`

**Comment by StephanHoyer** [comment]
Better solution would be imho [this](http://jsfiddle.net/7j4xgeye/96/)

**Comment by lhorie** [comment]
What @StephanHoyer said. Or you could setup an onunload in mainModule controller that calls the submodule's onunload
