### ISSUE TITLE
Creating comments for view?

### ISSUE THREAD

**Issue by stevenvachon** [lhorie/mithril.js#396]
Something like a `React.createComment()` (does not yet exist).

It'd just have to use `document.createComment()`.

It'd come in handy when working in the Inspector and when compiling to Mithril from other template systems.

**Comment by StephanHoyer** [comment]
What about

```m.trust('<!-- huhuhu -->')```

The rest is just a simple exercise ;)

**Comment by lhorie** [comment]
@StephanHoyer hah, that's clever. I totally didn't think of it.
