### ISSUE TITLE
Rendering resets cursor blinking on Chrome

### ISSUE THREAD

**Issue by kvanberendonck** [lhorie/mithril.js#397]
When the form renders, the cursor blinking in input fields is reset to the visible state, causing it to be always visible.

Looks pretty sketchy in applications where a websocket is continually triggering renders behind the scenes.

**Comment by lhorie** [comment]
I can't reproduce: http://jsfiddle.net/zvk3xav6/

Can you provide a jsfiddle demonstrating the issue?

**Comment by kvanberendonck** [comment]
You're right, I can't reproduce it here either. Not your bug then, feel free to close.
