### ISSUE TITLE
Allow normal caching via m.request (disable XHR's Cache-Control: max-age=0)

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#401]
I understand that overriding default cache behaviour is somewhat of a convention with XHR. However I'd like to rely on the browser's native behaviour in combination with response headers.

A standard XHR request produced by m.request looks like this:

```
GET {uri} HTTP/1.1
Host: {host}
Connection: keep-alive
Cache-Control: max-age=0
Accept: application/json, text/*
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2268.0 Safari/537.36
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,fr;q=0.6,sv;q=0.4
```

Going by the docs, I can modify headers by using a config option in the m.request. It's not clear from the XHR spec how I can remove a header, or what the 'default' Cache-Control value is, so I try the following:

```javascript
config : function( xhr ){
  xhr.setRequestHeader( 'CacheControl', false );
}
```

This screws up my XHR horribly. The eventual request is now:

```
OPTIONS {uri} HTTP/1.1
Host: {host}
Connection: keep-alive
Cache-Control: max-age=0
Access-Control-Request-Method: GET
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2268.0 Safari/537.36
Access-Control-Request-Headers: accept, cache-control
Accept: */*
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,fr;q=0.6,sv;q=0.4
```

So now this has become an OPTIONS request, it accepts anything, Cache-Control wasn't affected and I've effectively added a Access-Control-Request-Headers header. I've tried setting Cache-Control to other values ('public', 'cache'), but it produces the same XHR as above.

Any ideas?

**Comment by barneycarroll** [comment]
Not a Mithril bug. The `Cache-Control` header is determined by the client cannot be interfered with via author code. It's being continuously sent with `max-age=0` is a result of the client determining the resource should be fresh, either because of a user's hard-refresh, or (in my case) because developer tools disable caching.

```javascript
config : function( xhr ){
  xhr.setRequestHeader( 'CacheControl', false );
}
```

The code above is broken in several ways: `CacheControl` is misspelled (should be `Cache-Control`); you can't manually set this header; you can't remove headers this way.

**Comment by lhorie** [comment]
Normally I'd control caching from the server with response headers like etag
