### ISSUE TITLE
Add cache busting option to m.request config

### ISSUE THREAD

**Issue by ilog2000** [lhorie/mithril.js#402]
I use busting technique to prevent caching ajax results:
```javascript
	var util = {};
	util.bust = function () {
		return "?bust=" + (new Date()).getTime();
	};

// ...
	var Model = {}
	Model.list = function () {
		return m.request({ method: "GET", url: "/things" + util.bust(), config: util.xhrConfig })
	}
```
I believe, it would be helpful to have such an option in m.request config, adding this part to a query string only for GET requests.

**Comment by lhorie** [comment]
I think it's easier to just do it manually than go digging around docs for a framework-specific option that does this

**Comment by StephanHoyer** [comment]
that's why I love mithril :+1: 

thanks @lhorie
