### ISSUE TITLE
Pass ajax result through future chain

### ISSUE THREAD

**Issue by ilog2000** [lhorie/mithril.js#403]
Right now this code doesn't work (although was expected, at least by me)
```javascript
var users = m.prop([]); //default value
var log = function(data) {
    console.log(JSON.stringify(data))
}
m.request({method: "GET", url: "/user"}).then(log).then(users)
```
It would be good if ajax result is passed through the future chain.

**Comment by barneycarroll** [comment]
Each `then` consumes the return value of the last function in the chain. Because `log` has no explicit return value, it outputs `undefined`, which is then received by `users`. You can fix this by making `log` return its input, [as shown here](http://jsfiddle.net/barney/c63dp1vk/). This allows you to modify or replace values with `then`, which is useful if you want to modify values before assigning them ([example here](http://j(casting-the-response-data-to-a-class)).

**Comment by ilog2000** [comment]
Barney, thanks for the explanations. I had to understand this by myself. Could you, please, fix the second link in your post before I close the issue?

**Comment by StephanHoyer** [comment]
`promise.tap` would be great to have. This would be also easy to implement and only really little amount of code.

**Comment by barneycarroll** [comment]
@ilog2000 oops, fixed.

@StephanHoyer how would the proposed `tap` differ from the current implementation of `then`?

**Comment by StephanHoyer** [comment]
It returns what it gets. Like so

```
promise.tap = function(cb) {
  return this.then(function(result) {
    cb(result);
    return result;
  }
}
```
Not tested if this works.

**Comment by StephanHoyer** [comment]
Just saw that this is not in the es6 promise spec. So maybe don't integrate this to mithril.

**Comment by ilog2000** [comment]
@barneycarroll, thank you!

@StephanHoyer, 'tap' is a kind of extension. I was afraid that the expected behavior is broken, shortly experimenting with log function.

Guys, closing this issue, let's proceed with the discussion in #228

**Comment by barneycarroll** [comment]
@ilog2000 #228 is effectively a proposal to allow the behaviour you were originally describing, whereby the return value is ignored and the input value is automatically passed through to subsequent chained methods. We could effectively implement this as follows ([demo here](http://jsfiddle.net/barney/7thmbo5d/)):

```javascript
function tap( fn ){
  return function tapped( value ){
    fn( value );

    return value;
  };
}

m.request( /* ... */ ).then( tap( log ) ).then( users );
```

@StephanHoyer the behaviour you're describing (allowing asynchronous operations within then to be consumed by the subsequent chain) is automatic if the function passed to `then` returns a thenable. See [this example](http://jsfiddle.net/barney/jtnjsf7e/), where the remodelling function executes in a setTimeout and the following `then` only executes once that resolves.

**Comment by ilog2000** [comment]
@barneycarroll, I understood what @StephanHoyer 's code means. I decided to close this issue because
(a) I thought this is a default behavior of m.response which is broken, and you pointed that I was wrong,
(b) The ticket for 'tap' already exists ( #228 )
