### ISSUE TITLE
Add `promise.catch` to Promise implementation

### ISSUE THREAD

**Issue by StephanHoyer** [lhorie/mithril.js#404]
Would be great to have `promise.catch`.

see [here](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Promise)

This is maybe somewhat related to #228

**Comment by lhorie** [comment]
Yeah, it's related. Making promises follow ES6 means we would also have access to Promise.prototype, which can be extended for tap, value, spread, etc, but as I mentioned there, it's a breaking change.

I'll make a note there about catch
