### ISSUE TITLE
current version 0.1.28 looses key attribute...

### ISSUE THREAD

**Issue by webcss** [lhorie/mithril.js#405]
..., it's simply not rendered. 0.1.27 is fine though.

**Comment by barneycarroll** [comment]
@webcss the `key` attribute isn't intended as a DOM attribute – it's an abstract attribute for internal use by Mithril (like `config`) to preserve elements between redraws. If you want a unique identifier that is rendered as an attribute, you should use the HTML-valid `id` attribute.

**Comment by webcss** [comment]
Allright, thank you! Just like I used to do it. 
So the behaviour before 0.1.28 (key attribute was added to a node) could be considered *buggy* ;-)

**Comment by barneycarroll** [comment]
Yeah, I was a bit irritated with it polluting the DOM TBH – can't find my initial complaint though ;)

**Comment by lhorie** [comment]
yeah, this was done as a performance optimization, to allow diffs on elements without attributes to skip the attribute diffing portion of the code altogether.
