### ISSUE TITLE
Why it is so fast?

### ISSUE THREAD

**Issue by mainameiz** [lhorie/mithril.js#406]
According to http://jsperf.com/angular-vs-knockout-vs-ember/456 Mithril is the fastest framework.

Please, can you explain why Mithril is so fast? Primarily in compare to React (48.58 vs 111,520 operation per second). Thanks a lot.

**Comment by lhorie** [comment]
I'm not familiar w/ React internals, so I can't speak for it. However, Mithril's virtual dom engine is a lot smaller and largely made of procedural code (a lot of which has been micro-optimized).
