### ISSUE TITLE
on route change event

### ISSUE THREAD

**Issue by skyeagle** [lhorie/mithril.js#407]
Hello!

I have patched `mithriljs` to prevent user to being redirected before he is authenticated, so code at [this line](https://github.com/lhorie/mithril.js/blob/v0.1.28/mithril.js#L648) looks like:

```javascript
		for (var route in router) {
			if (route === path) {

                if (router[route].skipAuth === true) {
                    m.module(root, router[route])
                } else {
                    Auth.loggedIn().then(function(){
                        m.module(root, router[route]);
                    }, function(){
                        if (router[route].optionalAuth === true) {
                            m.module(root, router[route])
                        } else {
                            m.route('/login')
                        }
                    });
                }

				return true
			}

                // and the same wrapper for matched route goes below...
```

So, It will be awesome to have such event handling. I can't suggest an implementation because I'm not the JS guru. So, your help very appreciated.

Thank you for your excellent work.

**Comment by lhorie** [comment]
I usually handle it like so:

```javascript
var Layout = function(module) {
  return {
    controller: function() {
      return new Layout.controller(module)
    },
    view: Layout.view
  }
}
Layout.controller = function(module) {
  Auth.loggedIn.then(null, function() {
    m.route("/login")
  })
  this.content = module.view.bind(this, new module.controller)
}
Layout.view = function(ctrl) {
  return m(".container", ctrl.content)
}

//want to protect this
var MyModule = {
  controller: function() {},
  view: function() {}
}

m.route(document.body, "/", {
  "/": Layout(MyModule),
  "/login": Login //assuming a Login module also exists
})

```

**Comment by barneycarroll** [comment]
I agree with Leo that this code should go in controllers, and his approach of decorating modules is incredibly useful for situations like this: you can keep your core module ignorant of the higher-order logic, and pass it through a function that returns a decorated version which handles the logic. You could combine these fundamentals with your idea of a simple router map and components with property flags to highlight their authentication settings by passing through your `m.route` initialization arguments to a pre-processor function which handles the work of decorating the controllers for you.

This code should allow you to replicate the system you originally posted without touching Mithril internals:

```javascript
// Invoke as follows:
m.route( authRoutes( /* whatever you were passing to m.route in the first place */ ) );

function authRoutes( root, defaultRoute, router ){
  for( var route in router ){
    var module = router[ route ];

    // We define a higher-level module for each route
    router[ route ] = {
      // View stays the same
      view       : module.view,
      // Controller is only the same if module has a `skipAuth` flag
      controller : module.skipAuth ? module.controller : function authController(){
        // Auth is asynch, so stop rendering until the outcome is known
        // (otherwise the view will render with an empty ctrl argument)
        m.startComputation();

        Auth.loggedIn().then( success, module.skipAuth ? success : failure );

        function success(){
          // Redirect to the original module, resume rendering
          m.module( root, module );

          m.endComputation();
        }

        function failure(){
          m.module( root, router[ '/login' ] );

          m.endComputation();
        }
      }
    };
  }
}
```

**Comment by skyeagle** [comment]
It's really interesting and useful. Thanks.

Don't you think guys that mithriljs should have common solution to do so? I suppose that any non toy app requires this kind of logic. Might be It could be a global(and/or per route) resolver for controllers ?

**Comment by barneycarroll** [comment]
> Don't you think guys that mithriljs should have common solution to do so? I suppose that any non toy app requires this kind of logic.

It's true that Mithril's route component is relatively basic, and I agree that a complex application will quickly run into problems relying exclusively on the `m.route` API. But the API does have the benefit of being very simple to understand and being able to achieve complex route-matching relatively easily. On the other hand, the requirements for a routing framework can be pretty diverse and complex.

It's worth bearing in mind that you could easily ditch Mithril's routing component and use a 3rd party library for routing, and handle callbacks with a combination of model changes, `m.module` and `m.redraw` calls.

> Might be It could be a global(and/or per route) resolver for controllers ?

The code I posted above is catered specifically to the conditions you described, but essentially this is what the `authController` function is doing — it can be extended to handle any complexity of conditions dynamically before module controllers execute. I'm currently developing a plugin which offers an extended API for routing in Mithril based partly on this principle: I'll post back here when I get to a public release.

**Comment by BransonGitomeh** [comment]
hey @barneycarroll public release still comming? :-D

**Comment by barneycarroll** [comment]
Hey @BransonGitomeh, thanks for following up (all these years later)!

That plugin I wrote was [Moria](https://www.npmjs.com/package/moria). It allows you to write nested routes with any number of functions between match and resolution. .

Moria will only work for v0.2 - it relies on the `{ controller, view }` component structure deprecated in v1 - and I don't plan on releasing a version for v1. Instead I would recommend a less opinionated solution like [page.js](https://visionmedia.github.io/page.js/), which can more easily deal with any routing concerns you might have without an explicit relationship to Mithril components or whatnot. When dealing with this level of complexity, having to manually call `m.mount` at the end of a route resolution will be the least cumbersome aspect of your route logic.
