### ISSUE TITLE
handle embedding modules in views

### ISSUE THREAD

**Issue by weepy** [lhorie/mithril.js#410]
I wanted to know if mithril might ever be able to support embedding like this :

 ```
var inner = {
        controller: function() { return this }, 
        view: function() {
                  return    m("div", "inner")
        }        
}

var outer = {
        controller: function() { return this }, 
        view: function() {
            return    [  
                            m("inner", "outer"), 
                            m.module( inner )
                         ]
          }
 }

m.module(document.body, outer() );

```

Here's a larger example:

http://jsfiddle.net/odj8h4fa/1/

**Comment by StephanHoyer** [comment]
This is problematic, due to the way, mithril works:

View rendering happens pretty often, so the module initialisation would be repeated on every rerender.

One solution would be to init the module in the controller:

```javascript
var inner = {
  controller: function() {}, 
  view: function() {
    return m("div", "inner");
  }        
};

var outer = {
  controller: function() { 
    var innerCtrl = inner.controller();
    return {
      innerView: function() {
        return inner.view(innerCtrl);
      }
    }
  },
  view: function(ctrl) {
    return [  
      m("hr"), 
      ctrl.innerView(),
      m("hr")
    ]
  }
};

m.module(document.body, outer);
```
see http://jsfiddle.net/odj8h4fa/3/

Other solution would be to write a custom element handler. But this may not be good style I think.

**Comment by StephanHoyer** [comment]
More sophisticated example with utility function can be found [here](http://jsfiddle.net/odj8h4fa/4/)

```javascript
function embed(module, args) {
  var ctrl = inner.controller.apply(null, args);
  return function() {
    return inner.view(ctrl);
  }
}
```

**Comment by weepy** [comment]
Interesting.

I noticed that currying the controller to the view works :
http://jsfiddle.net/odj8h4fa/5/

Which ends up encapsulating the inner entirely.

Is this style ok ?

**Comment by StephanHoyer** [comment]
This does not work I think. Try to return any data from the inner controller. It never get's through.

The `embed` function pretty much does exactly this but works ;)

BTW: If you don't have anything in the inner controller the solution is pretty simple. Just call the `inner.view()`-function within the `outer.view()`.

```Javascript
var inner = {
  view: function() {
    return m("div", "inner");
  }        
};

var outer = {
  controller: function() {},
  view: function() {
    return [  
      m("hr"), 
      inner.view(),
      m("hr")
    ]
  }
};

m.module(document.body, outer);
```

**Comment by weepy** [comment]
sweet thanks :)

**Comment by JoeDRL** [comment]
I tend to do exactly like @StephanHoyer, except I called that function c() for component ;)
Works fine for now.

**Comment by barneycarroll** [comment]
WRT completeness, the code in the original example is exactly what the [Components](https://github.com/lhorie/mithril.js/blob/components/docs/components.md) branch does.

If you want to use that functionality now with current Mithril you can use my [Modulator](https://gist.github.com/barneycarroll/0e3c1b9811b47c012b13) plugin. The syntax is slightly different:

```Javascript
var inner = {
        controller: function() { return this }, 
        view: function() {
                  return    m("div", "inner")
        }        
}

var outer = {
        controller: function() { return this }, 
        view: function() {
            return    [  
                            m("inner", "outer"), 
                            mod( inner )()
                         ]
          }
 }

m.module(document.body, outer );
