### ISSUE TITLE
change components to singletons ?

### ISSUE THREAD

**Issue by weepy** [lhorie/mithril.js#411]
I wanted to discuss a change that I think could help mithril work more intuitively and work better for componentisation - that is change controllers from being functions to a singleton. View's will obviously stay as functions since they need to be recomputed, but controllers are automatically instantiated by mithril anyway.

So modules will look more like this : 

```

var app = {};

var pages =  [ { url, title } ...  ] ;

//controller
app.controller = {
        pages: pages,
        rotate: function() {
            this.pages.push(this.pages.shift());
        }
}
//view
app.view = function(ctrl) {
    return [
        ctrl.pages.map(function(page) {
            return m("a", {href: page.url}, page.title);
        })
    ];
};


```

In order to do this - all that's needed is removing the "new" keyboard on the following line

```var controller = new module.controller;```

I've tried this out and it appears to work for all examples so far. One benefit is that it means that the addition of the code below to the current m.module function means that we can get simple componentization out of the box

```
		if( arguments.length == 1) {
			// first arg is actually the module
			return root.view(root.controller)
		}

```

The example from the guide on components then becomes : 
```
//root module
var dashboard = {};

dashboard.controller = {
}

dashboard.view = function(ctrl) {
    return [
        userProfile,
        projectList
    ]
}
```

Of course the lack of being able to pass options into the controller constructor means that we would have to create factories instead.

Anyway --- I'm quite new to all this --- so entirely possible there's a gaping hole in all of this ^_^ Look forward to hearing your responses.

**Comment by Naddiseo** [comment]
Wouldn't that prevent controller reuse on the same page?

**Comment by lhorie** [comment]
More importantly, this would prevent lazy loading of controllers in a routing scenario (i.e. this would make controllers for all routes run on page load, which is most likely not what you'd want)

**Comment by weepy** [comment]
OK --- thanks for the heads up
