### ISSUE TITLE
Feature: Accept an array in the `config` attribute

### ISSUE THREAD

**Issue by tomekwi** [lhorie/mithril.js#414]
At the moment I'm using a helper like this:

```js
/**
 * Returns a new `callingAll` function, which calls all given `functions` in a series.
 *
 * Each of the `functions` is bound to `thisArg` and gets the same set of arguments
 * which has been passed to the `callingAll` function.
 *
 * @function callAll
 * @param {Any} thisArg
 * @param {Array} functions
 */
export default function callAll (thisArg, functions) {
  return function callingAll () {
    var args = arguments;
    functions.forEach(function (func) {
      func.apply(thisArg, args);
      });
    };
  }
```

…to be able to do this:

```js
m
( ".wrapper"
, { config: callAll(null,
    [ viewModel.wrapper
    , viewModel.hookHidingPopups
    ])
  }
);
```

I'd be delighted to able to do it without the cruft, out of the box. Like this:

```js
m
( ".wrapper"
, { config:
    [ viewModel.wrapper
    , viewModel.hookHidingPopups
    ]
  }
);
```

##### Reasoning

Basically, my view model always has a couple of functions designed to be passed to the config attribute. Moving things around, I sometimes find myself wanting to hook up multiple config functions on one element.

Sure, I could merge the two functions into one. But:
- often they concern different things – merging them would bring more complexity;
- often the functions are reusable (like the `viewModel.wrapper` which is an `elementProp` – a utility I've written to save a reference to any DOM element).

**Comment by StephanHoyer** [comment]
Why not just

```javascript
m
( ".wrapper"
, { config:
    [ viewModel.wrapper()
    , viewModel.hookHidingPopups()
    ]
  }
);
```

**Comment by barneycarroll** [comment]
The thing is that this isn't really about `config` or Mithril per se – it's a really generic convenience function for wrapping several functions into one.

For instance, another really useful application is event handling: what if I want several event handlers on click?

```javascript
m( 'input', {
  onclick : multi( preventDefault, appLogic )
} );

function preventDefault( e ){
  e.preventDefault();
}
```

This is just an example – if you've got a taste for ultra-functional programming, there are all sorts of situations where this becomes useful. 

I use this variation throughout my application (ES6isfied as per your preference, @tomekwi ;):

```javascript
export default function multi( ...handlers ){
	return function execute( ...args ){
		for( let fn of handlers ) fn.apply( this, args );
	};
}
```

It just so happens that I use it mostly for `config`, but really I don't believe it's Mithril's business to simplify this:

```javascript
m( 'input', {
  config : multi( autofocus, pluginX, pluginY )
} );
```

**Comment by StephanHoyer** [comment]
I also think this shouldn't be done in the view but have specific controller method that does this. This then should be called in the view. In the controller this can be generate using [function composition](https://lodash.com/docs#compose) or what ever you like.

So I'm with @barneycarroll: that's not Mithril's scope.

**Comment by lhorie** [comment]
If we're using ES6, how about this?

```javascript
m( ".wrapper", {
  config: (...args) => [
    viewModel.wrapper(...args),
    viewModel.hookHidingPopups(...args)
  ]
});
```

**Comment by tomekwi** [comment]
Hello, thank you all for your suggestions. They all make perfect sense. More elegant than my solution, I must admit.

I've also haven't had the chance to get to grips with ES6's beautiful, terse syntax. The only thing from the spec we've been using here in the office are modules. Just in case things don't play well and we have to revert to ES5.

It's just that I have the impression that Mithril's functions are heavily overloaded. I like the terseness of that. I'd still see it convenient and self-explanatory to be able to pass an array of functions to config or an event handler. But if you don't agree with me, I'll be happy to close the issue.

**Comment by barneycarroll** [comment]
@lhorie neat!
