### ISSUE TITLE
Manual unloading of modules

### ISSUE THREAD

**Issue by jrvidal** [lhorie/mithril.js#420]
As far as I can see, once a module has been appended to a DOM element, there is no way to unload it, it can only be substituted after another `m.module` call with the same root. I think that it'd make sense to add a `m.unload` method.

**Comment by lhorie** [comment]
Starting in the next release, this will be doable via `m.module(element, null)`

**Comment by fluxxu** [comment]
How to unload modules initialized by m.route?
Calling m.module(element, null) doesn't remove the listener attached to window object...
