### ISSUE TITLE
parent {config} block always runs?

### ISSUE THREAD

**Issue by saniko** [lhorie/mithril.js#422]
Hi, please check the following fiddle:
http://jsfiddle.net/ccxLymyv/5/

see that when i click the inner div (the click) i also get console from parent config code.
does onclick causes redrew? why does the config code runs twice?
how can i avoid this?

**Comment by barneycarroll** [comment]
Yes, event handlers bound through Mithril's DOM builder always trigger redraw after execution. The other place you get automatic redraws by default is after AJAX requests resolve.

This means you can do things like this without manually triggering redraws every time you want to update the view: http://jsfiddle.net/barney/hsmeay6u/ – when you have plenty of application variables and the model changes all the time, manually triggering `m.redraw()` all the time becomes tiresome.

One of the big appeals of Mithril is that the DOM diffing engine and DOM manipulation tools are so efficient that redrawing is less of performance problem than any other library. For an example of how this scales, occlusion culling creates and removes elements and modifies style values so fast that there's no stutter as you scroll through. I'm doing this with 1000s of richly styled elements in my application, and redraw is the last thing I'm concerned about performance-wise. 

If you're worried about logic and config functions firing when you don't want them to, you should use the `isInitialized` flag (also in my example) to determine whether the element has just been created or not.

**Comment by daryl** [comment]
When the section is rendered, it will call the config function (`ctrl.a`), whilst `ctrl.b` will only get called when the click event fires. After that event fires it seems that it redraws the whole thing.

One thing you can do is first check to see if `isInitialized` is `true`:

```js
this.a = function(element, isInitialized, context) {
  if(isInitialized) return; // runs once
  console.log("in a");
}
```

 http://jsfiddle.net/ccxLymyv/6/

**Comment by lhorie** [comment]
Another thing you can do is call m.redraw.strategy("none") if you know that an event handler did not require a redraw:

```javascript
m.module(document.body, {
    controller: function() {
      this.a = function(element, isInitialized, context) {
        if (!isInitialized) {
          //run only the first time
          console.log("in a");
        }
      }
      this.b = function(e) {
        if (foo) doStuff()
        else m.redraw.strategy("none") // nothing happened, so don't bother redrawing
      }
    },
    view: function(ctrl) {
        return m("section[id='start-here-1']",{config: ctrl.a}, [
            m(".someclass",{onclick:ctrl.b}, "click")
        ])
    }
})
```

**Comment by saniko** [comment]
Thanks!
