### ISSUE TITLE
List view getting out of sync after splice (even with keys)

### ISSUE THREAD

**Issue by a-s-o** [lhorie/mithril.js#424]
Hello,

I am trying to implement an sortable/editable list component but the rendered view of the list is not kept in sync after a drag-and-drop move operation.

Please see codepen at http://codepen.io/anon/pen/MYogzQ?editors=001
To test out the issue, just drag and drop an item to a different position in the "rendered view" section. At that point the "array" will reflect the correctly updated position of the item but the "view" gets out of sync. 

Here is the javascript source for convenience:
```
// Simple list item class
var ListItem = function(key) {
  return { key: key };
}

m.module(document.getElementById('container'), {
  controller: function(list, options) {
    var ctrl = this;
    
    // Generate a sample list
    ctrl.list = [];
    while (ctrl.list.length < 5) {
      ctrl.list.push(new ListItem('initial-' + ctrl.list.length));
    }

    // Method to add an item to the end of the list
    var counter = 0;
    ctrl.addItem = function( text ) {
      ctrl.list.push(new ListItem( 'added-item-' + counter++ ));
    }
  },

  view: function (ctrl) {
    // Generate item views and add a field in the end
    // for adding new items
    var listItems = ctrl.list
      .map(function(item) {
        return m('li.sortable-item', { key: item.key }, item.key);
      })
      .concat([
        m('li.new-item', { key: 'new-item' }, m('input', {
          placeholder: 'Click here and press enter to add item',
          style: { width: '50%' },
          onkeyup: function(e) {
            if (e.keyCode === 13) {
              ctrl.addItem(e.target.value);
              e.target.value = '';
            }
          }
        }))
      ]);

    return [
      m('h5', 'Rendered view'),
      m('ul', { 
        config: function (element, isInitialized, ctx) {
          if (isInitialized) return;

          var sortable = new Sortable(element, {
            animation: 200,
            draggable: '.sortable-item',
            onUpdate: function (e) {
              m.startComputation();
              var indexFrom = e.oldIndex;
              var indexTo = e.newIndex;
              if (indexFrom !== indexTo) {
                var movedItem = ctrl.list.splice(indexFrom, 1)[0];
                ctrl.list.splice(indexTo, 0, movedItem);
              }
              m.endComputation();
            }
          });

          ctx.onunload = sortable.destroy;
        }
      }, listItems),
      
      m('h5', 'Array'),
      m('pre', JSON.stringify(ctrl.list.map(function(i){
        return i.key;
      }), null, 2))
    ];
  }
});
```
Thank you in advance for you assistance.

**Comment by lhorie** [comment]
I'm getting a "Sortable is not defined" error in your link

**Comment by a-s-o** [comment]
Hi Leo,

Can you please try this link http://codepen.io/anon/pen/ZYyGmx

I was linking the Sortable lib directly from github. See if this one works?

**Comment by lhorie** [comment]
Yeah this is an issue. As a workaround, using an id instead of a key works.

**Comment by a-s-o** [comment]
OK, thanks for checking. If there is something I can do to help fix, please let me know (although that build function of yours is above my head at the  moment :)

**Comment by a-s-o** [comment]
The workaround works and the sorting is fixed by using id attribute.Thanks for that. However, the input tags inside the items no longer retain focus when the view re-renders.

For example, in my previous link it is possible to focus the input box once and then add multiple items by pressing enter. In this updated example (http://jsbin.com/vowuxivawe/1/edit?js,output) with id attributes, once an item is added the input box loses focus.

I know it is a bit of an edge case but I wanted to report in. I have tried various combinations of id on list items and key on input, both id and key, etc. but in some of those cases the effects get even more odd.

**Comment by lhorie** [comment]
This is fixed in origin/next and will be released in the next version.

**Comment by uxnow** [comment]
:+1:

**Comment by barneycarroll** [comment]
Excellent stuff!

**Comment by a-s-o** [comment]
Thank you Leo, appreciate the work. I will report back if I run into any problems.
