### ISSUE TITLE
Route redirect on back/forward in "pathname" mode doesn't work with query strings

### ISSUE THREAD

**Issue by bpartridge81** [lhorie/mithril.js#425]
I was trying to switch from "hash" to "pathname" mode for routing and running into an issue where mithril doesn't invoke a redirect when going back/forward and the route only differs by the query string.  I've been using query strings (e.g., "?param1=value&param2=value2") as a way to serialize state from my controllers to the URL for bookmarking.  With "hash" mode this was working perfectly.

It looks like the onpopstate callback that mithril registers doesn't consider query string differences when comparing the routes, which is the source of the problem.

I ended up working around this issue by using "search" mode instead, but it would be nice to fix this for consistency.  If I have time, I'll work on the pull request myself.

**Comment by lhorie** [comment]
Fixed in origin/next and scheduled to be released in the next version
