### ISSUE TITLE
Can't serialize `get` request that isn't jsonp

### ISSUE THREAD

**Issue by sdalezman** [lhorie/mithril.js#426]
Currently the bindData function doesn't allow you to serialize a get request that isn't jsonp

```javascript
	function bindData(xhrOptions, data, serialize) {
		if (xhrOptions.method == "GET" && xhrOptions.dataType != "jsonp") {
			var prefix = xhrOptions.url.indexOf("?") < 0 ? "?" : "&";
			var querystring = buildQueryString(data);
			xhrOptions.url = xhrOptions.url + (querystring ? prefix + querystring : "")
		}
		else xhrOptions.data = serialize(data);
		return xhrOptions
	}
```

I need to serialize the data that I am passing to `m.request` on a get request, because the data can have values that are lists. i.e. the data object:
```
{
  page: 0,
  locations: [ny, nj]
}
```

The way jquery handles a data object like that is by serializing the data so that the querystring looks like `"?page=0&location=ny&location=nj"` 

We can leave the bindData function alone and instead augment `buildQueryString` to handle arrays. 

Please advise on the best approach moving forward.

**Comment by lhorie** [comment]
This is fixed in origin/next and will land in the next release
