### ISSUE TITLE
Template compiler macro doesn't work with Browserify

### ISSUE THREAD

**Issue by liamcurry** [lhorie/mithril.js#427]
The sweet.js [template compiler](http://lhorie.github.io/mithril/optimizing-performance.html) doesn't seem to work with browserify.

Examples:

```js
// source.js
// note that we are not requiring mithril here
var view = function() {
    return m("a", {href: "http://google.com"}, "test");
}
```

Running the following comes up with the expected output:

```
browserify source.js > bundle.js
sjs -r -m ./template-compiler.sjs -o sweetened.js bundle.js
```

However as soon as we `require('mithril')` the template compiler stops working:
```js
// source.js
var m = require('mithril');
var view = function() {
    return m("a", {href: "http://google.com"}, "test");
}
```

(Omitted the browserify outputs for brevity)

**Comment by jrvidal** [comment]
I think that once a binding for `m` is introduced in a scope, sweetjs does not consider it a macro anymore.

You probably should see something like this in your output:

```
var m$123 = require('mithril');
var view = function() {
    return m$123("a", {href: "http://google.com"}, "test");
}
```

**Comment by liamcurry** [comment]
So is there any sensible way around this?

**Comment by liamcurry** [comment]
@jrvidal I confirmed your suspicions with this snippet:

```js
var m = function () {};
var view = function() {
    return m("a", {href: "http://google.com"}, "test");
}
```

**Comment by jrvidal** [comment]
You could do something like:
```javascript
// app.js
global.m$ = require('m');

// view.js
var view = function() {
    return m$("a", {href: "http://google.com"}, "test");
}
```
and then modify the sweetjs macro template to redefine `m$(...)` calls instead of `m(...)` calls. In this way you introduce a very specific global only for templating purposes.

@lhorie Do you think that dropping hygiene for the `m` macro would be a good idea? I'd argue that most of the time `m` will be `require`d or similar, instead of used as a global.

**Comment by liamcurry** [comment]
That solution seems less than ideal to me. I decided to use MSX instead, and added a [pull-request to pre-compile templates](https://github.com/insin/msx/pull/6).

**Comment by lhorie** [comment]
Not exactly pretty, but dropping the `var` in front of the `m = require("mithril")` woks. Unfortunately, I can't find anything in the sweet.js docs about breaking hygiene of shadowed variables.
