### ISSUE TITLE
HTML5 History

### ISSUE THREAD

**Issue by daryl** [lhorie/mithril.js#428]
I've noticed a bug(?) using `m.route` for anchors.

Let's say I'm on the page `/foo`, and I have this link on it:

```js
m('a', {href: '/foo', config: m.route}, 'Foo')
```

Every time I click that, despite already being on that page, it will push it into my browser history, so if I clicked it 5 times, I would have to go back in my history 6 times to get to the page I was on before. Ideally you'd want to prevent the history from being updated if the url is the same as the pathname.

If you'd like me to go into further detail, let me know.

**Comment by lhorie** [comment]
This is fixed and will be released on the next version
