### ISSUE TITLE
Can't express character groups in input pattern attributes

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#430]
Wondering if there might be a way around this:

```javascript
m( 'input[pattern=[a-z0-9_-]+]' )
```

Currently, `m` reads the character group's closing delimiter as the end of the attribute descriptor and gets indigestion with the rest. 
Admittedly, extending the selector parser to cater for nested Regex expressions isn't trivial :/

**Comment by lhorie** [comment]
Workaround:

```javascript
var symbol = "[a-z0-9_-]+"

m("input", {pattern: symbol})
```

**Comment by barneycarroll** [comment]
Yeah it works fine. There's no good reason to particularly want to express a pattern in the selector either – was just working with a predefined attributes object.

**Comment by barneycarroll** [comment]
Thx!
