### ISSUE TITLE
Rationale for synchronous promises

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#436]
What's the rationale for executing promises synchronously?

I'm playing about with inline module invocation (so controllers are executing during redraw) and getting thrown by controllers that call redraw when promises resolve. Non-standard usage and almost certainly doesn't deserve a 'fix', but I'm curious about the whats and wherefores of synchronicity as it relates to Mithril's various lifecycles, and specifically why Mithril mandates its own implementation of promises.

**Comment by lhorie** [comment]
The Promises/A+ spec mandate that callbacks be executed in the next event loop. In practical terms, this means use `setImmediate`. The problem with that is that neither Chrome nor Firefox teams are on board with the idea of implementing this function (which was proposed by the IE team), so it'll pretty much require a polyfill forever. The polyfill is ~6kb in size, so it'd add a relatively large weight to Mithril. The poor-man's alternative is setTimeout, but, per spec, it has to have a low bound delay of 4ms. Adding 4ms on every then callback is obviously unnacceptable.

Another reason for having a custom implementation of Promises is that error handling is not spec'd by A+ and, for practical purposes, the existing native implementations are broken.

http://lhorie.github.io/mithril/mithril.deferred.html#differences-from-promises-a-

**Comment by barneycarroll** [comment]
Sorry, it's right there in the docs – thanks for elaborating. I agree the way the native Promise spec worked out leaves a lot to be desired. Error trace mangling is tragic and I'm grateful for that deviation.

> Adding 4ms on every then callback is obviously unnacceptable

But synchronicity is a significant and qualitative functional difference, rather than a quantitative performance concern or a developer aid – and although I understand the undesirability of doubling the codebase to get this relatively incidental feature 'right', calling asynchronous code synchronously is really awkward. It's certainly not obvious to Q, or Bluebird, for instance.

Do you think we could get a (relatively) small compromise in forcing at least the first deferred resolution in any thenable is actually deferred, and then execute any subsequent chained callbacks synchronously? That could nerf the somewhat realistic concern of `this.then( that ).then( the ).then( other )` potentially skipping an animation frame… or am I missing the real worst case scenario?

**Comment by barneycarroll** [comment]
Just posting this untested WiP hack here as a gist of the compromise in mind. AFAICT it's doomed because of thennable return values, because closures.

	var ASAP = setImmediate || setTimeout;
	var mDeferred = m.deferred;
	
	function delay( callback ){
		return function capture( input ){
			var outcome = m.prop();
			
			ASAP( function apply(){
				outcome( callback( input ) );
			} );
			
			return outcome;
		};
	}
	
	m.deferred = function asyncDeferred(){
		var deferred = mDeferred();
		var mThen    = deferred.promise.then;
	
		deferred.promise.then = function asyncThen( yes, no, whatever ){
			return mThen( delay( yes ), delay( no ), delay( whatever ) );
		};
	};

**Comment by barneycarroll** [comment]
To put this in context, I'm dealing with a controller that fetches data and redraws when the data is retrieved. The data fetch interface is promised to allow asynchronous processes under the hood (which are not necessarily XHR — can come from application cache).

The controller is executing as part of a component's initialisation from being called in the view. There are mechanisms to register and instance, but the controller never returns because there's a synchronous loop in redraw > recompute view > initialise controller > redraw > ad infinitum.

I haven't had a decent look at your components branch but this situation might not be as unusual as it first seems. Right now it's a blocker for my components plugin to work with my codebase (works fine otherwise). Making promises asynchronous would solve this.

What do you think?

**Comment by lhorie** [comment]
FYI, you can get A+ compliant promises AND mithril m.prop behavior by passing a 3rd party promise to `m.prop`. Not ideal, but that would give you asynchrony.

How would you feel about an overridable asynchrony provider hook? e.g. `m.deferred.hookToMakePromisesResolveAsynchronously = setImmediate`

**Comment by barneycarroll** [comment]
Well synchronicity can result in unexpected behaviour but your rationale makes sense. The only time Mithril's own-brand promises are used under the hood is with XHR – and these will never resolve synchronously (my use case interfaced with a wrapper that used Mithril's promises to wrap what might be an XHR but might equally fetch from localStorage, and the latter case produced unexpected results). 

If asynchronicity is a real blocker for others, then they should evaluate native / 3rd party promise libraries. 

It isn't a blocker for me – the infinite redraw recursion bug is the result of a hack, which qualifies as user error (except AFAIC sub-modules not being able to dictate m.redraw.strategy is a feature, not a bug).
