### ISSUE TITLE
Issue with Mithril routing and arrays as values in params objects

### ISSUE THREAD

**Issue by sdalezman** [lhorie/mithril.js#437]
If you have params object that has a key that maps to an array and that key is subsequently not needed, mithril routing does not handle it well.

For example if you are object is:
```javascript
{
  name: 'some name',
  vals: [1, 2, 3]
}
```
and vals is deleted from the object, then mithril routing doesn't delete the query parameter from the route - in this case &vals=1&vals=2&vals=3. 

If you ensure that vals isn't deleted from the object, but set to an empty list then mithril leaves a `&=` in the route. 

It should seem that mithril routing should take into account that querystrings can constantly change throughout the state of an application and gracefully handle the query strings. 

If this is something you are open to fixing I have no problem augmenting `m.route(route, params)` to handle this use case.

**Comment by lhorie** [comment]
Can you post a jsfiddle? I'm trying this and it seems fine:

```javascript
var a = {}
a.controller = function() {
	console.log(m.route.param("a"))
	this.a = m.route.param("a")
}
a.view = function(ctrl) {
	return [
		m("p", ctrl.a),
		m("a[href='javascript:;']", {onclick: function() {m.route("/a", {a: 1, b: [1,2,3]})}}, "1"),
		m("br"),
		m("a[href='javascript:;']", {onclick: function() {m.route("/a", {a: 1, b: []})}}, "2"),
		m("br"),
		m("a[href='javascript:;']", {onclick: function() {m.route("/a", {a: 1})}}, "3"),
	]
}

m.route(document.body, "/a?a=1", {
	"/a": a
})
```

**Comment by sdalezman** [comment]
Hi Sorry I forgot I posted this - I actually submitted a merge request with a fix for this and you accepted it the other day. So this should be closed. Thanks!

**Comment by lhorie** [comment]
Oh, that fixed this too? Awesome! Thanks for that PR, btw :)

**Comment by sdalezman** [comment]
No problem! we love mithril!
