### ISSUE TITLE
bower surpport

### ISSUE THREAD

**Issue by ginus** [lhorie/mithril.js#441]
Bower [http://bower.io/] is a wanderful tool to manage javascript framework for project. This one is my first eye enjoy framework, so if it surpport bower My job will more fun!

**Comment by Jakehp** [comment]
http://bower.io/search/?q=mithril

**Comment by ginus** [comment]
Yes, I have found two repo "mithril" and "mithril.js" that "mithril.js" repo for dev and mithril repo for normal use, is it?

**Comment by Geen-Henk** [comment]
Apparently it's no longer supported. http://bower.io/search/?q=mithril returns nothing
