### ISSUE TITLE
Enhance Redraw Strategy to be Granular

### ISSUE THREAD

**Issue by lawrence-dol** [lhorie/mithril.js#442]
I've argued previously that `m.redraw.strategy` as implemented is a fundamentally broken concept, being a global flag for a non-global state.

I think that the issues encountered with the strategy in [How to mitigate infinite redraw loop] (https://github.com/lhorie/mithril.js/issues/439) and [problems in submodules] (https://groups.google.com/d/msg/mithriljs/-G5MxbBVRcI/r9lTIwTBY88J) are further evidence of that. 

It comes down to my argument that while any one part of a complex system can say "the model **has** changed and the view **must be** updated", no one part can say "the model **has not** changed and the view **need not** be updated" (where, of course, the model means any part, data or state). But the the redraw strategy flag is a global representation of the latter and as a result the last call to `m.redraw.strategy()` "wins".

I think it could work compatibly if at the completion of each logical unit of work which could affect the model (e.g. an event, subcomponent instantiation, etc) the value of `m.redraw.strategy` were reset after being applied to a single internal flag which indicated a view update is required. After rendering a view the internal flag is cleared to "none"; after completing a unit of work the flag is set if the strategy is not "none" and the *strategy* is reset to "diff". Setting would be something along the lines of:

    updateView=(updateView=="all" || strategy=="all" ? "all" : (updateView=="diff" || strategy=="diff" ? "diff" : "none"));

Thus the default for an action which does not set the strategy is still "diff", but if all actions set "none" the end-result is "none" and if any action sets other than "none" the most extensive strategy wins. In this way if any action sets "all" the view is entirely recreated; otherwise if any action sets "diff" (the default) the entire view is differentially recreated; otherwise no action required the view be updated.

This does imply a strict hierarchy between redraw strategies of all -> diff -> none. 

The remaining tricks would be to correctly determine what things constitute a separate unit of action and actually trigger the view rendering when the UI loop is over. I've done the latter like this, which would be invoked every time the internal flag was set, resulting in a redraw on the next UI loop:

    function redrawRqd() {
        if(!MithrilUtil.redrawPending) {
            MithrilUtil.redrawPending=true;
            setTimeout(function() {
                m.redraw();
                MithrilUtil.redrawPending=false;
                },20);                                                                                  // 1000/20 = 50 fps
            }
        }

**Comment by lhorie** [comment]
> while any one part of a complex system can say "the model has changed and the view must be updated", no one part can say "the model has not changed and the view need not be updated"

I'm pretty sure we already went through this, and that strategy("none") accomplishes this. Or am I missing something?

What sparked discussion re: strategy in the other threads were that @barneycarroll is using m.redraw.strategy("diff") mode in controller constructors, which changes the way lifecycles work. The problem can be summarized as this:

1 - it's not possible to NOT redraw something from scratch when strategy is all
2 - it's troublesome to redraw from scratch when strategy is diff

Problem 1 is bad if you want to keep an expensive thing lying around across redraws. Changing strategy to diff is the only workaround, but then you open yourself up to Problem 2.
Problem 2 is bad because it can potentially make unloading of things not happen when you expect them to. This can be worked around w/ setting id's, but as I mentioned, it can be troublesome.

Related problems: deferring redraws is NOT a potential solution because it opens other cans of worms related to the browser event loop and events getting lost.

**Comment by lawrence-dol** [comment]
@lhorie,

> Or am I missing something?

In the context of submodules, as they emerge, and possibly with subcontrollers as they now exist, maybe you are.

If one sub-something sets strategy X and another sets strategy Y, the last one to call `m.redraw.strategy` wins; the currently global conceptualization of the strategy makes it difficult for discrete things to independently interact with Mithril. As would be true for any global flag.

I fear you've band-aided the use of the strategy in a way that doesn't really solve the problem, but resolves the current symptoms, and I wonder if other edge-cases are coming out of the woodwork as a result. I was never convinced that the current implementation can possibly be correct for a modularized system (meaning truly separate independent modules participating in the application, with a "dashboard" as the quintessential example).

But I don't want to involve you in a debate, so much as to raise an idea that ensures a redraw strategy works by design rather than by accident.

**Comment by barneycarroll** [comment]
Hey @lawrence-dol check out #409 — we're coming at it from slightly different angles but root problem is the same.

**Comment by lawrence-dol** [comment]
@barneycarroll,

Yeah, same problem, different solution. I'm proposing a middle ground between flexibility and complexity.

Essentially the solution here proposed is within the current GUI loop, if anything sets "all" the entire view is reconstructed, *otherwise* if anything sets "diff", the view is differenced, *otherwise* nothing is done (because nothing happened which affected the view).

@lhorie,

> deferring redraws is NOT a potential solution because it opens other cans of worms related to the browser event loop and events getting lost.

Realizing that you may considered this a "over and done with issue", it would be helpful if you can in some way explicate the problem in concrete terms. Is it because the GUI event queue will drop events for DOM elements that are no longer part of the tree such that there's a race condition between triggering an event and ... what?

Responding, "please just take my word for it, I am absolutely certain" is a perfectly valid, only despite nearly a decade in writing and supporting my own GUI toolkit, which of course had to deal with the intricacies of event control and handling, I fail to envisage how events could be *lost* (how extraneous events are received for elements that are momentarily about to be removed, sure, but not lost).

**Comment by lhorie** [comment]
@lawrence-dol the is the issue I'm referring to is this one: #214

**Comment by lawrence-dol** [comment]
@lhorie,

I think I basically understand the problem. I suggest that, at it's core, the issue may have been more a problem of recreating an input field because it's value changed instead of the diff'ing recognizing that a change in value for an input field does not warrant recreating the element... but that area does seem like a potential can of worms.

Ideally, at the conclusion of an event Mithril should redraw inline, but only after all handlers have been run and then using the strategy, merged along the lines of what this issue suggests. Though this might already be true, though my impression is that every handler that doesn't set "none" causes a redraw such that if 7 handlers run 7 redraws will be done.

Dropping the suggestion of triggering an async redraw on the next event loop (which by the way has been working flawlessly for me with complex filtering as described by #214), the overall issue remains valid, in my opinion, though it might not be worth the effort. 

Async redrawing may be working for me because I suppress redraw on all input events, knowing that the input element has already been updated by the UI.

**Comment by lhorie** [comment]
FYI, I'm going to close this thread, since the solution is essentially the same thing as #409
