### ISSUE TITLE
Bug? When the first of `children` is an array, the latter are ignored.

### ISSUE THREAD

**Issue by tomekwi** [lhorie/mithril.js#443]
```javascript
m("", "a", ["b", "c"]).children
// » ["a", ["b", "c"]]

m("", ["a", "b"], "c").children
// » ["a", "b"]
```

Not sure if that's the expected behaviour. From the [signature](http://lhorie.github.io/mithril/mithril.html#signature) I understand that children can be listed in any order – whether they are arrays, strings or other stuff.

**Comment by barneycarroll** [comment]
I've come across this before. Because the structure is a matter of developer convenience rather than something which impacts on the desired eventual DOM structure, I think the ideal solution is to slice the children attributes and flatten them completely.

**Comment by webcss** [comment]
Children need to be wrapped in an array, like so:
m("", **[**, "a", ["b", "c"]**]**) => [ "a", ["b", "c"] ]
m("", **[**["a", "b"], "c"**]**) => [ ["a", "b"], "c" ]
and first param to m needs to be a css-style-selector, but at least an empty string, which defaults to <div> then.

**Comment by tomekwi** [comment]
@webcss, according to the [signature of m()](http://lhorie.github.io/mithril/mithril.html#signature) and my experience you don't need to wrap children in an array. So this works and should be perfectly valid:

```js
m(".a", child1, child2, child3);
```

Each `childN` can then be a Mithril view, a string, a SubtreeDirective or an array of children.

**Comment by webcss** [comment]
OK, to be on the save side you should wrap children into an array. But you are right, it's a bug. 
m checks for arg[1] to be an object and if not, it assumes arg[1] to be children. However, it doesn't slice the rest but takes args[1] as children and test for this beeing an array type. That's why your second example (array first) doesn't work as expsected.
