### ISSUE TITLE
bug in flatten array code of build function

### ISSUE THREAD

**Issue by kavaro** [lhorie/mithril.js#448]
While reviewing the mithril code, I believe to have encountered a bug in the mithril build function (diff/key alg).

If the data arg of the build function is an array, then the array needs to to be recursively flattened before entering the array diff algorithm (including keys alg). The current implementation (see below):
```
for (var i = 0, len = data.length; i < len; i++) {
				if (type.call(data[i]) === ARRAY) {
					data = data.concat.apply([], data);
					i-- //check current index again and flatten until there are no more nested arrays at that index
				}
			}
```
transforms
```
['a', ['b', ['c']]] into [ 'a', 'b', [ 'c' ] ] instead of [ 'a', 'b', 'c'  ]
```
because the temporary 'len' variable is not updated to the new length of the concatenated data array.
The bug only surfaces in a very specific edge case where an array that is nested at least multiple levels down increases the length of the final concatenated array. It appears to me that this may lead to very strange/inconsistent behavior of the array/key diff algorithm.

The issue can be fixed by adding one line of code (see below):
```
for (var i = 0, len = data.length; i < len; i++) {
				if (type.call(data[i]) === ARRAY) {
					data = data.concat.apply([], data);
					i-- //check current index again and flatten until there are no more nested arrays at that index
                    len = data.length; // THIS LINE WAS ADDED
				}
			}
```

**Comment by inta** [comment]
Or simply remove these unused var and check for "i < data.length" :)

(Though I only read this ticket and did not check the issue.)

**Comment by vivekimsit** [comment]
No, doing data.length is not a good idea. It will need to access length
property in each iteration.

**Comment by hurelu** [comment]
Not really. All modern browsers optimise the the loops and cash the .length
property. There are numerous jsperf tests showing this. Having temp data to
store the length used to be marginally faster, now it is actually slower.

**Comment by lhorie** [comment]
Fixed in origin/next and scheduled to be released in the next version
