### ISSUE TITLE
route replace

### ISSUE THREAD

**Issue by konsumer** [lhorie/mithril.js#449]
I am using `m.route.mode = 'pathname';` and I'd like to be able to replace a route in History, rather than just redirect & add it to the list, like react-router's `Router.replaceWith`

For example:

- I have [this page controller](https://github.com/konsumer/mithril-quickstart/blob/master/client/js/pages/Login.js)
- when a user gets auth-denied in an AJAX call, they get kicked to login form which remembers the route they came from
- After successful login, they get kicked to whatever route they were after or '/' (`m.route(Auth.originalRoute || '/');`)
- It'd be neat to be able to remove login from history (or rather, replace it with the next route) so they hit back and they just go to the page they were at before the login.

I'd be happy to implement if this is a feature others want.

**Comment by lhorie** [comment]
This actually exists for internal purposes, but I had not documented as a public API: `m.route(path, [args], [shouldReplaceHistory=false])`. So basically, just add a `true` as the last parameter to the m.route call.

Sounds like this is useful outside of core, so I'll update the docs.

**Comment by konsumer** [comment]
Sweet! Thanks so much.
