### ISSUE TITLE
mithril-modal and  m.redraw.strategy("none")

### ISSUE THREAD

**Issue by saniko** [lhorie/mithril.js#450]
Hi, I'm using Leo's modal  module:
https://github.com/HumanDesign/mithril-modal

If the modal view contains "input" field for instance ,each click causes redraw as it should.
The problem is that i must call "e.stopPropagation()",  m.redraw.strategy("none") still causes redraw and closing the modal. on input click

best

**Comment by TheThing** [comment]
This is explained pretty well here: http://lhorie.github.io/mithril/mithril.redraw.html#strategy

> Lastly, be aware that if a user action triggers more than one event handler (for example, oninput and  onkeypress, or an event bubbling up to event handlers in multiple ancestor elements), every event  triggers a redraw by default. Setting strategy to none in any one of those handlers will not affect the  redrawing strategy of other handlers (and remember that strategy("none") has no effect on asynchronous redraws).

**Comment by saniko** [comment]
10x
