### ISSUE TITLE
m.trust is broken for HTML character references 

### ISSUE THREAD

**Issue by sdalezman** [lhorie/mithril.js#453]
m.trust() is broken for HTML character references (e.g. &apos;), but it works for html. 

Please see the following [jsfiddle](http://jsfiddle.net/sdalezman/bh7jur91/1/).

I haven't been trying to identify the issue in mithril.js, but I haven't been able to find it. I am fairly confident  that m.trust was working as of early last week.

**Comment by lhorie** [comment]
This is fixed in origin/next and will be released in the next version
