### ISSUE TITLE
duplicated content on tab switch

### ISSUE THREAD

**Issue by saniko** [lhorie/mithril.js#456]
Hi, can someone please explain why I'm getting this behavior?
I'm using an external "circle progress" plugin in a tab view, the plugin activates 
on the last tab (tab C). the problem is when i switch between tabs and go back to "tab c", the content created by the plugin is getting duplicated.

please check the following fiddle:
http://jsfiddle.net/96356ngx/6/

How can i prevent this?

Thanks

**Comment by barneycarroll** [comment]
You're calling your plugin every time the application redraws instead of just once.

```Javascript
function(element,isInitialized) {
	if( !isInitialized ) $(element).percentcircle();
}
```

**Comment by saniko** [comment]
Hi, i actually use several instances of the plugin in my tab,
if i use the isInitialized, the progress circle "runs" once, i want that each time you open the tab, the circle progress will start.
http://jsfiddle.net/96356ngx/9/

thanks

**Comment by barneycarroll** [comment]
I see. In that case you probably want to teardown any prior DOM before initialisation:

```javascript
function(element) {
	$(element).empty().percentcircle();
}
```

Notice I took out all mention of `isInitialized`: when you give names to references you don't intend to use it looks like they haven't been invoked by accident.

**Comment by saniko** [comment]
Thanks
