### ISSUE TITLE
documentation: wrong output

### ISSUE THREAD

**Issue by StreetStrider** [lhorie/mithril.js#458]
Hi.
http://lhorie.github.io/mithril/routing.html page, says:
```javascript
    view: function(controller) {
        return m("div", controller.id);
    }
```
However, the output is printed like that:
```html
<body>johndoe</body>
```
instead of
```html
<body><div>johndoe</div></body>
```
looks like a bug. That `div` must be injected to `body` and not its content?

**Comment by lhorie** [comment]
Thanks for the catch. I'll push a fix with the next release
