### ISSUE TITLE
Logic fork for element attributes with boolean values

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#461]
I have the following code, which I expect to work intuitively:

```javascript
m( 'button', {
  disabled : ctrl.isValid(),
  onclick  : ctrl.submit
}, 'Go' )
```

Produces:

```html
<button disabled="false">Go</button>
```

In current Mithril, a value of `false` is coerced to string and used as the value for the `disabled` attribute, which is not the intended result. In DOM, boolean attributes are considered truthy by their presence, which means my button is always disabled in practical terms (and its `onclick` handler never triggers). To get the results I expect I need some cumbersome intermediary steps:

```javascript
var attrs = {
  onclick : ctrl.submit
}

if( ctrl.isValid() ) attrs.disabled = true;

m( 'button', attrs, 'Go' )
```

[According to the HTML4 spec](http://www.w3.org/TR/html4/intro/sgmltut.html#h-3.3.4.2) (I couldn't find anything more recent that treated boolean DOM attributes in as much detail) says:

> Some attributes play the role of boolean variables (e.g., the selected attribute for the OPTION element). Their appearance in the start tag of an element implies that the value of the attribute is "true". Their absence implies a value of "false".

Therefore I propose a further fork in the attribute mutation logic for the case of boolean values:

```javascript
if( typeof dataAttr === 'boolean' ){
  if( dataAttr ){
    node.setAttribute( attrName, attrName );
  }
  else {
    node.removeAttribute( attrName );
  }
}
```

There some arguable potential for dissonance, because the HTML5 spec highlights some attributes like [`contentEditable`](http://www.w3.org/TR/html5/editing.html#attr-contenteditable) which can take multiple values that look like booleans, but are in fact strings, two possible values of which are `"true"` and `"false"`. For those instances I believe it's fair enough to expect the author to specify string values for the attribute.

**Comment by lhorie** [comment]
I tried your first snippet and it seems to work: http://jsfiddle.net/zwkvznak/2/

Can you post a jsfiddle showing the issue?

**Comment by barneycarroll** [comment]
Confirm fixed! [Test case here](http://jsbin.com/kevuka/2/edit?html,js,output). Thanks @lhorie, sorry for drifting.

**Comment by barneycarroll** [comment]
I thought I'd just add this here because I keep mis-identifying this bug and coming back to this issue. To try and test for regression.

Only form elements can be disabled. `disabled` on any other kind of element (including `a`) is an unknown property and so gets set as a dumb DOM attribute rather than a DOM property, which is the desired behaviour which translates to native functionality effects.
