### ISSUE TITLE
polyfill.io link

### ISSUE THREAD

**Issue by jsguy** [lhorie/mithril.js#462]
Apologies if this is not the right place to raise this, but the polyfill.io link on this page:

http://lhorie.github.io/mithril/tools.html#internet-explorer-compatibility

No longer seems to work, and the html5 shim is rather large (~14kb) - I had a play around with the polyfill.io parameters, I think the link should be changed to:

http://cdn.polyfill.io/v1/polyfill.min.js?features=Array.prototype.indexOf,Object.keys,Function.prototype.bind,Array.prototype.forEach,JSON

I've created a gist here (~4kb):

https://gist.github.com/jsguy/edc7e51ae56e0ab37a5c

That can be used until the polyfill.io link is fixed, in case anyone is desperate :)

**Comment by barneycarroll** [comment]
Well noticed, @jsguy! Are you using polyfill.io yourself? I was really impressed by how ingenious the idea was, but could never bring myself to use it in practice — let alone attempt to qualify it's measurable usefulness.

**Comment by jsguy** [comment]
@barneycarroll I don't actually - I needed to support IE8 on one of my projects, so started looking for a solution - polyfill.io looks like a nice idea - though it's a shame they have backwards-breaking API changes, as I can imagine people just plonk in the URL, and forget about it... At least they now have a version in the URL, so that hopefully it shouldn't break again.

**Comment by lhorie** [comment]
I updated the polyfill.io link in the docs. This change will be up w/ the next release
