### ISSUE TITLE
enhance mock.js for test and server render?

### ISSUE THREAD

**Issue by ginus** [lhorie/mithril.js#464]
I image a futher mithril maybe client core + server mock(middleware core). In browser side client core + app code like before(maybe DI should use). Client code build should keep orign way allow gulp, grunt and other tools deal with. So server render only care about html rendered by mithril it self, now test/mock.js is there we can reuse it. In server side we use mock top of client core ,because of its render method rewrited fit for node enviverment. That is all my idea. I like mithril and learn it every day even english is some barriers for a chinese.

**Comment by lhorie** [comment]
If you're interested in isomorphic Mithril, take a look at https://github.com/jsguy/misojs

I believe it's the most comprehensive isomorphism project for Mithril around.
