### ISSUE TITLE
Gitter chat

### ISSUE THREAD

**Issue by StephanHoyer** [lhorie/mithril.js#467]
I use https://gitter.im as chat for my public github repos.

Maybe that's also an option for mithril.

I'm online most of the times, so I can maintain that half a day. Since the barriers to entry is pretty low (you just open a link in the browser) it's pretty helpful especially for newbies.

**Comment by lhorie** [comment]
There's an IRC channel at freenode ( #mithriljs ). A bunch of people hang out there. Is there a way to integrate the two?

**Comment by StephanHoyer** [comment]
quick google: https://irc.gitter.im/

no experiences with this.

**Comment by StephanHoyer** [comment]
sorry... that's only a possibility to connect to gitter with irc client.

Will do further search ;)

**Comment by StephanHoyer** [comment]
I think tight integration of both is not possible. With the upper service you can connect your IRC client with the gitter chat but there will still be two chat rooms (freenode/gitter).

**Comment by oren** [comment]
@StephanHoyer freenode on irc have a website as well: http://webchat.freenode.net/?channels=mithriljs
@lhorie maybe it will be a good idea to add this url to http://lhorie.github.io/mithril/community.html for those who never used irc and don't know about other irc clients.

**Comment by darsain** [comment]
I've actually send a feature request to allow pointing gitter rooms to already existing channels on freenode, and this was the response:

---

Hey there,

This is something we talk about a lot internally. There are some obvious identity and experience challenges.

One of our users built a bot that basically talks between a Gitter room and an IRC room and, unless everyone on Gitter had a freenode identity is somewhat like how the experience would probably end up if we did it natively. 
https://github.com/finnp/gitter-irc-bot

Would love to get your feedback if you're able to try it and see how it works for you.

**Comment by lhorie** [comment]
@oren I have the link to webchat there already, but I didn't know you could pass the channel as a querystring param. That's handy!

@StephanHoyer having two chat rooms sounds workable (just use the freenode one and ignore the other one). I haven't used gitter before, though. Can you think of any issues that would arise from that setup?

**Comment by StephanHoyer** [comment]
@lhorie two chats can lead to fragmentation. 

But we can give it a try. Maybe the IRC for core stuff and Gitter for Newbies.

**Comment by lhorie** [comment]
For the record, the gitter chat room is here: https://gitter.im/lhorie/mithril.js
