### ISSUE TITLE
 translate docs to chinese,how to start?

### ISSUE THREAD

**Issue by ginus** [lhorie/mithril.js#470]
I love this framework, so I want to introduce it to the my friends, and a bit barriers is they are not good at english, so I have to traslate it to chinese.
Now, I want more, I hope my translation can be read by any chinese who like this, how to achieve it?

**Comment by lhorie** [comment]
The docs are generated from [these markdown files](https://github.com/lhorie/mithril.js/tree/next/docs). If you want to submit a pull request to adding docs in chinese, I'd be happy to accept. The thing is that you'd need to maintain them as the docs get improved. Another (possibly expensive) option would be to fund the effort via donations and get a professional translator to do it.

A more feasible option would be for you to write tutorial articles in chinese on your own, covering the important topics. Porting Angular's phonecat tutorial might be a good way to cover a lot of the bases.

**Comment by ginus** [comment]
I choose first way that makes me follow your mind.
