### ISSUE TITLE
Strange mutating intermitent bug.

### ISSUE THREAD

**Issue by ThePanuto** [lhorie/mithril.js#475]
Hello.

I've decided to use Mithril in the application I'm currently developing. But I have this annoying and strange bug happening...

I created a repo to show the bug [here](https://github.com/thepanuto/strange-heisenbug).
Well, basically, sometimes, when accessing the `user` in the `sessionStorage`, it returns undefined, and breaks the code.
On the majority of times, it works as expected. I simply have NO IDEA what's causing it, but maybe it's something I screwed up. I just can't see where.

On the other hand, it could be a Mithril issue. Although I'm higly confident that it's not.

Thanks in advance, guys.

**Comment by ThePanuto** [comment]
Sorry for the ninja comments

**Comment by lhorie** [comment]
Hi @ThePanuto 

The readme says to start mongo on the data folder but I don't see a data folder. I tried logging in and got an "incorrect user" error. Does the login need to succeed in order for me to be able to see the bug?

**Comment by ThePanuto** [comment]
Hi @lhorie 

Sorry about that. Please, create the data/ folder in the root, and initialize mongo.
You can create a user by posting to /api/login and providing username, password, typeid and typename as arguments.

![captura de tela de 2015-03-05 23 42 01](https://cloud.githubusercontent.com/assets/5007727/6519337/52957cec-c391-11e4-83d0-e02ebd77274d.png)

That's a print of the bug.

Thanks for the feedback!

**Comment by ThePanuto** [comment]
btw, sorry about the portuguese stuff

**Comment by ThePanuto** [comment]
The error happens at public/js/modules/main-page.js, when I try to get the 'user' from sessionStorage. Might also wanna take a look at public/js/modules/views/login.js, that's where the login lives.

**Comment by ThePanuto** [comment]
Maybe requireJS is caching session.js?

**Comment by lhorie** [comment]
One thing that looks weird is in modules/views/login.js here: https://github.com/ThePanuto/strange-heisenbug/blob/master/public/js/modules/views/login.js#L30

That redraw happens before the only session.set call in the codebase, so if the session doesn't have a username, then session.get("username") would return undefined. You could either remove that redraw call, or set the session username to something first, or add a test for undefined in the main-page.js view

**Comment by ThePanuto** [comment]
Yes, that redraw call is ugly indeed. My intent was to show a message while the request is crunching the password hash on the server. It got buggy with the 'background' option to m.request. But maybe I should follow [this article](http://lhorie.github.io/mithril- blog/wait-for-it.html) to set that up.
