### ISSUE TITLE
Potential error in the code

### ISSUE THREAD

**Issue by venning** [lhorie/mithril.js#476]
Unless there's something subtle I don't understand about `Object.prototype.toString`, it looks like [line #288](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L288) contains an error.  The line reads:
```javascript
else if (typeof dataType != FUNCTION) {
```
but I'm assuming it should be
```javascript
else if (dataType !== "[object Function]") {
```
Is that right?

Reasoning:
* `dataType` was the result of `{}.toString.call(data)` which should mean that `typeof dataType` is always `"string"`
* `FUNCTION` equals `"function"` and is used differently than the other type checks, with actual `typeof` calls, so `"[object Function]"` would be required
* identity checks were used elsewhere in that if/else block, so I switched from the equality check

I'm assuming that `data` is rarely a function and that's why this wasn't caught, since the clause is always true right now.

**Comment by geekrelief** [comment]
The value of FUNCTION is defined as "function".  Though, I'm not sure it isn't "[object Function]" as you would assume.

**Comment by lhorie** [comment]
Fixed in origin/next

**Comment by venning** [comment]
Awesome.  Love Mithril, by the way.
