### ISSUE TITLE
m.route on element not working

### ISSUE THREAD

**Issue by mglazer-cengage** [lhorie/mithril.js#478]
I am trying to load routes in an element not the body.

http://jsbin.com/bihufopeni/edit

Note that the demo nav does get called but then the default (welcome) is called and overwrites it.

if I toggle the welcome to not display when demo called then blank is returned.

Any help or insight would be appreciated, thank you.

**Comment by barneycarroll** [comment]
The core problem with the jsbin is that `m.route` is not dynamic – it should be used instead of `m.module` to initialise your application.

Another few things:
* Rather than explicitly invoking `m.route` in an `onclick` handler, you can use `href : "/url"` and `config : m.route` for a more idiomatic way to implement links.
* There's a mysterious `call` property which was being called on the `.nav` element. Since this isn't part of the DOM API, I assume you forgot to set it on the `app` or `ctrl`.

[Here's a fork of your bin](http://jsbin.com/cisiha/2/) that tries to implement the points above.

**Comment by mglazer-cengage** [comment]
Thanks for your feedback

I was hoping the m.route was dynamic and could be attached to any element like with components.

My use case is to simply to have one part of the view (an element) change on route instead of the entire document.body but for a unique url, so can be refreshed, bookmarked at same point.

Thanks again

**Comment by barneycarroll** [comment]
`m.route` is effectively a way of pointing your app to different pages. In the example I forked, the same view is used for each route – only one element's text changes. So the pages are the same, except for that one bit. If you don't know what the routes are at initialisation time, you can use a route argument.

[Here's another example of more advanced `m.route` usage](http://jsbin.com/cisiha/3/edit). Here, the `m.route` initialisation doesn't know about any of the specifics, so it's effectively dynamic. Then, when any route change occurs, the controller looks up the current route in a map to get data out of it (in practice, you could add to that map over the course of the app lifecycle). Would that help? Don't hesitate to describe your requirements in more detail – I've done quite a lot of stuff with Mithril route so I'd be interested to see if we can address your scenario.

**Comment by mglazer-cengage** [comment]
Thanks! that did help a lot, i think i'm heading the right way now!

One last bother though I can't seem to get a programmatic route to work.

I've got a select menu not a href that onchange I map it to a route

 return m('select', {onchange: function () {
            m.route(actionMap[this.selectedIndex].link)
        }},[
            actionMap.map(function(d, i){
                return m('option', {config: m.route, value : i, innerHTML : d.text })
            })
        ])

I can see that in your above example it is being called just not rendered:

console.log(m.route.param( "key" ) )

**Comment by barneycarroll** [comment]
Not sure – tried cleaning things up a bit here and [it seems to work](http://jsbin.com/cisiha/4/edit) (`config : m.route` only works on links BTW).

Using the `innerHTML` property is really neat – there are plenty of times the view template just looks a bit weird when the text content is so disconnected from the tagname and attributes. Nice trick!
