### ISSUE TITLE
promise.then( m.redraw ) doesn't trigger

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#479]
I'm having difficulty reproducing a rather odd bug. I'm using background m.requests throughout my application. For ages I've been trying to track down a bug whereby the interface was always one redraw behind WRT sequentially loaded data. I managed to eliminate it by replacing instances of:

    var x = m.request();

    x.then( redraw );

…with:

    var x = m.request();

    x.then( function(){
      m.redraw();
    } );

The above is an oversimplification – I'm using wrapper interfaces to retrieve the relevant thennables – and if I try to reproduce the bug with m.deferreds it's a non-issue ([I would expect this to fail to redraw after the timeout, but it doesn't](http://jsbin.com/xezixi/1/edit?js,console,output)).

Any ideas, anyone?

**Comment by hurelu** [comment]
Could it be that in the unwrapped version, the promise passes an unexpected
parameter to the redraw function?

**Comment by barneycarroll** [comment]
Well, the code for `m.redraw` looks pretty safe – if `force === true` then it does a forced redraw but anything else should be fine. I'm wondering if `then` can behave weirdly depending on arguments passed to it – but the promises code is really difficult to follow!

**Comment by lhorie** [comment]
as far as I know, the only "weird" behavior in promise callbacks is that it handles returned promises slightly different than regular values (i.e. if the returned promise is rejected, then the downstream also gets rejected)

**Comment by barneycarroll** [comment]
Right – my case always failed in passed situations. I can only assume the intermediary interfaces aren't facading `then` properly. I'll close this until I can isolate the issue.
