### ISSUE TITLE
m.request with fake data

### ISSUE THREAD

**Issue by stumpdk** [lhorie/mithril.js#484]
According to threads on stackoverflow, it is possible to test m.request behavior using the mithril mock object created here: https://github.com/lhorie/mithril.js/blob/next/tests/mock.js.

But is it possible to create a mock object for which it is possible to create fake data, like this:
m.request.on({method: 'get', url: '/test'}, function(){ return {test: "this is test data for a given request"}});

I have tried to mock the request by injecting request objects into the constructor of my models, and then, when testing, injecting a mock object, responding on given requests by returning data. But if this is to work, the mock object should return promises, this being a larger task to implement while testing.

Or is this already possible?

**Comment by lhorie** [comment]
In the test suite, there are [some examples](https://github.com/lhorie/mithril.js/blob/next/tests/mithril-tests.js#L2307-L2478) of tests.

The mock xhr object used by the test suite simply [uses itself JSON.stringify'ed as the responseText](https://github.com/lhorie/mithril.js/blob/next/tests/mock.js#L150). You can get a handle to that object via `var xhr = mock.XMLHttpRequest.$instances.pop()` and add your own properties to it.

You can also fork mock.js and change `.send` to read from a cleaner object than `this`, e.g.

```javascript
//in mock.js (line 149)
this.send = function() {
	this.responseText = JSON.stringify(this.data || {}) //changed `this` to `this.data`
	this.readyState = 4
	this.status = 200
	request.$instances.push(this)
}

//in your tests
var prop = m.request({method: "GET", url: "test"})

var xhr = mock.XMLHttpRequest.$instances.pop()
xhr.data = {my: "data"} //populate mock response object
xhr.onreadystatechange()

assert(prop().my == "data")
//or
prop.then(function(response) {
  assert(response.my == "data")
})
```

**Comment by stumpdk** [comment]
Thank you so much for your reply!
And thank you for the expanded test examples. I'll try it right away.
,
Maybe you use the examples in the Mithrill.js documentation? (which by the way is VERY impressive. I've read a lot of framework documentation. The Mithrill.js documentation is my favorite! :) )

**Comment by stumpdk** [comment]
Okay, now I have worked some more with tests of requests (and I have implemented your suggestion JSON.stringify(this.data || {}); ).

But a new problem arises: I want to test a method that runs m.request, like this:

            var prop = m.request({method: "GET", url: "", dataType: "jsonp"});

            var xhr = mock.XMLHttpRequest.$instances.pop();

            xhr.data = [{value1: "test1"}, {value2: "test2"}]; //populate mock response object
            
            myObject.doJSONPRequestAndManipulateData(); //A method that runs a request with dataType: "jsonp"
            xhr.onreadystatechange();
        
            expect(myObject.convertedValues).toEqual(["test1", "test2"]);

When I run this, I get the following exception:

TypeError: Cannot read property 'appendChild' of undefined
at ajax (mithril.js:968)
at Function.m.request (mithril.js:1049)
    
Now, if I change my internal request so that it doesn't use dataType : JSONP, everything works fine.
Is this because the matcher method doesn't take into account the extra "&callback=mithrillxxxxxx"?

**Comment by tombh** [comment]
@lhorie I don't quite understand your example. From looking at mock.js it would seem to me that the best way to mock a response is like so;

```js
xhr = mock.XMLHttpRequest.$instances.pop()
xhr.responseText = JSON.stringify({ my: 'data })
xhr.onreadystatechange()
```
