### ISSUE TITLE
How to set focus after redraw?

### ISSUE THREAD

**Issue by newlix** [lhorie/mithril.js#488]
I am implementing an inline editing. After double clicking the text, mithril will redraw it to an input box and I want set focus to the input box.
The problems are 
1. How can I know the redraw process is done then I can call focus on the input?
2. How can I get the reference of the input box?

Here is a short jsfiddle:
http://jsfiddle.net/newlix/84z7kbk5/

In React I can do with the following code
```javascript
this.setState({editing:true},function(){
      var node = this.refs.input.getDOMNode();
      node.focus();
}.bind(this));
```
The second parameter is a callback function that will be executed once setState is completed and the component is re-rendered.

**Comment by Bondifrench** [comment]
Did you check the TodoMVC with Mithril?
This is how they did it: 
https://github.com/tastejs/todomvc/blob/gh-pages/examples/mithril/js/views/main-view.js#L64
You need to use `config` http://lhorie.github.io/mithril/mithril.redraw.html#changing-redraw-strategy

**Comment by newlix** [comment]
Thank you!

**Comment by derMart** [comment]
though this is very old, I am having the same issue.
Is this config property deprecated? Or does it just work inside TodoMVC?
Does not seem to do anything in vanilla mithril v2 where I need a solution for...

**Comment by fuzetsu** [comment]
@derMart 

`config` was replaced a long time ago by a series of [lifecycle methods](https://mithril.js.org/lifecycle-methods.html).

You likely want [`oncreate`](https://mithril.js.org/lifecycle-methods.html#oncreate)

Which would allow you to get a reference to the DOM node once it is created.

```js
m('input', { oncreate: ({dom}) => dom.focus() })
```

You could also store the reference to the dom node instead of calling it on the spot and use it later for focusing it under different conditions if necessary.

**Comment by osban** [comment]
@derMart as @fuzetsu said, you need to use the lifecycles. If you want to get the input after double-click, then you can use `onupdate: ({dom}) => dom.focus()`, as I you can see [here](https://tinyurl.com/yc2wovwr) in my version of the TodoMVC.

**Comment by derMart** [comment]
thnx alot, yes, both are elegant solutions.

**Comment by isiahmeadows** [comment]
And for future reference, please file new issues with these kinds of questions.
