### ISSUE TITLE
m.request throws errors on 401

### ISSUE THREAD

**Issue by calvinfroedge** [lhorie/mithril.js#496]
Line 992 of mithril.js is throwing an error for me on a generic 401:

`var response = unwrap(deserialize(extract(e.target, xhrOptions)));`

Here are the response headers:

```
Connection:keep-alive
Content-Length:35
Content-Type:text/html; charset=utf-8
Date:Wed, 18 Mar 2015 19:08:21 GMT
X-Powered-By:Express
```

Status code is `401` and the response is plain text.

**Comment by lhorie** [comment]
If the response is ever not JSON (and not an empty string), it needs to be handled via the [`extract` callback](http://lhorie.github.io/mithril/mithril.request.html#extracting-metadata-from-the-response)
