### ISSUE TITLE
Separate m.module into two separate functions

### ISSUE THREAD

**Issue by mindeavor** [lhorie/mithril.js#498]
Separate the DOM-mounting funcitonality of `m.module` into a new function, `m.mount`.

> Overloading is sometimes highly beneficial in reducing cognitive load in the API when closely related concepts are exposed (and m(...) is a great example), but in the case of m.module two different concepts are exposed through one name and that seems a mistake to me.
[source](https://github.com/lhorie/mithril.js/issues/413#issuecomment-83125450)

This will cleanly separate two responsibilities: creating a Mithril component, and mounting a component to the DOM.

As a side benefit, it will make it easier to [rename m.module to m.component](https://github.com/lhorie/mithril.js/issues/497).

Code examples:

```javascript
// "Preloading" a component
var Bar = m.component(Foo, {arg: "baz"})
m.mount(document.body, Bar)
// ----
m.mount(document.body, m.component(Foo))
m.mount(document.body, Foo) // shorthand
// ----
m.mount(document.body, m.component(Foo, { another: "arg" }))
m.mount(document.body, Foo, { another: "arg" }) // again, shorthand

// Preloading with routes
m.route(document.body, "/", {
  "/": m.component(Foo, {arg: "bar"})
})

// Within a view
App = {}
App.view = function (ctrl) {
  return m('.app', [
    m('h2', "Please fill out your information:"),
    m.component(VolunteerForm)
  ])
}

m.mount(document.body, App)
```

**Comment by lawrence-dol** [comment]
This has my very strong vote.

And I'll reiterate my comment to @lhorie from another thread -- I would personally prefer to see breaking changes land in 0.x releases, and a one or two at a time as they become clearly correct. Dropping in a new release and needing to make pervasive unrelated changes is less good, in my experience. Let version 1.0 change the focus to stability.

**Comment by tivac** [comment]
I'm totally ambivalent on this change. I don't mind the overloading and appreciate a small API surface but separating things out for clarity probably wouldn't harm things.

**Comment by Naddiseo** [comment]
+1 for what @markmarijnissen said in #497: using m.mount and m.component makes things conceptually clearer. To me at least, a 'module' is composed of components, and more akin to a library/package; so you could have a "forms" module/package/library made up of multiple `component` widgets that you `mount` on dom nodes.

**Comment by webcss** [comment]
I would still like to see Mithril having some sort of component registry, because it would avoid having components scattered around as var statements and would allow for seamless and consistent view building. 
´´´
// component declaration
m.component('Tabset', {
    controller: function(args) {},
    view: function(ctrl, args) {}
});

// usage in code:
var App = {
   controller: function(args) {...},
   view: function(ctrl, args) {
      return m('.page',
          m('header', 'AppTitle'),
          m('Tabset', [
                 m('Tab', { title: 'tab1' }, [contents]),
                 m('Tab', { title; 'tab2' }, [contents]),
                 m('Tab', { title: 'tab3' }, [contents])
         ])
     );
  }
};
´´´
m.component would register a component to a private registry, while component invokation via m(<componentName>) would lookup the component in that registry or asume a standard HTML tag if not found.
To me, this looks cleaner oppesed to this:
´´´
var App = {
   controller: function(args) {...},
   view: function(ctrl, args) {
      return m('.page',
          m('header', 'AppTitle'),
          Tabset([
                 Tab( { title: 'tab1' }, [contents]) ),
                 Tab( { title; 'tab2' }, [contents]) ),
                 Tab( { title: 'tab3' }, [contents]) )
         ])
     );
  }
};

// or this:
var App = {
   controller: function(args) {...},
   view: function(ctrl, args) {
      return m('.page',
          m('header', 'AppTitle'),
          Tabset([
                 m.component(Tab, { title: 'tab1' }, [contents]) ),
                 m.component(Tab, { title; 'tab2' }, [contents]) ),
                 m.component(Tab, { title: 'tab3' }, [contents]) )
         ])
     );
  }
};
´´´
Apart from that, renaming m.module to m.mount is a good choice, it avoids brain conflicts with ES6 modules and describes best what this method does (mount some component / module) to a DOM node.

Regards,
Clemens

**Comment by lawrence-dol** [comment]
@webcss : If that's what you desire, it would be trivial for you to make your own global registry, would it not, named, say, "tag"?

Then just do:

   view: function(ctrl, args) {
      return m('.page', [
          m('header', 'AppTitle'),
          tag.Tabset([
                 tag.Tab({ title: 'tab1' }, [contents]) ),
                 tag.Tab({ title; 'tab2' }, [contents]) ),
                 tag.Tab({ title: 'tab3' }, [contents]) )
   ...

And it's all in the application domain.

**Comment by webcss** [comment]
@lawrence-dol that's right, this is exactly what I use right now. But wouldn't it be more consistent to use m() for component invocation, as we do for standard HTML tags? 
Would make more sense to newcomers as well, rather than "use m() for standard tags, but you need m.xxxx() for custom components...
Another point, as I mentioned before, is we avoid vast amounts of var statements. 

Below I have a small monkeypatch for everyone who is wants to try it out for himself.

```javascript
(function(global) {

	var registry = {};
	var mo = global.m;
	var slice = [].slice;

	var m = function() {
		var comp = arguments[0]; // no type checking here, to lazy

		if (registry[comp]) {
			arguments[0] = registry[comp];
			return mo.module.apply(global, arguments);
		} else {
			return mo.apply(global, arguments);
		}
	};

	for(var key in mo) {
		if (mo.hasOwnProperty(key)) {
			m[key] = mo[key];
		}
	}

	m.component = function(name, component) {
		if(!component.controller) {
			component.controller = function() {};
		}
		registry[name] = component;
	};

	global.m = m;
	
}(this));
```
I think this feels more comfortable. We're still at the point of discussing what the perfect API for mithril should be like, this is my 2 cents, that's all.

**Comment by barneycarroll** [comment]
Wouldn't that essentially make components branch the same thing as Mithril
elements?

https://github.com/philtoms/mithril.elements/blob/master/README.md

On Wednesday, 1 April 2015, webcss <notifications@github.com> wrote:

> @lawrence-dol <https://github.com/lawrence-dol> that's right, this is
> exactly what I use right now. But wouldn't it be more consistent to use m()
> for component invocation, as we do for standard HTML tags?
> Would make more sense to newcomers as well, rather than "use m() for
> standard tags, but you need m.xxxx() for custom components...
> Another point, as I mentioned before, is we avoid vast amounts of var
> statements.
>
> Below I have a small monkeypatch for everyone who is wants to try it out
> for himself.
>
> (function(global) {
>
>     var registry = {};
>     var mo = global.m;
>     var slice = [].slice;
>
>     var m = function() {
>         var comp = arguments[0]; // no type checking here, to lazy
>
>         if (registry[comp]) {
>             arguments[0] = registry[comp];
>             return mo.module.apply(global, arguments);
>         } else {
>             return mo.apply(global, arguments);
>         }
>     };
>
>     for(var key in mo) {
>         if (mo.hasOwnProperty(key)) {
>             m[key] = mo[key];
>         }
>     }
>
>     m.component = function(name, component) {
>         if(!component.controller) {
>             component.controller = function() {};
>         }
>         registry[name] = component;
>     };
>
>     global.m = m;
>
> }(this));
>
> I think this feels more comfortable. We're still at the point of
> discussing what the perfect API for mithril should be like, this is my 2
> cents, that's all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lhorie/mithril.js/issues/498#issuecomment-88626138>.
>


-- 
Regards,
Barney Carroll

barney.carroll@gmail.com
+44 7429 177278

barneycarroll.com

**Comment by tobscure** [comment]
I think a component registry is outside the scope of the framework, because it's a pretty opinionated way of loading things.

But I do agree that it would be nice to be able to use m() for everything for consistency, though I don't know enough to know if it's feasible. Something like this:

```
view: function(ctrl, args) {
   return m('.page', [
       m('header', 'AppTitle'),
       m(Tabset, [
           m(Tab, { title: 'tab1' }, [contents]),
           m(Tab, { title: 'tab2' }, [contents]),
           m(Tab, { title: 'tab3' }, [contents])
```

Could m() just look at the type of the first argument — if it's a string then do a normal vdom element, if it's an object/constructor then do a component?

**Comment by lawrence-dol** [comment]
@tobscure : I think I agree, if in your example `Tabset` and `Tab` are the results of previously called `m.component`:

    var tabset=m.component(new TabsetComponent(...));
    var tab   =m.component(new TabComponent(...));

(and note the lowercase because they are not constructors, but an object containing a constructor and a view-generator).

But I think there might be problems binding the attributes and children into the component in this syntax, which might be why the syntax uses either `m` or `m.component`.

I wonder what @lhorie thinks?

**Comment by tobscure** [comment]
Any reason why it can't be done *without* the m.component setup? I like the way it currently works in the component branch (passing in a plain object and letting the rendering engine intelligently handle controller instantiation), I'm just suggesting to merge the m.module(component, args) API into m():

```
var ListItemComponent = {
  controller: function() {},
  view: function(ctrl, args) {
    return m('li', args.text)
  }
}

var ParentComponent = {
  controller: function() {},
  view: function() {
    return m('ul', [
      // current syntax
      m.module(ListItemComponent, {text: 'hello'})
      // proposed syntax, m() just needs to check if the first argument is an object
      // and do whatever m.module() currently does if it is
      m(ListItemComponent, {text: 'hello'})
    ])
  }
}
```

Sorry for digressing from the topic of this issue, this discussion is probably better had in #497.

**Comment by webcss** [comment]
@barneycarroll Deja vue, that's right ;) But is it really that bad after all? I don't think so, in terms of usability, since it feels natural.

@tobscure I think this would be perfectly doable, just needs to check for first argument to be an object with (controller and) view.

```javascript
(function(global) {
	var mo = global.m;

	var m = function() {
		var comp = arguments[0]; // no type checking here, to lazy

		if (arguments[0].controller && arguments[0].view) {
			return mo.module.apply(global, arguments);
		} else {
			return mo.apply(global, arguments);
		}
	};

	for(var key in mo) {
		if (mo.hasOwnProperty(key)) {
			m[key] = mo[key];
		}
	}
	global.m = m;
	
}(this));
```

**Comment by webcss** [comment]
@tobscure This actually is quite nice since it adheres to mithril's virtualDOM syntax m(element, attr, children) and makes components distinguishable from HTML tags. Furthermore a registry is not needed anymore as a hard dependency.
I like it!

**Comment by lhorie** [comment]
Personally I like this syntax:

```javascript
Tabset([
           Tab({ title: 'tab1' }, [contents]),
           Tab({ title: 'tab2' }, [contents]),
           Tab({ title: 'tab3' }, [contents])
])
```
more than this:

```javascript
m(Tabset, [
           m(Tab, { title: 'tab1' }, [contents]),
           m(Tab, { title: 'tab2' }, [contents]),
           m(Tab, { title: 'tab3' }, [contents])
])
```

I think conflating components and `m` would cause confusion at the top level, e.g.

```javascript
m.route(document.body, "/", {
  "/": m(Foo, {id: 1}) // implies plain elements also work here, which is not true
})
```

**Comment by tobscure** [comment]
That makes sense. +1 for that syntax then :)

**Comment by lawrence-dol** [comment]
@lhorie : Once again, though, in the example given, `Tabset` and `Tab` are not constructors and should not be lead uppercase, right?

Also, are they expected to be the return of an `m.component` call?

    var Tabset=m.component(new Tabset(...));
    var Tab   =m.component(new Tab(...));

    ...

    function view() {
        return Tabset([
           Tab({ title: 'tab1' }, [contents]),
           Tab({ title: 'tab2' }, [contents]),
           Tab({ title: 'tab3' }, [contents])
        ])

I must confess to be losing track of all the variant proposals at this point.

**Comment by lhorie** [comment]
@lawrence-dol yes

**Comment by mindeavor** [comment]
Hey all, component registry and component syntax are outside the scope of this issue.

Based on this thread, I take it there are no oppositions to separating the DOM-mounting functionality of m.module into `m.mount`. If there are any objections, please post them, otherwise I'd say this idea is in the clear.

**Comment by lhorie** [comment]
`m.mount` landed in components branch. It's an alias of the stable `m.module` API (i.e. no 3rd parameter).
