### ISSUE TITLE
parseQueryString doesn't support basic Arrays

### ISSUE THREAD

**Issue by Nijikokun** [lhorie/mithril.js#501]
**Method** 

`parseQueryString`

**Fixture**

```js
foo=bar&hello%5B%5D=world&hello%5B%5D=mars&hello%5B%5D=pluto
```

**Expected Result**

```js
{
  foo: "bar",
  "hello[]": [ "world", "mars", "pluto" ]
}
```

**Actual Result**

```js
{
  foo: "bar",
  "hello[]": "world"
}
```

---

Basic array (multiple key-value to key-array(values)) is not supported and data is **lost**.

**Comment by lhorie** [comment]
Fixes are up on origin/next
