### ISSUE TITLE
buildQueryString incorrectly parses object values

### ISSUE THREAD

**Issue by Nijikokun** [lhorie/mithril.js#502]
**Method** 

`buildQueryString`

**Fixture**

```js
{
  foo: "bar",
  hello: ["world", "mars", "mars"],
  world: { 
    test:3 
  },
  bam: "",
  yup: null,
  removed: undefined
}
```

**Expected Result**

```js
foo=bar&hello=world&hello=mars&world%5Btest%5D=3&bam=&yup
```

**Actual Result**

```js
foo=bar&hello%5B%5D=world&hello%5B%5D=mars&hello%5B%5D=mars&world%5Btest%5D=3&bam=&yup=null&removed=undefined
```

---

- Duplicate array values are not squashed.
- Array keys are appended with **PHP Notation** brackets `[]` should just duplicate key, and let key be in charge of framework specific details.
- Doesn't remove undefined properties
- Incorrectly supports `null` values, shouldn't contain the value segment

---

See http://medialize.github.io/URI.js/docs.html#static-buildQuery for examples of how building Querystring should be handled.

**Comment by lhorie** [comment]
Fixes are up on origin/next

**Comment by futurist** [comment]
This issue still exists in `1.x`, and my server cannot parse right with `m.buildQueryString` result.

Now we have to use [qs](https://github.com/ljharb/qs), with the the option in line 5:

```
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'indices' })
// 'a[0]=b&a[1]=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'brackets' })
// 'a[]=b&a[]=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'repeat' })
// 'a=b&a=c'
```

And `m.buildQueryString({ a: ['b', 'c'] })` always get:

```
"a%5B0%5D=b&a%5B1%5D=c"
```

Maybe mithril can let user pass into similar options?

Thank you!
