### ISSUE TITLE
Text nodes fall through diff

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#507]
I've recently encountered a bizarre situation whereby child text nodes of a given draw get appended to the VDOM node at the same position on subsequent redraws – even when redraw strategy is `all`. The effect is sometimes cumulative, as seen [in this example](http://jsfiddle.net/barney/m6tfvh3p/) (navigate to `/profile`, then back to `/home` – each time this is repeated the text nodes 'You need to ' and ' to view that page' appear to be cloned and re-appended).

**Comment by barneycarroll** [comment]
Update: this appears to behave differently in different browsers. My application has a generic loading micro-module that looks like this:

```javascript
var loading = {
	view : function(){
		return m( 'p.loading',
			m( 'span.spinner' ),
			m( 'em',
				'Loading',
				m.trust( '&hellip;' ) // Ellipsis
			)
		);
	}
}
```

I use it in all sorts of other modules when certain data has yet to resolve. In Chrome this is not a problem. In Firefox, a new ellipsis is added on every redraw (the effect is arguably pretty cool, but never intentional). WTF. Gonna try and replicate this simpler test case.

**Comment by lhorie** [comment]
Are you using v0.1.30 or bleeding edge (next branch)?

**Comment by barneycarroll** [comment]
@lhorie that might well be it. Not reproducible in my own code under certain environments, which suggests it's a problem in next. I'll get a better test case up this afternoon (GMT) and compare next to master.

**Comment by barneycarroll** [comment]
@lhorie BTW [my test case is still there](http://jsfiddle.net/barney/35zfg6uu/). [I forked it to use master](jsfiddle.net/barney/Lwg7scov/) instead of next, and it reveals a regression in the ability for top level components to work without explicit controller declaration. When did that happen?

**Comment by webcss** [comment]
confirmed. component branch requires explicit controller declaration for
components as well.

2015-03-25 12:29 GMT+01:00 Barney Carroll <notifications@github.com>:

**Comment by lhorie** [comment]
@barneycarroll ah sorry, I missed the link! Definitely reproducible.

**Comment by lhorie** [comment]
Fixed in origin/next

**Comment by barneycarroll** [comment]
@lhorie [same demo](http://jsfiddle.net/barney/o9pevr1p/), different bug. When you click on the profile link, everything after the ''You need to' node isn't built. Note I had to introduce `controllers` in the demo code because we regressed on free controller insertion.
