### ISSUE TITLE
components: Problems with nesting components

### ISSUE THREAD

**Issue by sloria** [lhorie/mithril.js#510]
I've been trying out the new "modules-as-components" API on the `components` branch and ran into a snag: one cannot nest components past a depth of one. This is due to the constraint that components *must* return a virtual element--returning a module is not allowed.

Example breaking code:

```js
var Panel = {
    view: function(ctrl, args, children) {
        return m('.mypanel', [
            m('.mypanel-header', [args.header], children)
        ]);
    }
};

var Menu = {
    view: function(ctrl, args) {
        return m.module(Panel, {header: 'My Menu'});
    }
};

var Page = {
    view: function(ctrl, args) {
        // Crashes because Menu.view returns a module
        return [
            m.module(Menu, {})
        ];
    }
}
```

**Comment by sloria** [comment]
I discovered that I can work around this issue by having calling the `view` method of the "intermediate" component:

```js
var Menu = {
    view: function(ctrl, args) {
        return m.module(Panel, {header: 'My Menu'}).view();  // workaround
    }
};

var Page = {
    view: function(ctrl, args) {
        return [
            m.module(Menu, {})
        ];
    }
}
```

This, however, is not ideal because a component now has to know whether it will be top-level or nested within another component.

**Comment by barneycarroll** [comment]
It's also the case that a component must consist of a single root, as opposed to a possible collection of elements. The simpler workaround is DIV soup — simply ensure every module returns an element, nesting the 'real' content within that if necessary.

**Comment by lhorie** [comment]
To add to what @barneycarroll said, a component must return a static virtual dom element, meaning that in addition to arrays not being valid return values, conditionally swapping root elements is also not valid.

Honestly, given the imposed limitations, I don't see a use case for returning a component from another - you may as well just use the inner component in the first place.

**Comment by sloria** [comment]
Sorry, my example code was too contrived. The use case is that I want to reuse a component within other components. 

Perhaps this is a better example:

```js
// Reusable panel. Provides header styling, etc.
var Panel = {
    view: function(ctrl, args, children) {
        return m('.mypanel', [
            m('.mypanel-header', [args.header], children)
        ]);
    }
};

// One type of panel
var Menu = {
    view: function(ctrl, args) {
        return m.module(Panel, {header: 'My Menu'}, [
            m('li', 'Menu item 1'),
            m('li', 'Menu item 2')
        ]);
    }
};


// Another panel
var SomeWidget = {
    view: function(ctrl, args) {
        return m.module(Panel, {},
            'Some panel content'
        );
    }
};

// A page with multiple panels
var Page = {
    view: function(ctrl, args) {
        // Crashes because Menu.view returns a module
        return  m('div', {}, [
            m.module(Menu, {}),
            m.module(SomeWidget, {})
        ]);
    }
};
```

How should components be properly nested within other components?

**Comment by lhorie** [comment]
This makes more sense, and actually seems like a legit problem, so I'm gonna reopen this issue

**Comment by lhorie** [comment]
Fixed in origin/components

**Comment by barneycarroll** [comment]
Was going to mention this secondary problem (persisting a component identity after moving it to another DOM island / parent component) in #514.

@lhorie could you elaborate on what the identification heuristics are doing under the hood to allow this? On the face of it it would seem that whatever logic allows the component to persist between hierarchical contexts is at odds with the notion that component identities are managed based on key / index only within any given parent node. I'm having difficulty seeing how the user could specify which of these behaviours they want.

**Comment by ArthurClemens** [comment]
Nice work. I've tested and updated the above example to make it work in the latest version:

```
// Reusable panel. Provides header styling, etc.
var Panel = m.component({
    view: function(ctrl, args, children) {
        return m('.mypanel', [
            m('.mypanel-header', [args.header || ''], children)
        ]);
    }
});
// One type of panel
var Menu = m.component({
    view: function(ctrl, args) {
        return Panel({
            header: m('h3', 'Menu')
        }, [
            m('li', 'Menu item 1'),
            m('li', 'Menu item 2')
        ]);
    }
});
// Another panel
var SomeWidget = m.component({
    view: function(ctrl, args) {
        return Panel({
            header: m('h3', 'Panel header')
        }, 'Panel content');
    }
});
// A page with multiple panels
var Page = m.component({
    controller: function() {},
    view: function(ctrl, args) {
        return m('div', {}, [
            m('h1', args.header),
            Menu(),
            SomeWidget()
        ]);
    }
});
m.mount(document.body, Page({
    header: "Page"
}));
```
