### ISSUE TITLE
Input fields get recreated when the class changes to/from empty string

### ISSUE THREAD

**Issue by hufman** [lhorie/mithril.js#512]
When an input field's class changes from an empty string to a class, or back to empty string, the input field apparently gets recreated and loses its value.
When a div's class changes in the same way, it doesn't recreate anything, but the input field still loses focus, which is even weirder to me.

What is going on? Can I signal to Mithril that the elements are the same and to not recreate them?

http://jsfiddle.net/hufman/n7b17whq/5/

**Comment by lhorie** [comment]
Fixed in origin/next

**Comment by hufman** [comment]
Thanks!
