### ISSUE TITLE
Date Formatters / parsers recommend

### ISSUE THREAD

**Issue by ginus** [lhorie/mithril.js#515]
https://github.com/phstc/jquery-dateFormat

**Comment by barneycarroll** [comment]
@ginus I highly recommend [Moment](http://momentjs.com/)

**Comment by adriengibrat** [comment]
moment.js is a very good library.
It's great to express dates and intervals in various ways, including
'natural' language.
But it's really not lightweight (11ko min.gz)

if you need a very simple utility (1.3ko min.gz):
http://stevenlevithan.com/assets/misc/date.format.js is the base of popular
node date formaters.


Adrien

2015-03-24 13:57 GMT+01:00 Barney Carroll <notifications@github.com>:

**Comment by lhorie** [comment]
Hmm ok, these are great, but they're not really issues :)

Feel free to use [Gitter](https://gitter.im/lhorie/mithril.js) or the [mailing list](groups.google.com/forum/#!topic/mithriljs/) to chat
