### ISSUE TITLE
Automatically set content-type for XHR POST requests.

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#516]
@mindeavour [came up with this issue](https://gitter.im/lhorie/mithril.js?at=55102d70bb9b35940a30b64c) where Mithril was firing OPTIONS requests that public APIs didn't know how to respond to. It turns out any CORS POST request will trigger a pre-flight OPTIONS request and most servers aren't equipped to respond adequately.

jQuery handles this stuff under the hood, and Mithril probably should too. Their docs describe the issue pretty well under [ajax settings](http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings):
>**contentType** (default: `'application/x-www-form-urlencoded; charset=UTF-8'`)
>Type: Boolean or String
>When sending data to the server, use this content type. Default is "application/x-www-form-urlencoded; charset=UTF-8", which is fine for most cases. If you explicitly pass in a content-type to `$.ajax()`, then it is always sent to the server (even if no data is sent). As of jQuery 1.6 you can pass `false` to tell jQuery to not set any content type header. 
>**Note:** The W3C XMLHttpRequest specification dictates that the charset is always UTF-8; specifying another charset will not force the browser to change the encoding. 
>**Note:** For cross-domain requests, setting the content type to anything other than `application/x-www-form-urlencoded`, `multipart/form-data`, or `text/plain` will trigger the browser to send a preflight OPTIONS request to the server.

This is the kind of weird stuff with XHR that nobody ever remembers. In my case I got our back-end devs to configure services to respond to OPTIONS, but this standard is obviously not well implemented. So we figured it would make sense to bake the logic described above into Mithril rather than rely on users writing their own serialize functions.

**Comment by barneycarroll** [comment]
The deeper I look into this, the less simple it is. Anecdotal evidence suggests adding any custom headers will force an OPTIONS preflight request which the server must be prepared to respond to in the value for the `Access-Control-Allow-Header` response header. Apparently, [in Safari](https://remysharp.com/2011/04/21/getting-cors-working#comment-1887063650) any CORS POST request mandates this, even without the user setting custom headers. Perhaps this isn't a trivial fix after all (it might explain why Mithril's XHR component is so tiny compared to other libs though ;).

For my purposes, I have the guy writing our services sat next to me so I can thrash this stuff out. I suppose a generic strategy depends upon de facto standards of major public XHR APIs. Which I have extremely little knowledge of (except for the fact I never had to worry about any of this stuff when I was using jQuery).

**Comment by tivac** [comment]
CORS is a complicated thing, I'd prefer mithril tried to stay out of taming it.

@barneycarroll Yes, any custom headers will require the preflight.

**Comment by barneycarroll** [comment]
@tivac you're right, there's just too much that could be happening. As they say in the Gulp community "recipes, not plugins". So in the case that you want to avoid a preflight request when doing a simple POST to another domain, [here's a gist](https://gist.github.com/barneycarroll/6836bdb13f00048f920b).
