### ISSUE TITLE
Support for generators

### ISSUE THREAD

**Issue by Naddiseo** [lhorie/mithril.js#517]
With generator functions now being native in recent chrome and firefox builds, it is probably a good idea to support generators as a basic type in the virtual dom. I would imagine they'd be treated much the same as arrays.

Example usage:
```javascript

var app = {};

app.controller = function () {
    this.dataList = function* () { yield* [1,2,3]; }
};
app.view = function(ctrl) {
     function *printNumber(lst) {
         for (var n of lst) {
            yield m('span', n);
         }
     }

    return m('div', printNumbers(ctrl.dataList));
}

m.module(document.body, app);
// output: <div><span>1</span><span>2</span><span>3</span></div>
```

**Comment by isiahmeadows** [comment]
AFAICT, this is not going to happen in the rewrite. First, I rarely hear of this. Second, it adds nothing other than internal complexity when you can just use Array.from or the function below with minimal cost to convert it.

```js
function toArray(iterable) {
    var iter = iterable[Symbol.iterator]()
    var result = []

    for (var next = iter.next(); !next.done; next = iter.next()) {
        result.push(next.value)
    }

    return result
}
```
