### ISSUE TITLE
404 mithril.min.js.map not found, if make demo app in plunker

### ISSUE THREAD

**Issue by vikbert** [lhorie/mithril.js#518]
I use mithril in plunker and have the same problem. 
`http://cdnjs.cloudflare.com/ajax/libs/mithril/0.1.30/mithril.min.js.map 404 (Not Found)`

the lib is linked in head
`    <script 
      data-require="mithril@*" 
      data-semver="0.1.30" 
      src="http://cdnjs.cloudflare.com/ajax/libs/mithril/0.1.30/mithril.min.js">
    </script>`

Any tips!?

**Comment by lhorie** [comment]
Yeah, package.json file is incorrectly pointing to mithril.min.map instead of mithril.min.js.map. This will be fixed with the next release

As a work around, you could use the unminified file to get readable stack traces.
