### ISSUE TITLE
Subtree directive documentation needs clearer example

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#520]
The documentation example for [subtree](http://lhorie.github.io/mithril/mithril.render.html#subtree-directives) is unnecessarily convoluted. We had a tough time working out expectations [in a recent chat](http://lhorie.github.io/mithril/mithril.render.html#subtree-directives).

A reworked example should clearly indicate where the property sits in the wider `m()` signature.

**Comment by farzher** [comment]
+1

I misinterpreted that documentation, tried doing something silly, and got very confused.

**Comment by barneycarroll** [comment]
Subtree is actually really difficult to produce a simple example for. I tried showing how I could 'freeze' part of the DOM while changing the model of a simple app, but using the most obvious way of changing the attribute (ternary operator on value) produces [insane results](http://jsfiddle.net/barney/qo8msnd2/).

At this point I thought I'd rework the code to come closer inline with the docs, avoiding use of the attribute key if retention isn't desired. Slightly less weird, but still [really really weird](http://jsfiddle.net/barney/fx5t34h1/). It seems subtree is totally borked.

**Comment by farzher** [comment]
Or maybe I didn't try something silly, and subtree retain just doesn't work :p

**Comment by farzher** [comment]
Oh and in that documentation, the view is missing a return, so it returns nothing.

![image](https://cloud.githubusercontent.com/assets/1005136/6889696/9dfe5b1e-d669-11e4-85d4-f9430210ee5c.png)

**Comment by barneycarroll** [comment]
There appear to be a host of weird rendering bugs associated with 0.1.31/32 — this one at least is reproducible in 0.1.30: http://jsfiddle.net/barney/fx5t34h1/1/

**Comment by lhorie** [comment]
FYI, subtree directives are NOT attributes. As per the docs: 

> m.render accepts a special low level SubtreeDirective object as a node in a virtual DOM tree.

**Comment by barneycarroll** [comment]
> …as a node

@farzher looks like you were right!

@lhorie so the SubtreeDirective interrupts diffing for all subsequent nodes?

**Comment by farzher** [comment]
There's possibly nothing wrong with subtree, and the weirdness just has to do with #524

**Comment by lhorie** [comment]
#524 is fixed and merged into both next and components branches, FYI
