### ISSUE TITLE
Strange bug with multiple components

### ISSUE THREAD

**Issue by mindeavor** [lhorie/mithril.js#521]
I'm running into a bug within the Mithril internals (latest components branch), and I'm not sure how to fix it. Here's how to reproduce:

- Open http://jsfiddle.net/gfy0of6y/
- Click inside the first text field
- Click an option from the dropdown (or click outside to close the dropdown)
- Click inside the second text field
- See js console for error

The bug only happens when you have more than one instance of MSelect on the page. Also, strangely enough, it only happens when you select the first box, and *then* the second (if you select the second box first, everything works fine).

**Comment by lhorie** [comment]
Appears to be related to #524. I tried the jsfiddle w/ the latest commit and it looks like the error no longer appears:

http://jsfiddle.net/gfy0of6y/1/

**Comment by mindeavor** [comment]
Thank you! :clap:
