### ISSUE TITLE
Test examples in the documentation 

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#522]
Inoperable example code really undermines adoption, as seen most recently in #520. 

In the short term we should go through the docs and fix these one by one, but it might be an idea to write regression tests for them.

Gold plating would be to embed jsbin / jsfiddle live examples that could be demo'd in situ.

**Comment by lhorie** [comment]
Yeah this is in the todo list. Contributions welcome.

**Comment by barneycarroll** [comment]
I've got a major release in the middle of the week so I'm going to stick to my usual role of whining until the tail end ;)

Thinking deeper about this, a sustainable choice would be to have all the example snippets as distinct JS files. This would make testing easier, and could allow some clever scripting to integrate with the [jsFiddle API](http://doc.jsfiddle.net/api/post.html) to ensure all code is perpetuated. This would make it super easy for beginners and old hands to fork examples to suit others' needs etc. One for the backburner.

**Comment by lhorie** [comment]
Closing this and #500 in favor of #526, which is more descriptive of the task at hand
