### ISSUE TITLE
Rendering bug if last element is a component

### ISSUE THREAD

**Issue by StephanHoyer** [lhorie/mithril.js#523]
This but might only apply to components branch

If the last element of an element list a component it will not removed properly.

https://jsfiddle.net/2dnatzeb/

If I add a key property to the component, it works

https://jsfiddle.net/315La3v7/1/

**Comment by StephanHoyer** [comment]
maybe related to #524

**Comment by lhorie** [comment]
Yep, looks like it's the same thing as #524. I merged that fix into components and reloaded the jsfiddle and it seems to work now
