### ISSUE TITLE
Make selector string optional in m() signature

### ISSUE THREAD

**Issue by barneycarroll** [lhorie/mithril.js#525]
Attribute-heavy code, where Mithril is being used to determine styles, event handlers and config actions on nested elements, tends to read better if the node's properties are described entirely in the attributes argument. At this point, the mandatory selector string ends up redundant and confusing – quick legibility of the overall structure is really undermined. Could we make it optional?

Example:

```javascript
// before:
var splash = {
	view : function( ctrl, contents ){
		return m( '', {
			config : fillHeight(),
			style  : {
				'background'      : '#f3f3f3 url( /img/bg.jpg ) 100% 100%',
				'background-size' : 'cover',
				'text-align'      : 'center'
			}
		}, m( '', {
			style : {
				'position'  : 'absolute',
				'top'       : '50%',
				'width'     : '100%',
				'transform' : 'translateY( -50% )'
			},
			contents
		} ) );
	}
}
// after:
var splash = {
	view : function( ctrl, contents ){
		return m( {
			config : fillHeight(),
			style  : {
				'background'      : '#f3f3f3 url( /img/bg.jpg ) 100% 100%',
				'background-size' : 'cover',
				'text-align'      : 'center'
			}
		}, m( {
			style : {
				'position'  : 'absolute',
				'top'       : '50%',
				'width'     : '100%',
				'transform' : 'translateY( -50% )'
			},
			contents
		} ) );
	}
}
```

**Comment by mindeavor** [comment]
What is the code doing? I've never tried using an empty selector before.

**Comment by barneycarroll** [comment]
Any kind of selector without an explicit tagName defaults to div. It's like div soup without the chunky bits ;)

**Comment by mindeavor** [comment]
Ah, I see. Personally I think having `'div'` as the first argument is more readable (less surprising).

**Comment by lhorie** [comment]
I agree w/ @mindeavor, and I'd say that `m('')` is relying on undefined behavior

**Comment by barneycarroll** [comment]
Fair enough. At this point it's probably best to keep as few moving parts as necessary. Meanwhile I'm looking at extending / monkey patching core in so many ways I should probably lay off feature suggestions until we hit the second point release :)
