### ISSUE TITLE
Manual dom changing (based on events)

### ISSUE THREAD

**Issue by RostyslavKhanas** [lhorie/mithril.js#528]
I just looked at Todo-App and noticed one kind of bug.
If you create 2 todo items, then select "Completed", then uncheck first one, you will see that second todo item is check but checkbox is not. That is because we change dom manually, while clicking on first todo item(should disappear from "Completed" view). The diff cannot find any difference between old and new item, because we changed dom, not virtual dom. I suspect that this is global problem in this framework.  It would be really cool to handle that kind of problem automatically.

**Comment by Bondifrench** [comment]
Which TodoMVC are you talking about? Can you link to some code?
The official [TodoMVC](http://todomvc.com/examples/mithril/) doesn't have the problem you mention.

**Comment by farzher** [comment]
The official TodoMVC does indeed have the problem he mentioned.
I actually found 3 problems with it. The first problem is what @RostyslavKhanas is referring to.


1. task elements are not given key attributes, so if you go to the active tab and start checking tasks off, the UI bugs out a bit.
2. when editing a todo title, the input always forces your cursor to be at the end (try moving cursor with arrow keys)
3. when deleting a task, you delete from the TOTAL list of items based on the index of the FILTERED list of items. So it deletes the wrong tasks (what looks like task 2 on the completed list isn't necessarily task 2 on the full list)

**Comment by Bondifrench** [comment]
1) not sure about one what you mean, if you check things off from active tab, they go to Completed
2) it depends what your expectations are, my automatic reaction when editing is to delete not move with the cursor
3) ok, just saw that error, not sure it's a problem with the framework, but with how the example has been modelled

**Comment by RostyslavKhanas** [comment]
@Bondifrench , just use your link. Add 2 list items, go to "completed" and check first item. And you will see that bug.

To see 3rd bug that @farzher mentioned, we can create 2 items, check first one, go to "active" and try to remove the only item there.

However these issues are not just about correctness of TodoApp, especially problem 1. It is also about the performance. After fixing this issue, Mithril will probably be the faster framework, but the performance will be a little bit worse while running some "todomvc-perf-comparison" task.

**Comment by RostyslavKhanas** [comment]
@Bondifrench, please, watch this screencast: https://docs.google.com/file/d/0B-9NAZKjNSDycW1oSkgtalRFRDg/

**Comment by Bondifrench** [comment]
ok got it

**Comment by farzher** [comment]
Regarding the original issue, I'm not sure it's possible to automatically solve.
When re-ordering, adding, or removing similar elements it's apparently hard/impossible to do without keys.

My idea is to allow the `key` attr to accept the value `true` (currently not a valid key). In which case Mithril generates a unique key automatically for me.

**Comment by mindeavor** [comment]
I wouldn't call this a "global problem"; Mithril does not do dirty-checking on the DOM by design. If it did, it would be immensely slower.

The solution is not the `key` attribute, but two-way data binding. I cover this in the [Two-Way Data Binding section](http://gilbert.ghost.io/mithril-js-tutorial-1/#twowaydatabinding) of my blog post.

In general you should not be modifying the DOM yourself; you should instead update *data*, and let Mithril handle the DOM manipulation for you.

**Comment by lhorie** [comment]
Just a minor note. `true` is technically a valid key by virtue of javascript to-string-auto-casting behavior. However, the docs don't explicitly say true is an acceptable value, so consider it undefined behavior.

**Comment by farzher** [comment]
@mindeavor idk what you're talking about. I read your thing. That's not the problem.

@lhorie yeah I know, I tried `true`, it treats them all as the same key. But that's not mentioned in the docs so I think it's fine to change behavior.
You can't fix reordering / adding / deleting similar items without using a `key`, right? It would kill performance too much?

**Comment by farzher** [comment]
Also, what do you guys mean by "Manual dom changing"?
The todo app isn't manually changing the dom, it's all mithril rendering.
Maybe I'm missing something.

**Comment by mindeavor** [comment]
@farzher My comment was directed at OP, sorry for not being clear

**Comment by lhorie** [comment]
> You can't fix reordering / adding / deleting similar items without using a key, right? It would kill performance too much?

No, ordering of elements requires keys. This is a requirement of the diffing algorithm, it's not performance related

**Comment by RostyslavKhanas** [comment]
@farzher , "Manual dom changing" means that we change "checked" property of checkbox directly while clicking on it, instead of changing virtual object and only after that dom element(using diff+patch).

**Comment by lhorie** [comment]
FWIW, the algorithmic limitation that causes the original issue is documented here: http://lhorie.github.io/mithril/mithril.html#dealing-with-focus (and the section after that one).

The 2nd issue @farzher brought up was fixed a while ago, and I think TodoMVC is using an old version of Mithril

The 3rd issue @farzher brought up looks like an app bug, not a Mithril core bug.

**Comment by farzher** [comment]
@lhorie 
My 2nd issue is also just an app bug. But why are you saying it's fixed? The todomvc still has that issue
Is this what you're referring to?
> when editing a todo title, the input always forces your cursor to be at the end (try moving cursor with arrow keys)

3rd issue is definitely an app bug, not mithril
