### ISSUE TITLE
Bug in documentation on the page

### ISSUE THREAD

**Issue by cachaito** [lhorie/mithril.js#531]
I've noticed a mistake in docs: http://lhorie.github.io/mithril/mithril.html

According to guide
```
var links = [
    {title: "item 1", url: "/item1"},
    {title: "item 2", url: "/item2"},
    {title: "item 3", url: "/item3"}
];

m.render(document.body, [
    m("ul.nav", [
        m("li", links.map(function(link) {
            return m("a", {href: link.url}, link.title)
        }))
    ])
]);
```
should have generate:
```
<body>
    <ul class="nav">
        <li>
            <a href="/item1">item 1</a>
            <a href="/item2">item 2</a>
            <a href="/item3">item 3</a>
        </li>
    </ul>
</body>
```
The result: [jsFiddle](http://jsfiddle.net/cachaito/19nwt8nq/)

By the way, how to achieve this code output using a .map() method?

**Comment by webcss** [comment]
pullrequest on its way. To answer your question:
´´´javascript
m.render(document.body, [
    m("ul.nav", [
        links.map(function(link) {
            return m("li", 
                  m("a", {href: link.url}, link.title)
            );
        })
    ])
]);
´´´
The LI tag must of course be returned by links.map() function.

**Comment by cachaito** [comment]
Thank You for help - ticket to close.
