### ISSUE TITLE
Mithril performing full redrawing instead of diff when we add a method to Object Prototype

### ISSUE THREAD

**Issue by dhinesh03** [lhorie/mithril.js#535]
On build method, Line number 245 : ```dataAttrKeys.join() != Object.keys(cached.attrs).join()``` condition  always fails when we  add a method to Object Prototype. 

I've added a method to Object's prototype for supporting Mixin
```
//For Mixin support 
if (typeof Object.prototype.addMixin !== 'function') {
    Object.prototype.addMixin = function (mixin) {
       mixin.call(this.prototype);
    };
}

m.module(document.body,, {
  view: function() {
    return [m('input', {oninput:function(){console.log('oninput triggered..')}})];
  }
});

console.log(dataAttrKeys.join()) // Output => "oninput,addmixin"
console.log(cached.join()) // Output => "oninput"
```
So i've added this check 
``` if(attrs.hasOwnProperty(attrName)) { ```
 on m() method , line no : 62.

Is this right way to do?

**Comment by jonahx** [comment]
Thanks for posting this.  This just bit me tonight and I might have wasted for more time were it not for finding this issue.

**Comment by lhorie** [comment]
Well, normally polluting `Object.prototype` is considered bad practice, but I could look into this

**Comment by jonahx** [comment]
Hey Leo,

I agree in theory.  In my case, the pollution was motivated by a desire to add a "map" function to objects (similar to Array.map).  To avoid the mithril collision problem from this issue, I ended up doing:

`Object.defineProperty(objToUpgrade, 'objMap', {enumerable: false, value: util.objMap});`

which is verbose.  So it was nicer to just have the method available to all objects, and indeed I find it's a utility function I want to use frequently.  Maybe there's a better way to do the "upgrade" on a per-object basis -- what I really want is syntax like ruby's `obj.extend(some_mixin)` -- but I don't know what it would be.
 
Thoughts?
Thoughts?

**Comment by barneycarroll** [comment]
Here's a test case: [without extensions](http://jsfiddle.net/barney/ovtj9gu2/) and [with](http://jsfiddle.net/barney/p11qsvwe/).

The 'ES6 today' camp has been getting a lot of traction recently – it might be difficult to convince people not to extend Object with `assign` or `observe` (as the increasingly popular [core.js](https://github.com/zloirock/core-js) – shipped with Babel's Polyfill – does).

**Comment by lhorie** [comment]
@barneycarroll extending `Object` is what people have been doing to work around the stigmas of extending `Object.prototype`. To extend Object.prototype these days, `Object.defineProperty` is meant to be the correct solution, but it doesn't work correctly in IE<8

@jonahx extending on this thought: What you're looking for is probably `Object.defineProperty(Object.prototype, "foo", {enumerable: false, value: foo})`

**Comment by jonahx** [comment]
@lhorie Yes, thanks, I think that is what I want.  And it will not cause any conflicts with Mithril so long as it's not enumerable?

**Comment by lhorie** [comment]
I believe that is correct

**Comment by lhorie** [comment]
Added a check in `m`
