### ISSUE TITLE
API to get all route params

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#539]
I would like to request an API method to retrieve all of the current route params. Use case is that I've implemented my own "named routes" system, so I can generate routes by passing an object of params:

```javascript
var href = app.route('discussion', {id: 1, slug: 'whatever'});
```

I want to be able to link to the current route, maintaining whatever params may be present, but with one of them changed. For example:

```javascript
var params = m.route.params();
params.foo = 'bar';
var href = app.route('discussion', params);
```

Could also just be `m.route.param()` without specifying a key, that way wouldn't increase the API surface

**Comment by nordfjord** [comment]
I would also like to see this implemented, in the meantime here's a solution you can use

```js
function parseQueryString() {
    var str = m.route();
    var index = m.route().indexOf( '?' );
    if( index < 0 ) return {};
    str = str.substr( index + 1 );
    var pairs = str.split( '&' ),
        params = {};
    pairs.forEach( function ( pair ) {
        var key, value, split = pair.split( '=' );
        key = window.decodeURIComponent( split[ 0 ] );
        if ( key === '' ) return;
        value = split[ 1 ] ? window.decodeURIComponent( split[ 1 ] ) : true;
        params[ key ] = value;
    } );
    return params;
}

var params = parseQueryString();
```

this is based on mithrils parseQueryString function.

**Comment by lhorie** [comment]
I was avoiding adding this to prevent using params as a "global", but this seems like a reasonable use case

**Comment by nordfjord** [comment]
A more comprehensive solution for now.

Though to be fair I used lodash for it's extend function because I'm lazy (which in my experience is a good trait for a programmer)

```js
function parseQueryString( str ) {
    if ( str === '' ) return {};
    var pairs = str.split( '&' ),
        params = {};
    pairs.forEach( function ( pair ) {
        var key, value, split = pair.split( '=' );
        key = window.decodeURIComponent( split[ 0 ] );
        value = split[ 1 ] ? window.decodeURIComponent( split[ 1 ] ) : true;
        params[ key ] = value;
    } );
    return params;
}
window.route = function ( route, conf ) {
    var routeconfig = {};
    var search = m.route();
    if ( search.indexOf( '?' ) === -1 ) {
        search = '';
    } else {
        search = search.substr( search.indexOf( '?' ) + 1 );
    }
    routeconfig = parseQueryString( search );
    _.extend( routeconfig, conf );
    Object.keys( routeconfig ).forEach( function ( key ) {
        if ( routeconfig[ key ] === false ) delete routeconfig[ key ];
    } );
    m.route( route, routeconfig );
    return;
};
```

so you can use it like this
```js
route('/my/link', {id: false, slug: '/something'});
```
where it would remove the id parameter if it exists and add/change the slug parameter to '/something'

**Comment by nordfjord** [comment]
@lhorie If you still want to prevent the usage of params as a global how about adding a flag to the existing m.route function which would indicate it should keep params?

**Comment by tobscure** [comment]
PR #767 merged this in.
