### ISSUE TITLE
m.route crashes on default route that doesn't exist

### ISSUE THREAD

**Issue by mindeavor** [lhorie/mithril.js#542]
I just ran into this while changing my routes paths. The following fails with a `Maximum call stack size exceeded` error. It'd be cool to get a more specific error message instead.

```javascript
m.route(document.getElementById('app'), '/a', {
  '/b': {
    view: function () { return m('div') }
  }
})
```

**Comment by Naddiseo** [comment]
dup of #275

**Comment by lhorie** [comment]
fixed in origin/components
