### ISSUE TITLE
bug in components branch with {class: undefined}

### ISSUE THREAD

**Issue by farzher** [lhorie/mithril.js#544]
Probably I shouldn't be doing this anyway. But sometimes I'm lazy and end up setting the class to undefined

```js
return m('div.a', {class: undefined}, 'hi')
```

This used to produce `class="a undefined"`
But in components branch it's now `class="aundefined"`

**Comment by farzher** [comment]
I think this should just produce `class="a"`

You can return the string `"undefined"` if you really need undefined as a class. A literal undefined should not be added as a class

**Comment by lhorie** [comment]
Fixed in components branch

**Comment by farzher** [comment]
I can go back to being lazy, and remove my extra undefined checking code
:+1:
