### ISSUE TITLE
Can't force redraw in an autoredraw context

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#551]
I am using a component hierarchy. I want to make a click handler that:

1. Makes a change to some data
2. Forces a synchronous redraw
3. Does something with the new DOM

I would expect the following code to work:

```javascript
return m('div', {onclick: function() {
  app.foo = 'bar';
  m.redraw(true);
  document.getElementById('whatever') // do something with new DOM
  m.redraw.strategy('none') // prevent another redraw
}});
```

But because the handler is run in an autoredraw context (m.startComputation has been called), the m.redraw call is causing the on-screen components to be removed from the DOM. This line is the problem: https://github.com/lhorie/mithril.js/blob/components/mithril.js#L244

**Comment by lhorie** [comment]
Fixed
