### ISSUE TITLE
$document.body unavailable when testing m.request with dataType: "jsonp"

### ISSUE THREAD

**Issue by stumpdk** [lhorie/mithril.js#553]
When running unit tests of methods using dataType: "jsonp", the following exception is thrown:

TypeError: Cannot read property 'appendChild' of undefined
at ajax (mithril.js:968)
at Function.m.request (mithril.js:1049)

The exception isn't thrown if dataType is set to "json".

**Comment by lhorie** [comment]
does your mock have `document.body.appendChild` ?

**Comment by stumpdk** [comment]
I'm using the mock.js from the tests folder in this repository. But I can see that it is missing.
My *.spec file starts like this:
mock = m.deps(mock.window);

**Comment by lhorie** [comment]
Ah yeah, mock.js doesn't have document.body. In the core test suite, I create it manually. Here's an example: https://github.com/lhorie/mithril.js/blob/next/tests/mithril-tests.js#L2510-L2528

**Comment by stumpdk** [comment]
Adding the document.appendBody does not solve the overall problem: When calling m.request in a test, the mocked method XMLHttpRequest is only called when the dataType in xhrOptions is different from "jsonp".
In other cases, a script tag containing the data is loaded to the document, and the XMLHttpRequest is not run ([it happens here](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L1025)).

If I want to test a method, that runs m.request({url: "/someUrl", dataType: "jsonp"), how can I catch the request, and fake the data returned, in the mock object?
