### ISSUE TITLE
Config context 'retain' set to true if node is introduced during a diff, leading to counterintuitive behaviour when routing

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#554]
```javascript
var MyComponent = {
  controller: function() {
    this.showing = false;
  },
  view: function(ctrl) {
    return m('div', [
      m('button', {onclick: function() { ctrl.showing = true; }}, 'show'),
      ctrl.showing ? m('div', {config: function(element, isInitialized, context) {
        if (isInitialized) { return; }

        console.log('loading', context)
        context.onunload = function() {
          console.log('unloading')
        }
      }}, 'showing') : ''
    ]);
  }
}
var IndexPage = {
  view: function() {
    return m('div', [
      m('a[href=/]', {config: m.route}, 'page 1'),
      m('a[href=/2]', {config: m.route}, 'page 2'),
      m('a[href=/3]', {config: m.route}, 'page 3'),
      m.component(MyComponent)
    ]);
  }
};
m.route(document.body, '/', {
  '/': IndexPage,
  '/2': IndexPage,
  '/3': IndexPage
})
```

The MyComponent controller is instantiated with `showing` as false. When the button is clicked, `showing` is set to true and an autoredraw is triggered with the redraw strategy as 'diff'. The 'showing' node is created and its config is run - and according to https://github.com/lhorie/mithril.js/blob/components/mithril.js#L321, the retain property of the config context is automatically set to true.

As a result, when clicking between any of the routes after this has taken place, the node is retained, even though the redraw strategy is 'all'.

This was causing complex problems in my app which I didn't get to the bottom of for hours. I don't think it's very intuitive to automatically set retain to true if a node is created during a diff. What's wrong with leaving it as undefined?

**Comment by lhorie** [comment]
I was just setting it for the sake of consistency, but yeah, this isn't right. I've now changed it to not auto-initialize the flag
