### ISSUE TITLE
Way to replace URL without routing

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#559]
I need to update the URL according to the user's scroll position. I've set up a scroll handler; currently I can see a few options on how to go about this:

**1)** I can manually call the following:
```javascript
window.history.replaceState(null, document.title, (m.route.mode === 'hash' ? '#' : '')+myRoute);
```
However, Mithril's current route state is not updated so subsequent calls to m.route() or m.route.param() are incorrect. Additionally, it's not very nice to have to manually specify the route mode prefix.

**2)** I can call `m.route(myRoute, true)` and then prevent unloading in the controller's onunload handler. This way, Mithril's current route state is updated. However, the actual URL is not, because `computePostRedrawHook` (where replaceState is called) is never run.

(I guess this is actually kind of a bug — if an onunloader prevents the transition, Mithril's current route state should not be update. It turns out that this is actually quite useful though, because it gives onunloaders a way to know what the next route is. Feature, not a bug :))

**3)** I can do a combination of 1 + 2, but that isn't very nice.

Would it be possible to get some kind of API, perhaps a fourth argument in m.route, that tells Mithril to update the current route state and the URL without following through with any remounting/drawing?

**Comment by lhorie** [comment]
In rewrite branch, routing no longer updates scroll position, and it no longer redraws from scratch, although it does replay the redraw with updated route arguments.
