### ISSUE TITLE
Seems unnecessary build call at the end of each element's hierarchy

### ISSUE THREAD

**Issue by dhinesh03** [lhorie/mithril.js#562]
**Low priority**
1) On line number 275 (v0.1.34), you haven't checked the following condition 
```
cached.children = (data.children != null && data.children.length > 0 || cached.children != null && cached.children.length > 0) ?
				 		build(node, data.tag, undefined, undefined, data.children, cached.children, false, 0, data.attrs.contenteditable ? node : editable, namespace, configs) : 
				 		data.children;
```
So, unnecessarily build function has been invoked once at the end of every element's hierarchy.
I found this when i was log the iteration count of build call.

2) Another question is, if attribute's value is a FUNCTION(onclick,onblur,etc) callback then will it be overwritten always by setAttributes function on every redraw? 
For example : 
```
dataAttr:function (e) {
        target = moduleName
        callback.call(this, e)
      }
cachedAttr:function (e) {
        target = moduleName
        callback.call(this, e)
      } 
```
``` (cachedAttr !== dataAttr) ``` condition always fails on line no 341.

**Comment by lhorie** [comment]
re: 1) pretty sure there's no unnecessary calls to `build`. That function recurses on arrays, so a list of child nodes always triggers at least 2 calls if there's at least one child. Are you counting the calls from arrays?

re: 2) yes, they are always overwritten because closures

**Comment by dhinesh03** [comment]
Thanks for the quick response @lhorie
1) I've added this  ```console.log('iterationCount='+ ++iterationCount +' data = '+ JSON.stringify(data));``` on the first line of build function. 
And i've reset it ```iterationCount = 0 ``` on the last line of m.endComputation function. 
Here is the [jsfiddle link] (http://jsfiddle.net/Lkrpkcfn/4/) .
Check out the console log. First time render of the view takes 11 iteration. After that every redraw takes 13 iteration.

**Comment by lhorie** [comment]
Ohhh, now I see what you mean. In that case, the extra build call is to handle removals, e.g. `m("div", [1])` => `m("div", [])`
