### ISSUE TITLE
Template compiler generates error

### ISSUE THREAD

**Issue by Helidium** [lhorie/mithril.js#565]
Hi,

when I run the template compiler i get the error:

Template:

/** @jsx m */
mainApp.views.dashboard.index = function( controller ) {
	"use strict";
	var activeGroup = mainApp.data.activeGroup;

	return  <div id="dashboard" config={ function(e,i,c) { ImageComponent.load( document.getElementById('dashboard-header-icon-image') ); document.getElementById('dashboard-header-icon-image').style.height = document.getElementById('dashboard-header-icon-image').style.width = (document.getElementById('dashboard-header-icon').clientWidth - 20) + 'px';controller.config(e,i,c)} }>
				<div id="row-top" class="table-row">
					<div class="row-cell">
						{mainApp.views.utils.topBar()}
					</div>
				</div>
				<div id="row-bottom" class="table-row full">
					<div class="row-cell row">
						<div id="main-menu-holder">{mainApp.views.menu.mainMenu()}</div>
						<div id="dashboard-items-holder" class="row">
							<div id="side-menu-holder" class="col-xs-3">
								{ mainApp.views.menu.documents( mainApp.data.groups ) }
							</div>
							<div id="dashboard-content-holder" class="col-xs-9">
								<div id="dashboard-content">
									<div id="dashboard-image"></div>
									<div id="dashboard-header">
										<div class="row">
											<div id="dashboard-header-name" class="col-xs-5">{ User.name() }</div>
											<div id="dashboard-header-icon" class="col-xs-2"><img id="dashboard-header-icon-image" data-src={ activeGroup.info.icon } /></div>
											<div id="dashboard-header-stats" class="col-xs-5">
												<dl data-title>
													<dt>Last login</dt><dd></dd>
													<dt>Local files</dt><dd></dd>
												</dl>
											</div>
										</div>
									</div>
									<div id="dashboard-data">
										<div class="row">
											<div class="col-xs-4">
												<div class="card">
													<div class="card-header row">
														Calendar<i class="fa fa-long-arrow-right float-right"></i>
													</div>
													{ CDashboardHelper.mapObject( activeGroup.agendas, function( agenda ) {
														return <div class="card-section">
															<h4>{ agenda.timestamp }</h4>
															<h5>{ agenda.title }</h5>
															<div>{ agenda.description }</div>
														</div>;
													} ) }
												</div>
											</div>
											<div class="col-xs-4">
												<div class="card">
													<div class="card-header row">
														News<i class="fa fa-long-arrow-right float-right"></i>
													</div>
													<div class="card-section">
														<div>Mail</div>
														<div><strong>{ activeGroup.info.mail }</strong></div>
													</div>
													<div class="card-section">
														<div>Phone</div>
														<div><strong>{ activeGroup.info.phone }</strong></div>
													</div>
													<div class="card-section">
														<div>Address</div>
														<div><strong>{ activeGroup.info.address }</strong></div>
													</div>
												</div>
											</div>
											<div class="col-xs-4">
												<div class="card">
													<div class="card-header row">
														Members<i class="fa fa-long-arrow-right float-right"></i>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
};

**Comment by dhinesh03** [comment]
I've also tried to use it but it always throws the error.
npm version is 2.7.6, Sweet.js version is 0.7.4, mithril version is 0.1.34 and
test.js code :
``` 
todo.view = function() {
    return m("html", [
        m("body", [
            m("input"),
            m("button", "Add"),
            m("table", [
                m("tr", [
                    m("td", [
                        m("input[type=checkbox]")
                    ]),
                    m("td", "task description"),
                ])
            ])
        ])
    ]);
};
``` 
![screen shot 2015-04-16 at 7 52 19 pm](https://cloud.githubusercontent.com/assets/750200/7196393/8b9cf9f6-e4ee-11e4-8db3-1df0e6bb096e.png)

**Comment by Helidium** [comment]
I have created a npm package called msx-optimized, that transforms templates to optimized mithril format.

It can be found here:
https://github.com/helidium/msx-optimized

**Comment by lhorie** [comment]
This is fixed in the components branch
