### ISSUE TITLE
buildQueryString / parseQueryString round-trip error

### ISSUE THREAD

**Issue by ariutta** [lhorie/mithril.js#566]
Thanks for your work on a great library!

Should buildQueryString followed by parseQueryString reproduce the original input? If so, the following round-trip test case fails for mithril@0.1.34.

# Test Case

```js
parseQueryString(buildQueryString([
  {
    name: "earth",
    color: "blue"
  },
  {
    name: "mars",
    color: "red"
  }
]));
```

# Expected Result

```js
[
  {
    name: "earth",
    color: "blue"
  },
  {
    name: "mars",
    color: "red"
  }
];
```

# Actual Result

```js
{
  0[name]: "earth",
  0[color]: "blue",
  1[name]: "mars",
  1[color]: "red"
}
```

**Comment by ariutta** [comment]
Maybe this is a better test case:

```js
parseQueryString(buildQueryString({planet: [
  {
    name: "earth",
    color: "blue"
  },
  {
    name: "mars",
    color: "red"
  }
]}));
```

**Comment by ariutta** [comment]
To give some context, I'm working on an open-source biological data project that involves [embeddable diagrams](http://wikipathways.org/index.php/PathwayWidget) with optionally highlighted elements. The existing URIs look like this:

http://www.wikipathways.org/wpi/PathwayWidget.php?id=WP4&label[]=APC&label[]=TP53&label[]=ATP&colors=green,red,blue

which is intended to encode this data:

```js
{elements: [
  {
    label: "APC",
    color: "green"
  },
  {
    label: "TP53",
    color: "red"
  },
  {
    label: "ATP",
    color: "blue"
  }
]}
```

I'm trying to use mithril routing to handle both the highlight query params and additional application state (e.g., ``/editor/disabled``), but if I set my default route to ``/editor/disabled``, a URI like this:

http://www.wikipathways.org/wpi/PathwayWidget.php?id=WP4&label[]=APC&label[]=TP53&label[]=ATP&colors=green,red,blue&/editor/disabled

loses the highlight query params because it redirects to just:

http://www.wikipathways.org/wpi/PathwayWidget.php?/editor/disabled

Thanks for any suggestions!

**Comment by barneycarroll** [comment]
Hi @ariutta, I find that serious URI modelling requirements are beyond the scope of Mithril's routing capabilities, which are designed to provide a simple, unopinionated page-routing mechanism. For my purposes, I use [URIjs](http://medialize.github.io/URI.js/), and then I'll query via `URI( m.route() )`. when I've finished manipulating, I'll pass the result in through `m.route( uriInstance.toString() )`.

**Comment by ariutta** [comment]
Makes sense. I'll give that a shot. Thanks.
