### ISSUE TITLE
How to override scroll-to-top on route transition?

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#567]
Mithril automatically scrolls to the top when m.route is called (via computePostRedrawHook). I would like to prevent this from happening and immediately scroll down to a certain point as soon as the page is rendered.

I would think I could do this in a node's config function, but it seems that computePostRedrawHook is called after the config functions are run. The only other way I can think of is to use setTimeout, but that results in a slight delay which isn't nice.

**Comment by barneycarroll** [comment]
@tobscure reading through the source, Mithril has a special exception for this [when you're using a routing mode other than hash (path or query), and you have a hash specified](https://github.com/lhorie/mithril.js/blob/ce20520f3a4aa60ffa9260692da950c797f93cea/mithril.js#L711). This sounds ideal – you could use the hash either to refer to the ID of the element you're scrolling to or some abstract that represents it…?

**Comment by tobscure** [comment]
@barneycarroll Problem is, I'm using the hash route mode, at least for the time being!

I think there needs to be a proper way to do this. Would running the configs after the postRedrawHook create any problems?

**Comment by barneycarroll** [comment]
Don't think so — believe config execution is tail-called by build, so these secure before the scroll reset :/

**Comment by lhorie** [comment]
@tobscure it's a somewhat contrived edge case, but technically, yes, running configs after postRedrawHook would mean that document.title changes in a config would not be reflected in the browser history

I'm assuming this issue only really exists because of the lack of support for #559?

**Comment by tobscure** [comment]
@lhorie No this is a separate issue for me. #559 is regarding updating the URL when the user scrolls; this one is regarding setting the scrolling position when routing into a URL that specifies a scroll position.

Yeah I took a look and I guess it would need to be render -> scrollTo(0, 0) -> run configs -> pushState. Could we add a preConfigHook?

**Comment by barneycarroll** [comment]
> document.title changes in a config

@lhorie hang on – are you saying the current execution order exists to preserve *that* feature?

**Comment by lhorie** [comment]
@tobscure yeah I think that makes more sense

**Comment by tobscure** [comment]
@lhorie if you think a preConfigHook sounds like a good solution, I can do a PR?

**Comment by lhorie** [comment]
Actually, just pushed a change for it. It's in the components branch

**Comment by tobscure** [comment]
Fantastic, thanks!

**Comment by barneycarroll** [comment]
Can we just rename `components` to `master`? ;)
