### ISSUE TITLE
bug when setting a select value to emty (null or "") while changing number of attrs

### ISSUE THREAD

**Issue by ldimi** [lhorie/mithril.js#569]
When changing the number of attributes  on a select node, the node gets recreated.
But when you set the value to empty at te same time, this is'nt enforced on the select node, resulting in an inconsistent ui.

I made a fiddle to illustrate the problem : https://jsfiddle.net/cnrdz0n9/3/
(Just toggle a few times between "two" and empty)

(this worked until version 0.1.22)

**Comment by lhorie** [comment]
Fixed in components branch
