### ISSUE TITLE
Ignore 'false' when building DOM?

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#572]
Where you use a ternary operator like this:

```javascript
m('div', showing ? 'foo' : '')
```

I think it would a bit more sugary to be able to do this:

```javascript
m('div', showing && 'foo')
```

But Mithril will actually output "false" as a string in the latter case if `showing` is false.

**Comment by barneycarroll** [comment]
@tobscure ternary statements seem awesome in Mithril views but they're not quite expressive enough. I wrote [this little helper](https://gist.github.com/barneycarroll/6718f48295b285cf39ec) that I use all over my views – you may find it handy. It's a function that follows the same syntax as a ternary operator (first argument is the condition, second is the truthy outcome, third is falsey – defaulting to empty string if it is falsey (including absent) itself.

So your code above would end up being:

```javascript
m( 'div', tern( showing, 'foo' ) )
```

One of the failings of this method is that in a function invocation, all the arguments are executed before function execution – a common scenario in views is checking for whether a promise has resolved or not before executing a sub-view which may break if the data structure it expects doesn't exist. So for that, you get `tern.defer`, which will execute functions passed in as outcomes when the condition is tested for:

```javascript
m( '.searchResults', tern.defer(
  ctrl.results,
  function resultsView(){
    m( 'ol', ctrl.results.map( function itemView( item ){
      return m( 'li', item )
    } ) )
  }
) )
```

**Comment by lhorie** [comment]
Two thoughts that pop to my mind are: 1) the `cond && alt` idiom is often considered too clever (in a bad way), and 2) `false` printing `""` reminds me of PHP's confusing feature that does the same thing

How about writing a helper that turns `false` into `""`? e.g. `pf(showing) && "foo"`?

**Comment by tobscure** [comment]
@lhorie fair enough, I guess I could also do something like `(showing || '') && 'foo'`, but that's just extra confusing - may as well just use ternary operator.
