### ISSUE TITLE
Cannot route on top of a base path

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#585]
For example if I have an app at http://mysite.com/admin and I want Mithril to route like http://mysite.com/admin#/whatever.

Currently Mithril just strips the URL back to the origin (http://mysite.com/#/) as soon as the page loads. This is because the window.history.pushState call provides a relative URL without the base path prepended.

Could we get a simple API added? Something like:

```javascript
m.route.base = '/admin'
```

Then it would just be prepended when window.history.pushState is invoked, i.e. `(m.route.base || '') + modes[m.route.mode] + currentRoute`

Happy to do a PR if you think this is a good idea.

**Comment by tobscure** [comment]
@lhorie Nope, this on localhost

This is strange, I read more into the window.history.pushState API and it seems this shouldn't be happening. I set up an isolated test (a page within a couple subdirectories which simply calls pushState) and couldn't reproduce. I'll keep investigating.

**Comment by tobscure** [comment]
@lhorie Sorry! I had a <base href="/"> tag that slipped through the cracks. Problem solved.

**Comment by mindeavor** [comment]
I'm running into the same problem. If it is in fact the `file://` protocol that's causing the issue, do you have any ideas for a workaround that we could try, @lhorie ?

**Comment by lhorie** [comment]
Reopening this re: `file://` protocol

**Comment by lhorie** [comment]
@mindeavor I tried setting up a minimum test case in cordova and it's working fine:

```javascript
document.addEventListener('deviceready', function() {
	var A = {
		view: function() {
			return m("div", [
				m("div", location.href),
				m("div", m.route()),
				m("a[href='/b']", {config: m.route}, "go to b")
			])
		}
	}
	var B = {
		view: function() {
			return m("div", [
				m("div", location.href),
				m("div", m.route()),
				m("a[href='javascript:;']", {onclick: function() {m.route("/a")}}, "go to a")
			])
		}
	}

	m.route.mode = "hash"
	m.route(document.getElementById("a"), "/a", {
		"/a": A,
		"/b": B,
	})
}, false);
```

Are you able to provide a minimum test case where you can reproduce the issue?

**Comment by zah** [comment]
Setting a base URL would also be useful when `m.route.mode` is set to `pathname`. As far as I can tell, currently it's not trivial to switch between the various routing modes, when your application lives under a certain base path such as `/admin`.

In my project, I've a made a very thin wrapper around `m.route` and the component responsible for handling navigation and now I can switch between the routing modes without modifying the rest of the code.

**Comment by lhorie** [comment]
rewrite should work fine w/ file:// protocol and non-root pathnames as well (the latter thanks to @pygy )
