### ISSUE TITLE
m.route.mode should be an m.prop()

### ISSUE THREAD

**Issue by Naddiseo** [lhorie/mithril.js#590]
For consistency with `m.redraw.strategy`, I think `m.route.mode` should also be an `m.prop()`.

**Comment by Nijikokun** [comment]
Conversely make `m.redraw.strategy` a `String` for consistency.

**Comment by Naddiseo** [comment]
@Nijikokun, indeed; I considered that, here are my arguments against changing `m.redraw.strategy` to a `String`: 

1. Everything else in the mithril api (except for `m.deps.factory`) uses function syntax.
2. Dogfooding.

**Comment by Nijikokun** [comment]
I'd rather it be a string because you don't have to invoke a function to do a memory lookup every redraw. Just my personal opinion on the matter.

**Comment by Naddiseo** [comment]
Other than personal opinion, I don't think that argument has much weight. `m.redraw.strategy` for the most part will be the same value every time it's called, so I suspect browsers would be able to optimize it. Said another way: I don't think there's much overhead of `m.redraw.strategy` being a function.

Here's a naive jsperf: http://jsperf.com/prop-vs-string

**Comment by Nijikokun** [comment]
Yeah they are pretty even, updated it to be a little more about the performance of the strategy with more iterations: http://jsperf.com/prop-vs-string/2

So either is good by me.

**Comment by lawrence-dol** [comment]
I agree. 

While we are at 0.x I will always favor addressing inconsistencies in the API even if it means occasional breaks. One possibility to avoid an immediately breaking change is to use a new name:

    m.route.strategy=m.prop();

and fall back to `m.route.mode` somehow, perhaps by setting `m.route.mode` initially to `null` and using it if non-null. Provided the fallback is clearly marked and removed in 1.x.

**Comment by lhorie** [comment]
In rewrite it's a setter called `prefix` (which defines the actual desired prefix, as opposed to a location mode). Getting it after the fact doesn't really make any sense (and even setting doesn't make sense except to keep 0.2.x ease-of-configuration, vs passing the desired prefix as a parameter to a factory)
