### ISSUE TITLE
Mithirl.d.ts Compile Errors

### ISSUE THREAD

**Issue by blacha** [lhorie/mithril.js#592]
I am getting a number of compile errors when compiling the current ``next`` branch with Typescript 1.4 and 1.5 :
```
mithril.d.ts(5,101): error TS2314: Generic type 'MithrilModule<T>' requires 1 type argument(s).
mithril.d.ts(6,70): error TS2314: Generic type 'MithrilModule<T>' requires 1 type argument(s).
```

You can reproduce this by running:
```
npm install -g typescript
tsc mithril.d.ts
```

**Comment by lhorie** [comment]
I've pushed a change that should hopefully fix it. Let me know if you run into any issues
