### ISSUE TITLE
Organize wiki

### ISSUE THREAD

**Issue by lhorie** [lhorie/mithril.js#593]
It's kinda messy right now...

**Comment by pelonpelon** [comment]
+1
@lhorie : "yeah I was thinking we could have three pages: one for projects consuming mithril, one for projects that complement mithril, and one for links to snippets and patterns" [April 27 2015 10:55 AM](https://gitter.im/lhorie/mithril.js?at=553e5bdc1035e6b2060399c8)

Several links on the Community page would need to be transferred to one of the above pages and the links from the spreadsheet distributed accordingly.

#### Tools that complement Mithril but are not part of userland source code:

- Sublime/Vim/Textmate/Atom snippets
- Sweet.js macros
- pre-processors (MSX, jss/mjss)

#### Projects consuming mithril (with accessible source code) :

- todomvc
- lichess (UI)
- the various starter kits

#### Snippets and patterns would preferably link to working examples on jsfiddle/jsbin/plunker etc.

---

Recommended tutorials should be collected on the Mithril home page, but there might also be a page for "secondary" tutorials, boilerplates, starter kits (Further Learning ?). The good ones might graduate to the home page when mature.

---

@lhorie The wiki home page needs an intro that you should write. Something about community contributions and "what you'll find here" ?

---

I'd be happy to contribute to this effort. With the merging of the components branch and the crazy interest coming from Japanese Twitter, I think organizing learning materials should be a high priority.

**Comment by lhorie** [comment]
> Recommended tutorials should be collected on the Mithril home page, but there might also be a page for "secondary" tutorials, boilerplates, starter kits (Further Learning ?). The good ones might graduate to the Mithril home page when mature.

I really like this idea

**Comment by barneycarroll** [comment]
:+1:

**Comment by lhorie** [comment]
FYI, I started to organize it. Anyone wants to start putting the stuff in the uncategorized section (especially the items in the google spreadsheet) into their appropriate sections?

**Comment by pelonpelon** [comment]
Gotta do some paid work. I'll work on it later if no one beats me to it.

**Comment by pelonpelon** [comment]
Spreadsheet links copied to wiki page.
Done.

@lhorie Could you look over the uncategorized section and find homes for those things. The spreadsheet link can be removed. I didn't want to be so bold ;)

**Comment by pelonpelon** [comment]
@lhorie I was thinking, now that events (meet-ups, periscope streams, talks) are happening, You might want to reserve a place for them on the Mithril home page.

Same goes for Mithril in-the-news. You commented that you missed a long Reddit post recently. The Twitter links at the bottom of the home page are very stale.

I think the footer could use a makeover.
