### ISSUE TITLE
npm/cdnjs should be updated to v0.2.0

### ISSUE THREAD

**Issue by pelonpelon** [lhorie/mithril.js#597]
https://www.npmjs.com/package/mithril
http://cdnjs.cloudflare.com/ajax/libs/mithril/0.2.0/mithril.min.js

BTW:
the component pkg manager is working but the link to component.io on the installation page is dead
http://component.io/

**Comment by lhorie** [comment]
I'm giving it a day to publish to npm, because something always comes up and you can't overwrite published versions there.

I fixed the component.io link

**Comment by barneycarroll** [comment]
There is precedent – `npm install 0.1.34-beta.0`…
