### ISSUE TITLE
components.md

### ISSUE THREAD

**Issue by pelonpelon** [lhorie/mithril.js#598]
@lhorie in [m.component](http://lhorie.github.io/mithril/archive/v0.2.0/mithril.component.html) the prefered way to pass the controller object is with the controller function return value, avoiding `this`, although later in the document you offer the option to use `this`.

I think [components.md](http://lhorie.github.io/mithril/archive/v0.2.0/components.html) should reflect the same philosophy to be consistent. At present the doc uses `this` throughout.

**Comment by tivac** [comment]
A PR would be happily merged.
