### ISSUE TITLE
Issues when i extend the component

### ISSUE THREAD

**Issue by dhinesh03** [lhorie/mithril.js#604]
I had an issue when i extend the component. For example  [multi-tenancy.js](https://gist.github.com/dhinesh03/4408820e78d14738f979). Everything works fine except the component controller. The controller function is invoked every time when the component is re-rendered. The reason is  data.view.$original also an wrapper function when i use the multi-tenancy.js, So the following line(line number 245 on mithril js) always return the -1 as controllerIndex.
```
var controllerIndex = m.redraw.strategy() == "diff" && cached.views ? cached.views.indexOf(view) : -1
```
Any ideas , how to override this issue ?

**Comment by lhorie** [comment]
You could set `view.$original = component.view`

**Comment by dhinesh03** [comment]
@lhorie If i do that i won't need to call the m.component right ?
```m.component.apply(undefined,[tenant(componentName,component)].concat(args)); ``` 
If i call the m.component anyway it will overwrite  the ``` view.$original = component.view ``` statement on parameterize function.

**Comment by lhorie** [comment]
m.component merely parameterizes the component. I'm saying to set `view.$original` of the final output component

**Comment by dhinesh03** [comment]
Thanks @lhorie It works :+1:
