### ISSUE TITLE
Way to retain a node/subtree between different positions in the DOM

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#607]
Suppose on one page I have a Mithril DOM structure like this:

```html
<div class="level1">
  <div class="expensive">expensive-to-draw subtree</div>
</div>
```

Then on another page, I have a more complex DOM structure like this:
```html
<div class="level1">
  <div>something</div>
  <div class="level2">
    <div>something else</div>
    <div class="expensive">expensive-to-draw subtree</div>
  </div>
</div>
```

Is there any way to retain div.expensive when redrawing between the two pages? I don't imagine that {subtree: "retain"} and context.retain will work in this scenario because the expensive div is in a completely different DOM position between the pages.

Any ideas?

**Comment by lhorie** [comment]
Hmm, no, subtree/context:retain won't work. Would copying the innerHTML of the tree work?

**Comment by tobscure** [comment]
Then it would lose all DOM state, and Mithril won't have it cached so won't be able to diff it

**Comment by tobscure** [comment]
What about some kind of global key mechanism. So in both pages the div.expensive would have an attribute like `{globalKey: 'whatever'}`, and then Mithril's diff algorithm would match them together and be able to retain.

**Comment by pelonpelon** [comment]
I've been thinking a lot about this. In my head I call it the ' globalKeyCache'. In a closed system it would just be an array, keeping order (for list maintenance) and telling the diff engine to trust when a key is matched. If matched, even in a different part of the vDOM, it would be 'retained'. With each render, unclaimed keys would be discarded -- functionally similar to the current key system but applicable to any element with a default of 'retain'. @tobscure I think this is what you're proposing. Finer grained control than subtree:retain, more general than the current key mechanism. It would be up to the dev to change keys (i.e. when data is potentially stale) -- with great power comes great responsibility!!. 

The idea begs endless questions, but the first that comes to mind is the problem that @lhorie and @barneycarroll have been discussing WRT components: You'd have to namespace keys to avoid collisions/overwriting from outside components, plugins, and libraries, which is a hard problem.

**Comment by tobscure** [comment]
@pelonpelon Yep, more or less exactly what I was thinking. Would love to see this!

FYI, my use-case is on http://demo.flarum.org when jumping back and forth between the discussion list and a discussion. The discussion list itself is a component which is placed in a different DOM structure on each page (main content vs. sidebar that slides out on the left). If you keep "loading more" discussions to make the list longer, then jumping back and forth between pages gets noticeably slower.

**Comment by pelonpelon** [comment]
@tobscure I see. So you'd like to keep list entries cached (retained) and let both components have access to the cache? Could you do that in userspace and abandon the retain mechanism altogether?

**Comment by pelonpelon** [comment]
@tobscure Flarum is gorgeous, BTW!

**Comment by tobscure** [comment]
@pelonpelon Thanks! Yeah the component instance itself is already cached between pages, so it doesn't have to reload data. The slowdown is with rebuilding the component's DOM each time because it's not retained.

**Comment by lhorie** [comment]
After much research, this doesn't seem very feasible and no other library even gets close to attempting it, so I'm going to `wontfix` this.
