### ISSUE TITLE
Child component controller's unload called multiple times on route change?

### ISSUE THREAD

**Issue by deakster** [lhorie/mithril.js#614]
Not 100% sure if this is an actual issue or just me being stupid since I'm very new to Mithril, but here is what I found: http://plnkr.co/edit/YW26xWCcwPF8MSdnGUfq?p=preview

When a child component's controller has an onunload function, it will get called on route change as many times as there were view re-renders on the previous route. The controller for the component was only constructed once, but in my case the onunload could end up getting called hundreds of times due to the dynamic nature of my UI.

**Comment by a-s-o** [comment]
Hello, just chiming in to say that I am also experiencing the same issue. I have a page with 2 child components. On route change only 2 controllers (once for each component) are instantiated but when I change the route again (onunload is called 4 times - i.e. twice for each component)

If I navigate to the page with the components and do a browser refresh 2 components are instantiated as expected and on route change 2 are unloaded. Therefore, the issue appears to be only during navigation within the app and not on refreshes
