### ISSUE TITLE
e2e tests failures

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#616]
In Firefox 37/OS X, when running the whole e2e test suite, there's a weird case of "jumping failure" between test 2 and 3. While the test suite is running, they alternate between success and failure. When run independently, they work ok.

In Chrome, I get an "issue214 regression" (#214).

**Comment by pygy** [comment]
I've also gotten an e2e "#288 regression" in FF, but it is intermittent.

**Comment by lhorie** [comment]
e2e tests are deprecated in favor of @isiahmeadows' new test suite
