### ISSUE TITLE
SVG <use> element

### ISSUE THREAD

**Issue by JasonHoffmann** [lhorie/mithril.js#620]
I'm having an issue when trying the "use" tag within an SVG tag. Is there any support for bringing in external SVG? For instance, with the code:

```javascript
m('svg.icon.icon-check[viewBox="0 0 100 100"]', [
    m('use[xmlns:xlink="http://www.w3.org/1999/xlink"][xlink:href=svg/spritemap.svg#check-circle][height="20"][width="20"]')
    ])
])
```

I would like to render an external SVG file. The HTML renders as expected, but no SVG is loaded in. Does anyone know why this might be?

Rendered HTML:

```html
<svg viewBox="0 0 100 100" class="icon icon-check">
    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="svg/spritemap.svg#check-circle">
    </use>
</svg>
```

**Comment by lhorie** [comment]
you need to remove the namespaces:

```javascript
m('svg.icon.icon-check[viewBox="0 0 100 100"]', [
    m('use[href=svg/spritemap.svg#check-circle][height="100"][width="100"]')
])
```

**Comment by JasonHoffmann** [comment]
Perfect! Thanks.

**Comment by chadfurman** [comment]
I'm having a similar problem here: https://github.com/lhorie/mithril.js/issues/1297

Originally, I didn't have the namespace attribute at all, so I don't think that's the problem (for me, atleast)
