### ISSUE TITLE
Minor reorganization of wiki (again)

### ISSUE THREAD

**Issue by pelonpelon** [lhorie/mithril.js#621]
The wiki is growing, and it's common to see questions answered on Gitter with: "see page X on the wiki". I don't want to stir the pot too much, but I think it would be good to enforce a little discipline on the wiki before it becomes a mess -- especially pre-Mithril 1.0

I propose the following changes:

1. rename **Basic Recipes** to **Recipes and Snippets**
  - raw code most likely found in a gist
  - cut-and-paste, tweak, move on -- kind of stuff
2. move **Proofs of Concept** to new **Recipes and Snippets**
3. move some **Miscellaneous** entries to new **Recipes and Snippets**
4. rename **Community Projects and Snippets** to **Community Projects**
  - exclusively "named" projects, most likely github projects
5. add a short intro to each page explaining "what you'll find here"
  - help users find what they want
  - guide contributors in adding links to the correct pages
6. move **Components** section to its own page
7. create a **FAQ**
  - when exploring new tech, many developers look for the FAQ
  - would act as a clearing house for questions repeatedly asked on Gitter
  - answers might be redundant -- many would just link to the docs and other wiki pages
8. **Solutions to Common Problems**  -- coding howto's (i.e. Leo's blog entries), not drop-in recipes
  - not really a change, just a guideline

I'm happy to make any or all of these changes.
@lhorie I await your approval -- or disapproval ;)

**Comment by lhorie** [comment]
Feel free to organize it however you feel makes the most sense. The only thing to be aware is that the Community Projects and Snippets page is linked from the main site, so that page needs to not 404 (you could just add a link to the new page for now, and I'll update the link in the docs)

**Comment by pelonpelon** [comment]
I'm done reorganizing.

There's a new page called [**Example Applications**](https://github.com/lhorie/mithril.js/wiki/Example-Applications). These are working applications that use Mithril. They differ from the "Who's Using" page in that the code is accessible -- and probably open source.

The renamed "Community Projects" page is located here: https://github.com/lhorie/mithril.js/wiki/Community-Projects

When you change the link on the homepage, could you please delete the old [**Community Projects and Snippets**](https://github.com/lhorie/mithril.js/wiki/Community-Projects-and-Snippets) page?

Thanks
