### ISSUE TITLE
ie8 woes with v0.2.0

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#625]
http://j2c.py.gy/ietest.html

==> `'length' is null or not an object` on [line 430](https://github.com/lhorie/mithril.js/blob/26a6664cd02623c8b7c44e60ef47a98dd797ab29/mithril.js#L430).

It is triggered by mounting a basic template on a span.

**Comment by tivac** [comment]
http://mithril.js.org/tools.html#internet-explorer-compatibility

**Comment by pygy** [comment]
I use a polyfill.io as recommended.

**Comment by lhorie** [comment]
I ran the code from Browserstack and aside from the error reported on line 42 of the html file (using `class` as an object key is considered a syntax error by IE8), there were no other errors

**Comment by suhaotian** [comment]
```js
m('span', {class: 'test', id: 'test'}, 'hello mithril.js!');
```
recommend to write like this: 
```js
m('span', {'class': 'test', 'id': 'test'}, 'hello mithril.js!');
```
