### ISSUE TITLE
Minor typo in API reference for m.component

### ISSUE THREAD

**Issue by nkabir** [lhorie/mithril.js#626]
In the *Nesting Components* section, `ctrl` should be `controller`:

```
var App = {
    ctrl: function() { // <== 
        return {data: [1, 2, 3]}
    }
    view: function(ctrl) {
        ...
    }
}
```

https://lhorie.github.io/mithril/mithril.component.html

**Comment by venning** [comment]
@nkabir This was fixed in [a previous commit](https://github.com/lhorie/mithril.js/commit/b70b4191b7c9589c4e6a4a4383393ca27bbe98ad#diff-7832f3c009c7802819bae024dc183736).  It appears that the site just hasn't been updated yet.
