### ISSUE TITLE
Add catch to Mithril's Promise

### ISSUE THREAD

**Issue by lawrence-dol** [lhorie/mithril.js#627]
From everything I've read, the Promise/A+ API includes a `catch` function. While this is just syntactic sugar on `then(null,xxx)` I'd really love to have the clear visual confirmation of having a final catch on all my promise chains.

    m.request(...)
    .then(function() {
        blah blah blah
        blah 
        blah blah
        })
    .then(doSomethingElse)
        blah blah blah
        blah 
        blah blah
        })
    .catch(logException);

is much more obviously correct than

    m.request(...)
    .then(function() {
        blah blah blah
        blah 
        blah blah
        })
    .then(doSomethingElse)
        blah blah blah
        blah 
        blah blah
        })
    .then(null,logException);

especially when the handler functions are inline.

Moreover, due to the trap of `...then(success,fail)` where `fail` does not see exceptions thrown by `success`, I always use the `.then(null,form)` as a separate thing, never the two function form, so the exception handler always looks slightly odd.

I looked into monkey-patching Mithril, but the Promise is not exposed.

**Comment by pygy** [comment]
I think you missed #599. tl;dr: it's already in there (-:

**Comment by lawrence-dol** [comment]
I did miss 599. Yay.
