### ISSUE TITLE
Controller of multi-parametrized component receive params only from the nearest wrapper.

### ISSUE THREAD

**Issue by rielsi** [lhorie/mithril.js#631]
Consider this:
`    var original = {`
`        controller: function(one, another) { console.log(one, another); },`
`        view: function(ctrl, one, another) { console.log(one, another); }`
`    };`
`    var param1 = m.component(original, 3);`
`    var param2 = m.component(param1, 5);`
`    m.render(document.body, param2);`
Output:
`3 undefined`
`3 5`
Fixing this should be as easy as inserting `args = args.concat([].slice.call(arguments, 0))` before line 554.

**Comment by lhorie** [comment]
In rewrite, component consumption will follow the vnode structure (meaning non-object attrs are no longer valid). Components will also not curry or mixin.

To achieve the proposed behavior, use standard attribute passing
