### ISSUE TITLE
Overloading m() for components allows use of Babel's JSX transpilation

### ISSUE THREAD

**Issue by insin** [lhorie/mithril.js#632]
Just something convenient I noticed related to components - overloading `m()` to allow a component to be passed as the first argument would make it possible to take full advantage of Babel's JSX support (you can already use it for tags).

```diff
diff --git a/mithril.js b/mithril.js
index 869c114..20ca227 100644
--- a/mithril.js
+++ b/mithril.js
@@ -34,6 +34,7 @@ var m = (function app(window, undefined) {
	 */
	function m() {
		var args = [].slice.call(arguments);
+		if (type.call(args[0]) == OBJECT) return parameterize(args[0], args.slice(1));
		var hasAttrs = args[1] != null && type.call(args[1]) === OBJECT && !("tag" in args[1] || "view" in args[1]) && !("subtree" in args[1]);
		var attrs = hasAttrs ? args[1] : {};
		var classAttrName = "class" in attrs ? "class" : "className";
```
`.babelrc` config:
```json
{
  "jsxPragma": "m"
}
```
Component support was recently added to msx, but it's quite hacky in comparison - I would deprecate msx if it was possible to use Babel instead.

**Comment by Naddiseo** [comment]
Using babel and mithril is easy enough as-is. I wrote (well, most of it is from the react transformer) a vdom precompiler babel-plugin that converts JSX to mithril compatible vdom. I recently enabled components similarly to how react does them.

Example output:
```javascript
let otherAttrs = {t: 1};
let vdom = <div style="1" {...otherAttrs}><Component foo="bar">Component children</Component></div>;
```

Transpiled:
```javascript
var otherAttrs = { t: 1 };
var vdom = {
    tag: 'div',
    children: [
       /* component gets the attrs and children as arguments */
        m.component(Component, {
             foo: 'bar'
        }, ['Component children'])
    ],
    attrs: babelHelpers._extends({
        style: '1'
    }, otherAttrs)
};
```

And if you don't like the precompilation; it should be pretty easy to convert it to use `m()` calls instead.

My loader gist: https://gist.github.com/Naddiseo/7b64e953c9e684f47ade

**Comment by statianzo** [comment]
I was testing out babel+mithril today and bumped into the same case. Supporting this would be helpful.

**Comment by asafyish** [comment]
+1

**Comment by veloce** [comment]
:+1:

**Comment by StephanHoyer** [comment]
I support this notation.

I always found this way of using components the most intuitive one.

If you consider `m('div', ...)` as the usage of the *native* HTML-DIV-component the notation makes totally sense to me.

**Comment by impinball** [comment]
For what it's worth, you could wrap `m` yourself [like in my gist](https://gist.github.com/impinball/5e4d6e64aba2ffb7cd23). (And it's almost tweet-sized minified.)

**Comment by asafyish** [comment]
@impinball It's already working in the 'next' branch.

**Comment by impinball** [comment]
Awesome!

**Comment by barneycarroll** [comment]
Push for release? :D
