### ISSUE TITLE
HTML to Mithril Converter breaks case-sensitive SVG elements.

### ISSUE THREAD

**Issue by taylorzane** [lhorie/mithril.js#642]
When using the HTML to Mithril conversion tool provided, SVG elements are converted to all lowercase. SVG is [case-sensitive](http://www.w3.org/TR/SVG/styling.html#CaseSensitivity), so this breaks those elements.

For example the following code does not work after passed through the converter.

**HTML Input**
```html
<svg version="1.1" x="0" y="0" width="360" height="420">
  <path id="guideTextPath" d="M180,312 A132,132 0 0 0 272.34,272.34" fill="none"></path>
  <text font-size="14pt">
    <textPath href="#guideTextPath" startoffset="50%" alignment-baseline="central">GUIDE</textPath>
  </text>
</svg>
```
**Actual Output (Converted to CoffeeScript)**
```coffeescript
m "svg[height='420'][version='1.1'][width='360'][x='0'][y='0']", [
  m "path[d='M180,312 A132,132 0 0 0 272.34,272.34'][fill='none'][id='guideTextPath']"
  m "text[font-size='14pt']", [
    m "textpath[alignment-baseline='central'][href='#guideTextPath'][startOffset='50%']", "GUIDE"
  ]
]
```
**Expected Output (Converted to CoffeeScript)**
```coffeescript
m "svg[height='420'][version='1.1'][width='360'][x='0'][y='0']", [
  m "path[d='M180,312 A132,132 0 0 0 272.34,272.34'][fill='none'][id='guideTextPath']"
  m "text[font-size='14pt']", [
    m "textPath[alignment-baseline='central'][href='#guideTextPath'][startOffset='50%']", "GUIDE"
  ]
]
```

`textPath` should be capitalized, otherwise the text fails to display correctly.

I have tested this in Safari, Chrome, and Firefox on Mac OS X 10.10.3, and on iOS 8.3 Mobile Safari.

I'm also on Gitter if you want to discuss this further.

**Comment by isiahmeadows** [comment]
Closing, since the converter in core no longer exists. See the wiki for the recommended replacement.

**Comment by ArthurClemens** [comment]
Please open issue in https://github.com/ArthurClemens/mithril-template-converter

**Comment by isiahmeadows** [comment]
@ArthurClemens This was for the old one in Mithril core, not yours. :smile:

**Comment by ArthurClemens** [comment]
It still has that problem.

**Comment by ArthurClemens** [comment]
This is now fixed.
