### ISSUE TITLE
div with contentEditable get duplicated content after redraw

### ISSUE THREAD

**Issue by newlix** [lhorie/mithril.js#647]
I am trying to set an div with contenteditable:"plaintext-only" and whose content is controller.content(). After editing, the onBlur event will trigger a function to save the innerText of the div to the controller.content . 
For example if I type "apple" in the div and leave it, I will get "apple apple" in the div.

http://jsfiddle.net/15L0qd6a/8/

**Comment by Naddiseo** [comment]
I got it to work; if you pass the plain prop into the `withAttr` it works:
http://jsfiddle.net/15L0qd6a/6/

**Comment by afhbl** [comment]
is it better access to `innerText` only?

http://jsfiddle.net/vh3yb6zf/

**Comment by barneycarroll** [comment]
@afhbl strongly agree! There's a temptation to look at `innerText` as a disreputable non-standard API, but it's significantly awesome. This is less a Mithril issue and more a raw DOM API concern. I strongly recommend reading [Kangax's article on the subject](http://perfectionkills.com/the-poor-misunderstood-innerText) to see how these APIs work _exactly_ and why it matters.

**Comment by newlix** [comment]
Work like a charm. Thank you!
