### ISSUE TITLE
Don't create controller every time when route changes

### ISSUE THREAD

**Issue by xlaywan** [lhorie/mithril.js#655]
My controller do some ajax calls and I don't want to do this calls every time. Also controller may have state that will be lost.

**Comment by StephanHoyer** [comment]
Maybe this helps you: http://lhorie.github.io/mithril-blog/put-your-controllers-on-a-diet.html

**Comment by barneycarroll** [comment]
@xlaywan another neat little trick which will ensure controllers only ever execute once, then persist: http://jsbin.com/sinobu/1/edit?js,output

**Comment by xlaywan** [comment]
@barneycarroll, Yeah, I used similar hack)
As I understood, I made mistake of saving the state inside controller instead of model(i'd create model within controller).
