### ISSUE TITLE
Minor inconsistency regarding download size.

### ISSUE THREAD

**Issue by lawrence-dol** [lhorie/mithril.js#663]
The main GitHub page still says Mithril is about 5 KiB gzipped. Meanwhile the "How is Mithril Different" page says it's about 12 KiB gzipped. In actuality it's about 8 KiB gzipped.

**Comment by pelonpelon** [comment]
8.2 kb according to DevTools

**Comment by lhorie** [comment]
Huh, you're right. Fixed
