### ISSUE TITLE
the m.request can not setRequestHeaders

### ISSUE THREAD

**Issue by nimo-mo** [lhorie/mithril.js#672]
m.request({
		url:'url',
		method: 'POST',
		config: function (xhr) {
			xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');
			xhr.setRequestHeader('X-User-Token','1c054eurffucuvign3k6si4prv');
			xhr.setRequestHeader('X-User-Mobile','***********');
		},
		data:{
			exch_code: '000130401',
			jsonString: JSON.stringify({
				lender_id: 7,
				pageNum: 1,
				pageSize: 10
			})
		}
	}).then(function (argument) {
		// body...
	});
Content-Type/X-User-Token/X-User-Mobile can not set key/value pairs into the requestHeaders

**Comment by lhorie** [comment]
This adds headers just fine for me: http://jsfiddle.net/hm0745uw/

Can you provide a jsfiddle demonstrating the issue?
