### ISSUE TITLE
When rendering, ignore attributes with null value

### ISSUE THREAD

**Issue by opax** [lhorie/mithril.js#679]
Rendering `m("tag-name", { "attr-name": null })` should perhaps not render the attribute `attr-name` but ignore the attribute altogether. At the moment, it is rendered as `<tag-name attr-name="null">` which rarely useful. 

If null-valued attributes were ignored, it would be easy to write e.g. `m("option", { "selected": some_condition ? "selected" : null)`

This would be a breaking change, though.

**Comment by barneycarroll** [comment]
There's already [some logic in place](https://github.com/lhorie/mithril.js/issues/461) for boolean DOM properties (as opposed to DOM attributes). This is kind of an extension of that, I suppose. 

[I put up a little fiddle to show how different attributes react to truthy / falsey values](http://jsbin.com/dihime/edit?js,output). 'Boolean attributes' in HTML have always been weird.

Personally, I think this is a good idea. The same already happens when Mithril encounters a null / undefined item in place of a virtual DOM element / textNode – why not all virtual nodes?

> This would be a breaking change, though

What would it break?

**Comment by opax** [comment]
It would break existing view code that relies on an attribute being rendered even if its value is given as null. Probably not a big deal.

**Comment by elektronik2k5** [comment]
+1
I currently handle this manually in all views to filter all attributes whose values are null. Would be really nice to have it built in.

**Comment by lawrence-dol** [comment]
Plus one from me too; moreover I think that a null element in a view should not be rendered (as an empty text element, which it currently is) either.

**Comment by pelonpelon** [comment]
:+1:

**Comment by pdfernhout** [comment]
As I mentioned in a response to issue #69 (with code examples), an alternative could be to use "undefined" instead of "null" for attributes you want Mithril to ignore.

So, for example: { "attr-name": attributeName || undefined }

**Comment by isiahmeadows** [comment]
I would vote for attributes that are explicitly `false` to be removed instead, like the Jade preprocessor. First of all, it's less surprising for people using boolean attributes. Second of all, it would allow things like this (I pulled this from my website and translated it from Jade as an example):

```ls
# In LiveScript: http://livescript.net
'use strict'

require! {path}

a = -> [.. for &]

module.exports =
    controller: ->
        FILE = m.route!
        resolve: resolve = url =>  (path.dirname FILE) `path.relative` url
        navAttrs: (href, file = FILE) ->
            | file == href =>
                class: 'selected'
                # This doesn't exist if it's the current file
                href: file != FILE and resolve href
            | otherwise =>
                href: resolve href

    view: ((f) -> -> f.call ...&) <| (file) ->
        m '#header', a do
            m 'nav', a do
                m 'a', href: (@resolve 'index.html'), 'Isiah Meadows'

                m 'div', a do
                    m 'div', m 'a', (@navAttrs 'index.html'), 'Home'
                    m '.separator'
                    m 'div', m 'a', (@navAttrs 'index.html', file), 'Home'
                    m '.separator'
                    m 'div', m 'a', (@navAttrs 'projects.html', file), 'Projects'
                    m '.separator'
                    m 'div', m 'a', (@navAttrs 'blog.html', file), 'Blog'
                    m '.separator'
                    m 'div', m 'a', (@navAttrs 'music.html', file), 'Music'
                    m '.separator'
                    m 'a[href=https://github.com/isiahmeadows]', 'Github'
                    m '.separator'
                    m 'div', m 'a', (@navAttrs 'contact.html', file), 'Contact'
```

**Comment by lawrence-dol** [comment]
@isiahmeadows : I would vote for explicitly false *as well*, not *instead*.

**Comment by isiahmeadows** [comment]
@lawrence-dol I would be fine if it were both, but care would have to be taken to *only* include `true`/`false`/`undefined`/`null`, because falsiness would include `0`, which would be extremely surprising.

**Comment by lhorie** [comment]
Rewrite branch removes attributes whose value are null
