### ISSUE TITLE
Feature request: promise.finally()

### ISSUE THREAD

**Issue by dgilland** [lhorie/mithril.js#680]
Thoughts on adding a `finally()` method (or similarly named method) to the Promise API?

My particular use-case is for clean-up code that needs to always run after an `m.request()` call regardless of anything that occurs further up the chain.

Or is there already an idiomatic Mithril-way to do this?

**Comment by dgilland** [comment]
@lhorie Any thoughts on including this? If this is something you'd consider adding, I could take a stab at creating a pull request for it.

**Comment by maranomynet** [comment]
I've worked around this by doing `m.sync([ myPromise ]).then( finalCallback )` which is a bit icky but works most of the time.

**Comment by adriengibrat** [comment]
@maranomynet your example is not correct, no need of `m.sync` which is equivalent to `Promise.all` in ES6.

The method `finally()` is closer to something like `myPromise.then(finalCallback, finalCallback); return myPromise;`.

This request is related to:
#404 add `catch()` method

The idea is to be fully compatible with ES6 API.

And also partially to
#1 About Promise implementation in mithil
#228  add `tap()` method
and other issues about promises 


If Mithril had a Promise A+ compliant implementation (meaning fully async), it would be easyer to have a 100% ES6 compatible API, and thus use Browser ES6 Promise when available.

May be it's time to use an external polyfill for Promise like https://github.com/jakearchibald/es6-promise
Browser support start to be quite good http://caniuse.com/#feat=promises

**Comment by maranomynet** [comment]
As I said, it's a workaround "which doesn't do the same thing". :)
But it provides a way to execute a .then() *after* a mithril promise has been finished.

**Comment by franzliedke** [comment]
@lhorie It seems like this is again gone in v1.0?

**Comment by isiahmeadows** [comment]
@franzliedke It's because it [now bundles a conditional polyfill for the ES6 native promise](https://github.com/lhorie/mithril.js/blob/next/promise/promise.js) instead of exclusively using its own implementation like it did in 0.2. You may want to keep tabs on a [related ES proposal](https://github.com/tc39/proposal-promise-finally), though.
