### ISSUE TITLE
is there any shorthand form for nested tags?

### ISSUE THREAD

**Issue by stefanocrosta** [lhorie/mithril.js#688]
is there any shorthand form for nested tags?
Eg.

```
m('pre', m('code', 'something')) 
```
=> could be shorten into something like:
```
m('pre,code', 'something')
```

...or would it be worth it?
(any nested level adds some parenthesis, so saving a few of them looks sleek in the editor for largish view...)

**Comment by tobscure** [comment]
Not yet... https://github.com/lhorie/mithril.js/pull/630

**Comment by stefanocrosta** [comment]
uhu thanks I didn't see it! I'm all for that then, my comments will go  there!
