### ISSUE TITLE
m.component with key of 0 behaves poorly

### ISSUE THREAD

**Issue by drakes** [lhorie/mithril.js#689]
It looks like redraws with a group of components leave behind elements when a component has a key of zero. Here's an example:

https://jsfiddle.net/g89znqkr/24/

According to the [documentation](http://mithril.js.org/mithril.component.html#nesting-components) keys must be strings or numbers; I'm guessing there's a check for truthiness that trips on 0. I'm not necessarily saying the code need accommodate 0 as a key, this could be resolved with a documentation change if that's preferred.

**Comment by pelonpelon** [comment]
You are correct. There's an if statement that tests against key.

**Comment by lhorie** [comment]
@pelonpelon your fix is merged in. Thanks!
