### ISSUE TITLE
Component integration broken

### ISSUE THREAD

**Issue by jsguy** [lhorie/mithril.js#690]
Hi,

Just trying to do some component integration, as per the Select2 example here: http://lhorie.github.io/mithril/integration.html - I've set up the example here:

http://jsbin.com/vihejewada/1/edit?js,output

However the default controller does not seem to be passing the arguments through, so it cannot map the data. I've fixed the example here:

http://jsbin.com/lebecakoye/1/edit?js,output

But I had to:

1. Add a controller to the component, that passes the arguments to the view, shouldn't the default controller do that?
2. Use a prop in order to pass non-stale data around, not sure why, but if I just use static data, I seem to always get data[1] returned, so changing the value makes no difference.

Edit: Also, the original example has a small typo: "{config: select2.config" it should be "{config: Select2.config" (capital 'S')

**Comment by pelonpelon** [comment]
You're confusing ctrl with attr:
`controller: function(attrs){}`
`view: function(ctrl,attrs){}`

The default controller **does** pass its return value to the view, but it passes an empty object.
Your data is stored in attributes which the view receives in its second argument.

Here is a jsbin with the attrs used properly
http://jsbin.com/fugaso/1/edit?js,output

But it still doesn't quite work:
In your solution

- Wrapping data in an m.prop makes it available anywhere in your App.
  In your first version, `ctrl.currentUser.id` referenced the same unchanged id with every redraw. Your data may be static, but your view has state -- the initial user and the new user (onchange).
- To **get** data from an m.prop() you must call it with no arguments: `data: ctrl.currentUser()`.
  You left off the parenthesis. That will place *John* in the box initially.

I'd recommend placing your data in a model using m.props to maintain state, not in the controller.

**Comment by jsguy** [comment]
@pelonpelon that for that - the attrs clears it up - the code is from Leo's example page, so we should ask him to update it - I've adjusted the solution slightly more to bind back to the value @lhorie Here is an updated example for your select2 integration page:

http://jsbin.com/guyecehofa/1/edit?js,output

This page: http://lhorie.github.io/mithril/integration.html

**Comment by pelonpelon** [comment]
I should have gone back to look at @lhorie's example. It looks like it was updated with the introduction of components to Mithril core, but a detail or two got lost in translation.

I like your solution. Although, for clarity I would change references of `ctrl` in your config function to `attrs` since that is what it truly represents from the call `Select2.config(attrs)`.

For reference, in case Leo wants to keep the example as close to the current one as possible, I submit this jsbin:
http://jsbin.com/vajoje/2/edit?js,output
I've only changed `select2` to `Select2` and adjusted the `Select2.view` to accommodate `attrs`.

**Comment by jsguy** [comment]
@pelonpelon Your example seems broken - the Select2 component doesn't execute.
I already changed the arguments to be "ctrl" and "attrs" in the example above:

http://jsbin.com/guyecehofa/1/edit?js,output

I think it would do. @lhorie can you, (or someone) with access please update this page: http://lhorie.github.io/mithril/integration.html with the code from the jsbin linked here?

**Comment by lhorie** [comment]
@jsguy updated on origin/next
