### ISSUE TITLE
Request: make m.sync() support "background" and "initialValue" options

### ISSUE THREAD

**Issue by purcell** [lhorie/mithril.js#696]
`m.sync` is often used to tie together promises created by `m.request`. When we would like to display initial data without blocking rendering, `m.request`'s `background` and `initialValue` options are perfect, but they cannot be used when the requests are made via `m.sync`.

Would it make sense to have `m.sync()` support those same options?

**Comment by isiahmeadows** [comment]
Closing, as we are no longer accepting 0.2.x feature requests.
