### ISSUE TITLE
Mount to iframe contents?

### ISSUE THREAD

**Issue by codeclown** [lhorie/mithril.js#698]
What is the correct way to mount DOM inside an iframe?

I tried this, but it doesn't work:

    m('div.sample', [
        m('iframe', {
            config: function(element, isInitialized, context) {
                if(isInitialized) return;
                m.mount(element.contentWindow.document.body, m('div', 'foobar'))
            }
        })
    ])

If trying to mount to `contentWindow.document`, this error appears (`mithril.js:345`):

    Uncaught HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': Nodes of type '#text' may not be inserted inside nodes of type '#document'.

In React iframes can be handled very nicely with [this component](https://github.com/ryanseddon/react-frame-component). Something similar would be amazing.

Great library, though! Looking forward to using it properly.

**Comment by lhorie** [comment]
you can create Mithril instances with `var $m = m.deps.factory(element.contentWindow)`

**Comment by codeclown** [comment]
Thanks for the reply, sounds promising. Still can't quite get it to work, though. This is the code I tried based on your answer:

    var $m = m.deps.factory(element.contentWindow);
    $m.mount(element.contentWindow.document.body, $m('div', 'foobar'));

**Comment by codeclown** [comment]
My mistake... Should've realized `mount` wants a proper component. This seems to work:

    var $m = m.deps.factory(element.contentWindow);

    var component = {
        controller: function() {},
        view: function() {
            return $m('div', 'foobar')
        }
    };

    $m.mount(element.contentWindow.document.body, component);

**Comment by codeclown** [comment]
Actually, `$m` isn't needed, it seems. This works:

    m('iframe', {
        config: (element, isInitialized, context) => {
            if(isInitialized) return;

            let component = {
                controller: () => {},
                view: () => {
                    return m('html', [
                        m('head', [
                            m('title', 'Test!')
                        ]),
                        m('body', [
                            m('div', 'Foobar')
                        ])
                    ]);
                }
            }

            m.mount(element.contentWindow.document, component);
        }
    })
