### ISSUE TITLE
Listen for change/redraw

### ISSUE THREAD

**Issue by codeclown** [lhorie/mithril.js#699]
I need to generate some HTML I will then export. What would be the best way of doing this?

I guess the only way to export HTML is to render to a DOM element, then get the contents of that element.

In any case what I need to do is detect when a change was made and then grab the HTML. Is it possible to add a listener for the change/redraw event?

**Comment by lhorie** [comment]
[`config`](http://lhorie.github.io/mithril/mithril.html#accessing-the-real-dom-element) runs after rendering to a DOM element.

There's also a library called [mithril-node-render](https://github.com/StephanHoyer/mithril-node-render) that can render templates to strings

**Comment by codeclown** [comment]
Right, didn't think of utilising `config` for this case. Thanks!
