### ISSUE TITLE
Can't mock "jsonp" requests?

### ISSUE THREAD

**Issue by stumpdk** [lhorie/mithril.js#700]
Related to [#553](https://github.com/lhorie/mithril.js/issues/553)

When calling m.request in a test, the mocked method XMLHttpRequest is only called when the dataType in xhrOptions is different from "jsonp".
In other cases, a script tag containing the data is loaded to the document, and the XMLHttpRequest is not run ([it happens here](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L1032)).

If I want to test a method, that runs m.request({url: "/someUrl", dataType: "jsonp"), how can I catch the request, and fake the data returned, in the mock object?

**Comment by lhorie** [comment]
The core tests show an example of [mocking a jsonp request](https://github.com/lhorie/mithril.js/blob/next/tests/mithril-tests.js#L3990-L4009). Basically, it manually grabs the script tag from the mock DOM, and manually calls the appropriate callback. It's not particularly clean, but it could be put in a function to make it easier to reuse.

**Comment by stumpdk** [comment]
Thanks again for your comment.
I might be blind by looking too much at the code, so bare with me.
I simply can't figure out, how to test a method like this:

	Filter.prototype.updateValues = function(filterValues){
		if(this._requiredFiltersSet(filterValues)){
			m.request({method: "GET", url: this._buildUrl(filterValues), dataType: "jsonp"})
			.then(function(data){
				this.values = data;
				if(this.values.length == 1){
					this.selectedValue(this.values[0]);
				}
			}.bind(this));
		}		
	};

In my test I would do something like this:
var myFilter = new Filter();
myFilter.updateValues(["some", "filter", "values"]);
expect(myFilter.selectedValue()).toBe("expectedResult");

To have control of the test, I wish to mock the response data.

The situation is this:
I can't mock the data as suggested [here](https://github.com/lhorie/mithril.js/issues/484) as the XMLHttpRequest is not run.
And it is not enough to simply pull data from a document appended script tag as suggested [here](https://github.com/lhorie/mithril.js/blob/next/tests/mithril-tests.js#L3991-L4009), again because I can't mock the data.

As I see it, I have two options:
1) To mock the whole ajax function in Mithril.js - but that seems like a lot of work.
2) To intercept the callback script tag before it is appened to the mock document, and then change the data to what I need. But I simply can't figure out how this can be done.

I hope I'm not completely lost! :)
