### ISSUE TITLE
Question: Can you make components that don't return HTML?

### ISSUE THREAD

**Issue by mrunderhill89** [lhorie/mithril.js#703]
Hello,
I'm trying to make a library that binds Mithril to [Pixi.js](https://github.com/GoodBoyDigital/pixi.js), similar to [this project using React](https://github.com/Izzimach/react-pixi). Right now I've got a simple Mithril component that creates a canvas using Pixi and attaches it to a `<div>`. 

Now I want to make container and sprite components, and I figured the easiest way to do this (without reimplementing what Mithril does already) would be to make a component whose view() function returns a Pixi object, which would then be attached to the parent container. However, this would require the component to return something other than HTML. Is this possible? And if so, what's the recommended way to do this?

**Comment by lhorie** [comment]
Sorry, currently that is not supported. You can create functions that return non-elements, though.

**Comment by barneycarroll** [comment]
@mrunderhill89 you may be interested in [Xule](https://github.com/JoshGalvin/Xule), inspired by Mithril, which uses a similar API to generate WebGL structures…

**Comment by JoshGalvin** [comment]
Note: WebGL is a pain to debug.  You could do something similar with the diff based rendering to generate structures that get rendered to Pixi objects.

You can also use Mithril directly as a game engine:
https://github.com/SchoolHouseRock/CollegeQuest : http://collegequest.js.org/
https://github.com/JoshGalvin/3dtransformtest : http://joshgalvin.github.io/3dtransformtest/
