### ISSUE TITLE
`subcomponent` not defined on line 599 of "mithril.js"

### ISSUE THREAD

**Issue by impinball** [lhorie/mithril.js#705]
I didn't get errors spewed at me, but as I was working on another PR, I found this with JSHint's assistance an [undefined function](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L599). I'm surprised it wasn't noticed.

**Comment by impinball** [comment]
Also, I'm not sure what exactly it is supposed to do, since the code path doesn't give me any real hints here.

**Comment by venning** [comment]
Duplicate: https://github.com/lhorie/mithril.js/issues/662
