### ISSUE TITLE
Incremental DOM vs Mithril Render

### ISSUE THREAD

**Issue by renancouto** [lhorie/mithril.js#712]
Have you guys take a look at https://github.com/google/incremental-dom?
Do you think it is faster than the Mithril rendering engine? Would be possible to use this approach in a Mithril app?

**Comment by asafyish** [comment]
According to [this benchmark](http://vdom-benchmark.github.io/vdom-benchmark/), Incremental DOM is much faster.

**Comment by lhorie** [comment]
I'm taking inspiration from cito.js for the rewrite that I'm currently working on

**Comment by renancouto** [comment]
Great @lhorie, I'm looking forward to that!

**Comment by trueadm** [comment]
@lhorie definitely worth working with @joelrich. I know he's working on a "new" version of Cito too and the cross-over would be obvious. I can put you in contact via email as I know Joel is on the road currently?
