### ISSUE TITLE
Unable to edit certain styles (e.g. fontSize) via attributes

### ISSUE THREAD

**Issue by codeclown** [lhorie/mithril.js#716]
I stumbled upon this yesterday and haven't been able to figure it out, so thought I should submit an issue. I'm not able to edit certain styles, e.g. fontSize from the attributes. For some reason they are not applied to the element.

Example code ([JSFiddle](https://jsfiddle.net/gaLdyhh0/)):

```
var component = {
    controller: function() {},
    view: function(controller) {
        var style = { color: 'red', fontSize: 20 };
        return m('div', { style: style }, 'Foobar');
    }
};

m.mount(document.body, component);
```

In the example above the text is coloured red, but the font size remains default. Tested in Chrome and Safari.

I've tried different wordings of `fontSize`, e.g. `'font-size'` and `fontsize`, but I'm [pretty sure](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Properties_Reference) `fontSize` is what I should be using. I also tried putting it outside `style`, directly in the attribute object root.

**Comment by barneycarroll** [comment]
Hi @codeclown, `20` isn't a valid value for fontSize – you need to specify the units (ie pixels). Here's a [working style declaration](https://jsfiddle.net/barney/yy3nnyf9/):

```javascript
var style = { color: 'red', fontSize: '20px' }
```

**Comment by codeclown** [comment]
Oh, thank you!
