### ISSUE TITLE
m.redraw adds duplicate content with m.trust

### ISSUE THREAD

**Issue by milesmatthias** [lhorie/mithril.js#721]
If you look at one of my sites that I'm using Mithril on: https://bluebirddc.com/projects/bluebird-bakery (sorry for the restriction pop up, state regulations say you have to be a resident of DC to view the page), you'll see duplicate timeline info under the press section: https://s3.amazonaws.com/screenshots.equityeats.com/S6LXq.png

The code for this view looks something like this:

```
          <div class="headline">
            <h1>{"Timeline"}</h1>
          </div>
          { m.trust(ctrl.project.timeline_html()) }

          <div class="headline">
            <h1>{"Press"}</h1>
          </div>
          { m.trust(ctrl.project.press_html()) }
```

(using [msx](https://github.com/insin/msx) so that's why the view syntax is different, but you get the idea.)

I've already verified silly things (I call this view code more than once / `press_html` literally containing the timeline html) and none of those things are the issue.

This problem only happens on production (minified & concatenated JS being the main difference), not locally when testing.

Then I noticed something weird. If I open the dev tools and call `m.redraw()` in the JS console, that specific block is duplicated again on the page. I would expect `m.redraw()` to not change anything since none of the project data has changed, but for some reason that one section duplicates some view code every time I call `m.redraw()`.

For more background info, this page is loaded and then makes an ajax call to get the project information, which calls `m.redraw()` after the ajax call has returned with the project info.

I'm using the v.0.2.0 tagged version of Mithril. I've also tried using the bleeding edge version from the `next` branch, but no luck.

I'm considering this being a bug of msx, but it that were the case, I don't know why this single section is having issues where the same pattern is being used several times elsewhere on the page and we're not having any issues.

Any advice here? Are there other things I should try or check? Has this behavior been seen before?

**Comment by milesmatthias** [comment]
I was able to narrow the issue down. I think the problem is with using `m.trust`. I recognize that [`m.trust`](https://lhorie.github.io/mithril/mithril.trust.html) returns a String object instance, not a String literal.

When I do something like `m.trust(ctrl.project.timeline_html()).toString()`, then I don't get this repetition, although the html is no longer encoded. I end up with literal html tags (ex: "<p>Some text</p>").

However when I just use `m.trust` it seems like `m.redraw` is not recognizing that the String object instance is the same instance, so it's re-adding it to the page.

Is this theory plausible?

**Comment by milesmatthias** [comment]
Okay, after some more debugging I narrowed down *exactly* what the problem is. It happens when you use multiple `m.trust` calls in the same function. See [this simple jsFiddle](https://jsfiddle.net/ccf9gmo1/) that I made to prove the issue.

**Comment by ArthurClemens** [comment]
A variation: it works correctly when `m.trust` is returned from the controller: https://jsfiddle.net/375uceLy/

**Comment by milesmatthias** [comment]
Good find @ArthurClemens. I modified it to include a model, which is how my app is laid out: https://jsfiddle.net/375uceLy/, however when I move the `m.trust` call to my model layer in my application, it's still broken.

**Comment by milesmatthias** [comment]
I was able to recreate the problem in the jsFiddle by changing:

```javascript
		return m("div", [
			m('div', ctrl.page.content()),
            m('div', ctrl.page.content_two())
		]);
```

to 

```javascript
return m("div", [
			ctrl.page.content(),
            ctrl.page.content_two()
		])
```

so something about using `m("div", m.trust(...))` fixes this. Weird.

**Comment by marcolamberto** [comment]
I'm experiencing the same issue on firefox 39 while on chrome 44 everything works as expected.

**Comment by llambda** [comment]
I had a similar issue in FireFox and IE (but not Chrome), but the problem was I didn't set my content-type header to "application/json; charset=utf-8" for an API endpoint serving JSON I was rendering into the document.

**Comment by marcolamberto** [comment]
I've spotted the issue in the injectHTML function, the "else" branch of "if (nextSibling)" performs:
parentElement.insertAdjacentHTML("beforeend", data);

Two or more calls will produce a single text node containing the "correct" output. I think is a Firefox bug since the 'afterbegin' works as expected (of course the output is reversed).

Here follows a snippet for testing this behaviour:

(function () {
	document.body.innerHTML = '';
	document.body.insertAdjacentHTML("beforeend", '12345');
	document.body.insertAdjacentHTML("beforeend", '12345');
	console.log('Expected true:', document.body.childNodes.length === 2);

	document.body.innerHTML = '';
	document.body.insertAdjacentHTML("afterbegin", '12345');
	document.body.insertAdjacentHTML("afterbegin", '12345');
	console.log('Expected true:', document.body.childNodes.length === 2);
})();

**Comment by marcolamberto** [comment]
Replacing the insertAdjacentHTML with a Range seems fixing the issue:

parentElement.appendChild(document.createRange().createContextualFragment(data));

I'll submit a pull request.
