### ISSUE TITLE
Web Worker support

### ISSUE THREAD

**Issue by seggy** [lhorie/mithril.js#722]
I like to use Mithril as a one stop shop for all my Ajax calls, but currently it doesn't support the Worker API. That is, you can do m.request inside your Worker code. 

As workarround I now replace all "window" references to "self" and it works just fine. Would be nice if Mithril would support the Worker API out of the box.

 Thanks in advance :)

**Comment by lhorie** [comment]
Not sure I understand the request. You mean you're copying the mithril library code to a worker file? Can you show me some code of what you're doing?

It's possible to change the `window` reference that is used by mithril via `m.deps()`. Is this what you need?

**Comment by seggy** [comment]
See http://www.html5rocks.com/en/tutorials/workers/basics/

The bottom-line is that in your worker code you no longer have access to the window object. You do have access to navigator, location, XMLHttpRequest, setTimeout etc.. But window, document, parent and DOM are off-limits.

Now obviously, you wanna use XMLHttpRequest to load some data, but you cannot reference that object via `window.XMLHttpRequest`. And nor can Mithril. And that is exactly what Mithril does in Line 1063 And that is not gonna fly in a Worker envionment. 

I just want to be able to use the Mithril lib in my worker like so:

importScripts('mithril.js');

m.request({method: "GET", url: "pages.json"}).then(function(data){
    self.postMessage(data);
})

The above code fails: "Uncaught TypeError: undefined is not a function" And if I change the Mithril lib and replace all occurrences of `window` with `self` all works fine.

**Comment by StephanHoyer** [comment]
calling 
```
m.deps({
  XMLHttpRequest: XMLHttpRequest
});
```

before any other code should do the trick.

**Comment by seggy** [comment]
Yep that worked. Though now I get an error on line 625 Uncaught TypeError: undefined is not a function mithril.js:625  But that fine (and expected) since the requestAnimationFrame stuff is not supposed to work. Still I think Mithril should "taste" that it is running in a Worker environment, just to avoid all these errors.
