### ISSUE TITLE
subtree:retain doesn't work with async components; also doesn't work unless parent element's context is set to retain

### ISSUE THREAD

**Issue by sjungwirth** [lhorie/mithril.js#724]
subtree:retain doesn't work without a parent element's context set to retain. See fiddles:
doesn't work: http://jsfiddle.net/sjungwirth/u0qcee3z/
context.retain = true, works: http://jsfiddle.net/sjungwirth/u0qcee3z/1/

Also, even when setting parent element context.retain, if there is an async component on the page, subtree:retain results in the loss of content.
http://jsfiddle.net/sjungwirth/d8hrm9g6/1/

**Comment by sjungwirth** [comment]
By the way, I believe the issue with async components is caused by https://github.com/lhorie/mithril.js/blob/next/mithril.js#L284
```javascript
data = (pendingRequests == 0 || forcing) || (cached && cached.controllers && cached.controllers.indexOf(controller) > -1) ? data.view(controller) : {tag: "placeholder"};
```

In my testing this seemed to fix the issue:
```javascript
var previousPendingRequests = pendingRequests;
var controller = controllerIndex > -1 ? cached.controllers[controllerIndex] : new (data.controller || noop);
var newPendingRequests = pendingRequests - previousPendingRequests;
var key = data && data.attrs && data.attrs.key;
data = newPendingRequests == 0 || (cached && cached.controllers && cached.controllers.indexOf(controller) > -1) ? data.view(controller) : {tag: "placeholder"}
```

**Comment by lhorie** [comment]
Subtree:retain is gone in rewrite, in favor of `shouldUpdate`
