### ISSUE TITLE
TypeError: Cannot set property length of #<NodeList> which has only a getter

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#732]
[This commit/line](https://github.com/lhorie/mithril.js/commit/9ae592ee4d186567925c866b663f5d995d374ee6#diff-0bf87cbdb33b829b275ac7973ba7bc1bL474) on the next branch introduced a change which is breaking my app.

Not really sure why, any ideas?

**Comment by lhorie** [comment]
Should be fixed now
