### ISSUE TITLE
chunks

### ISSUE THREAD

**Issue by lightning02** [lhorie/mithril.js#736]
Matierials and stuff of your mod will generate only in new chunks? Or even in old chunks of my world?

**Comment by lhorie** [comment]
Sorry, I don't understand the question. Can you clarify?

**Comment by lightning02** [comment]
The question was: if for example I explore the End dimension in an existing world, then I add your mod, the mitril minerals will generate in the old chunks anyway?

**Comment by lightning02** [comment]
Sorry, i close thread for mistake '-'

**Comment by barneycarroll** [comment]
You're thinking of a different kind of Mithril — this is a library for web development :)
