### ISSUE TITLE
Suggestion: Make m.route.param() return all params

### ISSUE THREAD

**Issue by jandreola** [lhorie/mithril.js#737]
You be useful to get all params with a single method. Sometimes the user could have several params and it has to get all of them by passing the key to m.route.param(key). I think that angular does that and its useful.

**Comment by tobscure** [comment]
Relevant: #539

**Comment by jakobdamjensen** [comment]
would also make it prettier when using ES2015 syntax

```
var {param1, param2} = m.route.param()
```

**Comment by jakobdamjensen** [comment]
Well I've made a pull request for this feature...

**Comment by jakobdamjensen** [comment]
So I guess this can be close now since the feature has been merged into the next branch...

**Comment by jandreola** [comment]
Thanks, much appreciated
