### ISSUE TITLE
Publish v0.2.1?

### ISSUE THREAD

**Issue by Naddiseo** [lhorie/mithril.js#740]
Is v0.2.1 ready for release? Or are there outstanding issues with it?

At $WORK we've run into issues with `m.request` not returning a promise with `catch` (we were using `fetch` but found out we needed the progress handler which isn't supported cross-browser).

**Comment by impinball** [comment]
I know of no reason it shouldn't be. FWIW, the npm package is still stuck at 0.1, and really needs updated.

**Comment by tivac** [comment]
> FWIW, the npm package is still stuck at 0.1, and really needs updated.

No it isn't? https://www.npmjs.com/package/mithril

```
> npm view mithril versions

[ '0.1.0',
  '0.1.2',
  '0.1.3',
  '0.1.4',
  '0.1.12',
  '0.1.13',
  '0.1.16',
  '0.1.17',
  '0.1.18',
  '0.1.19',
  '0.1.20',
  '0.1.21',
  '0.1.22',
  '0.1.23',
  '0.1.24',
  '0.1.25',
  '0.1.26',
  '0.1.27',
  '0.1.28',
  '0.1.29',
  '0.1.30',
  '0.1.31',
  '0.1.32',
  '0.1.33',
  '0.1.34-beta.0',
  '0.1.34',
  '0.2.0' ]
```

**Comment by barneycarroll** [comment]
Been using Mithril 0.2 from NPM for a long time. Perhaps too long…

**Comment by impinball** [comment]
I'm confused, then.

**Comment by impinball** [comment]
Either way, I'm behind my PR, which bumps the version and will cause an npm update next time @lhorie publishes. (it will be faster)
