### ISSUE TITLE
Do not set scroll on pop state

### ISSUE THREAD

**Issue by andre-gh** [lhorie/mithril.js#747]
Browsers will nicely handle persisting the scroll position when using the back/forwards button.  Mithril negates that by scrolling top on every route, a good move when routing manually obviously but it is a lot nicer to trust the browser on the back button pop state in regards to the scroll position for a more seamless user experience.

**Comment by mindeavor** [comment]
I wonder if some kind of `m.route.on('change', ...)` would work for these scenarios

**Comment by andre-gh** [comment]
This actually does not seem to be the case actually, the browser is still setting the scroll just fine.
