### ISSUE TITLE
bower mithril is BAD. bower mithriljs seems correct

### ISSUE THREAD

**Issue by pelonpelon** [lhorie/mithril.js#750]
They both say they're v0.2.0 (more or less - Grunt is in disagreement)
But
bower `mithril/mithril.js = 45041 k`
bower `mithriljs/mithril.js = 46200 k`
github `master/mithril.js = 46200 k`

I vaguely recall Leo knows about this, but I spent a long time helping @cyberco troubleshoot a problem that came down to this discrepancy. Any way to fix it?

**Comment by cyberco** [comment]
Thanks for helping, @pelonpelon 
In addition, in the end I had to use `bower mithril/mithril.js` to make things work.

**Comment by impinball** [comment]
@lhorie?

**Comment by opax** [comment]
FWIW, the files in the bower packages mithril and mithriljs only differ in their line endings. mithriljs uses windows-style line-endings. This explains the size mismatch. 

The bower.json in the mithril package references a non-existing commit.

It would be nice to only have _one_ official package.

**Comment by tivac** [comment]
Closing due to lack of movement.
