### ISSUE TITLE
Add an event for route change

### ISSUE THREAD

**Issue by andre-gh** [lhorie/mithril.js#755]
I have a couple route change handlers which I need to fire (closing overlays on route change, etc) and it would be great to have a route change event.  Currently I have to handle this with a physical DOM component with a setup event checking for !isInitialized to indicate a route change.

**Comment by barneycarroll** [comment]
According to Mithril's 'stateless' logic, this is controller logic. I've found that for more ambitious routed applications top level components will often have a lot of similar 'setup' logic in the route. The way I handle this is roughly as follows:

```javascript
const routeMap = { /* ... */ }

let lastRoute = null

Object.values( routeMap ).forEach( [ route, component ] => {
	const { controller } = component

	routeMap[ route ] = {
		controller : function thisRoute(){
			// Universal setup logic here

			if( !( this instanceof lastRoute ) ){
				// Route change logic here
			}

			lastRoute = thisRoute

			return new controller()
		}
	}
} )

m.route( document.body, '/', routeMap )
```

If that doesn't sit well with your idea of separated concerns (ie you don't feel this logic really belongs in your routed components), you can use this pattern - a mounted component with no host element or view output - to fire on Mithril lifecycle events. If you execute this before your application code, you can ensure the logic will execute *before* your components initialise / redraw.

```javascript
m.mount( document.createElement( 'x' ), {
	controller : function routeHandler(){
		// Universal 'onroute' logic
	},
	view : () => {
		// Universal 'onredraw' logic
	}
} )
```

**Comment by pelonpelon** [comment]
Your first example is, of course, the prudent one. But the tricksy one is quite clever. I've avoided using components to perform nefarious deeds, like with React. At least with MIthril, I hadn't entertained the thought of using components for lifecycle logic, and I'm sure I'll get myself in trouble with this new power soon enough. Thanks @barneycarroll

**Comment by lhorie** [comment]
event handlers for route changed (and route not found) exist in the rewrite branch

**Comment by doesntgolf** [comment]
Hi @lhorie -- did event handlers for route changes end up in the rewrite branch?

**Comment by pygy** [comment]
@doesntgolf yes they did, look for RouteResolvers in the [router docs]. Specifically, the `onmatch` method...
