### ISSUE TITLE
Have a component method to be called after view.

### ISSUE THREAD

**Issue by ivanceras** [lhorie/mithril.js#760]
Is there a method that is called after the view method of a component. It is componentDidMount in reactjs, I was looking for something similar for mithriljs. 

Use case: I can be able to upgrade an element in getmdl.io `componentHandler.upgradeElement(button);`  after it has been mounted to the view, but not before the view is mounted.

**Comment by pelonpelon** [comment]
After Mithril has finished all rendering, it calls every *config* function attached to every component that includes them. Config functions affect the real DOM - post rendering. It's where you might run animations or invoke external libraries. It's not exactly the same as componentDidMount, but it can usually accomplish the same thing.

The API:
http://lhorie.github.io/mithril/mithril.html#the-config-attribute
Animation Use case:
http://lhorie.github.io/mithril-blog/velocity-animations-in-mithril.html

**Comment by ivanceras** [comment]
@pelonpelon Thanks, it works. :)
