### ISSUE TITLE
Manipulating output from m.component()

### ISSUE THREAD

**Issue by a-s-o** [lhorie/mithril.js#761]
Hello, 

I would like to know if there is a way to manipulate the output of `m.component()`. I am trying to implement lifecycle hooks for mithril components to reduce some of the config/controller instantiation code, which requires getting access to the `{ tag: '', attrs: {}, children: [] }` object.

Probably better explained with an example. Please have a look at [this lifecycle hooks implementation](https://gist.github.com/a-s-o/1ecdb5584a099ec9cc3c). In order to hook up `componentDidMount`, `componentDidUpdate` and `componentWillUnmount`. I am using a config function on the top level element. I basically call the render function and override the top-elements config function in lines [L72-L74](https://gist.github.com/a-s-o/1ecdb5584a099ec9cc3c#file-component-js-L72-L74). (I will eventually wrap any pre-existing configs, but for the sake of example let's say we just want to override them).

This works great when returning a top level element like `m('div.Element', ...)` but breaks down when the render function returns a top level component `m.component(SomeComponent, ...)`.

In the second case, I get back a `{ controller, view }` object. My question is whether there is a way to get the view output from this object. If I just call the view, the component would lose it's controller instance, right?

**Comment by a-s-o** [comment]
Currently using this workaround: 
```javascript
const output = hooks.render.apply(wrapper, [ctrl, ...args]);
if (_.has(output, 'attrs')) {
   output.attrs.config = makeConfig(ctrl);
   return output;
}

return m('div', { config: makeConfig(ctrl) }, output);
```
Breaking the question down to the basics, I guess what I am asking is the best way to handle higher order components:
```javascript
m.component(Outer, { some: 'args'  }, m.component(Inner))
```
What is the best way to manipulate the inner component from the outer component?

**Comment by a-s-o** [comment]
Breaking the question down to the basics, I guess what I am asking is the best way to handle higher order components:

> m.component(Outer, { some: 'args'  }, m.component(Inner))

What is the best way to manipulate the inner component from the outer component? Or...

> m.component(Modal, { isOpen: true }, m.component(ModalContents, { some: 'args' }))

What is the best way for the Modal component to extend the parameterized ModalContents' arguments to provide lets say a `modalClose()` callback, etc

**Comment by pelonpelon** [comment]
@a-s-o
I'm not sure this is what you want, but maybe you'll find some inspiration.
http://jsbin.com/vujiha/13/edit?js,output

`m.component` can be called from outside of a view. It returns a component with parameters applied. You can then work with that component, applying "patches" if you wish, possibly with output from a parent or sibling component. The resulting component can then be dropped into a view. If user input is required you'll need to use config, of course.

One caveat is that parameter application (attrs) are not cumulative. A controller is called only once in the lifetime of the component and thus, attributes are applied only once.

A side note:
In some cases you can preserve the link between a view and it's controller by calling the view with the controller as a parameter (if you have access to both).
```myComponent.view( new myComponent.controller() )```
Of course, state will be lost.
If you need to apply attributes you could try your own customized version of the the internal `parameterize` function https://github.com/lhorie/mithril.js/blob/next/mithril.js#L740

**Comment by a-s-o** [comment]
> If you need to apply attributes you could try your own customized version of the the internal parameterize function https://github.com/lhorie/mithril.js/blob/next/mithril.js#L740

Brilliant. I didn't think of that. `parameterize` is an internal function but I can just wrap m.component and do my manipulations there before calling parameterize. I will try that.

Thanks for your reply @pelonpelon 

Furthermore, thanks for the modal implementation link, but that case was just one example. Really what I need to deal with are views that return a `m.component(SomeComponent)` as a top level
element and I want to fiddle with them somehow. 

It was easier with normal mithril elements ({ tag, attr, children }); it was possible to just go in and manipulate the children array as needed but parameterized components are little more opaque. Anyways, I will try replacing m.component.
