### ISSUE TITLE
Model library suitable for mithril.js?

### ISSUE THREAD

**Issue by ludbek** [lhorie/mithril.js#762]
Is there any client side library which can be used with mithrijs? I am looking for library which has following features:
1. schema and validation
2. REST api
3. offline storage

**Comment by a-s-o** [comment]
Hmm, you can try JS data (https://github.com/js-data/js-data). Probably the best fit based on your requirements. The offline store is in-memory (if I recall correctly), you may have to rig your own system to persist to local storage, etc.

**Comment by mindeavor** [comment]
For the record, any model library that works with JavaScript will work with Mithril. Mithril does not enforce any limitations on your data.

**Comment by ludbek** [comment]
@a-s-o thanx, this is exactly what i needed
