### ISSUE TITLE
Resume after error

### ISSUE THREAD

**Issue by abdollahpour** [lhorie/mithril.js#764]
I'm using ```route``` to handle different views. Sometimes I'm getting error in one of my views because of rest API or something else. Like by clicking on a button. So, the route will not apply, but I can not call m.route any more. The page does not handle anything. It's like the new page did not load and the old one also got problem! Is there anyway to at least not loose the old one?

**Comment by barneycarroll** [comment]
This is standard behaviour for uncaught Javascript errors – they break the runtime. If it's an XHR thing, you should catch it using your XHR handler. This will happen by default if you use [`m.request`](https://lhorie.github.io/mithril/mithril.request.html), Mithril's own XHR API.

**Comment by lhorie** [comment]
There's some code to recover from this in 0.2.2+
