### ISSUE TITLE
view receives a reference to the controller twice

### ISSUE THREAD

**Issue by Satyam** [lhorie/mithril.js#765]
In https://github.com/lhorie/mithril.js/blob/next/mithril.js#L853

The view is receiving the reference to the controller twice, once as `controllers[i]` and then again as `args` which has been just set to `controllers[i]` in the line above.  Before m.component, this might not have been an issue as the extra arguments were ignored.  Now, with parameterized components this might cause trouble.  A component that might  be used as either a component or not will get its arguments confused.

**Comment by Pumpuli** [comment]
Just posting a future proof link to the source :)
https://github.com/lhorie/mithril.js/blob/d3cbbef4d593f9b20b356390ec07a9426dd1cad3/mithril.js#L852-L853

**Comment by tivac** [comment]
Closing due to lack of movement.
