### ISSUE TITLE
Transparent support of JSX syntax with Babel

### ISSUE THREAD

**Issue by avesus** [lhorie/mithril.js#768]
Latest Babel supports the `/** @jsx m */` pragma. So, transpiling to working Mithril code is elegant and easy.

Upcoming version 0.2.1 don't play well when secondary argument of the `m()` function is `null` instead of `Object`.

Surprisingly, it works well when supplying children elements with subsequent arguments instead of `Array` - I've found no docs describing the feature, so it could be undocumented or upcoming.

So, as modifying Babel to support Mithril is unlikely task, could we hope Mithril's `m()` function to play well with `null` secondary argument?

**Comment by asafyish** [comment]
+1

**Comment by avesus** [comment]
I will post a PR. 5 lines in m().

**Comment by avesus** [comment]
Hope this helps: https://github.com/lhorie/mithril.js/pull/772

**Comment by avesus** [comment]
Sorry, but my support for the PR #772 is very slow now. Anyone feel free to complete it! It's trivial enough, don't fear! :-)

**Comment by lhorie** [comment]
`m` in rewrite branch is jsx-pragma-friendly
