### ISSUE TITLE
Components get reinitialized on mount

### ISSUE THREAD

**Issue by StephanHoyer** [lhorie/mithril.js#774]
Hi, I just added a slightly bit of mithril to an ampersand application. For this I used multiple mount points (until the complete transition to mithril is done :)).

But I have a problem that the components of each mount-point get reinitialiezed on every mount.

Is this intended or a bug?

http://jsfiddle.net/fx5t34h1/9/

**Comment by Zhouzi** [comment]
Actually it looks like mounting the second component triggers a full redraw and every components are instantiated again. You can avoid it by setting the redraw strategy to "diff": http://jsfiddle.net/fx5t34h1/10/

Relevant documentation: https://lhorie.github.io/mithril/mithril.redraw.html

**Comment by StephanHoyer** [comment]
Seems like a workaround to me. But works, thanks. Since this is only temporally problem it's ok.
 
@lhorie Ticket can be closed if you think this is the right way to solve this.

**Comment by Zhouzi** [comment]
I took a look at `m.mount` and the redraw strategy is purposely set to `"all"`: https://github.com/lhorie/mithril.js/blob/next/mithril.js#L788

It probably solve lots of edge cases but I'd also be interested to know the reasoning of this behavior.

**Comment by barneycarroll** [comment]
Redraw strategy all is there to emulate a 'reload' behaviour as if the browser had just rendered a new page from scratch. The supposed benefit is that you reset anything that might have been done by state keeping or DOM-modifying config functions — Mithril's early examples strongly imply that Mithril assumed you would be doing all your complicated stuff in config functions and wouldn't be taking care to manage state yourself. AFAICT it's a defeatist attitude resting on circular logic — the assumption being that you'll be managing state badly in the first place means that redrawing everything from scratch is a crutch.

The workaround is to invoke `m.redraw.strategy( 'diff' )` in all your top-level controllers.
