### ISSUE TITLE
Merging several js files together: m becomes undefined

### ISSUE THREAD

**Issue by halfabench** [lhorie/mithril.js#779]
Hi,
I'm working on a little mithril project with several other js libs as well. They all work well together until I merge them all up in a same big js file.
I have tried to put mithril on top and then at the end of the file but m always becomes undefined. The only "solution" I found so far is to put mithril back in its own file. 
I am definitely not a javascript expert, so maybe you would have a clue about the possible cause as well as some tips to merge all the libs without losing mithril?
Thanks for your help and for this great project!

**Comment by Naddiseo** [comment]
I would suggest using [webpack](http://webpack.github.io/) or [browserify](http://browserify.org/) instead of doing it manually.

**Comment by halfabench** [comment]
Oh well In fact I already use a tool (from scalajs). But maybe it would be faulty? I'll try one of the tools you mentioned to check. Thanks for the hints!

**Comment by qwertyuiop924** [comment]
Most tools make a commonjs-like shim around your files. Try adding `module.exports = m` to the end of mithril.js. Then, at the top of your file, add `var m = require("path/to/mithril")` with path/to/mithril relative to the root of the bundle. That's how require paths work in brunch, anyway, and I hear webpack and browserify are similar, but you should check your tool's docs to be sure.

**Comment by Zhouzi** [comment]
Actually Mithril already follows the UMD pattern, which means that it works with any type of module system loader. I don't think the problem is related to Mithril, nor webpack/browserify but probably to the tooling and/or configuration. Can you reproduce this issue somewhere so we can have a look at the relevant code?

**Comment by lhorie** [comment]
The Mithril codebase was changed to use an explicit assignment instead of a hoisted var, so this should no longer be an issue
