### ISSUE TITLE
a 500 response on a request breaks stuff

### ISSUE THREAD

**Issue by dannycochran** [lhorie/mithril.js#780]
if I do:

```
m.request({type: 'GET', url: '/some/url/', contentType: 'application/json'}).then(function (data) {
  console.log('success', data);
}, function (err) {
  console.log('error', err);
})
```

and the server returns a 500, it'll break on this line in mithril, without ever getting into my reject block above.

```
var response = unwrap(deserialize(extract(e.target, xhrOptions)), e.target);
Uncaught SyntaxError: Unexpected token <
```

I can fix this by passing extract into the request:

```
extract: function (xhr, xhrOptions) {
  if (xhr.status === 500) return xhr.status;
  else return xhr.responseText;
}
```

Is this expected behavior? Shouldn't the request be able to continue gracefully even without an extract option?

**Comment by Pumpuli** [comment]
It sounds like the server is returning some HTML content on a 500 error but mithril expects JSON by default (`deserialize` option). [Docs](https://mithril.js.org/mithril.request.html#using-variable-data-formats)

**Comment by dannycochran** [comment]
yeah it is serving raw HTML. My question is whether it should cause a blocking error or proceed gracefully like jQuery / zepto do?

**Comment by pelonpelon** [comment]
This has been discussed many times in issues and the forums. As it stands, anything returned that is not JSON must be handled by you. I understand your reasoning, but `m.request` is a complicated mechanism that returns an `m.prop` wrapped in a promise. It can also trigger a `redraw`. Handling non-JSON responses *gracefully* would require reworking several integrated parts of Mithril core. Mithril would have to grow and might suffer speed penalties.

`m.request`, is a built-in extra that does simple/limited ajax requests. You're expected to use a 3rd party library or write your own code if you want more/different functionality.

This is just a consequence of keeping Mithril small and on target.

**Comment by dannycochran** [comment]
fair enough -- wasn't sure if it was intentional or not.

**Comment by Zhouzi** [comment]
@dannycochran I know this issue is closed but I was reading the documentation of `m.request` and found that there is a way to deal with such case: https://lhorie.github.io/mithril/mithril.request.html#using-variable-data-formats

You can use the `extract` option to specify a function that's going to manage the response.

**Comment by dannycochran** [comment]
Indeed. I noted as such in my original comment :)
