### ISSUE TITLE
Expose a route test

### ISSUE THREAD

**Issue by andre-gh** [lhorie/mithril.js#784]
It would be nice to have an external hook which can be called to evaluate what view a route would resolve to and which arguments it would have without actually navigating to that route.

**Comment by vicnicius** [comment]
Not quite sure if I understand how this feature would work. Maybe some code example could help here.

Despite that, it's important to notice that mithril is a minimalistic framework. 

This means that there are quite a lot features that would sure be cool, but that mithril will end up not adding to it's core code to keep it's simplicity intact.

**Comment by avesus** [comment]
> ... it's important to notice that mithril is a minimalistic framework.

It would be useful to split `mithril.js` to allow modularized pick. It could work without promises and XHR which included into its body. Shure, it could even work without components just as a diff-render template engine. Why all parts are in the same file?

**Comment by StephanHoyer** [comment]
@avesus  This was [discussed](https://github.com/lhorie/mithril.js/pull/665) [several](https://github.com/lhorie/mithril.js/issues/651) [times](https://github.com/lhorie/mithril.js/issues/8).

Mithril is so small, it probably won't reflect on the size of your overall code when you leave parts out. Also such a move would add additional overhead that probably most of the people have to include. So it's unfair to bloat the code just for the people who want modularisation.

@lhorie sees mithril as a collection of the minimal modules you mostly need to build a web application. They are build to work well together.

@andre-gh Can you please describe a use case for this. Don't see, why one want's such a behaviour.

**Comment by andre-gh** [comment]
I am leveraging Mithril to do some server side rendering and need to know which View would end up getting rendered for a particular route (but do not want to mount mithril on a server side virtual dom and have tons of overhead).

Essentially I an implementing by own router and renderer on the server end, using Mithril only for compatible promises, m() calls, etc.  This allows my server side view pre-rendering/warming to use identical code component/view as the client.

The tidbit I am running into mostly involves routing, I need to grab route data and route in the same way mithril would to ensure there are no differences.  I can/have reimplemented this but it would be nice if Mithril just exposed the code which already exists.

I implemented this just by copy-pasting a few lines of the internal code and it is very frustrating to need to copypase a few lines which could otherwise be exposed:

          for (var route in routes) {
            if (route === path) {
              return routes[route]
            }

              var matcher = new RegExp("^" + route.replace(/:[^\/]+?\.{3}/g, "(.*?)").replace(/:[^\/]+/g, "([^\\/]+)") + "\/?$");

      if (matcher.test(path)) {
        path.replace(matcher, function() {
					var keys = route.match(/:[^\/]+/g) || [];
					var values = [].slice.call(arguments, 1, -2);
					for (var i in keys) {
            var key = keys[i]
            globalparams[key.replace(/:|\./g, "")] = decodeURIComponent(values[i]);
          }
				})
        return routes[route]
      }

Essentially I want the internal code to be broken out and exposed as something an advanced user can use using Mithril as a utility.   It would be passed a list of routes and would spit out parameters and the given route selected.

Otherwise I am just copypasting the internal regexes and hoping for the best.

**Comment by andre-gh** [comment]
It is important to note that the impact on the internal code would be super minimal only breaking out that code block a little bit, which at this point is very internally nested.

**Comment by pelonpelon** [comment]
Currently, `m.route(el, '/', { routesObject })` returns void. Would it help if it were to return the routes object? Then you could determine a view something like this:
```javascript
var currentRoute = m.route() // or var futureRoute = m.route('/another/route')
for ( path in Object.keys( routesObject ) ) {
  if ( path === currentRoute ) { // or futureRoute
    var Component = routesObject[path]
    var componentView = Component.view( new Component.controller(attrs) )
}
```
This is a purely hypothetical question at this point. Attributes would need to be accessible to get a complete copy of the view template object. `m.route('my/route')` would have to return the new route instead of `void`. And something like `m.route.params()` would need to return a parameters object.

My first thought is that all of this is doable and would require only small changes to mithril.js. I hesitate to investigate this further, not knowing if exposing the routes object would fulfill your needs.

**Comment by andre-gh** [comment]
Using m.route is not an option for me as it does not work without a window object and DOM and I do not want to hack a mocked environment in place.  I am realizing now that I would _not_ need this solution if there were a router which worked in such a virtual environment.

**Comment by lhorie** [comment]
I'll take this into consideration for the rewrite. For the v0.2.x stream this is out of scope
