### ISSUE TITLE
prevent change in param cause controller reload

### ISSUE THREAD

**Issue by learner010** [lhorie/mithril.js#785]
It seems mithril reloads a page even when its param changes. Is there a way to tell mithril not to reload the page when its params change.

I have a list view where i can filter using different parameters. I does not need reloading the controller. I only need to change the list of contents. Is there any way to achieve it?

**Comment by jakobdamjensen** [comment]
set the m.redraw.strategy("none") or "diff" depending on what's necessary...

**Comment by learner010** [comment]
thanks
