### ISSUE TITLE
Mithril vs Riot?

### ISSUE THREAD

**Issue by pyros2097** [lhorie/mithril.js#786]
Can anyone benchmark mithril against [riot](https://github.com/riot/riot)? To me its seems a lot like mithril but smaller and maybe faster?

**Comment by avesus** [comment]
Riot is definitely larger and slightly slower. Google it or write your own
tests.

**Comment by fluxxu** [comment]
Riot v2.0.11
http://vuejs.github.io/js-repaint-perfs/riot/

Mithril v0.1.30
http://vuejs.github.io/js-repaint-perfs/mithril/

Mithril is 200% faster.

**Comment by thinkloop** [comment]
Running the above tests I see about 11.3 repaints/sec for riot and about 10.3 repaints/sec for mithril - not a big deal, but it riot is about 10% faster for me, what are you seeing? [Chrome 47.0.2526.106 m]

**Comment by isiahmeadows** [comment]
These might be soon moot, given my recent perf work on this (that really needs more tests written). Also, there's one other big perf patch that made it into 0.2.0, but not 0.1.x. I think it's worth re-testing.

**Comment by isiahmeadows** [comment]
And don't forget, performance isn't usually the end-all. Not to mention a just using different algorithm can make a massive performance jump (there's a reason Angular 2 and Ember are joining React with their new vdom implementations, not to mention they're often *faster*).

And another comparison: a simple [merge sort](https://en.wikipedia.org/wiki/Merge_sort) in Python will almost always outperform a [bogosort](https://en.wikipedia.org/wiki/Bogosort) in C, and 10-item arrays are much faster to loop through than 1,000-item arrays.

Or, in other words, performance is nice, but this is the difference between comparing 10 and 11, not 10 and 3,000, which is roughly Angular 1. I'd be reconsidering if it was doing 60 repaints/sec, which I don't believe even Cito can do. Not too concerned here. :wink:

**Comment by thinkloop** [comment]
Agreed! Just wondering where the 200% came from

**Comment by isiahmeadows** [comment]
Also, Riot has seen a fair number of optimizations itself, so don't feel too bad. The speed picture is a bit different now.

**Comment by fluxxu** [comment]
Riot is upgraded from v2.0.11 to v2.2.4 in the test.
Yes, the speed picture is a bit different now...
Fortunately I wrote the version number there xD

**Comment by tivac** [comment]
Forked, updated to `mithril@0.2.2-rc1`, and rewrote closer to **my** mithril coding style.

http://tivac.github.io/js-repaint-perfs/mithril/

I didn't go deep into optimizing because that feels disingenuous, but I'm sure there's a few places it could be going faster.

**Comment by futurist** [comment]
here Chrome45+XP32Bit

Mithril@0.2.2-rc1:  `18-19 / sec`
(previous url) Riot@2.0.11: `23-24 / sec`

**Comment by fluxxu** [comment]
OK, I forked and reverted to the version I saw.
**Please move the mutations to maxium(100%).**

Riot@2.0.11 = **8 /sec**
http://fluxxu.github.io/js-repaint-perfs/riot/

Mithril@0.1.30 = **21 /sec**
http://vuejs.github.io/js-repaint-perfs/mithril/

Chrome 47.0.2526.106 (64-bit) 2.2 GHz Intel Core i7 RMBP

**Comment by pbowyer** [comment]
As another data point, using Chrome 47/Win7x64, the latest [DBMON Angular 2.0 Alpha](http://mathieuancelin.github.io/js-repaint-perfs/) is giving me 50fps at 50% mutations and 31fps at 100% mutations.

Not that it matters for my usages, where file size >> speed.

**Comment by leeoniya** [comment]
@pbowyer you need to post what you get on one of the other baseline libs tested here also. pure repaint rates are meaningless since hardware plays a huge part in these results.

**Comment by pbowyer** [comment]
Apologies @leeoniya, RiotJS was 29-30fps and Mithril was ~25fps at 50% mutations.
At 100% mutation, Riot here was 9fps and http://tivac.github.io/js-repaint-perfs/mithril/ and http://vuejs.github.io/js-repaint-perfs/mithril/ gave 19-20fps.
