### ISSUE TITLE
Possible memory leak when "overwriting" top level modules

### ISSUE THREAD

**Issue by lukeautry** [lhorie/mithril.js#787]
We're using Mithril in a large single page application (Durandal) for rendering in a section where the datasets can be quite large and we needed the rendering performance. In Durandal, view models can have an "attached" method, which gets hit when said view model gets inserted into the DOM. In "attached", we initializing the top level Mithril module like this:

m.module($("#mithril")[0], this.MyObject);

As you might imagine, this code can be called many times in the lifetime of a page.

We observed some significant memory leaks in our app; many of the references not being GC'd seemed to be within Mithril. From debugging and inspecting the code, it doesn't look like there's anything trigger cleanup of Mithril's internal references to the module when you "overwrite" the module:

https://github.com/lhorie/mithril.js/blob/next/mithril.js#L758

     m.mount = m.module = function(root, component) {
	        	if (!root) throw new Error("Please ensure the DOM element exists before rendering a       template into it.");
		var index = roots.indexOf(root);
		if (index < 0) index = roots.length;

In our case, roots.indexOf(root) is going to be -1 since we're doing object level comparison, but is this the correct approach? I made these (flawed, I know) changes which allowed cleanup to happen:

     m.mount = m.module = function (root, component) {
          if (!root) throw new Error("Please ensure the DOM element exists before rendering a template    into it.");

     var index = roots.map(function(r) { return r.id}).indexOf(root.id);
     if (index < 0) {
     index = roots.length;
     } else {
          // This root has been initialized before; reset it
          removeRootElement(root, index);
     }

And then this change to getCellCacheKey:

     function getCellCacheKey(element) {
          var index = nodeCache.map(function(n){ return n.id}).indexOf(element.id);
          return index < 0 ? nodeCache.push(element) - 1 : index;
     }

So two questions I guess:
1) Is this just a case of us Doing It Wrong
2) If not, how should we signify that a module's cached state should be cleared?

**Comment by lhorie** [comment]
In rewrite branch, there's no longer a cell cache
