### ISSUE TITLE
Tell Mithril not to redirect the page while changing query string in the URL.

### ISSUE THREAD

**Issue by ludbek** [lhorie/mithril.js#790]
~~Is there a way to tell mithril not to redraw app when the query/search params in url changes?~~
Is there a way to tell Mithril not to redirect the page while changing the query string in the URL?

Example: when url changes form `/fruits` to `/fruits?search=apple` tell mithril not to redirect.

It would be handy if one could do following tasks:
```javascript
// given a url http://example.com
m.route.param({search: 'apple', order_by: 'quantity'}) // http://exampal.com?search=apple&order_by=quantity
m.route.param() // {search: 'apple', order_by: 'quantity'}
m.route.param({search: 'apple'}, false) // tell mithril to just change the query set but not to redirect the page
```
Right now I am using `URL.js` to manipulate query string and `History.js` to update query string without redrawing the app.

Also `History.js` does not work well with `m.route.mode = 'hash'`

# Update
`Tell Mithril not to redirect the page when updating query string.`

**Comment by barneycarroll** [comment]
Hey @ludbeck, I had a similar requirement for my application – route param changes on the same component need to play different logic. 

First off all, I highly recommend [URIjs](http://medialize.github.io/URI.js/) for working with URIs. Unless you're using `path` [`m.route.mode`](https://lhorie.github.io/mithril/mithril.route.html#mode) – in which case it's possible to query the `location` and get an accurate representation of your route, you will probably need some kind of URI abstraction tool. Regardless of route mode, you can get a location-like URI abstraction of the current route with the expression `URI( m.route() )`.

First you need a higher-scope reference to store what the last route was, so that components can compare current route to previous:
```javascript
var previous;
```
Then in each top-level controller:
```javascript
component.controller = function(){
  var current = m.route()

  // If the paths haven't changed
  if( URI( current ).path() === URI( previous ).path() )
    // Don't redraw
    m.redraw.strategy( 'none' )

  // Store the snapshot – you need to do this in every top-level controller or the logic above becomes unreliable
  previous = current
}
```

If you think URIjs is a bit of overkill, I wrote this little tool for getting all the `location` properties for any given URI: [Location.js](https://gist.github.com/barneycarroll/5310151). The condition expression then becomes `Location( current ).pathname === Location( previous ).pathname`.

**Comment by avesus** [comment]
> First off all, I highly recommend URIjs for working with URIs. 

9 KiB minified gzipped.

**Comment by barneycarroll** [comment]
> First off all, I highly recommend URIjs for working with URIs.
> > 9 KiB minified gzipped (8 KiB w/o URITemplate.js).

…

> If you think URIjs is a bit of overkill, I wrote this little tool for getting all the location properties for any given URI: [Location.js](https://gist.github.com/barneycarroll/5310151). The condition expression then becomes Location( current ).pathname === Location( previous ).pathname.

**Comment by avesus** [comment]
[Location.js](https://gist.github.com/barneycarroll/5310151) is great, thank you!

**Comment by barneycarroll** [comment]
@avesus I hadn't looked at that gist in a while. I managed to gold it down a bit further:

```javascript
function Location(uri){
  return document.createElement('a').href = uri;
}
```

As an ES6 module:

```javascript
export uri =>
  document.createElement('a').href = uri
```

It's possible to keep all the functionality while simplifying a great deal :)

**Comment by ludbek** [comment]
@barneycarroll I know I could achieve  it  one way or the other but it would be great if the above functionality was the part of mithril core.

**Comment by barneycarroll** [comment]
> it would be great if the above functionality was the part of mithril core.

The problem is A) your API wouldn't work for links B) 'change the params of a route but don't redraw' isn't exactly generically useful functionality that deserves a specific API. For instance, it's not at all what I wanted to do when I established the params hadn't changed. It's also ambiguous. Should the controller execute in a no-redraw-but-params-have-changed situation?

> I know I could achieve it one way or the other 

Knowing you can do what you want to do, that's the important thing :)

**Comment by ludbek** [comment]
>>> A) your API wouldn't work for links
Could you elaborate on this? :)

>>> 'change the params of a route but don't redraw' isn't exactly generically useful functionality that deserves a specific API
Consider a view with a table of fruits and a bunch filters. I would like to filter the fruits, at the same time attach the filter prams at the URL so that I could bookmark the URL. I feel redrawing with each filter is an expensive task so I would love to just update the list without redrawing entire app.

**Comment by barneycarroll** [comment]
> A) your API wouldn't work for links

Say you're at '/page?query=foo'. Your view contains `m( 'a', { href : '?query=bar', config : m.route } )`. The API you're proposing wouldn't be able to deal with those situations. This is because the situation you've identified is something that happens _as a result of certain conditions being met_ as opposed to _a specific direction_ being given.

If all you want to do is be able to trigger this behaviour, then all you need is the existing API:

```javascript
// Go to route X
m.route( '/page?query=bar' );
// Don't redraw
m.redraw.strategy( 'none' );
```

> Consider a view with a table of fruits and a bunch filters

The idea that there may be different useful bookmarkable states with identical rendered views is completely at odds with the MVC paradigm. The motive for the views staying exactly the same is completely unclear.

**Comment by ludbek** [comment]
```
// Go to route X
m.route( '/page?query=bar' );
// Don't redraw
m.redraw.strategy( 'none' );
```

I tried the code above it redraws app as soon as I execute `m.route('/page?query=bar')`

I even tried

```
// Do not redraw 
m.redraw.strategy( 'none' );
// Go to route X
m.route( '/page?query=bar' );
// Can redraw now
m.redraw.strategy( 'diff' );
```

This doesn't work either.

**Comment by barneycarroll** [comment]
> I tried the code above it redraws app as soon as I execute m.route('/page?query=bar')

You're totally right. I'd forgotten route changes were synchronous (unlike regular redraws). So you need to prepend the code with `m.startComputation()` and append `m.endComputation()`.

Check it out in action – the view only renders once: https://jsbin.com/cudiha/edit?js,output

**Comment by ludbek** [comment]
Could you explain why mine did not work?
What I was trying to do is
1) disable redraw so that app wont redraw in next route change
2) change the route
3) enable redraw again for other events

**Comment by ludbek** [comment]
So `m.redraw.strategy` determines the next redraw but not the global redraw strategy? I think I finally got it. Thanx @barneycarroll  for your time

**Comment by avesus** [comment]
> m.redraw.strategy determines the next redraw but not the global redraw strategy

:+1: that this words are written on the stone now - they will save time for a lot of people!

**Comment by barneycarroll** [comment]
Yeah, if you ask me `m.redraw.strategy` is incredibly confusing – it took me ages to figure out how it worked. 

First of all, `m.redraw.strategy` only affects the next redraw. Whenever a redraw is called, the redraw strategy is reset internally to either 'diff' or 'all': If the redraw is the result of a Mithril-bound DOM event (like `onclick`) in my example, then it's `diff` – same if you manually call `m.redraw()`. These redraws are deferred / queued / async – they will not execute until the next animation frame resolves. So in _those_ situations, you can change strategy in the code that calls the redraw. But in the case of `m.redraw(true)` or route change, or the _first_ draw, then A) the redraw strategy is set to 'all', and B) the redraw is triggered _immediately_. The only way to get around this is to start a computation – thus blocking redraws – _then_ change the strategy, and end the computation – which triggers a deferred redraw if there are no other pending computations.

I desperately hope these horribly confusing APIs are completely overhauled for v2! :)

**Comment by barneycarroll** [comment]
> So m.redraw.strategy determines the next redraw but not the global redraw strategy

That's the most succinct description yet :)

**Comment by ludbek** [comment]
Including the snippet by @barneycarroll  below, hope it would be useful to others with similar needs

```javascript
m.route( document.body, '/', {
  '/' : {
    view : () => {
      alert( 'Redraw!' )
      
      return [
        m( 'button', {
          onclick : () => {
            m.startComputation()
          
            m.route( '/?' + Date.now() )
          
            m.redraw.strategy( 'none' )
          
            m.endComputation()
          }
        }, 'Route without redraw' ),
        
        m( 'button', {
          onclick : () => {
            alert( m.route() )
            
            m.redraw.strategy( 'none' )
          }
        }, 'Alert current route' )
      ]
    }
  }
} )
```

**Comment by ludbek** [comment]
@barneycarroll  does `m.redraw.strategy` determines the redraw strategy only for the component in which it is called while rest of the components' redraw strategy is unaffected?

**Comment by barneycarroll** [comment]
@ludbek no, it affects the whole DOM redraw. If you want to change redraw policies for individual components, you would need to configure those components views to either produce new unique `key`s for their root nodes (forcing a redraw of `all` locally) or return `{ subtree : 'retain' }` (the equivalent of `none`).

**Comment by ludbek** [comment]
I have a situation with the solution you provided. The architecture of the app I am working looks roughly as follows.

```coffeescript

Customer.List = {
  customers: []

  controller: (pl) ->
    console.log 'initialized'
   # ...
    return

  view: (ctrl) ->
    m.component TwoCol, {
      title: m.component Header, {content: 'List of Customers'}
      content: [
        m.component Customer.Component.FilterForm, {model: ctrl.filters}
        m.component Customer.Component.Table, {
          headers: [
            ['First Name', 'first_name'],
            ['Last Name', 'last_name'],
            ['Mobile', 'mobile']          
          ],
          collection: Customer.List.customers,
          resource: CustomerModel
        }
      ]
      nav: m.component VNavbar, {}
    }
  }



m.route document.body, '/',
   '/customer': Customer.List
  '/customer/create': Customer.Create
  '/customer/:id': Customer.Update  
```

When I make changes to the filters, `Customer.Component.FilterForm` and `Customer.Component.Table` 's controllers are not re-instantiated but the controller in Customer.List gets instantiated.

**Comment by barneycarroll** [comment]
> It seems Mithril instantiates the root controller no matter which strategy is used while changing route.

That's a separate issue – the fact that controllers initialise on route change is by design. Mithril would be broken if that weren't the case.

You can still use the logic I originally proposed to avoid this:
```javascript
var previous 

component.controller = function(){
  var current = m.route()

  if( URI( current ).path() === URI( previous ).path() ){
    m.redraw.strategy( 'none' )

    previous = current

    // Don't execute the rest of the controller logic
    return;
  }
  else {
    previous = current
  }

  // The rest of your controller logic
}

**Comment by ludbek** [comment]
@barneycarroll Thanx for the solution. But I still believe the functionality should be included in the core. What tools does Mithril use for test? Is it only QUnit or few other tools which I am not aware of?

**Comment by JAForbes** [comment]
@barneycarroll In that code example above: is mithril initializing the new controller of the same route but due to `redraw('none')` the process is cancelled midway, and your existing controller stays active?

Essentially the conditional at the top of the controller isolates whether to reinitialize the route on param change by changing the redraw strategy?

And is start/end computation necessary in the latest example too?

**Comment by barneycarroll** [comment]
When the URI changes, Mithril looks through the route map to see which route the new URI matches, and executes the controller for the associated component *before* rendering the view. By default a route change means a total rebuild of the DOM (`m.redraw.strategy( 'all' )` — compared to the usual `m.redraw.strategy( 'diff' )` which compares each part of the new virtual DOM with the old), but by specifying `m.redraw.strategy( 'none' )` Mithril is instructed to ignore the next draw completely, so the view doesn't even execute (resuming normal behaviour on the next redraw).

**Comment by pharzan** [comment]
I want to display various video files one after another by clicking on a button, and the button onclick would just change the source url of the HTML5 video player. These video files should be available by their unique URLs but when I change the url using m.route and the m.redraw.strategy( 'none' ) method in the onclick event it causes the controller to unload and load again.
Here is a example of what I'm trying to accomplish.
https://jsfiddle.net/fb66uLmx/6/

**Comment by barneycarroll** [comment]
When loading a route in Mithril, the top level component associated with that route will execute. This is the whole point of routed components in Mithril. The only code that should be in the controllers for those components is code you *want* to execute in that context. If you don't want that code to execute, you should put it elsewhere.

@pharzan in your code, there is no relationship between route and content — they just both happen to change as the result of the same action. If you want to change video based on route, you could do that by setting the video source as a route parameter, [like this](https://jsfiddle.net/barney/p5zc8s95/). If you just want to change the video source and leave route intact, you could do that [as follows](https://jsfiddle.net/barney/oxLy0bju/).

**Comment by lhorie** [comment]
Rewrite branch no longer treats route changes as redraw-from-scratch events

**Comment by javajared** [comment]
:stuck_out_tongue_closed_eyes:
