### ISSUE TITLE
Inconsistent library size

### ISSUE THREAD

**Issue by shamrin** [lhorie/mithril.js#792]
GitHub README [says][0]:

> Only 5kb gzipped, no dependencies

Mithril [home page][1] says:

> Only 12kb gzipped, no dependencies

And inside [mithril zip archive][2] (from home page):

```
$ cat mithril.min.js | gzip | wc -c
    7340
$ cat mithril.js | gzip | wc -c
   13265
```

It looks inconsistent…

[0]: https://github.com/lhorie/mithril.js
[1]: http://mithril.js.org/
[2]: http://mithril.js.org/mithril.min.zip

**Comment by StephanHoyer** [comment]
Feel free to create a PR ;)

**Comment by lhorie** [comment]
fixed
