### ISSUE TITLE
alertify.alert doesnt work in mithril (m.request) response

### ISSUE THREAD

**Issue by aatifbandey** [lhorie/mithril.js#793]
i am working on a project where i am using [mithril.js][1] and also using [alertify.js][2] in the response i want to alert some data it doesnt work and if the same alert i am using before m.request it works fine

            function send_data()
            {        
             m.request({
                method: "GET",
                url: url_root,
                config: xhrConfig
            }).then(
                function(response) {
                 alertify.alert("test");
              });
         }
    send_data();

 

  [1]: https://lhorie.github.io/mithril/
  [2]: http://fabien-d.github.io/alertify.js/

**Comment by barneycarroll** [comment]
[Works for me using alertify 3.11](https://jsbin.com/qudupo/edit?html,js,output). v0.5rc1 can't even execute without breaking ('alertify is undefined'). What problem are you facing?

**Comment by aatifbandey** [comment]
Thanks Dude :) u made my day ! 
Problem was indeed with the version

**Comment by barneycarroll** [comment]
@aatifbandey no worries :) – does that mean I get an 'answer accepted' on the SO question? :D
