### ISSUE TITLE
Default units on styles

### ISSUE THREAD

**Issue by jargv** [lhorie/mithril.js#794]
please consider: 
```js
var width = 640;
var height = 480;
return m('div', {
  style:{
    width: width,
    height: height
  }
}, [...])
```

Where's the bug? Width and hight are not picked up because they require a unit! This becomes very cumbersome and error prone. I don't know how many times I've seen dynamic styles not applied because I forgot the unit.

```js
var width = 640;
var height = 480;
return m('div', {
  style:{
    width: width + 'px',
    height: height + 'px'
  }
}, [...])
```

It would be awesome if mithril would apply a default unit (perhaps configurable, but I only care about 'px') when there are numbers in the style object. If there's interest in this change, I'd be happy to put together a pull request.

**Comment by StephanHoyer** [comment]
I think this stands against the concept of mithril.

It can easily done with a library. In fact there are [some](https://github.com/jsstyles/jss) [libraries](https://github.com/pygy/j2c) that do exactly that

**Comment by Zhouzi** [comment]
@StephanHoyer is right, from the documentation:

> Note that in order to keep the framework lean, Mithril does not auto-append units like px or % to any values. Typically, you should not even be using inline styles to begin with (unless you are dynamically changing them).

https://lhorie.github.io/mithril/mithril.html

**Comment by jargv** [comment]
@StephanHoyer @Zhouzi Thanks for the responses. Sounds like this has already been thought about, and decided against. I'm going to go ahead and close.
