### ISSUE TITLE
Mithril doesnt auto redraw the view

### ISSUE THREAD

**Issue by aatifbandey** [lhorie/mithril.js#795]
When changing prop values mithril doesnt auto redraw the view, on press of a button i update my prop as:
           
         something.vm.test(something.vm.test() + 1);

it updates the prop value but doesn't reflect on view by using m.redraw() it works fine ?

**Comment by barneycarroll** [comment]
Mithril autoredraws after its event handlers resolve. If you put that line in an `onclick` bound to the button using Mithril, it'll work. Otherwise, yes — you have to call `m.redraw()` yourself.

**Comment by aatifbandey** [comment]
can you provide a fiddle please,thanks a lot

**Comment by barneycarroll** [comment]
Here's automatic redraws:
https://jsbin.com/nepiba/edit?js,output

Here's an example with explicit redraws:
https://jsbin.com/nepiba/edit?html,js,output

A better way to find the source of the problem might be to show us the code that's broken?

**Comment by aatifbandey** [comment]
with m.redraw() it works fine without using m.redraw() wont mithril auto redraw

**Comment by Zhouzi** [comment]
You should attach your event handlers the "mithril-way" e.g:

```javascript
m('button[type=button]', {onclick: function () {}, 'Some button'})
```

Here is how you could implement a counter: http://jsfiddle.net/cjjwh83w/
Relevant documentation: https://lhorie.github.io/mithril/mithril.html
