### ISSUE TITLE
Attach an event handler on an element with mithril

### ISSUE THREAD

**Issue by aatifbandey** [lhorie/mithril.js#796]
i am working on a project where i want event event handler in one of the cases where x=='a' and not for other case so can we attach and event handler to the element in mithril
   
     if (x=='a'){
   
      view = m('.leftPaneGrey#id', {
                      key: 1,
                      class: (some.vm.selectKey() === 1) ? 'changeColor' : '',
                      onclick: loadNewStage.bind('', 1)
                   },
             m('span', 'test')
        );

    }
         else {
   
      view = m('.leftPaneGrey#id' ,
             m('span', 'test')
        );

    }

**Comment by Zhouzi** [comment]
Here is an example of how you could return a different view based on a given parameters: http://jsfiddle.net/jg32cLsd/

That been said, I'd recommend to simply stop the execution of the function when the flag is disabled: http://jsfiddle.net/jg32cLsd/1/

**Comment by aatifbandey** [comment]
But handler will there always if ctrl.enabled is false

**Comment by Zhouzi** [comment]
Sure but there's nothing wrong with it. Actually, the fact that the button shouldn't do anything in certain situations is probably related to some logic that should be handled by the controller. 

Let's consider an example where you have a button that loads some data from a server. While the request is pending, chances are you'll want to store the loading state to avoid requesting twice the same resource in case the user click the button again. So the fact that the button should have no effect when loading is strongly related to the state of the controller.

I've created a fiddle to illustrate this example: http://jsfiddle.net/z5arjn5h/

Reading the "loadSomeData" function, it's pretty clear that nothing is going to happen if the loading state is set to true. Using your approach (http://jsfiddle.net/z5arjn5h/1/) the logic is abstracted from the controller to the view and things tends to get confusing.
