### ISSUE TITLE
Should controllers be restricted to be a constructor?

### ISSUE THREAD

**Issue by Zhouzi** [lhorie/mithril.js#799]
I am submitting an issue to open up the discussion on whether controllers should be restricted to be a constructor or a function (but not both). This issue may relate to #618 #733 #735.

For now, Mithril is supposed to support both approaches and it works just fine until you get to use a constructor with `m.component`. The problem being that there's no real way to know if the controller must be used as a constructor `new fn()` or a function call `fn()`. Currently it's the later that's used with an attempt to move prototyped methods from an object to another: https://github.com/lhorie/mithril.js/blob/next/mithril.js#L742

This leads to inconsistencies and unexpected behavior. So the question is, should the use of controller be restricted to one of those approach but not both? IMHO a controller should be a "class" (constructor) but I know that some of Mithril's contributors prefer the function call pattern.

**Comment by barneycarroll** [comment]
It's about time this conversation was had again :)

I believe constructors are an incredibly ambiguous, brittle and overrated Javascript 'feature'. Eric Elliott writes up some of the generic arguments against them [here](https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3). 

As regards how all this relates to Mithril specifically: it's impossible - without ECMA Script 5 (which means ditching IE<9 support) - to [partially apply variadic constructors](http://stackoverflow.com/questions/10594957/binding-applying-constructors-in-javascript) - ie subclasses - whilst retaining `instanceof`. And it's impossible to achieve deferred variadic construction without subclassing until ECMA Script 6 (still not fully implemented by any browser as of now). This just one example of how fragile, confusing and disparate the whole class / constructor / prototype / instance API is. See people who've seen this screw them up [here](http://stackoverflow.com/questions/10594957/binding-applying-constructors-in-javascript).

Moreover the case for subclassing / getting any value out of construction / prototyping in controllers hasn't been made anywhere I've seen where it isn't easier and safer to do it without using those specific APIs. There was [this article on the Mithril blog](http://lhorie.github.io/mithril-blog/prototypes-closures-and-the-zen-of-javascript-oop.html), but it doesn't look credible to me.

There was talk of ditching the notion of constructor controllers - and advocating explicit `return`s in Mithril 0.2. The bugs you've mentioned are excellent reasons why this should be followed through explicitly.

**Comment by Zhouzi** [comment]
Thanks for sharing @barneycarroll, lots of very interesting and valid points in there. Actually I'm not against the idea of using a function's return value but I believe Mithril do need to make a choice (unless both syntax are fully supported - which is not the case).

According to #802, it looks like Mithril's next version is going to address this issue so I'm closing :)

**Comment by impinball** [comment]
@Zhouzi Not necessarily the next version, but the current consensus AFAICT is that both should be supported. The only reason it isn't yet added is because the current implementation is so tightly coupled to the current `controller`/`view` format.
