### ISSUE TITLE
Use a real testing and assertion framework

### ISSUE THREAD

**Issue by impinball** [lhorie/mithril.js#801]
Come up a couple times in Gitter with @lhorie.

Reasons:

- More approachable for new contributors.
- Easier to know what broke.
- Better assertion error messages (euphemism).
- Easier debugging experience with core.

Ideas:

- Mocha + Chai/Should/Expect/etc. (most likely)
- QUnit
- Jasmine
- Tape
- Something else better than what's [currently used](https://github.com/lhorie/mithril.js/blob/next/tests/test.js)

**Comment by barneycarroll** [comment]
Mithril suffers from the ['lightweight' anti-pattern](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4): testing is one of many aspects that was kept small and without dependencies at the cost of clarity and manageability. Having said that, [there are very good arguments in favour of keeping tests simple](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4) while keeping the benefit of assertions, granularity, and messaging.

**Comment by impinball** [comment]
@barneycarroll I gave Mocha as most likely since that's what @lhorie said in Gitter a while back, if I recall correctly. I can help migrate the tests, once the final opinion has been made.

**Comment by impinball** [comment]
@barneycarroll I'm actually considering rewriting a bunch of unit tests (actually in the 200-300 range) in tape, simply because Chai is getting limiting in its assertions, it's verbose, and Mocha is verbose as one of the least verbose of the testing frameworks. And plus, rewriting Mithril's tests will be easy in tape, as a similar format is already used.

**Comment by lhorie** [comment]
> testing is one of many aspects that was kept small and without dependencies at the cost of clarity and manageability

Yeah... I didn't want to bother setting it up properly at the beginning, but in hindsight that was obviously a bad call.

To be honest, I don't particularly care about what testing framework is used, as long as individual assertions get descriptions. @impinball if you want to submit a PR, I can fill in the assertion descriptions.
