### ISSUE TITLE
Invalid Argument Exception on Component Mount

### ISSUE THREAD

**Issue by gdubbs1776** [lhorie/mithril.js#810]
I have been working with Mithril 0.2 . I am only experiencing this issue in IE 11. 
The issue I am experiencing occurs when I have a component mounted and then use the application functionality to remove the widget hosting the component. When I try to re-add the widget with the same component again I receive an error: Invalid Argument. 

Line 356 to line 369:
```
//corner case: replacing the nodeValue of a text node that is a child of a textarea/contenteditable doesn't work
//we need to update the value property of the parent textarea or the innerHTML of the contenteditable element instead
if (parentTag === "textarea") parentElement.value = data;
else if (editable) editable.innerHTML = data;
else {
		if (nodes[0].nodeType === 1 || nodes.length > 1) { //was a trusted string
		clear(cached.nodes, cached);
		nodes = [$document.createTextNode(data)]
		}
-------->parentElement.insertBefore(nodes[0], parentElement.childNodes[index] || null);
			nodes[0].nodeValue = data
}
 
```
The trouble is that the logic is expecting a nodeType equal to 1 (element node), however, it is getting nodeType equal to 3 (text node). The nodes array is of length 1.

I suspect nodes[0] is an empty text node as a result of a sluggish response from IE because I am not seeing this issue on any other browser. 

My current fix for this issue is to add logic to the if statement immediately above where the error is thrown:
```
if (nodes[0].nodeType === 1 || nodes.length > 1  || !nodes[0].nodeValue.trim() ) 
```
The code:
```
|| !nodes[0].nodeValue.trim()
```
checks that in the event there is a text node, and it is empty then we will clear the cache and create new nodes.

Would this be the correct fix for this particular scenario?

Just to re-iterate the initial add of the widget with the mithril component is added / mounted correctly the first time and the application works fine.

**Comment by sjungwirth** [comment]
I'm having the same error in IE on the same line in Mithril. When I break on the exception I can see that `nodes[0]` is an `EmptyTextNode`.

**Comment by gdubbs1776** [comment]
@sjungwirth : I am glad to hear that was able to assist you with this issue.
@lhorie and other participants : Is this something worth investigating further? I can pull and create a separate branch with this checkin that will fit my needs if this will not be addressed. Thanks.

**Comment by lhorie** [comment]
@gdubbs1776 do you want to send a PR with your fix?

**Comment by lhorie** [comment]
Fixed
