### ISSUE TITLE
Diff missing changes on element replacement

### ISSUE THREAD

**Issue by AugustBrenner** [lhorie/mithril.js#813]
If there is a scenario where an array of elements with different style or different text, and the element from the beginning is shifted off and pushed onto the end, the diff will not always recognize the change properly and even though many of the elements attributes and attached components will update properly, the element is sometimes left with the same text or color as before.

In the following example I have a text post component on top and a comment component on the bottom, both are feeding from the same data source

![screen shot 2015-10-14 at 9 41 05 pm](https://cloud.githubusercontent.com/assets/4537070/10504966/9ad745d2-72bc-11e5-8dcc-f73777aed427.png)

As I scroll the page up the data source array will shift the component off the array as soon as it passes 50px outside of the screen

![screen shot 2015-10-14 at 9 41 36 pm](https://cloud.githubusercontent.com/assets/4537070/10504971/a25c9730-72bc-11e5-8a29-2c68e78f9dd3.png)

Nearly There this is the moment of truth..........................................................................

![screen shot 2015-10-14 at 9 42 06 pm](https://cloud.githubusercontent.com/assets/4537070/10504972/a691eb34-72bc-11e5-80a3-d45ee7fe4b36.png)

And there you go, The item was shifted off the array. The virtual DOM diffing did it's work to remove the comment elements from the DOM because they clearly changed, as the first Item it the array no longer has any comments associated with it. But as you can see the text (which is wrapped inside an <a> tag) did not update.  Mithril did not sense that the text values had changed, and reused the same elements to reconstruct the DOM.

![screen shot 2015-10-14 at 9 42 40 pm](https://cloud.githubusercontent.com/assets/4537070/10504997/05c0569a-72bd-11e5-881a-a12da91919c6.png)

I have also been able to recreate this issue setting the background-color style.
Here is a demo I made from your getting started that has the issue in case you wanted to debug it

`<!doctype html>`
`<script src="mithril.min.js"></script>`
`<script>`
`    var InfiniteScroll = function(element, func, options){`

`        options = options || {}`

`        var disabled = false;`

`        var container = options.container || window`

`        this.disable = function(disable){`
`            disabled = disable;`
`        }`

`        this.destroy = function(){`
`            container.removeEventListener('scroll', handleScroll)`
`            container.removeEventListener('resize', handleScroll)`
`        }`

`        container.addEventListener('scroll', handleScroll)`
`        container.addEventListener('resize', handleScroll)`

`        function handleScroll(){`

`            if(disabled) return`

`            colors.vm.isScrolling = true    `

`            var rect = element.getBoundingClientRect()`

`            if(rect.bottom <= window.innerHeight){`
`                console.log('run')`
`                func()`
`            }`

`            colors.vm.viewPort.top = ~rect.top + 1`
`            colors.vm.viewPort.bottom = colors.vm.viewPort.top + window.innerHeight`

`            console.log(colors.vm.viewPort)`
`            m.redraw()`

`            return`

`        }`
`    }`

`var MIN_WIDTH = 250`

`//this application only has one component: colors`
`var colors = {};`

`//for simplicity, we use this component to namespace the model classes`

`//the Colors class has two properties`
`colors.Colors = function(data) {`
`    this.initialHeight = m.prop(data.height);`
`    this.color = m.prop(data.color);`
`    this.height = m.prop(0);`
`    this.top = m.prop(0);`
`    this.left = m.prop(0);`
`    this.shouldDisplay = m.prop(true);`
`};`

`//the ColorsList class is a list of Colors's`
`colors.ColorsList = Array;`

`//the view-model tracks a running list of colors,`
`//stores a description for new colors before they are created`
`//and takes care of the logic surrounding when adding is permitted`
`//and clearing the input after adding a colors to the list`
`colors.vm = (function() {`
`    var vm = {}`
`    vm.init = function() {`
`        //a running list of colors`
`        vm.list = new colors.ColorsList();`

`        // height`
`        vm.getHeight = function(){`
`            return Math.floor(Math.random() * 400) + 200 + 'px'`
`        }`

`        vm.getColor = function(){`
`            return '#'+Math.floor(Math.random()*16777215).toString(16);`
`        }`

`        vm.container = m.prop("")`

`        vm.setContainer = function(element, isInitialized){`
`            if(isInitialized) return`

`            vm.container(element)`

`            // setup infinite scroll`
`            var infiniteScroll = new InfiniteScroll(vm.container(), vm.add);`

`        }`

`        vm.getWidth = function(){`
`            return (1 / Math.floor(vm.container().clientWidth / MIN_WIDTH)) * 100 + '%'`
`        }`

`        vm.getColumnMin = function(index){`
`            var index = 0`
`            var length = vm.columns[0]`
`            var i = vm.columns.length`
`            while(i--){`
`                if(vm.columns[i] < length){`
`                    index = i;`
`                    length = vm.columns[i]`
`                }`
`            }`
`            return index`
`            // var columnLength = Math.floor(vm.container().clientWidth / MIN_WIDTH)`
`            // return (index % columnLength)`
`        }`

`        vm.viewPort = {`
`            top:0,`
`            bottom:0`
`        }`

`        vm.columns = []`
`        vm.setColumns = function(){`
`            colors.vm.columns = []`
`            for(var i = 0, len = Math.floor(vm.container().clientWidth / MIN_WIDTH); i < len; i++){`
`                vm.columns.push(0)`
`            }`
`        }`

`        vm.getLongestColumn = function(){`
`            var index = 0`
`            var length = 0`
`            var i = vm.columns.length`
`            while(i--){`
`                if(vm.columns[i] > length){`
`                    index = i;`
`                    length = vm.columns[i]`
`                }`
`            }`
`            return length`
`        }`

`         vm.getShortestColumn = function(){`
`            var index = 0`
`            var length = vm.columns[0]`
`            var i = vm.columns.length`
`            while(i--){`
`                if(vm.columns[i] < length){`
`                    index = i;`
`                    length = vm.columns[i]`
`                }`
`            }`
`            return index`
`        }`

`        vm.startTime = 0;`

`        vm.elementsToRender = 0`

`        vm.isScrolling = true`

`        vm.setPosition = function(element, isInitialized, context, vdom){`

`            if(vm.isScrolling === true) element.style['transition'] = 'none'`

`            var index = vdom.attrs.index;`

`            var height = element.clientHeight`

`            var column = vm.getColumnMin(index)`

`            if(vm.list[index].height() === 0){`

`                element.style['top'] = vm.columns[column] + 'px'`

`                vm.columns[column] += height`

`                element.style['left'] = (1 / Math.floor(vm.container().clientWidth / MIN_WIDTH)) * 100 * column + '%'`
`            }`

`            vm.list[index].height(height)`

`            if(vm.getLongestColumn() > vm.container().clientHeight){`
`                vm.container().style.height = vm.getLongestColumn() + 'px'`
`            }`

`            element.style['transition'] = 'top 0.15s linear, left 0.15s linear'`

                
`            vm.elementsToRender--`

`            if(vm.elementsToRender === 0){`
`                vm.isScrolling = false`
`            }`

`            if(vdom.attrs.index === vm.list.length - 1){`
`                console.log(Date.now() - vm.startTime)`
`            }`
`        }`

`        //adds a colors to the list, and clears the description field for user convenience`
`        vm.add = function() {`
`            var i = 40`
`            while(i--){`
`                vm.list.push(new colors.Colors({height: vm.getHeight(), color: vm.getColor()}));`
`            }`
`            m.redraw()`
`        };`

`        vm.changeHeight = function(index){`
`            return function(){`
`                vm.list[index].initialHeight(vm.getHeight())`
`            }`
`        }`

`    }`
`    return vm`
`}())`

`//the controller defines what part of the model is relevant for the current page`
`//in our case, there's only one view-model that handles everything`
`colors.controller = function() {`
`        colors.vm.init()`
`}`

`//here's the view`
`colors.view = function() {`
`    colors.vm.startTime = Date.now()`
`    return m("html", [`
`        m("body", [`
`            m("div", {config: colors.vm.setContainer, style: {'position': 'relative', 'width':'100%', 'height':'20px'}}, [`

`                function(){`

`                    var elements = []`
`                    colors.vm.setColumns()`
`                    console.log('Column Reset')`

`                    var reversionColumns = []`
`                    for(var i in colors.vm.columns){`
`                        reversionColumns[i] = 0`
`                    }`

`                    var len = colors.vm.list.length`
`                    var head = colors.vm.list.length - 1`
`                    while(len--){`
`                        var index = head - len;`

`                        var post = colors.vm.list[index]`
                            
`                        var height = post.height()`

`                        if(height > 0){`

`                            var column = colors.vm.getColumnMin(index)`
`                            var columnHeight = colors.vm.columns[column]`

`                            if(columnHeight > colors.vm.viewPort.bottom){`
`                                // console.log('Past Viewport: ' + index)`
`                                break`
`                            }`

`                            post.top(columnHeight)`
`                            colors.vm.columns[column] += height`

`                            if((columnHeight + height) < colors.vm.viewPort.top){`
`                                // console.log('Before Viewport: ' + index)`
`                                continue`
`                            }`
`                            else{`
`                                reversionColumns[column] += height`
`                                post.height(0)`
`                            }`

`                            post.left((1 / Math.floor(colors.vm.container().clientWidth / MIN_WIDTH)) * 100 * column)`
`                        }`

`                        elements.push(m("div", {onclick: colors.vm.changeHeight(index), config: colors.vm.setPosition, index: index, style: {'position':'absolute', 'height': post.initialHeight(), 'top': post.top() + 'px', 'left': post.left() + '%', 'width': colors.vm.getWidth(), 'background-color': post.color()}}, index + "    Hey Leo, you're lookin' real cool today"))`
`                    }`

`                    for(var i in reversionColumns){`
`                        colors.vm.columns[i] -= reversionColumns[i]`
`                    }`

`                    colors.vm.elementsToRender = elements.length`

`                    return elements`

`                }(),`

`                m("button", {onclick: colors.vm.add, style:{'position':'absolute', 'bottom': '0', 'left':'10px'}}, "Add")`
`            ])`
`        ])`
`    ])`
`};`

`m.mount(document, {controller: colors.controller, view: colors.view});`

`</script>`

**Comment by AugustBrenner** [comment]
Here is a quick color demo I made from your getting started that has the issue in case you wanted to debug it


<!doctype html>
<script src="mithril.min.js"></script>
<script>
    var InfiniteScroll = function(element, func, options){

        options = options || {}

        var disabled = false;

        var container = options.container || window

        this.disable = function(disable){
            disabled = disable;
        }

        this.destroy = function(){
            container.removeEventListener('scroll', handleScroll)
            container.removeEventListener('resize', handleScroll)
        }

        container.addEventListener('scroll', handleScroll)
        container.addEventListener('resize', handleScroll)


        function handleScroll(){

            if(disabled) return

            colors.vm.isScrolling = true    

            var rect = element.getBoundingClientRect()

            if(rect.bottom <= window.innerHeight){
                console.log('run')
                func()
            }

            colors.vm.viewPort.top = ~rect.top + 1
            colors.vm.viewPort.bottom = colors.vm.viewPort.top + window.innerHeight

            // console.log(colors.vm.viewPort)
            m.redraw()

            return

        }
    }










    var MIN_WIDTH = 250


    //this application only has one component: colors
    var colors = {};

    //for simplicity, we use this component to namespace the model classes

    //the Colors class has two properties
    colors.Colors = function(data) {
        this.initialHeight = m.prop(data.height);
        this.color = m.prop(data.color);
        this.height = m.prop(0);
        this.top = m.prop(0);
        this.left = m.prop(0);
        this.shouldDisplay = m.prop(true);
    };

    //the ColorsList class is a list of Colors's
    colors.ColorsList = Array;

    //the view-model tracks a running list of colors,
    //stores a description for new colors before they are created
    //and takes care of the logic surrounding when adding is permitted
    //and clearing the input after adding a colors to the list
    colors.vm = (function() {
        var vm = {}
        vm.init = function() {
            //a running list of colors
            vm.list = new colors.ColorsList();

            // height
            vm.getHeight = function(){
                return Math.floor(Math.random() * 400) + 200 + 'px'
            }

            vm.getColor = function(){
                return '#'+Math.floor(Math.random()*16777215).toString(16);
            }

            vm.container = m.prop("")

            vm.setContainer = function(element, isInitialized){
                if(isInitialized) return

                vm.container(element)

                // setup infinite scroll
                var infiniteScroll = new InfiniteScroll(vm.container(), vm.add);

            }

            vm.getWidth = function(){
                return (1 / Math.floor(vm.container().clientWidth / MIN_WIDTH)) * 100 + '%'
            }

            vm.getColumnMin = function(index){
                var index = 0
                var length = vm.columns[0]
                var i = vm.columns.length
                while(i--){
                    if(vm.columns[i] < length){
                        index = i;
                        length = vm.columns[i]
                    }
                }
                return index
                // var columnLength = Math.floor(vm.container().clientWidth / MIN_WIDTH)
                // return (index % columnLength)
            }

            vm.viewPort = {
                top:0,
                bottom:0
            }


            vm.columns = []
            vm.setColumns = function(){
                colors.vm.columns = []
                for(var i = 0, len = Math.floor(vm.container().clientWidth / MIN_WIDTH); i < len; i++){
                    vm.columns.push(0)
                }
            }

            vm.getLongestColumn = function(){
                var index = 0
                var length = 0
                var i = vm.columns.length
                while(i--){
                    if(vm.columns[i] > length){
                        index = i;
                        length = vm.columns[i]
                    }
                }
                return length
            }

             vm.getShortestColumn = function(){
                var index = 0
                var length = vm.columns[0]
                var i = vm.columns.length
                while(i--){
                    if(vm.columns[i] < length){
                        index = i;
                        length = vm.columns[i]
                    }
                }
                return index
            }

            vm.startTime = 0;

            vm.elementsToRender = 0

            vm.isScrolling = true

            vm.setPosition = function(element, isInitialized, context, vdom){

                if(vm.isScrolling === true) element.style['transition'] = 'none'

                var index = vdom.attrs.index;

                var height = element.clientHeight

                var column = vm.getColumnMin(index)

                if(vm.list[index].height() === 0){

                    element.style['top'] = vm.columns[column] + 'px'

                    vm.columns[column] += height

                    element.style['left'] = (1 / Math.floor(vm.container().clientWidth / MIN_WIDTH)) * 100 * column + '%'
                }

                vm.list[index].height(height)

                if(vm.getLongestColumn() > vm.container().clientHeight){
                    vm.container().style.height = vm.getLongestColumn() + 'px'
                }

                element.style['transition'] = 'top 0.15s linear, left 0.15s linear'

                
                vm.elementsToRender--

                if(vm.elementsToRender === 0){
                    vm.isScrolling = false
                }

                if(vdom.attrs.index === vm.list.length - 1){
                    console.log(Date.now() - vm.startTime)
                }
            }

            //adds a colors to the list, and clears the description field for user convenience
            vm.add = function() {
                var i = 40
                while(i--){
                    vm.list.push(new colors.Colors({height: vm.getHeight(), color: vm.getColor()}));
                }
                m.redraw()
            };

            vm.changeHeight = function(index){
                return function(){
                    vm.list[index].initialHeight(vm.getHeight())
                }
            }


        }
        return vm
    }())

    //the controller defines what part of the model is relevant for the current page
    //in our case, there's only one view-model that handles everything
    colors.controller = function() {
            colors.vm.init()
    }

    //here's the view
    colors.view = function() {
        colors.vm.startTime = Date.now()
        return m("html", [
            m("body", [
                m("div", {config: colors.vm.setContainer, style: {'position': 'relative', 'width':'100%', 'height':'20px'}}, [

                    function(){

                        var elements = []
                        colors.vm.setColumns()
                        console.log('Column Reset')

                        var reversionColumns = []
                        for(var i in colors.vm.columns){
                            reversionColumns[i] = 0
                        }

                        var len = colors.vm.list.length
                        var head = colors.vm.list.length - 1
                        while(len--){
                            var index = head - len;

                            var post = colors.vm.list[index]
                            
                            var height = post.height()

                            if(height > 0){

                                var column = colors.vm.getColumnMin(index)
                                var columnHeight = colors.vm.columns[column]


                                if(columnHeight > colors.vm.viewPort.bottom){
                                    // console.log('Past Viewport: ' + index)
                                    break
                                }

                                post.top(columnHeight)
                                colors.vm.columns[column] += height


                                if((columnHeight + height) < colors.vm.viewPort.top){
                                    // console.log('Before Viewport: ' + index)
                                    continue
                                }
                                else{
                                    reversionColumns[column] += height
                                    post.height(0)
                                }

                                post.left((1 / Math.floor(colors.vm.container().clientWidth / MIN_WIDTH)) * 100 * column)
                            }

                            elements.push(m("div", {onclick: colors.vm.changeHeight(index), config: colors.vm.setPosition, index: index, style: {'position':'absolute', 'height': post.initialHeight(), 'top': post.top() + 'px', 'left': post.left() + '%', 'width': colors.vm.getWidth(), 'background-color': post.color()}}, index + "    Hey Leo, you're lookin' real cool today"))
                        }

                        for(var i in reversionColumns){
                            colors.vm.columns[i] -= reversionColumns[i]
                        }

                        colors.vm.elementsToRender = elements.length

                        return elements

                    }(),

                    m("button", {onclick: colors.vm.add, style:{'position':'absolute', 'bottom': '0', 'left':'10px'}}, "Add")
                ])
            ])
        ])
    };


    m.mount(document, {controller: colors.controller, view: colors.view});

</script>

**Comment by Bondifrench** [comment]
I might be wrong but sounds like a typical case of keys's usage in a list:
http://mithril.js.org/mithril.html#dealing-with-sorting-and-deleting-in-lists

**Comment by AugustBrenner** [comment]
You were exactly right.  I added a key attribute and it fixed all of the issues. Not a bug after all. Thank you!
