### ISSUE TITLE
Error in IE8

### ISSUE THREAD

**Issue by suhaotian** [lhorie/mithril.js#818]
I just change the guide code:
```js
m("td", {style: {textDecoration: task.done() ? "line-through" : "none"}}, task.description())
```
to
```js
m("td", [m('label',{for: index, class: task.done() ? "done" : ""}, task.description())])
```
then don't work 

demo at: http://jsbin.com/kunoxirura

**Comment by adriengibrat** [comment]
Numeric id may be the source of your bug, could you try with: 
` m("input[type=checkbox]", {id: 'task_' + index})`

`m('label', {for: 'task_' + index}, task.description())`

**Comment by suhaotian** [comment]
still alive: 
![_ db_lp n 7ocdrlyqs_ze](https://cloud.githubusercontent.com/assets/6512574/10725236/6a16379e-7c05-11e5-9d75-34bc3f118804.jpg)

**Comment by Bondifrench** [comment]
what is the `for` used for in `m('label', {})`? Where did you see it used in the examples/tutorials for Mithril?

**Comment by lhorie** [comment]
it should be `{htmlFor: 'task_' + index}` or `{'for': 'task_' + index}`

**Comment by suhaotian** [comment]
@Bondifrench  well, I add 'label' by myself for test it ..

**Comment by tinchoz49** [comment]
```for``` is a reserved word of the javascript language. If you want use that word in a literal object you need define the property as a string. As @lhorie explained above.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar

**Comment by suhaotian** [comment]
@lhorie  thanks,  but just now I change `for` to `'for'` or `htmlFor`,  don't change anything. 
but I remove `class: test` , it's work .  
![image](https://cloud.githubusercontent.com/assets/6512574/10732966/7ff3cb9e-7c37-11e5-82a0-372418d2d854.png)

**Comment by suhaotian** [comment]
@tinchoz49 and the `class` too

**Comment by suhaotian** [comment]
I change `class` to `'class'`, it's work! so close it

**Comment by lhorie** [comment]
ah, yeah. `class` is also a reserved word.
