### ISSUE TITLE
Compiler variable does not matched

### ISSUE THREAD

**Issue by accessibleweb** [lhorie/mithril.js#819]
Hi,
I found two problems or maybe it is because i does not use compiler like it should be...

1) Reading https://lhorie.github.io/mithril/optimizing-performance.html
and http://sweetjs.org/doc/main/sweet.html
sjs -r -m ./template-compiler.sjs -o view.compile.js view.js
It transform some variables event if i pass --readable-names.

So 

```
var model = {count: 0}

var MyComponent = {
    controller: function(data) {
        return {
            increment: function() {
                //This is a simplication for the sake of the example.
                //Typically, values are modified via model methods,
                //rather than modified directly
                model.count++
            }
        }
    },
    view: function(ctrl) {
        return m("a[href=javascript:;]", {
            onclick: ctrl.increment //view calls controller method on click
        }, "Count: " + model.count)
    }
}

```

Will produce 
```
var model = { count: 0 };
var MyComponent = {
    controller: function (data) {
        return {
            increment: function () {
                //This is a simplication for the sake of the example.
                //Typically, values are modified via model methods,
                //rather than modified directly
                model.count++;
            }
        };
    },
    view: function (ctrl$2) {
        return {
            tag: 'a',
            attrs: {
                'href': 'javascript:;',
                onclick: ctrl.increment
            },
            children: 'Count: ' + model.count
        };
    }
};
m.mount(document.body, MyComponent);
```

The ctrl variable is not defined.

2) Other issue is when you define var m = require('mitrhiljs');
The compiler does not compile.

**Comment by tivac** [comment]
I'd recommend [mithril-objectify](https://www.npmjs.com/package/mithril-objectify) instead, and @lhorie [seems to agree](https://twitter.com/LeoHorie/status/659487458032295938).

**Comment by lhorie** [comment]
+1 what @tivac said. sweet.js has been giving me a lot of headaches.

**Comment by accessibleweb** [comment]
@tivac @lhorie Thanks !!! you saved my day :)

**Comment by tivac** [comment]
@accessibleweb Very curious to see how it goes for you! `mithril-objectify` is pretty new but we've been using it in our dev environment without issues. If you run into any bugs I'd love to hear about them :+1:

**Comment by barneycarroll** [comment]
@tivac out of interest, so you do any kind of automated performance analysis?

**Comment by tivac** [comment]
@barneycarroll nothing recently, but I'd like to get set back up on [SpeedCurve](https://speedcurve.com/). We used them during their beta period and it was amazing.

`mithril-objectify` has been able to convert 50-75% of our `m()` invocations into static objects, I haven't taken deep perf readings yet on the result of that unfortunately, but it's unlikely to be slower! Once we have some real-world data I'll probably update the readme with our findings.

**Comment by barneycarroll** [comment]
Didn't know about SpeedCurve, I'd recently hit upon [browser-perf](https://www.npmjs.com/package/browser-perf) and thought, Jesus, why aren't we all using this!

**Comment by accessibleweb** [comment]
@tivac I have not tested yet, i will check it next week.
I will provide an app generator / CMS with UI and set of components in order to create quiclky and easly applications with a small of code :)

**Comment by impinball** [comment]
To be honest, the template compiler is at this point very out of sync with the current API. It may be removed in the future.
