### ISSUE TITLE
cached.nodes is undefined

### ISSUE THREAD

**Issue by xlaywan** [lhorie/mithril.js#820]
I sometimes catch a bug on this line, cached.nodes is undefined:
```var isNew = cached.nodes.length === 0;```

Maybe replace it by this?
```var isNew = !cached.nodes || cached.nodes.length === 0;```

**Comment by Zhouzi** [comment]
I think it would be really helpful if you could come up with a way to reproduce the bug or at least give some more details on when/how it happens.

**Comment by impinball** [comment]
@xlaywan A stack trace would be extremely helpful here.

**Comment by impinball** [comment]
Also, if you can show some code that causes this to fail, that would be even more helpful.

**Comment by lhorie** [comment]
Please re-file with reproduction steps
