### ISSUE TITLE
`e.preventDefault` doesn't skip route change when called in `.onunload`

### ISSUE THREAD

**Issue by isiahmeadows** [lhorie/mithril.js#825]
[Relevant tests](https://github.com/lhorie/mithril.js/blob/0b173deed753ce86762f02e79446e32324064770/test/mithril.route.js#L105-L222).

It initializes the controller when it shouldn't.

**Comment by 2is10** [comment]
Fixed now? Looks like #1117 enabled those tests.

**Comment by isiahmeadows** [comment]
@2is10 Correct. This is a relatively old bug, anyways.
