### ISSUE TITLE
mithril.min.js is not kept in sync with mithril.js

### ISSUE THREAD

**Issue by mrtracy** [lhorie/mithril.js#827]
There is currently no system in place to ensure that the checked-in `mithril.min.js` is kept up-to-date with `mithril.js`.  For example, as of this issue the two files are out of sync in the "next" branch.  This can present surprising problems when attempting to test new versions of Mithril in downstream projects (for example, by updating a version in bower).

**Comment by lhorie** [comment]
`grunt build` should regenerate the minified file. Or am I misunderstanding?

**Comment by barneycarroll** [comment]
@lhorie you might want to ensure Mithril is never updated in package repositories without running all these steps. For npm you can add a `prepublish` script to handle this: https://github.com/barneycarroll/xet/blob/master/package.json#L7

**Comment by lhorie** [comment]
That's a good idea. Want to send a PR?

**Comment by barneycarroll** [comment]
Wilco :)
