### ISSUE TITLE
Rendering other things besides DOM.

### ISSUE THREAD

**Issue by trusktr** [lhorie/mithril.js#830]
Can Mithril be used to render other things besides DOM structures. For example, what if I want to render Three.js scene graph structures?

**Comment by JoshGalvin** [comment]
I did an experiment with the Three.js scene graph example.
https://github.com/joshgalvin/xule

While you can't use three.js directly for that, you can definitely take inspiration from it. You can render SVG structures w/ Three.js btw.

**Comment by Bondifrench** [comment]
I am using [paths-js](https://github.com/andreaferretti/paths-js) to render svg graphs with Mithril, it works perfectly well.

**Comment by barneycarroll** [comment]
This is really interesting. React 0.14 has managed to separate the high-level view language and diffing process from the build & patch operations (for which you can use either React DOM or React native). React already had component methods such as `shouldUpdate` that allowed a comparison of input data from one draw to the next, but in practice you can perform this logic in the `view` function, and (if you're using Mithril to create the DOM that houses your canvas) you can use `config` on a Mithril-created node to perform whatever canvas / WebGL draw operations you need.

@Bondifrench I was reading the recent [AMA with Mike Bostock](https://www.reddit.com/r/dataisbeautiful/comments/3k3if4/hi_im_mike_bostock_creator_of_d3js_and_a_former/) and reading about what he thought made D3 so special, and he said it was the `data` & `join` operations - being able to associate data points with DOM nodes. And I was thinking, this is so trivial with Mithril. Seeing as Mithril can do SVG out of the box, what are the advantages of using a specifically SVG-targeted library within Mithril? Can you show us or outline an example of how you use the two in conjunction?

**Comment by Bondifrench** [comment]
@barneycarroll Sorry for the late reply.
When you are doing a chart with svg, there needs to be some abstraction to draw geometric shapes and lines.
In particular, you don't want Mithril to handle the very low level stuff like generating `path`. 
A typical example of path looks rather obscure: `M 50 0 A 50 50 0 0 1 89.599813 19.473703 L 73.759888 31.684222 A 30 30 0 0 0 50 20 Z`
I have implemented an example of using `Mithril` with `paths-js`, [here](http://codepen.io/bondifrench/pen/jbJVXa), inspired by this [article](http://www.sitepoint.com/create-performant-template-based-charts-paths-js/), showing both the plain javascript and the Mithril implementations.
I think the Mithril version looks very clean, both complement each other very well, one for creating DOM stuff, the other for calculating svg shapes.

**Comment by trusktr** [comment]
> React already had component methods such as shouldUpdate that allowed a comparison of input data from one draw to the next

Just thought I'd throw it out there, but I wouldn't recommend using that for things like drawing (svg) animations, as ticking react in an animation loop won't be so performant. React's great for creating structures that change over time, but not necessarily for modifying those structures at 60fps. For example, instead of animating each tick of an animation with React (or Mithril) you might like to instead just change the start and end state of some structure, then handle the actual transition natively (CSS animations, custom WebGL code, etc).

**Comment by impinball** [comment]
@trusktr Mithril does render at 60fps. I don't know how well suited it is for SVG animations, though, and it most certainly isn't a drop-in replacement for WebGL. :smile:

**Comment by lhorie** [comment]
For animations, you really do want to run as little code as possible between frames, so I'm actually inclined to agree w/ @trusktr that you should prefer to offload animations to CSS or a dedicated library.

**Comment by trusktr** [comment]
If we tick mithril (or React) we'll be ticking the diff mechanism every frame, which can possibly run at 60fps if the animation isn't too complex and the tree structures to diff aren't too big, but there's definitely an overhead from that compared to just animating purely with an engine designed for animation.

**Comment by isiahmeadows** [comment]
@trusktr Still, Mithril is probably not the best one to run animations on. As great as Mithril is, animations aren't really its thing.

**Comment by trusktr** [comment]
> Mithril is probably not the best one to run animations on

@isiahmeadows I hear what you're saying, but the problem is that I see many people (online, as well as people I've met in real life) trying to use things like React, Mithril, Elm, for animation without thinking of the performance hit. The way these libraries are designed, it is tempting to be able to make animations in such a way as Mithril, React, etc let us program. It's actually nice in concept, but the mechanism behind these libraries just simply isn't a good fit for performant animations.

On the other hand, things like Mithril, React, etc, are a great fit for determining changes to a UI structure (or any other structure) on a non-animation-based basis (for example, switching views or layouts on a single user action (not on a repeated animation tick).

**Comment by isiahmeadows** [comment]
Yeah, but the problem with vdom libraries in that application is that you
can't diff an object as fast as you can simply mutate references. Not even
Cito, the fastest library out there right now, can render 60 frames a
second in simple cases. It's a misunderstanding of how tree diff algorithms
work (and the only way to fix it is with persistent structures faster than
any JS library that exists right now).

**Comment by trusktr** [comment]
Yep, exactly! Thanks for pointing that out.

n a side note, I just discovered that cito will support Promises, which makes it really really attractive to me because we can use `async` functions in the `children` of an element. Wow!

**Comment by barneycarroll** [comment]
@isiahmeadows a good way to mitigate massive node hierarchy diffs is to decorate views so as to return subtree retainers based on custom logic comparing new input received to previous input.

@trusktr the above is a degree simpler in Cito, where a view can return undefined to noop its diff.

**Comment by barneycarroll** [comment]
Just remembered [I wrote a gist for that very purpose](https://gist.github.com/barneycarroll/4c395a2dafe90f4043e5) (custom diff logic per-component)

**Comment by isiahmeadows** [comment]
That doesn't solve the problem of if it's nested deeply inside a sea of
nodes, which is why subtree rendering is such a high demand feature
request. It's a performance bottleneck when you're rendering an entire tree
only to animate with a deeply nested SVG.

That's probably one of the two main reasons why no vdom library has stood a
chance in rendering smooth animations, the second being the inherent high
GC pressure from creating a ton of objects living just long enough to
survive the first generation (which are usually pooled where possible) in
most engines.

**Comment by JoshGalvin** [comment]
https://github.com/JoshGalvin/aframemulti/blob/master/app.js


I was able to use Mithril to render a-frame elements which ultimately go through three.js to WebGL. This seems like a pretty great way of utilizing Mithril to render non-dom elements (by rendering dom elements ;) )

**Comment by trusktr** [comment]
Yes indeed!

/#!/JoePea

**Comment by isiahmeadows** [comment]
Just FYI, this isn't a sufficient enough use case to add support in Mithril
proper. If you want to create a utility to do that, no one's going to
complain. Just be aware that GC will kill your performance. (This is why
vdom libraries are unsuitable for animations - they put a lot of pressure
on the GC because most of the objects survive just barely too long to be
reliably elided or pooled efficiently, and they're too deep to quickly
collect.)
