### ISSUE TITLE
help !

### ISSUE THREAD

**Issue by suhaotian** [lhorie/mithril.js#842]
In http://mithril.js.org/ , the Sample code is fine :)

I try to add search to filter the result,easy like this (see **search** method):
```js
       	//controller
	controller: function() {
		var pages = Page.list();
		return {
			pages: pages,
			rotate: function() {
				pages().push(pages().shift());
			},
			search: function() {
				
				var TMP = pages().filter(function(page){
					if (page['title'].indexOf('Get')>-1) return page;
				})
			}
		}
	},
```
```js
	//view
	view: function(ctrl) {
		return m("div", [
			ctrl.pages().map(function(page) {
				return m("a", {href:'#' + page.url}, page.title);
			}),
			m("button", {onclick: ctrl.rotate}, "Rotate links"),
			m('button', {onclick: ctrl.filter}, 'filter')
		]);
	}
```
how could I make **TMP** to change the pages's data and redraw render it? please help!

**Comment by lhorie** [comment]
You could pull out the filter and use it in the view. Then the search method would simply change the search term used by the filter function

https://jsfiddle.net/L6yu6xk2/

**Comment by suhaotian** [comment]
:+1: nice answer , thank you!
