### ISSUE TITLE
Maybe bug ?

### ISSUE THREAD

**Issue by suhaotian** [lhorie/mithril.js#843]
```js
var Demo = {
	//controller
	controller: function() {
		var pages = Page.list(),
			searchTerm = ''
		return {
			pages: pages,
			rotate: function() {
				pages().push(pages().shift());
			},
			filter: function(page) {
				
				return page['title'].toLowerCase().indexOf(searchTerm.toLowerCase()) > -1
				
			},
			search: function(v) {
				searchTerm = v.trim() || ''
			}
		}
	},

	//view
	view: function(ctrl) {
		return m("div", [
			m("input", {onkeyup: m.withAttr('value', ctrl.search)}),
			m("button", {onclick: ctrl.rotate}, "Rotate links"),
			ctrl.pages().filter(ctrl.filter).map(function(page) {
				return m("a", {href:'#' + page.url}, page.title);
			})	
		]);
	}
};
```
it's fine:
![11 13 2015 02 34](https://cloud.githubusercontent.com/assets/6512574/11127592/00f8c16a-89b0-11e5-881d-203797d8dc24.gif)

but when I put **m("button", {onclick: ctrl.rotate}, "Rotate links")** to the **ctrl.pages().filter...** after, like this:
 ```js
	//view
	view: function(ctrl) {
		return m("div", [
			m("input", {onkeyup: m.withAttr('value', ctrl.search)}),
			ctrl.pages().filter(ctrl.filter).map(function(page) {
				return m("a", {href:'#' + page.url}, page.title);
			}),
                        m("button", {onclick: ctrl.rotate}, "Rotate links")	
		]);
	}
```
then the rotate button render again, see gif:
![again](https://cloud.githubusercontent.com/assets/6512574/11127598/0b69e98a-89b0-11e5-9cf0-3356098880e5.gif)

why different ? is it a bug ?

Demo at:  http://jsbin.com/nenekiziwu and http://output.jsbin.com/regefokigu 
type something and see console DOM change

**Comment by lhorie** [comment]
You should use keys if dealing w/ variable size arrays: http://lhorie.github.io/mithril/mithril.html#dealing-with-sorting-and-deleting-in-lists

Or put the list of `<a>`'s inside of a `<div>`

**Comment by suhaotian** [comment]
@lhorie  Thank you for your patience.

**Comment by lhorie** [comment]
Happy to help :)
