### ISSUE TITLE
How to render plain text in m?

### ISSUE THREAD

**Issue by futurist** [lhorie/mithril.js#847]
How to render plain text in m? like this html:
````
<div><span>abc</span>&nbsp;&nbsp;<span>cde</span></div>
````
translate into m('div', [m('span', 'cde'), ?, m('span', 'cde')] )

The ? part, I don't know how to do, 
the document don't reveal how, so maybe it's an enhancement?

**Comment by renancouto** [comment]
Use `m.trust`, like this:

```
m('div', [
  m('span', 'abc'),
  m.trust('&nbsp;&nbsp;'),
  m('span', 'cde')
])
```

**Comment by futurist** [comment]
true, it's can be done! Mithril is awesome!
