### ISSUE TITLE
Mithril and Immutable Data (Rendering other things besides DOM)

### ISSUE THREAD

**Issue by veggiemonk** [lhorie/mithril.js#848]
I was wondering exactly the same thing as #830 (Rendering other things besides DOM).

How about persistent data structures library? If you use `immutable.js` or `mori.js`, you end up doing a lot of `.toJS()` if it's a Map or `.toArray()` if it is a List. Is there a way to let mithril know how to destructure immutable object? Most people had the same problem in `React`  ( both `React` and `Immutable.js` are from facebook, now `React` 0.14 can destructure immutable object ). 

Immutable objects also allow for **super fast diffing** because a reference to an immutable object, no matter how deep the data tree, can be compared by just `===`. If the reference to the immutable object is not changed, the whole object is exactly the same. Which is a powerful things to know when diffing. That allows for some optimizations with the method `shouldComponentUpdate` (in React). 

This talk is by the author of `Immutable.js` is very interesting: [React.js Conf 2015 - Immutable Data and React](https://www.youtube.com/watch?v=I7IdS-PbEgI)

There are libraries like `Om` (made by David Nolen (@swannodette on github) who take advantages of immutable object and and a rendering library (in this case, again, React).

Could we do the same with mithril? 

For those who want to play with immutable data and mithril, this environment is ready: http://codepen.io/veggiemonk/pen/bVOKMY

**Comment by tinchoz49** [comment]
Hi @veggiemonk maybe you can extend the example code of [bindOnce](https://lhorie.github.io/mithril/mithril.render.html) and create a shouldComponentUpdate function working with immutable structures.

**Comment by tivac** [comment]
@tinchoz49 that's a pretty interesting idea! We've been experimenting w/ mithril & redux and found that the auto-redraw doesn't make much sense when you've got a redux store managing all application state. 

Something like what you've proposed could make that way more straightforward.

**Comment by barneycarroll** [comment]
Replicating `shouldComponentUpdate` just requires proxying the view with `{ subtree : 'retain' }` as failure case return, something like this:

```Javascript
const should = 'shouldComponentUpdate'
const retain = { subtree : 'retain' }

const reactive = component => ( {
	...component,
	view : function(){
		if( should in this && !this[ should ]( ...arguments ) )
			return retainer
		
		return this::component.view( ...arguments )
	}
} )
```

**Comment by veggiemonk** [comment]
Thank @tinchoz49 @tivac @barneycarroll for your suggestions and code. I'm a just speechless every time something seems super complicated, there are always a use case in mithril with a code example. This is quite amazing.

There is this [fiddle](http://jsfiddle.net/veggiemonk/cuvhwdnv/4/) with the code from the website (bindOnce). 
And this [fiddle](http://jsfiddle.net/veggiemonk/y2b0dyf0/3/) with the code from @barneycarroll which I need more time to understand how to make it work with an example. @barneycarroll if you have any ideas for improvements it would be so nice. 

By the way, my other question was how about persistent data structures library? How to allow the rendering of an immutable object, I mean, without the .toJS() or .toArray() function.

**Comment by impinball** [comment]
If you want customizable destructuring, [there's been substantial talk on es-discuss about it](https://esdiscuss.org/topic/extensible-destructuring-proposal), which is a wheel I really don't see Mithril needing to reinvent. To be honest, I believe that would belong there. Outside of that, there's not a lot Mithril can do about it, not without a performance-reducing hook.

**Comment by veggiemonk** [comment]
Thanks @impinball 
It was more an exploration than a really important needed feature. 
I got more than I asked for with the answer above. :smile: 

This issue can be now be closed
