### ISSUE TITLE
Syntax error and unclear function in "Data-driven component identity"

### ISSUE THREAD

**Issue by ghornich** [lhorie/mithril.js#851]
Hello! I'd like to use this Mithril's feature, but I can't get it to work. The [documentation lists an example][1]:

`m.render(document.body, ProjectList({key: people[0].id, value: people[0]})`

But (1) this is missing a closing parenthesis, (2) what is `ProjectList`? It looks like a function, but m.render expects an object {view: Fn, controller: Fn}.

> "Suppose we have a component called ProjectList"

If `ProjectList` is a component object, it cannot be called as a function?

***

I was expecting this example to call the controller every time I press the button, but it doesn't:
http://codepen.io/anon/pen/avMaqW

    var persons = [
      {name: 'John'},
      {name: 'Steve'}
    ]
    
    var currentPersonIdx = 0;
    
    var comp = {
      view: function(ctrl, args){
        return m('', [
          persons[currentPersonIdx].name, ', ', args.key,
          m('button',{onclick:ctrl.exchange},['exchange persons'])
        ]);
      },
      controller: function(args){
        console.log('ctrl ctor');
        
        this.exchange = function(){
          currentPersonIdx = (currentPersonIdx+1)%2;
        }
        
      }
    };
    
    m.mount(document.querySelector('#mount'), {
        view: function(){
          return m.component(comp, {key: currentPersonIdx});
        }
    });

***Thank you for your efforts!***

[1]: https://lhorie.github.io/mithril/mithril.component.html#data-driven-component-identity

**Comment by StephanHoyer** [comment]
think this a bug in the docs. @lhorie was experimenting with components as factory function at the time he created it. He dropped it in favour of `m.component(ProjectList, args)`.

Controllers are called only once on mount/routechange.

Besides that, the controller is not reinitialised due to #823 components that only return a component.

Can be solved by simply wrapping the response in an array.

**Comment by ghornich** [comment]
@StephanHoyer Thank you for your answer!

**Comment by lhorie** [comment]
fixed docs
