### ISSUE TITLE
can provide a tool or API to report v-dom diff result?

### ISSUE THREAD

**Issue by futurist** [lhorie/mithril.js#852]
When data binded into view increasing, and in some larger project, there's a need for an API or tool to generate **diff result of v-dom** for **debug purpose**.

That way user can found which part the data trigger a redraw, and tune the program to have better result and performance.

**Comment by barneycarroll** [comment]
This is an excellent idea. Dovetails nicely with the possibility of implementing logic akin to React's `shouldComponentUpdate` to get tighter and finer grained control of the draw process. It is also quite ambitious though, and depends upon the refactoring of Mithril's view logic to allow a detachment of  diff and patch, which would also open up the possibility of rendering non-DOM views.

In the meantime, it's possible to get a log of what has changed in the DOM _after_ the fact by using [Mutation Observers](https://developer.mozilla.org/en/docs/Web/API/MutationObserver).

**Comment by lhorie** [comment]
subtree retain is the equivalent of shouldComponentUpdate

A tool like this would indeed be nice but it's neither easy to support with the current diff engine, nor something that I'm interested in adding as a part of the download payload
