### ISSUE TITLE
Talk from node's DOM to component's controller

### ISSUE THREAD

**Issue by futurist** [lhorie/mithril.js#855]
Talk from DOM node to component's controller? I mean, in `config` function, to invoke some function in controller.

This is my case:
1. In `config` function, bind an event to the dom, which will triggered by some other library
2. when the binded event come to the dom, dom should inform controller to do some thing

cannot find the way right now in step 2. I've figured using config's `cached` param to get the controllers array, but that array don't always contain data, some times the length is zero, it's not seem stable and thinking not the right way.

The observer pattern in doc seems too heavy to do such a thing, and will have scope problems in some cases.  is there any direct way?

**Update 1**

Maybe the issue is some times the controller lost from cached, I have `onunload` property in controller, and after some redraw, the controller become `undefined` in view

**Comment by futurist** [comment]
basicly the work around is to using `inline function` as below:

````
m('div.receiver', { 
    config: function(el, hasInited, context, vdom, ctrl )
               {  
                   if(!hasInited) $(el).on("some.event", function(){  ctrl.someFunc()  })
               }
    }
}, "child content" )
````

**Comment by StephanHoyer** [comment]
For those questions the [gitter-chat](https://gitter.im/lhorie/mithril.js) is a good point to ask

Here is one of the solutions proposed there:

```
component.controller = function() {
  return {
    fancyStuff: function (element, isInit, ctx) {
    }
  }
},
component.view = function(ctrl){
     return m( '.foo', {
          config: ctrl.fancyStuff
     } )
};
```

**Comment by futurist** [comment]
thank you very much! will using gitter-chat more!

**Comment by StephanHoyer** [comment]
Wouldn't consider this as a workaround. It common practice.

Am Samstag, 21. November 2015 schrieb yjm :
