### ISSUE TITLE
Mithril should work without the DOM available

### ISSUE THREAD

**Issue by isiahmeadows** [lhorie/mithril.js#856]
Although it won't display anything, it should still work without a DOM present. Benefits:

- [misojs](https://www.npmjs.com/package/misojs), [isomorphic-mithril](https://www.npmjs.com/package/isomorphic-mithril), [mithril-node-render](https://www.npmjs.com/package/mithril-node-render), etc. will be completely irrelevant.
- Mithril will be completely testable and usable in Node.
- Mithril can be more thoroughly tested in browsers, with fewer assumptions on the environment.

Requirements:

- The Mithril mock should use [htmlparser2](https://www.npmjs.com/package/htmlparser2) and a recursive converter to parse trusted HTML into what the mock understands. It's nontrivial, but it's not difficult.
- It should be possible to create multiple clean mocks at will.
- Mithril will have to use a `browser` field in its package.json pointing to the main Mithril file, and provide a proxy that requires the mock with its htmlparser2 dependency and adds whatever methods are useful when lacking a DOM. An example would be `m.root()` for creating a root and `root.toString()` to render that root to a string.

**Comment by impinball** [comment]
I will also note that this will fix a *lot* of broken tests (50 failing locally in real browser on `next`).

**Comment by StephanHoyer** [comment]
It already works without the DOM when you set `m.deps` accordingly. And how would you accomplish the serialisation to HTML-strings in this case? You have to to write a serialiser which than results in libs that you mention.

If you think there is a way to better integrate mithril in node without sacrificing the small size of mithril this might be an option. But since this can perfectly done in user-land I would stay away from this otherwise.

**Comment by barneycarroll** [comment]
I agree with @StephanHoyer's general message. Exporting the `m` function with existing tests gives us a reliable form of virtual DOM. Making that work with target environments other than the browser is an outside-context problem whose requirements aren't obvious (what would you expect config to do in a static output environment?) and should IMO be left to minimal external middleware packages according to consumer intent.

On a related note, JSDOM has recently undergone a major release…

**Comment by impinball** [comment]
@barneycarroll jsdom hasn't been supporting legacy Node releases (they dropped support for 0.x before iojs 2.0), and we don't need a full DOM.

**Comment by impinball** [comment]
And `config: m.route` already replaces the `href` with `sitename.href`. We would have to make that an argument for the Node driver.

**Comment by cmawhorter** [comment]
total mithril noob researching the project, but FWIW a possible usecase for this? 

http://electron.atom.io/ -- it's similar to nwjs (node-webkit) with the notable difference that it is purely a node context.

this might be my noob talking, but to use mithril in electron it'd mean that you need to stick with a backend/frontend architecture?

**Comment by lhorie** [comment]
that's what m.deps is for. It could conceivably be used w/ jsdom on the server. The rewrite will most likely address this in a different way to leverage modularity and avoid the overkill-ness of jsdom.

**Comment by isiahmeadows** [comment]
@lhorie And just make sure there's a way to know when a render starts/finishes. Please?

(That's been driving me crazy in testing, BTW.)
