### ISSUE TITLE
Suggestion; Add "how to install Mithril with bower" on readme.md file

### ISSUE THREAD

**Issue by tno2007** [lhorie/mithril.js#858]
I am starting to love Mithril.

Please add "how to install" in the readme.md file, by means of bower.

I feel it's important since this library is gaining mega traction at least according to me. It wil also help everyday web devs since most if not all of them is using bower.

Thanks

**Comment by Bondifrench** [comment]
Check the website: http://mithril.js.org/installation.html

**Comment by lhorie** [comment]
Added a link to the README
