### ISSUE TITLE
m.request options.extract doesn't work in next

### ISSUE THREAD

**Issue by tobscure** [lhorie/mithril.js#859]
The refactoring of the m.request method uses a default implementation of `extract` and doesn't allow it to be overridden.

https://github.com/lhorie/mithril.js/blob/next/mithril.js#L2090

**Comment by pitjow** [comment]
+1 for this issue!

had problem with error handling for m.request and used the proposed extract option in https://github.com/lhorie/mithril.js/issues/123. but there is no sense in using a custom extract if its not overwritten.

**Comment by impinball** [comment]
PRs welcome :)

**Comment by veggiemonk** [comment]
PR for this issue #862
