### ISSUE TITLE
Revive blog

### ISSUE THREAD

**Issue by StephanHoyer** [lhorie/mithril.js#860]
The mithril blog has always be a good source of knowledge not only regarding mithril but also regarding javascript in general. But it's not updated since a year now. Not only that it's sad it also leaves a bad taste of abandonment for visitors.

Maybe we as a community can change this.

Distinctive mithril developers can create blogposts and let them review by the community.

Topics can be destilled from common problems newbies asking for in the gitter chat. Also people can make suggestions on what topic they would like to have a blogpost about.

Some ideas that come to mind
* flux patterns in mithril
* what is a good mithril-components api?
* isomorphic mithril
* mithril on phones
* mithril-"native"
* `m.request` in depth and how to replace it with superagent/request/es6-fetch
* ES6 and mithril
* mithril and advanced styling
* reactive programming with mithril
* mithril 0.3 - what we can do better
* mithril 1.0 - road to first major
* data-handling-patterns in mithril

What do you think? Any other ideas?

**Comment by StephanHoyer** [comment]
* data-handling-patterns in mithril

**Comment by limdauto** [comment]
I definitely agree. I have learnt so much from Leo's blog and following discussions in Github is always educational. That said, I imagine something like Digital Ocean's community-driven tutorials would be extremely beneficial.

As another idea, I am working on a d3 replacement for and based on mithril, so bridging complex data operation (join, aggregation, etc.) and presentational operation with good performance is something I'd like to hear more about as well.

**Comment by barneycarroll** [comment]
Thanks for bringing this to the fore @StephanHoyer.

The Mithril blog posts were absolutely fantastic. I was incredibly lucky to discover Mithril when they were in issue.

I completely agree with your assertion that it's the duty of the beneficiaries of Mithril (us, the users) to recapture that evangelist insight and put it back out to the world in standalone articles.

I want to write about processing efficiency and how to achieve patterns seen in other libraries without the need for framework APIs — analyse the problem, look at how others try to solve it generically, and show how to do it in Mithril with your own code. I'm going to start writing as soon as I submit this comment. What next?

Publish on Medium, notify on this thread, in the Gitter chatroom and on the Google Group?

I think that might be a good enough start. No harm in using all disparate media currently available.

**Comment by veggiemonk** [comment]
I can think of: 
- Mithril virtual dom optimization (perf) ( #848 https://github.com/lhorie/mithril.js/issues/848#issuecomment-156562082)
- Mithril template precompilation (perf)
- Mithril and immutable data (data structure rendering)
- testing your Mithril app ( test )
- Mithril and JSX (or MJSX or MSX, I never know how to call it) (dev)
- how to gradually migrate an app from jQuery to Mithril ( transition steps, tips & tricks ) (dev)

It would be great to have a dump of the gitter chat room for that.

**Comment by rw3iss** [comment]
Definitely into helping in this endeavor. I know a bit of mithril, but am starting to employ it more heavily, so now is a good time to get this going ;)

**Comment by lhorie** [comment]
Even basic here-is-how-to-do-a-hello-world articles would be a good way to get the ball rolling for those who don't consider themselves mithril experts yet.

I think the most important thing to do is to get something out first. Even doesn't even have to be a good topic. I find that the pressure to publish is a really good motivation to actually sit down and write, and that is the hardest part. The topics aren't even that important. Strangely, you naturally find topics to talk about, and you get better at exposing your ideas as you write more.

**Comment by rw3iss** [comment]
OK, I'll start writing up some things as I go along here. Learning it all for a modern single-page application, with dynamic routing/cached views, etc, so hopefully it should be useful. I think, for the most part, your guides and articles and posts on the Mithril site are pretty thorough an well-put together, for real-world cases. I think most people primarily just want to see an update or two on the Mithril blog to know that you're still standing behind the project and things are moving a bit. With all these new frameworks bursting out, it would be great to see an update or two announced on the Mithril side! Just an observation :-) Thanks for all your hard work Leo.

**Comment by StephanHoyer** [comment]
Too posts I wrote some time ago:
* [icons with mithril](https://gist.github.com/StephanHoyer/de107b794c43f28ffd75)
* [isomorphic apps](https://gist.github.com/StephanHoyer/bddccd9e159828867d2a)

Would love to get some feedback.

**Comment by lhorie** [comment]
I actually found that first article useful for something I was doing at work a while back. @StephanHoyer

**Comment by cmnstmntmn** [comment]
:+1:

**Comment by lhorie** [comment]
Going to close this, since it's not really about a bug
