### ISSUE TITLE
Template compiler as Babel transform plugin?

### ISSUE THREAD

**Issue by liamcurry** [lhorie/mithril.js#864]
It would be nice to have the [template compiler](https://lhorie.github.io/mithril/optimizing-performance.html#compiling-templates) implemented as a [Babel plugin](https://babeljs.io/docs/plugins/), since most developers aren't going to be using SweetJS but Babel is becoming pretty ubiquitous.

[Here's the source code for the stock Babel plugins for reference](https://github.com/babel/babel/tree/master/packages)

**Comment by veggiemonk** [comment]
Check out https://github.com/Naddiseo/babel-plugin-mjsx
There is also a branch for babel6. 
Is it what you are looking for?

**Comment by liamcurry** [comment]
@veggiemonk Not exactly. I just want to have precompiled templates without using JSX.

**Comment by tivac** [comment]
@liamcurry it's not a babel transform, but [mithril-objectify](https://github.com/tivac/mithril-objectify/) exists and is both safer & better at optimizing than the sweet.js macro.

I feel weird pimping it, but @lhorie seemed to like it.

https://twitter.com/LeoHorie/status/659487458032295938

**Comment by lhorie** [comment]
For the record, if you sent me a PR linking the official docs to mithril-objectify instead of the macro, I would happily accept it @tivac

**Comment by tivac** [comment]
Oh, sure. Put the ball in **my** court.

:smiley:

**Comment by impinball** [comment]
The template compiler in the repo is horribly outdated, sadly. So, in
reality, it would have to be written from scratch.

**Comment by lhorie** [comment]
@tivac oh [fine](https://github.com/lhorie/mithril.js/commit/b121ba28241c3624e24be104977ae4b31c4edb76) :)

**Comment by tivac** [comment]
I'll try to send a PR tonight.

**Comment by liamcurry** [comment]
@tivac that is perfect! There's one small issue with ES6 imports though tivac/mithril-objectify#11
