### ISSUE TITLE
mobile browser, withattr textarea, fast typing

### ISSUE THREAD

**Issue by gebv** [lhorie/mithril.js#865]
If fast typing, often not all symbols are displayed, displayed with a delay
iphone 4 + ios 7, safari

It is inevitable for weaker phones? You had such a problem?

``` javascript
var config = {
onkeypress: m.withAttr("value", c.value),
value: c.value()
};
m("textarea", config);
```

**Comment by Bondifrench** [comment]
I have a textarea in my sample app, it works perfectly fine using oninput
```javascript
m('textarea#pad.col-md-6[placeholder="Write your text here"].full-height',{oninput: m.withAttr('value', ctrl.content) })
```
with `ctrl.content` just being a simple `m.prop()`

**Comment by barneycarroll** [comment]
There may be a meaningful distinction between oninput — which simply reacts to native form input behaviour — and onkeypress, which is a lower-level event which has the capability of interrupting, transforming or cancelling native input behaviour.

**Comment by lhorie** [comment]
yeah, as others said, use oninput. Onkeypress is not reliable
