### ISSUE TITLE
preventing current redraw from view

### ISSUE THREAD

**Issue by rewlad** [lhorie/mithril.js#870]
Hi,

I'm implementing a kind of lazy tree view;
Fact, that some tree node is expanded is stored in view-model, local to browser;
Main data is stored in remote key-value storage;
When some tree nodes are already expanded, and user makes refresh,
then main data for expanded nodes is loaded on demand;

```javascript
  const cacheData = new Map()
  const needData = new Set()
  function idToData(id){
    if(!cacheData.has(id)) needData.add(id)
    return cacheData.get(id)
  }
  ...
  function view(ctl){
    needData.clear()
    ...
                        someDeepNodeData =  idToData(someDeepNodeId)   
    ...
    if(needData.size > 0) {
        m.request({method: "GET", url: "/db/"+Array.from(ids).join(".")}).then(function(res){
            res.forEach(function(rec){
                cacheData.set(rec.id, rec)
            })
        });
    }
    ...
  }
```
m.request is executed during execution of view;
On refresh view is called multiple times, according to number of expanded tree levels;
Redraw is done multiple times, and it looks not good;
How to solve this better?

May be view caller could cancel redraw if redraw was caused by computationCounter <= 0 and computationCounter become >0 during view?
Or I could use something like redraw-strategy-none from inside view?
Or I should just remember previous returned vdom and return it again?
Or I should call view and render myself in such complex case?

I can use localStorage for caching data (so cache will survive refresh), but the state may lead to unrepeatable bugs in future;
I can optimize code to ask everything in one request, but it will be non-general solution with duplication of complex tree logic;

**Comment by barneycarroll** [comment]
@rewlad your approach in this is uncannily similar to mine. It's good to know I'm not the only one having these thoughts :) The `idToData` function is a pattern I've found incredibly helpful for 'memoizing' function outputs in a declarative way (the same application code executes repeatedly but values are cached) - I published this as a package to be used as a Map method, which I called [xet](https://www.npmjs.com/package/xet) (get/set).

Before we try to create new solutions though, it might be best to explain the context of this code: Where is this view invoked? `needData` appears to be intrinsically linked to `cacheData` - why not just use one store? How is `needData` populated, if the view resets it each time it runs? Where does `ids` come from, and what does it represent?

I also can't help wondering if this situation wouldn't be better addressed by putting initialisation logic in controllers - running async code in views (m.request) is generally a really bad idea. It seems that there is far too much logic happening in the view, a part of the code which should be used exclusively to tell Mithril how to draw DOM - in fact, the view `forEach` doesn't return any virtual DOM at all, and I can't see anything being returned by the DOM. Why not make the request in a controller? What is the DOM you want to draw?

**Comment by rewlad** [comment]
Great to hear You,

Our favourite pattern is even a standard in some languages e. g. Scala:
```lazy val a = ``` and ```cache.getOrElseUpdate(key,create(key))```

```cacheData``` lives until user refreshes screen or leaves the form;
Individual entries in ```cacheData``` can be invalidated sometimes;

```needData``` lives during single view execution;
It indicates that some data was missing during view execution;
```needData``` helps to aggregate requests for multiple missing ```ids``` to single http request;

>> too much logic happening in the view
Yes, most of this code should belong to controller; 
my code example was simplified, it just shows an execution order;

The main ideas are:
* Controller is responsible for **how** to load data and proves it to view;
* View asks controller for data, as if it's just exists locally;
* But controller do not always know weather to load specific data or not;
* View knows **what** data is currently visible, so view asks only for this data;
* When controller does not have local data, it returns default data to view, and marks ```id``` as missing;
* At the end of view execution controller checks if there is something missing;
* If something is missing, then controller http-requests missing data;
* If something is missing, then result of view is inconsistent and should not be applied to real dom;
* Mithril need to be told **in some proper way** to cancel current redraw;

I'll try to compose some minimal working example tomorrow;

**Comment by rewlad** [comment]
So here's some simplified example with the default and fixed behavior:
https://github.com/rewlad/mithril_stream/blob/master/lazy_tree.html

Trees are "loading" in a few iterations;
Click to a node will expand/collapse it, and causes lazy loading too;
Left tree redraws on every iteration;
Right tree was fixed to redraw only at the end using ```preventManyRedraws```;

However, it seems strange to me, that at least one of the folowing was not working out of the box:

> Once the counter (```m.endComputation```) reaches zero, Mithril redraws.
Yes, counter reaches zero, but during ```view``` it is increasing back, and ```view``` happens before real redraw;

```m.redraw.strategy("none")```

**Comment by isiahmeadows** [comment]
@rewlad Could you make an equivalent file in ES5 (or convert the existing one)? It's more widely testable.

**Comment by rewlad** [comment]
I've changed ```lazy_tree.html```; I don't have old browser nearby to check, but hope it's OK;
