### ISSUE TITLE
m.mount() and m.component() behave differently on controllers

### ISSUE THREAD

**Issue by mikegleasonjr** [lhorie/mithril.js#871]
The former creates a new controller() the latter just calls it normally.

I use components in both situations and was expecting to be created the same way.

Can we get the reasons behind in the doc if its on purpose?

Thank you!

**Comment by isiahmeadows** [comment]
There's no reason it should. They both call the same construction function.

**Comment by mikegleasonjr** [comment]
Sorry I meant m.mount() in the title not m(). See https://lhorie.github.io/mithril/mithril.component.html#controller-as-a-class-constructor

When using m.route() it does indeed call new on my controller also.

m.component just do something like ctrl.apply() (no new ctrl()) in the function parameterize in the source.

Sorry the title may be incorrect and I'm on mobile can't link and beautify this :)

**Comment by isiahmeadows** [comment]
That sounds like a proper bug. I'm replying via my phone through email.
Feel free to send a PR. Even a failing minimal test is acceptable.
Currently, there's 7 malfunctioning tests (soon to be six, as soon as
@lhorie cuts a patch release, as there's nothing breaking, only things
additive).

**Comment by mikegleasonjr** [comment]
I'm on a bus in Nepal actually ;) Working on a startup using Mithril while
travelling.

I'll send a PR hopefully today!

**Comment by mikegleasonjr** [comment]
Well I couldn't be understand why my test was passing in the next branch.

Looks like the issue has been fixed.

Is it safe for me to use this version while in development? I expect to go live in 3 months. Will there be a release on your part before that time frame?

Thank you

**Comment by isiahmeadows** [comment]
I can't, but I've been asking @lhorie lately about that. I've got minor breaking changes to `m.prop()` and `m.deferred()` that I'm not merging until then.

(Specifically, `m.prop()` will no longer return a Mithril deferred when passed a promise, but of the type of promise passed in. If you're depending on synchronous behavior when, e.g. passing a Bluebird promise as the parameter, then you'll be affected. It shouldn't affect most consumers, though.)

**Comment by mikegleasonjr** [comment]
Alright thanks for pointing that out

**Comment by isiahmeadows** [comment]
But as it stands, what's in `next` is stable enough that I would trust it
in production, since not much is going to change between this and the next
release.

**Comment by mikegleasonjr** [comment]
Yup I'm developing on it right now :)

I'm a minimalist kind of guy and really.. really like this framework and the philosophies behind it.

Thanks for your work guys!

**Comment by mikegleasonjr** [comment]
Closing this one since fixed in the `next` branch.

Thank you
