### ISSUE TITLE
m.request needs a finally block, otherwise endComputation is never called on JSON.parse error

### ISSUE THREAD

**Issue by farzher** [lhorie/mithril.js#873]
This took a few hours to debug...
Why doesn't the `try/catch` catch the error? Why is `finally` required? (I never even knew `finally` did anything)
I have no idea. Let me know if you figure it out.

http://stackoverflow.com/questions/34188009/mithril-js-dies-after-m-request-receives-an-error/34193763

Error is caused here:
![](http://i.imgur.com/HaXEKBO.png)

Still throw as an error, even though it's in a try block
![](http://i.imgur.com/kZ74Arv.png)

And causes this code not to run:
![image](https://cloud.githubusercontent.com/assets/1005136/11707203/1e9112ca-9ecf-11e5-8a13-3a252c2a8847.png)

Which breaks mithril

**Comment by isiahmeadows** [comment]
PRs + relevant tests welcome.

**Comment by farzher** [comment]
Nevermind... I just tested with unminified next branch and it does not have this issue.
The minified version and current release are affected. But this will be fixed on next release.

Looks like how you handle `pendingRequests` has been changed, so it doesn't get stuck anymore on error, even though `m.endComputation()` isn't called

Although I think there's still a bug here. You've moved even more code below the `try/catch`

`deferred[doSuccess ? "resolve" : "reject"](response)` https://github.com/lhorie/mithril.js/blob/next/mithril.js#L2135

Won't be executed on `JSON.parse` error. So, the deferred won't be rejected

I don't have a test for this. And I don't understand why `finally` is required. I guess that's what we should do? I'm hoping someone who understands error handling better will look at this

**Comment by farzher** [comment]
Oh, I understand! `m.deferred.onerror(e)` which is inside of the `catch` rethrows the error... lol >_>
That explains why the `try/catch` seemed to not work, and why finally is required.

**Comment by isiahmeadows** [comment]
@farzher By the way, here's what `finally` does:

```js
function foo() {
  try {
    return 2
  } finally {
    console.log("foo") // This always runs
  }
}

function bar() {
  try {
    throw new Error(e)
  } finally {
    console.log("foo") // This always runs
  }
}

function doComputation() {
  m.startComputation()
  try {
    return doSomethingThatMightThrow()
  } catch (e) {
    console.log(e)
    throw e
  } finally {
    m.endComputation() // This always runs
  }
}

// This always throws
function weird() {
  try {
    return doSomething()
  } finally {
    throw new Error("Gotcha!")
  }
}
```

It runs regardless of how the try or catch block ends (end of block, error, or early return). That makes it useful for cleanup actions.

**Comment by farzher** [comment]
Wow, it executes even after return. Finally, I understand its point.

**Comment by isiahmeadows** [comment]
Welcome. Just make sure to never return directly from a finally block. :)
