### ISSUE TITLE
Routing on multiple elements not working

### ISSUE THREAD

**Issue by explorer2309** [lhorie/mithril.js#875]
I am trying to write a LOB application with Navigation bar and content section with forms and grids. Currently I am trying to highlight the element in the navigation bar for the current path.

I was hoping to find methods and events in router which will allow me to list the paths configured, and select the current one from them. Since that does not seem to be supported, I am now trying to create 2 elements which will be called by the router. But that is not working either.

This is my html:
```
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>

  <header></header>
  <main></main>
  <footer></footer>

  <script src="scripts/jquery.js"></script>
  <script src="scripts/mithril.min.js"></script>
  <script src="scripts/browserify/main.js"></script>

</body>
</html>
```

And this is my code so far:
```
'use strict';

var shell = {
  view: function() {
    return m("h1", "Shell")
  }
}

var login = {
  view: function() {
    return m("h1", "Login")
  }
}

var dashboard = {
  view: function() {
    return m("h1", "Dashboard")
  }
}

var routes = [
  { path: "/", module: shell, nav: 'Home' },
  { path: "/login", module: login, nav: 'Login' },
  { path: "/dashboard", module: dashboard, nav: 'Dashboard' }
];

var navBar = {
  controller: function() {
    return {id: m.route.param("path")};
  },
  view: function(controller) {
    return m("div", controller.id);
  }
};

m.route(document.querySelector('header'), "/", {
    "/:path": navBar,
});

/*
m.route(document.querySelector('main'), "/", routes.reduce(function(prev, route) {
  prev[route.path] = route.module;
  return prev;
}, {}));
*/

m.route(document.querySelector('main'), "/", {
    "/": shell,
    "/login": login,
    "/dashboard": dashboard,
});

m.mount(document.querySelector('footer'), {
  view: function() {
    return m("span", "Copyright None");
  }
});

```

The content in the 'header' element gets rendered, but the content in 'main' element is not.

Am I doing something wrong here? or is there an easier way to achieve this.

Thanks!

**Comment by barneycarroll** [comment]
There is only one location and one route map per application, and it needs to be bound to a single routed element. If there is different logic for different parts of the app, that logic needs to be included in the components for the various routes at that element.

Here's a refactor whereby a single component, `layout`, takes responsibility for rendering the whole app. `m.component` is used to associate different main nested components to be passed to the `layout` component.

I also added a `location` component to allow navigation to the different routes.

http://jsfiddle.net/barney/y72p0yt2/

**Comment by explorer2309** [comment]
This is fantastic!

Did not know I could use m.component as routers target. But I suppose, component and regular module will have the same interface.

Many thanks for being so helpful !
