### ISSUE TITLE
Passing variables to a m() configs

### ISSUE THREAD

**Issue by pobri19** [lhorie/mithril.js#885]
I'm trying to get the jQuery FooTable plugin working in my mithril app. I've got a config call like so in my component:

    view: function(ctrl, args) {
      return m("table", {id: "globalConfigTable", config: execFooTable})
    }
    
    this.execFooTable = function(element, isInit, context) {
      $('#globalConfigTable').footable({
        "columns": columns(),
        "rows": args.configRows
      })
    }

args.configRows is my promise returned from my GET request that I'm passing to this ConfigListWidget component. I can see that it does successfully call my execFooTable function, but I can't seem to figure out how to access my args.configRows variable. I've tried context.configRows, and a bunch of other things, but they all come back as undefined. 

One thing that did work was to use a variable outside of my view like this:

    this.configs = null
    view: function(ctrl, args) {
      configs = args.configs
      return m("table", {id: "globalConfigTable", config: execFooTable})
    }

And then I could access configs from my execFooTable function. But I'm not sure if there's a more correct way to do this.

Can anyone please help me out? Thank you.

**Comment by isiahmeadows** [comment]
Try this:

```js
var footable = {
  controller: function (args) {
    this.columns = args.columns
    this.rows = args.rows
    this.config = function (el, isInit, ctx) {
      if (!isInit) {
        $(el).footable({
          columns: this.columns,
          rows: this.rows
        })
      }
    }.bind(this)
  },
  view: function (ctrl) {
    return m("table", {config: ctrl.config})
  }
}
```

Note that 1. the `el` is the element that the vdom is being diff'd against, and 2. that `isInit` is used to guard against if the element isn't initialized yet. Also, do [feel free to ask this on Gitter](https://gitter.im/lhorie/mithril.js). People are on there very frequently, and we are really friendly there. :smile:

**Comment by pobri19** [comment]
Thank you isiah, I wasn't aware of the Gitter so it's good to see that exists. I'll be sure to jump on there if I have any other questions :)
