### ISSUE TITLE
Can't use a "404" not found route

### ISSUE THREAD

**Issue by mikegleasonjr** [lhorie/mithril.js#890]
Hello,

I tried to configure a "not found" catch all route like:

```
m.route.mode = 'hash';
m.route(document.body, '/not-found', {
  '/': components.pages.Login,
  '/not-found': components.pages.NotFound,
  [...]
});
```

It works fine when I type anything as the URL. But when I load up the page without any hash (http://domain.com/), it redirects to `/not-found` on the first page load.

Any ways to simulate a not found page?

Thank you

**Comment by ArthurClemens** [comment]
Use a variadic route to catch 404:
```
m.route(document.body, '/', {
    '/': home,
    '/:any...' : notFound
})
```

**Comment by mikegleasonjr** [comment]
Thank you very much!
