### ISSUE TITLE
Next: List of m.trust elements get multiplied on redraw

### ISSUE THREAD

**Issue by ArthurClemens** [lhorie/mithril.js#891]
This occurs in the next branch. See JSBins:

* [next branch](http://jsbin.com/penisu/4/edit?js,output)
* [isiahmeadows speed branch](http://jsbin.com/ziwevuf/5/edit?js,output)
* [0.2 version - works fine](http://jsbin.com/samuzu/3/edit?js,output)

**Comment by lhorie** [comment]
side note: m.trust test coverage could definitely use some more love

**Comment by isiahmeadows** [comment]
I think I noted that in the tests, actually. As soon as I fix my patch, an
m.trust test is actually the one failing. (It's not a regression, because
it was failing since I converted the tests to use Mocha, an async test
runner)

**Comment by lhorie** [comment]
This should work again as of the revert for 0.2.2-rc.1
