### ISSUE TITLE
M.deferred regressions

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#903]
While the Mithril deferred have always diverged from the spec, since Promiz was merged in, said divergence from the A+ 1.0 spec has been limited to 

1) The then handlers can be called synchronously

2) Error handling

The last refactoring breaks other things:

```JS
prmA = m.deferred()
prmB = m.deferred()

prmA.resolve("A")
prmB.resolve("B")

prmA.promise.then(function (A) {
    console.log("A, please?", A)
    return prmB.promise
}).then(function(B) {
    console.log("B, now", B) // "A" with the current implementation
})
```
If a then handler returns a promise, the parent promise should adopt the state of the child promise.

That example works fine with v0.2.0

Provided, there are 340 regressions on the test suite between v0.2.0 and v0.2.1, there are probably other issues as well. 

340 regressions may seem high, but the suite tests many variations of the same pattern for corner cases, and thus a single bug can cause many regressions.

**Comment by pygy** [comment]
Another one that the A+ suite can't detect:

Once resolved, a promise must be immutable. Currently:

```JS
d=m.deferred()
d.resolve(5)
d.promise.then(console.log.bind(console))
//-> 5
d.promise(6)
d.promise.then(console.log.bind(console)) //should log 5
//-> 6
```

**Comment by isiahmeadows** [comment]
That's been intentional behavior for a while. But I'm pushing for Leo to
roll back for another patch release, because there's other regressions as
well. This release wasn't properly documented or tested.

**Comment by lhorie** [comment]
@isiahmeadows deviating from A+ spec shouldn't be intended behavior unless it has a documented reason

**Comment by lhorie** [comment]
this should work again as of the revert for 0.2.2-rc.1

**Comment by isiahmeadows** [comment]
I get this now.
