### ISSUE TITLE
Type error "selector cannot be an empty string" raised with list of components

### ISSUE THREAD

**Issue by ArthurClemens** [lhorie/mithril.js#905]
I have this common situation in components: 

```
const content = [
    opts.before ? opts.before : null,
    opts.content
    opts.after ? opts.after : null
];
return m('a', {}, content);
```

Component is called with:
```
m.component(iconButton, {
    after: m.component(ripple, rippleOpts)
})
```

While this is a perfectly legal situation, 2.0.1 raises an error and prevents execution.

**Comment by isiahmeadows** [comment]
That's weird. It should *only* be checking empty strings.

**Comment by lhorie** [comment]
This should work again as of the revert for v0.2.2-rc.1
