### ISSUE TITLE
m.new()

### ISSUE THREAD

**Issue by pygy** [lhorie/mithril.js#908]
As discussed earlier in the Gitter channel...

This is a proposal kill several birds in one stone.

- m.attr with proper scope
- multi-tenant apps (i.e. protection against redraws on route change)
- if needed, per component m.deps (supposing they are extended as @isiahmeadows hinted at)
- possibly other things.

The idea would be to have `mx = m.new()` where `mx` is a distinct, extensible mithril instance *without a router*. Components mounted with `mx.mount()` would be oblivious to route changes while those mounted with `m.mount()` would react to route changes.

`mx` could be extensible, with, for example @barneycarroll's  [`m.attr`](https://github.com/lhorie/mithril.js/pull/586), but, crucially, *`m` would be restricted to vanilla behavior*, so that it can be depended on.

Likewise for promises. Have `m.deferred` provide something small if a bit broken[1] for simple cases, and provide the ability to inject a different, propified promise implementation in `mx`.

Implementation strategy (based on what currently exist, but it can be adapted easily post modularization):

- Put all API functions (including extensibility code) but the router in a big factory (`mnew`).
- Create the default instance `m = mnew()`
- Define `m.route` based on it.
- Strip the extensibility methods from `m`.
- Attach `mnew` as `m.new` (or as a function that also adds `mnew` to the new instance).

Thoughts?

----

[1] The current Mithril promises are like a piano with a few notes out of tune. You can play beautiful music on it as long as you avoid the few bad keys. The trouble is that, in this case, a bad note is a race condition...

**Comment by pygy** [comment]
Also, AFAICT, you could, with the current code, mount `mx(...)` elements with `m` and vide versa (provided the `mx.attr` handlers run at `mx(...)` call time, and not at `mx.mount()` time).

**Comment by pygy** [comment]
By the way, I'm not necessarily attached to the whole thing, but I like the idea of having the default instance not extensible while the custom ones are. It could also offer a smoother migration path for changing the promise engine, for example, where components could be migrated one at a time from the current `deferred` to more compliant promises, by using a `mx` that uses ES6 under the hood.

**Comment by isiahmeadows** [comment]
I'm +1 on this. But it'll require a partial rewrite of the routing and renderer, because they currently use global state (which is bad, but it's not easy to rewrite). And your `this.redraw()` is effectively subtree rendering, which is not easy to implement. And to my knowledge, the majority of vdom libraries and frameworks don't implement this.

**Comment by isiahmeadows** [comment]
@lhorie You mind taking this stuff into account in your rewrite? It may make it easier for you to do there, given the increased modularity.

**Comment by pygy** [comment]
What is currently "global" is actually locally scoped in the IIFE. These variables could be relocated to the instance factory.

For the router, I was suggesting to make it a singleton, but it could exist per instance too, provided there was a way to ignore unknown routes rather than redirecting to the default. Details in #952.

**Comment by lhorie** [comment]
Rewrite branch is entirely modular and everything that is stateful can have multiple instances via factories, so I think it satisfies the spirit of this proposal
