### ISSUE TITLE
How does events handler works ?

### ISSUE THREAD

**Issue by accessibleweb** [lhorie/mithril.js#910]
Hi,

...
m.component(App,
[m.component(Header),
m.component(Content,...), ...]);
...

If i add an event handler on one of theses view for exemple onclick.
The views function (for exemple Header) will be executed in order to do the diff strategy.
I tried to put strategy none but nothing it do it again.
How can i prevent it ?
Thanks

**Comment by barneycarroll** [comment]
Hi @accessibleweb, [here's a fiddle showing how different redraw strategies affect controller & view execution logic](https://jsfiddle.net/barney/uj7zuaer/). Is this as expected, or is the problem deeper?

**Comment by accessibleweb** [comment]
HI @barneycarroll, i just change the jsfiddle and have the same problem, the view function is called after each event.
I think it's normal because of mitrhiljs redrawing system and diff, i was just looking to a behavior that say to mitrhil all right now, skip the diff for this part of code or for all of this view, so that it evoid function execution time.

An other thing, i am not sure it is normal, if you do :

 onmousedown: function (e) {
                m.redraw.strategy('none');
            // ...
                m.redraw();
            },

It will cause controller initialisation ...

**Comment by barneycarroll** [comment]
> the view function is called after each event.

That's not the case for me — redraw strategy `none` does not result in view re-computation (you can tell because the Content component view function increments the `draws` integer, and there are no incrementations when you click the 3rd button).

> if you do … it will cause controller initialisation

[Here's a forked fiddle where I run that code](https://jsfiddle.net/barney/gn5wpu13/1/). The controller doesn't reinitialise, it just computes the view twice (@lhorie is that a bug?).

It seems like your code is doing something else somewhere, perhaps involving more complex initialisation logic…?

**Comment by accessibleweb** [comment]
the view function is called after each event.
m.redraw.strategy('none'); works perfectly maybe i did a mistake.

  onclick: function () {
                                m.redraw.strategy( 'none' );
                              ctrl.currentId(screensaver);
                                m.redraw(); // call the view function 2 times and the others views one time
                            }

In some controllers it reload the controller.

Maybe i have a broken strategy somewhere ...

**Comment by accessibleweb** [comment]
Finaly it does not what i would like.
The commend inside code.


```
'use strict';

module.exports = function (ctrl, args) {

    // How to prevent it ?

    console.log('Header :: view');

    return m('.app-header', {
        onclick: args.onclick || function (e) {
            window.history.back();
        }
    }, ctrl.title());
};
```

```
'use strict';

module.exports = function (ctrl, args) {

    var Header, Popin;

    Header = require('../Header/index.js');
    Popin  = require('../Popin/index.js');

    return m('.page.page-settings-screensaver', [
        m.component(Header, {title: 'TITLE'}),
        m('.content', m('.content-inner', [
            m('section', [
                m('.app-title', 'TITLE'),
                m('.field.text', m('input', {
                    oninput:m.withAttr("value", ctrl.screensaverTimeout), value: ctrl.screensaverTimeout(),
                    type: 'text',
                    required: true,
                    placeholder: '0',
                    pattern: '[0-9]+'
                }))
            ]),
            m('section',
                m('.app-title', 'TITLE'),
                m('.field.radio.no-margin', m('ul', ctrl.screensavers().map(function (screensaver) {
                    return m('li' + (ctrl.currentId() === screensaver ? '.on' : ''),
                        {
                            onclick: function () {
                                
                                // Prevent diff and redraw of the application but just redraw the part depending on the currenId (.on class)

                                m.redraw.strategy('none');
                                
                              ctrl.currentId(screensaver);
                            }
                        }
                        , screensaver.split('-')[1])
                })))),
            m('section', m('.app-align-center', [
                m('.app-btn.btn-disable', 'BTN'),
                m('.app-btn.btn-save', 'BTN')
            ])),
            ctrl.isInError() ? m('.overlay') : null,
            ctrl.isInError() ? m.component(Popin) : null
        ]))
    ]);

};
```

**Comment by barneycarroll** [comment]
You can't redraw individual components - a `diff` redraw tells Mithril to compute the whole view, and modify only the parts that change. An `all` redraw replaces the entire DOM from scratch, and a `none` redraw does nothing at all.

**Comment by accessibleweb** [comment]
i see, it could be call to add a specific flag because for performance it will be very useful.
VanillaJS or Exoskleton speed up in my case.
Mitrhil is fine in some case but can be slowly in some large use case.

**Comment by barneycarroll** [comment]
Yes, the feature has been much in demand. I agree it should be a priority.

**Comment by accessibleweb** [comment]
Anyway, Mitrhiljs is very faster than ReactJS and in my embedded device it makes the difference, thanks for the community and @lhorie for is job.

**Comment by barneycarroll** [comment]
@accessibleweb I've tried extending Mithril to do granular redraws several times. [This is my latest attempt](https://jsfiddle.net/barney/u3d6v2rp/): notice that once a component is granularly redrawn, it will no longer be redrawn by default global redraws, *until a strategy `all` redraw occurs*. I think this shows the limits of the possible :/

**Comment by accessibleweb** [comment]
Awesome, maybe a new strategy could be a good way, or extending m.redraw(); to tell Mitrhil what he has to redraw and/or wich component/function it has to re-call.

**Comment by accessibleweb** [comment]
Ok, this JS Fiddle, will break the mithril computation queue if i do a request on init without background flag.
And so on page change it will do a redraw from scratch!

https://jsfiddle.net/uj7zuaer/8/

What is the best way to do request on init without breaking queue ?
It will be good to have an onload event on the controller.
I could fix it getting the data on the view config if not init but i does not like this approach, is there a good practice?

**Comment by accessibleweb** [comment]
```
// Fix the problem in controller
   m.request({url: '//fiddle.jshell.net', extract: extract,background:true}).then(function(){
       m.redraw();
   });


// Fix the problem in view/controller
....
this.doRequest() {
return m.request({url: '//fiddle.jshell.net', extract: extract});
}
...
 	config:function(el,isInit){
    		if(!isInit) {
                  ctrl.doRequest();
            }
    	}
```

**Comment by barneycarroll** [comment]
@accessibleweb fancy joining us on [the Gitter chatroom](https://gitter.im/lhorie/mithril.js)? It might be easier to describe that problem there…

**Comment by accessibleweb** [comment]
Solution from @barneycarroll https://jsfiddle.net/barney/k80t8wo6/
