### ISSUE TITLE
HTML to Mithril Template Converter is Broken

### ISSUE THREAD

**Issue by sirsavary** [lhorie/mithril.js#915]
The converter breaks whenever it encounters an HTML tag with the "class" attribute. The error is:

>Uncaught TypeError: Cannot read property 'replace' of undefined

**Comment by isiahmeadows** [comment]
@sirsavary Consider it unofficially deprecated in favor of [mithril-objectify](https://github.com/tivac/mithril-objectify), anyways. It's eventually going to be removed, since no one bothered to keep it up to date with Mithril itself for the last several iterations.

**Comment by sirsavary** [comment]
Alright, but if I have HTML I'd like to convert to Mithril? It's a bit of a pain to write all of it by hand. Using an HTML editor then converting it was much easier and less error prone.

**Comment by tivac** [comment]
@isiahmeadows pretty sure this is about http://mithril.js.org/tools/template-converter.html not the sweetjs macro.

**Comment by isiahmeadows** [comment]
Wait...I misread the title... My bad.

**Comment by sirsavary** [comment]
Yep, sorry if that wasn't more clear! I've got an idea as to why it's breaking and I'll see if I can try and fix it myself.

**Comment by D3ucalion** [comment]
I just opened a pull request(#933) which resolves this issue. If you add the line of code below to line 76 just after the return for "style". It will prevent the uncaught type error and still correctly handle the class attribute.
`if(el.attrs[attrName]===undefined) return;`

**Comment by isiahmeadows** [comment]
Tell me if #933 fixes this for you. Otherwise, I'll reopen this.

**Comment by sirsavary** [comment]
That line of coded fixes it, thak you very much.
