### ISSUE TITLE
Timing issue with m.redraw and component

### ISSUE THREAD

**Issue by ariutta** [lhorie/mithril.js#926]
Hello,

I have a test that I think should always pass synchronously but actually it appears to sometimes require waiting for an asynchronous redraw. You can see a test case with a sync expectation [here](https://github.com/ariutta/mithril-simple-modal/blob/b45261f17a337bb3e77071ca67dc5b1e177e4aad/test/unit/api.js#L167) that occasionally fails, but waiting 20ms ([see here](https://github.com/ariutta/mithril-simple-modal/blob/b45261f17a337bb3e77071ca67dc5b1e177e4aad/test/unit/api.js#L173)) makes it always work.

You can also see [here](https://github.com/ariutta/mithril-simple-modal/blob/b45261f17a337bb3e77071ca67dc5b1e177e4aad/test/unit/api.js#L243) or any of the other lines with the "Missed a frame..." message.

Shouldn't `m.redraw()` be complete by the time the `expect` runs?

**Comment by barneycarroll** [comment]
`m.redraw()` is asynch by default — it requests an animation frame (which typically resolves within 16 milliseconds if the machine isn't under strain). You can force a synchronous redraw by passing `true`; `m.redraw( true )`.

**Comment by ariutta** [comment]
Awesome - thanks!
