### ISSUE TITLE
Input element's value attribute does not appear

### ISSUE THREAD

**Issue by amireldor** [lhorie/mithril.js#927]
Hi. It's late and something strange is happening. The following code does not produce a `value` attribute for the input elements.

    m('input', { value: 'monkey madness' });    # :(
    m('input[value="monkey madness"]');    # :( as well

Other attributes, as well as custom attributes, appear just fine.  
Is this code correct? If it is then I must be doing something very weird in my code. I just want to be sure I'm right on the mithril-side of this business. Thanks.

**Comment by tivac** [comment]
That looks fine, can you jsbin a minimal broken example?

**Comment by futurist** [comment]
before I've encountered similar problem, with lower version of Android(<4.1) & some Firefox@WIndows, seems it's compatible problem. I'm using code below:
````
 m('input[type=checkbox]', { checked:true } )  // some browser don't show as checked
 m('input[type=checkbox][checked]' )  // this also
````
also remembered tested with minimal code at that moment. and workaround:
````
 m('input[type=checkbox]', { config:function(el, old ){ if(!old) el.checked='checked';  } })
````

**Comment by futurist** [comment]
and below alway **not work** on all platforms, don't know whether it's an issue of mithril, but it's not handy when you encountered the problem:

````
var style= { color:'red'};

m.mount(document.body, {
    view : function() {
        return m('p', {
            style : style,
            onclick : function(e) {
                e.preventDefault();
                style.color = 'blue';
            }
        },'hello')
    }
});
````

http://jsbin.com/wuhoca/10/edit?html,js,output

**Comment by amireldor** [comment]
@tivac, hmm, I tried with jsbin and it seems to work. It must be something wrong with the structure of my code as a whole. I will try to track it down and report back for the greater good.

@futurist, thanks for the tip. If nothing works for me I will try your solution.

_(the simple jsbin showing all is working nicely:)_
http://jsbin.com/bovuyifoyo/edit?html,js,output

**Comment by Morklympious** [comment]
@amireldor Did you ever manage to figure this out? Or is this still an issue?

**Comment by amireldor** [comment]
@Morklympious Oh, it's been a while and I haven't reported back. Sorry.

It is not an issue anymore.

I don't fully remember what I did or how to reproduce, but if I recall correctly it was something faulty in my code. Either way I don't think I can find the problematic code, so I'm closing the issue.

Thanks.
