### ISSUE TITLE
Is there any benefit to use immutable for mithriljs?

### ISSUE THREAD

**Issue by whatifif** [lhorie/mithril.js#930]
I know there are benefits to use immutable for reactjs: easy undo-redo and high performance.

Are these benefits still applicable for mithriljs?

This may be related with how the diff of mithriljs works, I think.

Thanks in advance

**Comment by isiahmeadows** [comment]
If you're dealing with a lot of one-way binding, you might. Mithril doesn't
care about your data model. As long as your virtual nodes are still POJOs,
you're good.
