### ISSUE TITLE
Question: alternative template engine?

### ISSUE THREAD

**Issue by RenaudParis** [lhorie/mithril.js#937]
Hi there,

Mithril seems very interesting as a lightweight MVC micro-framework.

However, is it possible to use doT.js instead of the Mithril templates?

Like so (for example):

```javascript
todo.view = function() {
    return my_precompiled_doT_template(params);
};
```

(which basically means returning plain HTML)

**Comment by ondreian** [comment]
You can use `m.trust` http://mithril.js.org/mithril.trust.html

**Comment by RenaudParis** [comment]
That's great news, thank you!! (not a big fan of JS / JSX templates)

**Comment by StephanHoyer** [comment]
With that you will sacrifice a lot of mithrils power. I really recommend to give mithrils way of doing things a try. You won't regret it!

**Comment by RenaudParis** [comment]
I'm happy with doT, which is easy to write, easy to compile, easy to render, and with a syntax that I am used to.

What could JS/JSX templates bring me, that would not just slow me down? (i.e. learning a new syntax, with no gain to that)

I am not a fan of fraweworks. I am used to a setup with only a lightweight router and doT.js, and that matches my needs (lightweight, non-intrusive, one specific lib for each specific task).

I am willing to give Mithril a try because I heard a lot of nice things about it, what I began to read in the docs pleased me, and it sure is lightweight ; however, I am not sure I am willing to fully go the MVC way...

**Comment by StephanHoyer** [comment]
Things you won't get when not using plain JS for template
* easy debugging
* full power of turing complete language
* full power functional programming (e. G. composition)
* access to real DOM-nodes using the config callback
* copy and paste stuff from other mithrilers
* no buildstep, no additional template lib
* better support from the mithril community (they probably understand things quicker)
* less things to reason about, when others see your code

There are plenty more I think. This is what comes into my mind first :)

**Comment by RenaudParis** [comment]
Well then... At the very least I promise I will give it a try!

**Comment by StephanHoyer** [comment]
Than, welcome to mithril community :p

If you have any problems, feel free to come to the [gitter-chat](gitter.im/lhorie/mithril.js) and ask questions or just have a quick chat :dancers:

**Comment by RenaudParis** [comment]
Thank you Stephan! Will surely do :)

**Comment by ondreian** [comment]
Great run down on some of the advantages of using Mithril for templates @StephanHoyer !

I think the biggest one for me was the lack of API surface area to relearn with mithril templates... if you know HTML and Javascript, you already know how to write templates in mithril.  There are no "gotchas" with learning array comprehensions or hacks for boolean conditions like in a lot of template languages, you just have access to all of JS's powerful methods like `Array.prototype.filter`.  

Mithril templates are probably my favourite feature.

**Comment by RenaudParis** [comment]
Thank you Benjamin for that comment. I don't like to have the template inside the JavaScript code, that's the main reason I don't want to use such templates... I prefer to have a separated file for the template, and one for the code.

**Comment by tivac** [comment]
I haven't actually tested this, but does code going through `m.trust` actually go through the diffing algorithm? I assume it's just a transparent blob that gets splatted over whatever was there previously so you'd miss out on much of the advantage of using a virtual dom library.

**Comment by tehChromic** [comment]
Renaud,
You can use mithrilify transform with browserify build tool with nodejs and
npm if you want to keep your templates separated to some degree. I do this
and it makes a world of difference when writing a big application.

Cheers!

**Comment by RenaudParis** [comment]
Thank you theChromic and tivac for these advices!
