### ISSUE TITLE
Typo in docs/m.component.md

### ISSUE THREAD

**Issue by Slevinski** [lhorie/mithril.js#938]
I believe there is a mistake in the docs for m.component.  The shorthand syntax section looks like this...

### Shorthand syntax

If the first argument to `m()` is a component, it acts as an alias of `m.component()`

```javascript
var MyComponent = {
	controller: function() {
		return {greeting: "hello"}
	},
	view: function(ctrl, args) {
		return m("h1", ctrl.greeting + " " + args.data)
	}
}

m.render(document.body, [
	//the two lines below are equivalent
	m(component, {data: "world"}),
	m.component(component, {data: "world"})
])
```

But I believe the last function call should look like this.

```javascript
m.render(document.body, [
	//the two lines below are equivalent
	m(MyComponent, {data: "world"}),
	m.component(MyComponent, {data: "world"})
])
```

**Comment by isiahmeadows** [comment]
PRs accepted. Also, don't forget the dot in `m.component()` and
`m.render()`. ;-)
