### ISSUE TITLE
Using GET with `m.request` doest not send `Content-Type: application/json` request header

### ISSUE THREAD

**Issue by mikegleasonjr** [lhorie/mithril.js#948]
Using latest in next.

As per this page, it says it assumes it is always JSON: http://mithril.js.org/mithril.request.html

**Comment by mikegleasonjr** [comment]
What's annoying is that if I always set it, it concatenates with the current one if any: https://www.w3.org/TR/2006/WD-XMLHttpRequest-20060405/#dfn-setrequestheader

**Comment by dayuoba** [comment]
@mikegleasonjr what i think header content-type is for data-sent. if browser sends datas it may tell server what content-type is. same as server sends datas to client. so i think a `get` request has no need for content-type

**Comment by mikegleasonjr** [comment]
That's logical. I am coding against a JSON api and all endpoints are assumed to have this content-type. 

I managed to get it done in userland by taking the exact same `if` in the source code and negating it.
