### ISSUE TITLE
Typo in docs/mithril.component.md#parameterized-initial-state

### ISSUE THREAD

**Issue by Slevinski** [lhorie/mithril.js#949]
There is a typo in docs/mithril.component.md#parameterized-initial-state

Rather than **function(name)**, it should be **function(thing)**

The view section contains this...
```javascript
			ctrl.things().map(function(name) {
				return m("li", thing.name)
			})
```

But I believe it should be this...
```javascript
			ctrl.things().map(function(thing) {
				return m("li", thing.name)
			})
```

**Comment by isiahmeadows** [comment]
PRs welcome :smile:
