### ISSUE TITLE
Checking wrong property before calling onunload function

### ISSUE THREAD

**Issue by timboslice69** [lhorie/mithril.js#951]
It may be a sign of a problem somewhere else but I was having lots of type errors related to this if statement in the _builderMaybeRecreateObject_ function:

```
if (controller.unload) { 
    controller.onunload({preventDefault: noop})
}
```
Gives: _Uncaught TypeError: controller.onunload is not a function_

Oddly enough, the controller in question does have an _unload_ function, but no _onunload_ handler exists for it. Changing the code to actually check for the _onunload_ property prevents the error, so far i have not seen any other related problems occurring from this change.

```
if (controller.onunload) { 
    controller.onunload({preventDefault: noop})
}
```

**Comment by lhorie** [comment]
yeah, it should be onunload. Typo, maybe? @isiahmeadows 

Pushed a fix

**Comment by isiahmeadows** [comment]
@lhorie It's a pre-existing typo (pre-0.2) that I never caught..
