### ISSUE TITLE
App constants

### ISSUE THREAD

**Issue by cmnstmntmn** [lhorie/mithril.js#959]
hey,

```javascript
var app = {
  state: {
    pageY: 0, 
    pageHeight: window.innerHeight, 
    pageWidth: window.innerWidth
  }
}

window.addEventListener("scroll", function(e) {
  app.state.pageY = Math.max(e.pageY || window.pageYOffset, 0);
  app.state.pageHeight = window.innerHeight;
  m.redraw() //notify view
})

window.addEventListener("resize", function(e) {
  app.state.pageWidth = window.innerWidth;
  m.redraw() //notify view
})
```

i have this code, and i want to keep values of scroll Y and window size.
still, i don't know how to create one single constant object, and make use of it in any component i want to; more like decorators works ..

**Comment by barneycarroll** [comment]
Hi @cmnstmntmn , it doesn't look like this issue has anything to do with Mithril. 

ES6 allows you to set [constants](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const) (reference which cannot be rebound) in strict mode: `var app` would become `const app` and you can be sure that any attempt at re-assigning `app` in that scope would throw an error. In general, it doesn't look like there's anything problematic with your code.

**Comment by cmnstmntmn** [comment]
well, when i use outside component, even with constant

```javascript
require('assets/styles/app.sass');

var m = require('mithril');

const app = {
  state: {
    pageY: 0, 
    pageHeight: window.innerHeight, 
    pageWidth: window.innerWidth
  }
}
```
it throws an error 

`Uncaught ReferenceError: app is not defined`

**Comment by barneycarroll** [comment]
It looks like you're using CommonJS modules via Browserify or Node. The idea behind modules is to create separate execution contexts. What you define in one module will not be accessible to another unless it is `export`ed.

You might want to export the `app` reference and `require` it in your other modules that want to modify it, eg:

```javascript
// app.js
module.exports = {
  state: {
    pageY: 0, 
    pageHeight: window.innerHeight, 
    pageWidth: window.innerWidth
  }
}

// somewhere-else.js
var app = require( '../path/to/app.js' )

app.state.pageY = 'foo'
```

**Comment by cmnstmntmn** [comment]
that's it :+1:  
thank you (;

**Comment by barneycarroll** [comment]
Excellent :)

Could you close the issue please?
