### ISSUE TITLE
m.route as config function loses hash information

### ISSUE THREAD

**Issue by tivac** [lhorie/mithril.js#960]
We're using `m.route.mode = "pathname";` and have some links that point deeply into another section of the site, `<a href="/en/teams#fooga-wooga">`. When those links are using `config : m.route` they are stripped of the hash portion of the their URL, so the resulting route is just `/en/teams`.

This is happening because of https://github.com/lhorie/mithril.js/blob/next/mithril.js#L1665

```js
m.route(currentTarget[m.route.mode]
			.slice(modes[m.route.mode].length), args)
```

because of how anchor element properties work in the DOM when requesting `currentTarget.pathName` (in this case) it gives back the pathname only, stripped of any query params or hash values. This is then passed directly into `m.route()` and that information is lost.

Interestingly, the `m.route()` matching code wouldn't know what to do w/ a hash or a query string anyways, because calling `m.route("/en/teams#fooga-wooga");` doesn't match our `/:lang/teams` route.

Is this a known issue? It seems like it must be but I wasn't able to dredge up any mentions of it. Is there a good workaround? The only ones I can come up w/ atm are to remove the `config : m.route` handler entirely (thus losing all the nice SPA-ness), or to remove it and add our own `onclick` handler to save off the hash somewhere and re-apply it after the route changes.

Both of those sound pretty gross.

**Comment by barneycarroll** [comment]
[Got a reproducing test case in this fiddle](https://jsfiddle.net/barney/jpwL5v6v/).

**Comment by barneycarroll** [comment]
[Gotta reproducing test case in this fiddle](https://jsfiddle.net/barney/jpwL5v6v/).

I never bumped into this because I always doing `hash` routing (further `#` & '?' are treated as part of the `hash`). I guess the right way around this is to replace
```
currentTarget[m.route.mode]
  .slice(modes[m.route.mode].length)
```
…with:
```
currentTarget.href.substr(
  currentTarget.href.indexOf(currentTarget[m.route.mode]) 
  + modes[m.route.mode].length
)
```

**Comment by barneycarroll** [comment]
[Here's a demo allowing you to switch route modes](https://jsfiddle.net/barney/jpwL5v6v/3/), which shows the hash being lost in pathname & search modes, and here's a [partial fix](https://jsfiddle.net/barney/jpwL5v6v/4/) using [this fork](https://github.com/barneycarroll/mithril.js/blob/preserveRouteSegments/mithril.js#L801) (ie via fix proposed above). Doesn't resolve pathname mode.

**Comment by barneycarroll** [comment]
So it turns out Mithril does more logic later on if you pass in query params, so the hash has a further opportunity to get lost, which I guess is a sub-bug.

**Comment by tivac** [comment]
FWIW this all seems fixed in `rewrite`: https://jsbin.com/wotugi/1/edit?js,output
