### ISSUE TITLE
Range element value not set correctly if attributes defined in a certain order

### ISSUE THREAD

**Issue by bcliff323** [lhorie/mithril.js#961]
When trying to set the value of a range input over 100, you seem to need to define the value attribute after the max/min attributes.  If you define value before max/min, a value of 200 will be set to 100.

```
m('input', {
    type: 'range',
    value: "1000", // sets value to 100
    max: '2000',
    min: '0'
})
```

Example:  https://jsbin.com/zegocix/8/edit?html,js,output

Mithril Versions: 0.2.0 & 0.2.1

Tested on:
Firefox 38
Chrome 47
Safari 8

**Comment by maranomynet** [comment]
This happens in plain JavaScript also because <input type="range"> has a default `max` value of `100` - so the `value` you assign it gets capped unless you've raised the `max`

```js
var input = document.createElement('input');
input.type = 'range';
input.value = 9999;
console.log(input.value); // ==> 100
```

**Comment by bcliff323** [comment]
Ah, thanks. That's good to know. Somehow I had not come across this before. Since this is consistent with how the DOM works, it doesn't seem like a bug to me.

**Comment by maranomynet** [comment]
@lhorie it might be at least worth noting this issue in the documentation.

I.e. that the assignment order of attributes is significant and must match the order one would use in POJS.
