### ISSUE TITLE
Definition of MithrilPromise in the typescript definitions(mithril.d.ts)

### ISSUE THREAD

**Issue by AlexanderLindsay** [lhorie/mithril.js#963]
The current definition of MithrilPromise<T> in mithril.d.ts extends a MithrilProperty of itself.
```javascript
interface MithrilPromise<T> extends Thennable<T>, MithrilProperty<MithrilPromise<T>>
```

If I use the promise like the following:
```javascript
var d = m.deferred<string>();
d.resolve("test");
var p = d.promise;
var result = p();
```
I would expect `result` to hold a string value of "test" but instead it is a `MithrilPromise<string>`.

It seems like the interface should be
```javascript
interface MithrilPromise<T> extends Thennable<T>, MithrilProperty<T>
```

Or if it is correct how it is, how am I suppose to get the value out of a MithrilPromise?

**Comment by isiahmeadows** [comment]
It should be the union. Try resolving with a promise. Also, do file a PR.

**Comment by AlexanderLindsay** [comment]
I created a pull request: [#964](https://github.com/lhorie/mithril.js/pull/964l).

**Comment by isiahmeadows** [comment]
Should be fixed at this point. Closing.
