### ISSUE TITLE
Calling m.trust() in mobile browsers crashes an application

### ISSUE THREAD

**Issue by MaralisDaniel** [lhorie/mithril.js#967]
Hello everyone!
Description:
It seems I have a small problem with `m.trust()` - any app with this method crases in default mobile browsers. Everything is Ok if it is mobile version of Chrome or desktop browser.
Browser: 
default iPhone 5 or iPhone 4, Android Platforms 4.3 and 2.3 (like: Mozilla/5.0 AppleWebKit/601.4.4 or AppleWebKit/530.17)
Current version: 
min.zip 0.2.2-rc1
example: 
`m.render(document.body, m.trust('Hello<br>world'));` or `m.render(document.body, m.trust('Hello'));`
Note:
In previous version i`ve used - 0.2.0, everything was Ok

**Comment by isiahmeadows** [comment]
Try 0.2.2-rc. 0.2.1 epicly failed because of lack of testing beforehand.

**Comment by tivac** [comment]
@isiahmeadows 

> Current version:
> min.zip 0.2.2-rc1

So I don't think that is going to help.

**Comment by isiahmeadows** [comment]
Test with the unminified dev version from the repo itself. It's a single
file. Trying to rule out as much as I can first.

**Comment by MaralisDaniel** [comment]
Tested with Mithril.min.js and Mithril.js from minimal package (zip with 3 files)
Result is same. 
Using try-catch returns this:
`NOT_SUPPORTED_ERR: DOM Exception 9`
Tested on full version (mithril.js-next from GitHub) - `m.trust()` works. 
It seems some problem with minimized package

**Comment by isiahmeadows** [comment]
The zip package was regenerated in `next`. Is it still broken?

**Comment by MaralisDaniel** [comment]
Yes, it`s Ok now. Thanks for help)
