### ISSUE TITLE
Apparent bug with m.request swallowing exceptions

### ISSUE THREAD

**Issue by lukeasrodgers** [lhorie/mithril.js#968]
I am new to mithril, so could be wrong about this, but it looks like master and v0.2.2-rc.1 are swallowing exceptions in `then`s for `m.request`, which seems to be contrary to the docs.

Here is a fiddle with 0.2.0 that works correctly: https://jsfiddle.net/tc5t2s30/

Here is a fiddle with 0.2.2-rc1 that (I believe) is incorrect: https://jsfiddle.net/3910bbb8/
EDIT -- had to copy+paste mithril source into this fiddle, since it's not on a CDN

To see the results, open your dev console and click "Run" in the top-left corner.

**Comment by isiahmeadows** [comment]
It shouldn't. m.request literally uses m.deferred under the hood, the
exported function, matter of fact. Does this do the same with m.deferred?

```js
var deferred = m.deferred()
deferred.promise.then(function () {
  console.log(xx)
})
setTimeout(function () {
  deferred.resolve()
}, 10)
```

m.request and m.deferred could easiky go in different files (by
design...the plan is to depecate it in 0.3 in favor of depending on actual
promises, and I've already done some prep work for that).

(sorry...I'm typing this on my phone, not the best place to test code.)

**Comment by lukeasrodgers** [comment]
@isiahmeadows your code appears to work just fine, yeah.

**Comment by isiahmeadows** [comment]
Which is utterly confusing.

**Comment by isiahmeadows** [comment]
Does it hit `catch`?

**Comment by lukeasrodgers** [comment]
Appears not: version  0.2.2-rc1 https://jsfiddle.net/Lc2qzzsy/1/

**Comment by isiahmeadows** [comment]
It's called for some reason, where m.deferred.onerror rethrows native Error subclasses by default, the browser is mysteriously *not* logging the error. It doesn't look like a Mithril problem at all, unless the Deferred implementation is catching errors it shouldn't.

Check out [this pen](http://codepen.io/isiahmeadows/pen/XdJRPp?editors=0010) to see what I'm talking about. (It uses the latest version in `next`, with the help of [RawGit](https://rawgit.com/).)

**Comment by robinchew** [comment]
Errors in .then() are still suppressed in 0.2.3

**Comment by robinchew** [comment]
I've updated Luke's jsfiddle to use 0.2.3 https://jsfiddle.net/tc5t2s30/2/

**Comment by isiahmeadows** [comment]
Here's my thought:

1. [This line](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L2174) should really just be a `throw`.
2. [This line](https://github.com/lhorie/mithril.js/blob/next/mithril.js#L2177) is just a standard deferred resolution. There's no magic here.

I have no clue why it's not working. An extra `m.deferred.onerror` call would fix this, but I feel it's a bit hackish. :frowning:

**Comment by robinchew** [comment]
Thanks Isiah, but I am confused. Are you saying if I apply those 2 changes, this bug would be fixed? I am confused because you followed with 'i have no clue why it's not working'.

**Comment by isiahmeadows** [comment]
@robinchew 

To clarify, I meant to do this:

1. Replace the reject in \#1 with a `throw`.
2. Add a `m.deferred.onerror(e)` after \#2.

I also meant I'm confused as to how it's even broken in the first place (it clearly is).

**Comment by robinchew** [comment]
Are you gonna do those 2 things for 0.2.4?

**Comment by isiahmeadows** [comment]
I haven't had a lot of time on my hands, but if you'd like, I'd definitely consider a PR.

**Comment by lhorie** [comment]
Apparently this regression was introduced by commit `cb29a2`, which is related to #873

That commit replaced a call to `m.deferred.onerror(e)` with the current `deferred.reject(e)` on L2177

I added the call to `m.deferred.onerror(e)` back there

**Comment by isiahmeadows** [comment]
@lhorie That wouldn't surprise me.

**Comment by robinchew** [comment]
Thank you @lukeasrodgers @isiahmeadows and @lhorie!
