### ISSUE TITLE
Discussion: Mithril Native

### ISSUE THREAD

**Issue by gebrits** [lhorie/mithril.js#969]
Is there any interest, or perhaps even some progress, in creating Mithril Native, similar to React Native? 

Alternatively, what would be needed to make Mithril output React Native code? Would this even be possible? 

Thoughts?

**Comment by isiahmeadows** [comment]
What would be easier would be to abstract Mithril away from the DOM, which is still admittedly very difficult. It took Facebook quite a while to get React decoupled, and that's Facebook. If you feel like partially rewriting Mithril to do some of its own bookkeeping and being able to delegate rendering to external tools, go for it.

**Comment by lhorie** [comment]
Mithril Native is currently not in the near future roadmap. Maybe when I have more time
