### ISSUE TITLE
Add EmberJS in the benchmarks

### ISSUE THREAD

**Issue by batisteo** [lhorie/mithril.js#970]
When you get bored, could you please add EmberJS to your benchmarks?

**Comment by lhorie** [comment]
PR welcome :)

Generally speaking though, Ember has always been the slowest framework in just about every benchmark I've seen, often by an order of magnitude or more.

**Comment by leeoniya** [comment]
@lhorie speaks the truth. see for yourself. [1]

[1] http://threaditjs.com/

**Comment by isiahmeadows** [comment]
:-1: from me. I took the runner from [Merri/nom's TodoMVC benchmark](https://github.com/Merri/nom/tree/gh-pages/todomvc/benchmark) and ripped everything out except for Mithril. It's here purely for Mithril. It doesn't actually compare against anything.

**Comment by isiahmeadows** [comment]
@lhorie You see where I'm coming from with this?

**Comment by lhorie** [comment]
@isiahmeadows I thought he was referring to the benchmarks on the homepage

**Comment by isiahmeadows** [comment]
Oh. Good point. I'll take that back, then. Also, the benchmarks probably need updated, anyways.

**Comment by batisteo** [comment]
Yeah, from the homepage. But it's just a poney anyway, no PR, I won't mind if you close/wontfix.

**Comment by lhorie** [comment]
Alright closing then. Sorry I don't have time to wrestle w/ Ember right now :)
