### ISSUE TITLE
Attribute-only definition leads to value being set to "true"

### ISSUE THREAD

**Issue by cmawhorter** [lhorie/mithril.js#971]
Doing `m('a[href]', 'test')` renders as `<a href="true">`.  It should render as `<a href>`, which is [valid html5](https://www.w3.org/TR/2008/WD-html5-20080610/semantics.html#boolean).  Mithril should not default undefined attribute values to true.  

https://jsbin.com/totelucoko/edit?html,output

My workaround is `m('a[href="javascript:;"]',`.  Doing just `<a>` without href can have side-effects.

I could also see this being a problem for `m('span[data-whatever],`

**Comment by barneycarroll** [comment]
In real DOM, there's no such thing as an empty attribute. Writing `<body test>` will appear as `<body test>` in some DOM inspectors but this is a presentational nicety — [the actual attribute value is an empty string](https://jsfiddle.net/barney/dhhpxhm3/), which can be seen upon querying it via `getAttribute` or `outerHTML`.

**Comment by cmawhorter** [comment]
Yes, you're correct.  Maybe it should match with an empty string instead of string true?

**Comment by barneycarroll** [comment]
That would be my call, it's what the browser does when parsing HTML so it's as good a guide aa any for how Mithril should parse equivalent query selectors.

However I believe the core team have some ideas as to changing the behaviour that distinguishes properties and attributes which might impact that straight fix.

**Comment by isiahmeadows** [comment]
IMHO it should match with the property. `m("a[href]")` should be equivalent to `m("a[href=href]")

**Comment by isiahmeadows** [comment]
IMHO it should match with the property. `m("a[href]")` should be equivalent to `m("a[href=href]")`, since that's what the HTML spec does.

**Comment by niothiel** [comment]
The formal HTML5 spec considers a valueless attribute equivalent to an attribute with a zero-length string. This is different than jade templates, which seem to set the value equal to the attribute name if the html5 doctype is not specified. See https://github.com/pugjs/jade/issues/370#issuecomment-85654654.

I see two options here:
- Use a reasonable default, either an empty string or the attribute name.
- Detect the doctype and select the appropriate value.

**Comment by isiahmeadows** [comment]
Okay. First of all, detecting the right doctype is not trivial to my
understanding (it's pointless 99.999999% of the time). I'm not even sure
such an API exists. Second of all, I think Jade's option is based on its
XML support, and in the XML world, repeating the name is a bit more common.
XML doesn't have boolean attributes, though. A secondary argument, although
probably much weaker, is that it's still truthy. Not sure how much of a
difference it makes in practice, though.

I'm backing off my opinion a little, though. IMHO, it's probably best to
agree with whatever the spec says. I'm used to Jade, which does that.

**Comment by cmawhorter** [comment]
another option is disallowing value-less attributes and throwing an error.  including it for completeness.  not saying it's better than others already mentioned.

**Comment by barneycarroll** [comment]
@cmawhorter throwing errors isn't a credible user expectation and doesn't solve any problems.

@isiahmeadows [that's not what the HTML spec says at all](https://www.w3.org/TR/html-markup/syntax.html#syntax-attr-empty). Let's deal with user expectations instead.

**Comment by isiahmeadows** [comment]
@barneycarroll 

> I'm backing off my opinion a little, though. IMHO, it's probably best to agree with whatever the spec says. I'm used to Jade, which does that.

I would prefer spec conformance over anything else, BTW. I just put my quick opinion change a little more indirectly.

**Comment by barneycarroll** [comment]
I think I've lost the thread of this conversation @isiahmeadows. Could you reiterate your concerns with regards to the issue raised and / or pull request?

**Comment by isiahmeadows** [comment]
@barneycarroll 

My concerns were that I didn't remember that `<form disabled></form>` was equivalent to `<form disabled=""></form>`, but instead thought the spec was consistent with XML conventions of `<form disabled="disabled"></form>`. It's moot now. I was seeking spec conformance, but misremembered the spec itself (I usually don't have to think about that).
