### ISSUE TITLE
Create a Promises/A+ wrapper for `m.deferred()`/`m.sync()` exporting a Promise global

### ISSUE THREAD

**Issue by isiahmeadows** [lhorie/mithril.js#978]
This is more or less a TODO for me. It'll help ease migration for some of the changes I'll be making to `m.request()` in light of #800 and #802.

**Comment by isiahmeadows** [comment]
On a related note, a modified version of the suite needs to make it into core as well. It's better to safely deprecate stable things than potentially broken things.

**Comment by lhorie** [comment]
This is now done [here](https://github.com/lhorie/mithril.js/blob/rewrite/promise/promise.js)
