### ISSUE TITLE
mithril.js, semicolons and minify issue

### ISSUE THREAD

**Issue by slothbag** [lhorie/mithril.js#985]
I noticed in mithril.js there is a semicolon at the start and none at the end, this causes issues when minifying with other JS files.

But when I check mithril.min.js there is no semicolon at the start and there is one at the end.

Not sure how that happens.

**Comment by lhorie** [comment]
Added a semicolon to the end again

**Comment by isiahmeadows** [comment]
@lhorie Would this be worth reporting as a feature request to the UglifyJS project?
