### ISSUE TITLE
Variadic routes take precedence over more specific routes with parameters

### ISSUE THREAD

**Issue by mikegleasonjr** [lhorie/mithril.js#986]
```
'/:not-found...': component1
```

will take precedence over:

```
'/section/:id': component2
```

which will use `component1` when `http://x.com/section/1`
(and stangely `component2` when `http://x.com/section/:id`)

**EDIT:** I just read more carefully the doc and it states that _Note that Mithril checks for route matches in the order the routes are defined_ but **isn't there no guarantees of objects elements order in a map in javascript**? I also populate my routes dynamically with if and elses in an object..

**Comment by lhorie** [comment]
The Javascript spec technically doesn't guarantee order for object iteration, but all the major js implementations behave as if it did.

**Comment by isiahmeadows** [comment]
@lhorie ES6 now requires it BTW, for this reason (compatibility). V8 actually [ran into problems with doing otherwise](https://bugs.chromium.org/p/v8/issues/detail?id=164), because most of the other engines did this, most notably FF and IE.
