### ISSUE TITLE
Best way to eliminate scroll to top on route change

### ISSUE THREAD

**Issue by Slevinski** [lhorie/mithril.js#989]
I have a problem where scrolling to the top of the page on route changes is not desired.

I'm using hash routing.  The left side of the page contains a list of items that grows using infinite scroll.  The right side of the page is displayed in a fixed position so that it is always visible.  Clicking on an item on the left of the page changes the hash, which updates the right side of the page.  Unfortunately, the function setScroll scrolls the page to the top, so the user looses their place.

My temporary work around is to redefine the window.scrollTo function to do nothing before adding mithril to the page, and then restoring the scrollTo function after mithril has been created.  Definite kludge.  Any better ideas?

**Comment by tobscure** [comment]
https://github.com/lhorie/mithril.js/issues/567 Is this relevant?

You could save the current scroll position somewhere (e.g. in the click handler, or in the view function?) and then restore it in the config function.

**Comment by Slevinski** [comment]
Thanks.  That sounds like a much better approach.  I'm not sure exactly how the code would look, but I should be able to figure it out.  Thanks for the idea.

**Comment by lhorie** [comment]
this behavior is removed in rewrite

**Comment by volnei** [comment]
But changing to different pages is terrible to keep the another page scroll position. I think this must be configurable cause the most acceptable behavior is scrolling to top, this is the way any website works.
